### PR TITLE
Update polybase-configure-oracle.md

### PR DESCRIPTION
**Pull request by pabechevb**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@pabechevb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by MikeRayMSFT** [comment]
@pabechevb - thank you for the submission. We are reviewing.

**Review by NathanMSFT — APPROVED** [review]
Looks good to me!

**Comment by MikeRayMSFT** [comment]
staging in private repo

**Pull request closed without merging**
