### PR TITLE
Corrected maximum difference calculation

### PR DESCRIPTION
**Pull request by Kolthor**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Kolthor : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @pmasl, can you please confirm this change is technically accurate?

**Comment by MashaMSFT** [comment]
Hi @Kolthor, thank you for your contribution! Would you mind clarifying the justification for removing milliseconds and replacing it with nanoseconds? It may be better to leave the milliseconds example as it is, and just add the nanosecond example as an additional example. Thanks!

**Comment by Kolthor** [comment]
Because it seems the sentence was copied from the page on DATEDIFF, which returns an int.
DATEDIFF_BIG returns a bigint, so for millisecond or even microsecond precision, there will never be an overflow.
(with microsecond precision the overflow would happen at 292 thousand years; way more than the maximum span of 10,000 years a DATEDIFF_BIG would have to deal with)

**Comment by Kolthor** [comment]
@pmasl Where did you get those values?
I agree that second, and millisecond precision is more common than microsecond and nanosecond, but the maximum differences you state for second and millisecond are wrong.

The fact is that there are no other precisions than **nanosecond**, that will ever (with the current available date and time data types) cause `DATEDIFF_BIG` to run into an overflow, for any input dates, since the maximum timespan it would ever have to deal with is the one between a minimum **datetime2** of 0001-01-01T00:00:00.0000000 and a maximum **datetime2** of 9999-12-31T23:59:59.9999999.

The .NET DateTime construct is actually just a **bigint** (64-bit integer) amount of 100ns ticks which i believe is exactly why that precision (100ns) was chosen in the first place; it is the highest precision you can have, if you need to support a span of 10,000 years. The SQL **datetime2** has the same maximum precision, and i believe it is for the same reason.

At **microsecond** precision (being 1000ns), you will never reach the maximum value for a **bigint**, since a **bigint** maxvalue of microseconds, would be a hair over 292,277 years.
A **bigint** maxvalue of milliseconds, would be ~292,277,024 years, and a **bigint** maxvalue of seconds is ~21.18 times the age of the universe.

If some of this information is needed for clarification, i would change it to the following:

> For a return value out of range for **bigint** (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807), `DATEDIFF_BIG` returns an error. Unlike `DATEDIFF` which returns an **int** and therefore may overflow with a precision of **hour** or higher, `DATEDIFF_BIG` can only overflow if using **nanosecond** precision, and where the difference between *enddate* and *startdate* is more than approximately 292.27 years.

Or something to that effect.

Here is some SQL that shows what I've been saying:
```sql
DECLARE @minDateTime       DATETIME;          SET @minDateTime       = '1753-01-01 00:00:00.000';
DECLARE @maxDateTime       DATETIME;          SET @maxDateTime       = '9999-12-31 23:59:59.997';
                                                                
DECLARE @minDateTime2      DATETIME2(7);      SET @minDateTime2      = '0001-01-01 00:00:00.0000000';
DECLARE @maxDateTime2      DATETIME2(7);      SET @maxDateTime2      = '9999-12-31 23:59:59.9999999';

DECLARE @minDateTimeOffset DATETIMEOFFSET(7); SET @minDateTimeOffset = '0001-01-01 00:00:00.0000000+00:00';
DECLARE @maxDateTimeOffset DATETIMEOFFSET(7); SET @maxDateTimeOffset = '9999-12-31 23:59:59.9999999+00:00';

DECLARE @minSmallDateTime  SMALLDATETIME;     SET @minSmallDateTime  = '1900-01-01 00:00:00';
DECLARE @maxSmallDateTime  SMALLDATETIME;     SET @maxSmallDateTime  = '2079-06-06 23:59:29';

DECLARE @minDate           DATE;              SET @minDate           = '0001-01-01';
DECLARE @maxDate           DATE;              SET @maxDate           = '9999-12-31';

DECLARE @minTime           TIME;              SET @minTime           = '00:00:00.0000000';
DECLARE @maxTime           TIME;              SET @maxTime           = '23:59:59.9999999';

SELECT -- SECOND/S (ms) one second (1 seconds)
       [DateTime s Min]        = DATEDIFF_BIG(SECOND, @maxDateTime, @minDateTime),
       [DateTime s Max]        = DATEDIFF_BIG(SECOND, @minDateTime, @maxDateTime),
       [DateTime2 s Min]       = DATEDIFF_BIG(SECOND, @maxDateTime2, @minDateTime2),
       [DateTime2 s Max]       = DATEDIFF_BIG(SECOND, @minDateTime2, @maxDateTime2),
       [DateTimeOffset s Min]  = DATEDIFF_BIG(SECOND, @maxDateTimeOffset, @minDateTimeOffset),
       [DateTimeOffset s Max]  = DATEDIFF_BIG(SECOND, @minDateTimeOffset, @maxDateTimeOffset),
       [SmallDateTime s Min]   = DATEDIFF_BIG(SECOND, @maxSmallDateTime, @minSmallDateTime),
       [SmallDateTime s Max]   = DATEDIFF_BIG(SECOND, @minSmallDateTime, @maxSmallDateTime),
       [Date s Min]            = DATEDIFF_BIG(SECOND, @maxDate, @minDate),
       [Date s Max]            = DATEDIFF_BIG(SECOND, @minDate, @maxDate),
       [Time s Min]            = DATEDIFF_BIG(SECOND, @maxTime, @minTime),
       [Time s Max]            = DATEDIFF_BIG(SECOND, @minTime, @maxTime),

       -- MILLISECOND/MS (ms) one thousandth of one second (0.001 seconds)
       [DateTime ms Min]       = DATEDIFF_BIG(MILLISECOND, @maxDateTime, @minDateTime),
       [DateTime ms Max]       = DATEDIFF_BIG(MILLISECOND, @minDateTime, @maxDateTime),
       [DateTime2 ms Min]      = DATEDIFF_BIG(MILLISECOND, @maxDateTime2, @minDateTime2),
       [DateTime2 ms Max]      = DATEDIFF_BIG(MILLISECOND, @minDateTime2, @maxDateTime2),
       [DateTimeOffset ms Min] = DATEDIFF_BIG(MILLISECOND, @maxDateTimeOffset, @minDateTimeOffset),
       [DateTimeOffset ms Max] = DATEDIFF_BIG(MILLISECOND, @minDateTimeOffset, @maxDateTimeOffset),
       [SmallDateTime ms Min]  = DATEDIFF_BIG(MILLISECOND, @maxSmallDateTime, @minSmallDateTime),
       [SmallDateTime ms Max]  = DATEDIFF_BIG(MILLISECOND, @minSmallDateTime, @maxSmallDateTime),
       [Date ms Min]           = DATEDIFF_BIG(MILLISECOND, @maxDate, @minDate),
       [Date ms Max]           = DATEDIFF_BIG(MILLISECOND, @minDate, @maxDate),
       [Time ms Min]           = DATEDIFF_BIG(MILLISECOND, @maxTime, @minTime),
       [Time ms Max]           = DATEDIFF_BIG(MILLISECOND, @minTime, @maxTime),

       -- MICROSECOND/MCS (µs) one millionth of one second (0.000001 seconds)
       [DateTime µs Min]       = DATEDIFF_BIG(MICROSECOND, @maxDateTime, @minDateTime),
       [DateTime µs Max]       = DATEDIFF_BIG(MICROSECOND, @minDateTime, @maxDateTime),
       [DateTime2 µs Min]      = DATEDIFF_BIG(MICROSECOND, @maxDateTime2, @minDateTime2),
       [DateTime2 µs Max]      = DATEDIFF_BIG(MICROSECOND, @minDateTime2, @maxDateTime2),
       [DateTimeOffset µs Min] = DATEDIFF_BIG(MICROSECOND, @maxDateTimeOffset, @minDateTimeOffset),
       [DateTimeOffset µs Max] = DATEDIFF_BIG(MICROSECOND, @minDateTimeOffset, @maxDateTimeOffset),
       [SmallDateTime µs Min]  = DATEDIFF_BIG(MICROSECOND, @maxSmallDateTime, @minSmallDateTime),
       [SmallDateTime µs Max]  = DATEDIFF_BIG(MICROSECOND, @minSmallDateTime, @maxSmallDateTime),
       [Date µs Min]           = DATEDIFF_BIG(MICROSECOND, @maxDate, @minDate),
       [Date µs Max]           = DATEDIFF_BIG(MICROSECOND, @minDate, @maxDate),
       [Time µs Min]           = DATEDIFF_BIG(MICROSECOND, @maxTime, @minTime),
       [Time µs Max]           = DATEDIFF_BIG(MICROSECOND, @minTime, @maxTime),

       -- NANOSECOND/NS (ns) one billionth of one second (0.000000001 seconds)
       -- All of these results in overflow with the message below, as the value would be larger than a bigint can handle
       -- Msg 535: The datediff_big function resulted in an overflow. The number of dateparts separating two date/time instances is too large. Try to use datediff_big with a less precise datepart.

       --[DateTime ns Min]       = DATEDIFF_BIG(NANOSECOND, @maxDateTime, @minDateTime),
       --[DateTime ns Max]       = DATEDIFF_BIG(NANOSECOND, @minDateTime, @maxDateTime),
       --[DateTime2 ns Min]      = DATEDIFF_BIG(NANOSECOND, @maxDateTime2, @minDateTime2),
       --[DateTime2 ns Max]      = DATEDIFF_BIG(NANOSECOND, @minDateTime2, @maxDateTime2),
       --[DateTimeOffset ns Min] = DATEDIFF_BIG(NANOSECOND, @maxDateTimeOffset, @minDateTimeOffset),
       --[DateTimeOffset ns Max] = DATEDIFF_BIG(NANOSECOND, @minDateTimeOffset, @maxDateTimeOffset),
       --[SmallDateTime ns Min]  = DATEDIFF_BIG(NANOSECOND, @maxSmallDateTime, @minSmallDateTime),
       --[SmallDateTime ns Max]  = DATEDIFF_BIG(NANOSECOND, @minSmallDateTime, @maxSmallDateTime),
       --[Date ns Min]           = DATEDIFF_BIG(NANOSECOND, @maxDate, @minDate),
       --[Date ns Max]           = DATEDIFF_BIG(NANOSECOND, @minDate, @maxDate),
       [Time ns Min]           = DATEDIFF_BIG(NANOSECOND, @maxTime, @minTime),
       [Time ns Max]           = DATEDIFF_BIG(NANOSECOND, @minTime, @maxTime)
```

**Comment by pmasl** [comment]
@Kolthor the numbers here are incorrect as I used an int based formula by mistake. 
You mention that it can overflow with hour or smaller - did I get this right? This obviously depends on input data type, as your demo suggests.
Using DT2, the max DATEDIFF_BIG diff for seconds is 315537897599 which starting at '0001-01-01  00:00:00.00000000' gets you roughly to 9999-12-31 23:50:00.0000000 which is 9998 years, 11 months, 30 days, 23 hours, 50 minutes and 0 seconds. 
For 315537897599 ms of max diff and the same start datetime2, it gets you to 8247-12-31 23:50:00.0000000 which is 8246 years, 11 months, 30 days, 23 hours, 50 minutes and 0 seconds. 
All these don't overflow bigint as you confirmed in your DATEDIFF_BIG explanation above. 
But for microsec, max diff is 315537897599999999, which will overflow DATETIME2 because that's roughly 10033.035696018 years.
So the change you propose IMO can be extended to account for input data type differences, and still mention the widest use case which is usually datetime/datetime2 (this can be shown just for reference, even in a 2nd paragraph but it's important to mention).

**Comment by Kolthor** [comment]
Correction, `DATEDIFF` may overflow with a precision _higher_ than **hour**, i.e. **minute** or higher. Not, as i wrote, with a precision of **hour** or higer.

An `int.MaxValue` of hours is around 245k years, an `int.MaxValue` of minutes is about 4k years.

**Comment by PRMerger9** [comment]
@Kolthor : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by pmasl** [comment]
@Kolthor the numbers you pointed out in my previous comment are incorrect as I used an int based formula by mistake. 
You mention that it can overflow with hour or smaller - did I get this right? This obviously depends on input data type, as your demo suggests.
Using DT2 range, and because in these functions we are using the Gregorian year, the max DATEDIFF_BIG diff can overflow for millisecond, microsecond (see below examples of when it overflows) and nanosecond (above 292.2 years like you mention). How can it overflow for lower precisions?
Ex.
For minute, diff is 5258964959, which gets you to 9999-12-31 23:50:00.0000000 (9998 years, 11 months, 30 days, 23 hours, 50 minutes and 0 seconds). Similar result for hours, days, etc. It won't overflow.
For ms the max diff is 260250105599996, which gets you to 8247-12-31 23:50:00.0000000 (8246 years, 11 months, 30 days, 23 hours, 50 minutes and 0 seconds). This will overflow if a higher date range is provided. 

So I propose, based on your last edit (btw hour can't overflow in DATEDIFF because max diff is 72291695):

For a return value out of range for **bigint** (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807), `DATEDIFF_BIG` returns an error. Unlike `DATEDIFF` which returns an int and therefore may overflow with a precision of **minute** or higher, `DATEDIFF_BIG` can only overflow if using:
-  **millisecond** precision where the difference between *enddate* and *startdate* is more than 8246 years, 11 months, 30 days, 23 hours, 50 minutes and 0 seconds.
-  **microsecond** precision where the difference between *enddate* and *startdate* is more than 9998 years, 11 months, 30 days, 23 hours, 50 minutes and 0 seconds.
-  **nanosecond** precision where the difference between *enddate* and *startdate* is more than 292 years, 2 months <I'm working to find the exact precision with which it overflows> .

**Comment by pmasl** [comment]
@Kolthor the numbers you pointed out in my previous comment are incorrect as I used an int based formula by mistake. 
So I propose, based on your last edit and max date for ns is  roughly 0293-04-11 23:47:16.854:

For a return value out of range for **bigint** (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807), `DATEDIFF_BIG` returns an error. Unlike `DATEDIFF` which returns an int and therefore may overflow with a precision of **minute** or higher, `DATEDIFF_BIG` can only overflow if using **nanosecond** precision where the difference between *enddate* and *startdate* is more than 292 years, 3 months, 10 days, 23 hours, 47 minutes and 16.854 seconds.

**Comment by pmasl** [comment]
@Kolthor I can't make any changes to your PR. Once the changes are in, I can sign-off. Thank you again

**Comment by PRMerger18** [comment]
@Kolthor : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@pmasl Could you review the latest updates to the pull request? Thanks!

**Comment by pmasl** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@pmasl: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by pmasl** [comment]
@MashaMSFT @ktoliver #sign-off

**Comment by PRMerger7** [comment]
@pmasl: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
