### PR TITLE
Update azure-active-directory.md

### PR DESCRIPTION
**Pull request by yitam**
Added ODBC requirements to connecting using access token or managed identities

### CODE REVIEW

**Comment by PRMerger6** [comment]
@yitam : Thanks for your contribution! The author, @david-puglielli, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @yitam - Thanks for your contribution. Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules. 

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 

For more information, see [Should I work in a private or a public repo?](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) 

Thanks!

**Comment by yitam** [comment]
Thanks @ktoliver 
Are you saying that I should close this PR and resubmit my changes to master instead?

**Comment by ktoliver** [comment]
@yitam No. This PR can move forward. In the future, you should open new pull requests in the private repo, **sql-docs-pr**.

**Comment by yitam** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@yitam: I'm sorry - only the author of this article, @david-puglielli, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by david-puglielli** [comment]
#sign-off

**Pull request merged**
