### PR TITLE
Typo in UpdateAbility

### PR DESCRIPTION
**Pull request by LowlyDBA**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@LowlyDBA : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @LowlyDBA, thank you so much for your contribution! Neither updateability nor updatability is an actual dictionary term, and there are sources online for spelling it both ways. However, within the product, the values actually return updatability so this is not a typo. I appreciate you bringing this to our attention though! #please-close

**Comment by LowlyDBA** [comment]
@MashaMSFT This does not appear to be true for at least the below version of 2017:

```sql
SELECT @@VERSION
select DATABASEPROPERTYEX('master', 'UPDATEABILITY')
select DATABASEPROPERTYEX('master', 'UPDATABILITY')


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) 
	Aug 22 2017 17:04:49 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Home 10.0 <X64> (Build 17134: )
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
READ_WRITE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
NULL
```

**Comment by MashaMSFT** [comment]
Hi @LowlyDBA, I checked the source code for this specific function and you're right, it is spelled with the e. Thanks for  noticing this and following up!

**Comment by MashaMSFT** [comment]
#sign-off

**Pull request merged**
