### PR TITLE
correction of Event Log property

### PR DESCRIPTION
**Pull request by fatherjack**
'SQLWriter' is in the ProviderName property of the Application Log

### CODE REVIEW

**Comment by PRMerger4** [comment]
@fatherjack : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@Guillaume-Fourrat - Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Guillaume-Fourrat** [comment]
Thanks for the Feedback,
ProviderName is the underlying _XML_ property indeed, but the EventViewer GUI uses the "Event Source" naming everywhere to expose this information to the user. Simply _replacing_ as indicated in PR would confuse most users who access the info through Event Viewer.
Instead, I will _add_ the XML property to make everyone happy =)

**Review by Guillaume-Fourrat — CHANGES_REQUESTED** [review]
please _add_ a reference to Xml "provider name" instead of _replacing_ the GUI "Event Source" reference which is valid.

**Comment by fatherjack** [comment]
> Thanks for the Feedback, ProviderName is the underlying _XML_ property indeed, but the EventViewer GUI uses the "Event Source" naming everywhere to expose this information to the user. Simply _replacing_ as indicated in PR would confuse most users who access the info through Event Viewer. Instead, I will _add_ the XML property to make everyone happy =)

Thanks @Guillaume-Fourrat , I was indeed trying to filter the log contents with PowerShell when I needed to use 'ProviderName', having both in the documentation makes a lot of sense, I appreciate your input.

**Comment by rwestMSFT** [comment]
@Guillaume-Fourrat Is there anything you need from our side on the Docs team to help close this issue?

**Comment by Guillaume-Fourrat** [comment]
> @Guillaume-Fourrat Is there anything you need from our side on the Docs team to help close this issue?

Hi @rwestMSFT, I pushed preview repo PR https://github.com/MicrosoftDocs/sql-docs-pr/pull/25421 to properly address the remark (my github-Fu didn't let me create a PR on top of current one...).
So you can close this one without action / solved by another PR.

**Comment by rwestMSFT** [comment]
#please-close

**Pull request closed without merging**
