### PR TITLE
Configuration Manager rebranding

### PR DESCRIPTION
**Pull request by v-thpra**
[User Story 1643831](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1643831): Content Update: ConfigMgr rebrand
System Center Configuration Manager is now part of Microsoft Endpoint Manager with Intune, Desktop Analytics, Autopilot, and the Device Management Admin Center (DMAC). 

Its full brand name is now **Microsoft Endpoint Configuration Manager**.

This PR addresses the rebranding of all instances of "System Center Configuration Manager" in this repo.

Note: I edited the include file to remove an extra space at the end.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@v-thpra : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-thpra** [comment]
@maggiesMSFT Is it possible to get this reviewed? It was submitted 2 weeks ago and I don't want it to get stale. Thanks!

**Comment by v-thpra** [comment]
@maggiesMSFT Updated the ms.date. Thanks for the review!

**Comment by maggiesMSFT** [comment]
#sign-off

**Pull request merged**
