### PR TITLE
Update download-azure-data-studio.md

### PR DESCRIPTION
**Pull request by snwnst**
Update macOS list of Supported Operating Systems

### CODE REVIEW

**Comment by PRMerger20** [comment]
@snwnst : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by snwnst** [comment]
Is a only little change of the documentation.

**Comment by ktoliver** [comment]
@snwnst Thanks for your pull request. The PR has been assigned to the article author @yualan to review it. Thanks.

**Comment by rothja** [comment]
@snwnst Thank you for this suggested addition. @markingmyname Mark, I am adding you as well in case you know. Thank you. #assign:markingmyname

**Comment by markingmyname** [comment]
@snwnst, thank you for your contribution.

approved.

#sign-off

**Comment by PRMerger14** [comment]
@markingmyname: I'm sorry - only the author of this article, @yualan, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@markingmyname: I'm sorry - only the author of this article, @yualan, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
