### PR TITLE
Update sql-server-backup-to-url-best-practices-and-troubleshooting.md

### PR DESCRIPTION
**Pull request by ujpat**

### CODE REVIEW

**Comment by ujpat** [comment]
added common issues and solutions

**Comment by Court72** [comment]
@WilliamDAssafMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @ujpat this content is great for customers.  I've pushed a commit for an edit pass. 
I think we should say more about the item `Backup failed when using a maintenance plan.`  aside from just advising them to abandon their maintenance plan. 
+ @SudhirRaparla @Hemin-MSFT to review

**Comment by MashaMSFT** [comment]
closing for https://github.com/MicrosoftDocs/sql-docs-pr/pull/27782

**Pull request closed without merging**
