### PR TITLE
TCP/IP is not default for all Edition

### PR DESCRIPTION
**Pull request by taroarai**
For SQL Server Express and Developer Edition, TCP/IP is disabled by default, so it should remove TCP/IP as default here, instead it should link to following page for default configuration.

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/default-sql-server-network-protocol-configuration?view=sql-server-ver15

### CODE REVIEW

**Comment by PRMerger4** [comment]
@taroarai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by markingmyname — APPROVED** [review]

**Comment by markingmyname** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@markingmyname, these changes should be moved to the private repo for validation and staging. Can you do that? Thanks.

**Comment by jborsecnik** [comment]
@taroarai, Microsoft staff are expected to work in the private repo. Otherwise changes like this (includes, formatting, links, images), need to be moved to the private repo, which supports staging view and build validation. Can you submit these changes to the private repo? 

See [How to get to the private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=main#how-to-get-to-the-private-repo). You can also take a look at the [GitHub account setup page](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=main) for additional details on making sure you're set up.

@markingmyname

**Comment by taroarai** [comment]
I'm CSS, so it is ok to submit on publisc as in your doc.
Well, I filed one on private repo.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/21731

**Comment by ShannonLeavitt** [comment]
Thanks for moving the commits to the private repo @taroarai 

You can sign-off on the PR when you're ready for a review. I'll close this public PR now.

**Pull request closed without merging**
