### PR TITLE
Update sys-foreign-key-columns-transact-sql.md

### PR DESCRIPTION
**Pull request by rjk**
Added an example to show how the view should be joined. Without an example like this it's super hard to work out.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@rjk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by rwestMSFT** [comment]
@rjk Thank you for the suggestion to add an example query. This article needed a refresh, so I have submitted a PR against your branch with proposed updates to bring it up to 2022 standards. Once you approve that it'll update here, and then I'll give it another quick check before approving it.

**Comment by PRMerger14** [comment]
@rjk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rwestMSFT** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
@rwestMSFT - The changes in this PR would benefit from automated checks and validation. Can you move the commits to the private repo and submit the content there? If you need help moving the commits, contact our alias: techdocprs.

#hold-off

**Comment by ShannonLeavitt** [comment]
@rwestMSFT - An alternative is to remove your commits and approve only the commit that @rjk added. Then you can make your further adjustments in the private repo.

**Comment by rwestMSFT** [comment]
@rjk Closing this because it's been handed off to an internal PR. You will retain credit for your contribution, which should reflect in the next day or so.

#please-close

**Pull request closed without merging**
