### PR TITLE
Update sql-server-linux-configure-msdtc-docker.md

### PR DESCRIPTION
**Pull request by roberto-mardeni**
Replaced MSSQL_SA_PASSWORD for SA_PASSWORD

### CODE REVIEW

**Comment by PRMerger20** [comment]
@roberto-mardeni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hello @roberto-mardeni! Thank you for this submission! Can you please provide some details for this change request?

**Comment by roberto-mardeni** [comment]
Because the newest container image available at https://hub.docker.com/_/microsoft-mssql-server indicates that the environment variable for the password is SA_PASSWORD and not MSSQL_SA_PASSWORD

**Comment by VanMSFT** [comment]
Thanks, @roberto-mardeni!

@vin-yu - Can you please help confirm the change?

**Comment by VanMSFT** [comment]
Confirmed with Vin.

Thanks @roberto-mardeni! We appreciate your assistance on our documentation!

#sign-off

**Pull request merged**
