### PR TITLE
Do not use "current version" but keep referring to 2016

### PR DESCRIPTION
**Pull request by SvenAelterman**

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @SvenAelterman for all of your help!   @CarlRabeler please review

**Comment by CarlRabeler** [comment]
Reviewing and updating in a separate PR. Stay tuned.
Carl

**Comment by craigg-msft** [comment]
@CarlRabeler should we then close this PR? it now has a merge conflict.

**Comment by CarlRabeler** [comment]
#close  @craigg-msft yes - please close - fixed in another PR

**Comment by CarlRabeler** [comment]
please close

**Comment by CarlRabeler** [comment]
# please close 
#pleaseclose 
#pleaseclose

**Pull request closed without merging**
