### PR TITLE
Update automatic-seeding-secondary-replicas.md

### PR DESCRIPTION
**Pull request by sidesw1pe**
Can the database owner have an owner?

### CODE REVIEW

**Comment by PRMerger16** [comment]
@sidesw1pe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by cawrites — COMMENTED** [review]
reviewed

**Comment by cawrites** [comment]
@rothja is there an action needed for this tag? keep open

**Comment by rothja** [comment]
@cawrites No need to do anything for the keep-open tag. If the change that sidesw1pe recommends is accepted, you can sign off. Thank you!

**Comment by cawrites** [comment]
@sidesw1pe thank you for contacting Microsoft your update will appear in the next content refresh.

**Pull request merged**
