### PR TITLE
Add default for HeapTypeForObjects

### PR DESCRIPTION
**Pull request by matt40k**
Add the default option for HeapTypeForObjects

### CODE REVIEW

**Comment by craigg-msft** [comment]
@Minewiskan please review

**Comment by Minewiskan** [comment]
@matt40k Yes. This one should be included. Thanks for contributing, Matt.
#sign-off

**Comment by amirchandani** [comment]
VertipaqPagingPolicy should say:
0 --> (default for Azure AS)
1 --> (default for Analysis Services)


In description, Azure AS should mention that VPP=1 should not be used due to the hard job limits on the AS process in the service. These hard limits can cause out of memory errors when paging is enabled, and therefore customers should stay with VPP=0 in AAS.

**Comment by matt40k** [comment]
Hey @amirchandani!
This isn't the right place to raise this bug as this was for a different bug and it's for "pulling" the fix. 
You should look at creating a new pull request - info here https://docs.microsoft.com/en-gb/sql/sql-server/sql-server-docs-contribute?view=sql-server-2017

**Comment by amirchandani** [comment]
Thanks @matt40k, my mistake - I think @Minewiskan is taking care of this issue...

**Comment by Minewiskan** [comment]
@matt40k @amirchandani I'm a bit confused by which fix is which. Can you both take a look at https://docs.microsoft.com/en-us/sql/analysis-services/server-properties/memory-properties and make sure what you're asking for is shown?  
Thanks

**Comment by matt40k** [comment]
Looks good to me 👍

**Pull request merged**
