### PR TITLE
Remove PKI acronym

### PR DESCRIPTION
**Pull request by sensomatic**
The PKI acronym is not relevant in this context and so I removed it. It does not stand for Public Key Cryptography and although some aspects of a PKI are discussed here, it is not specifically about PKI, but more about Asymmetric keys and certificates

### CODE REVIEW

**Comment by PRMerger18** [comment]
@sensomatic : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@sensomatic The initialism 'PKI' stands for Public Key Infrastructure. But the initialism is defined inaccurately in the original documentation, and it was never used in the article, and thus was superfluous. Your recommendation to remove "(PKI)" thus makes sense.  Thank you for this edit.
#sign-off

**Comment by PRMerger16** [comment]
@MightyPen: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by craigg-msft** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@craigg-msft: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger9** [comment]
@sensomatic : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by sensomatic** [comment]
Resolved merge conflict from the other change I made on the same line.

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
