### PR TITLE
Update sp-add-jobschedule-transact-sql.md

### PR DESCRIPTION
**Pull request by kendra-little**
Got a little confused when first looking at this page, I think this fixes it. Thanks!

### CODE REVIEW

**Comment by ttorble** [comment]
@markingmyname 

Can you review the proposed changes?  

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.  

#label:"aq-pr-triaged" 
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
This pattern appears in several articles under system stored procedures, so I'll adopt your change into an internal PR.

**Comment by kendra-little** [comment]
thank you! (hopefully this comment doesn't reopen it)

**Comment by rwestMSFT** [comment]
No, this isn't JIRA 😄

**Pull request closed without merging**
