### PR TITLE
Largest Allocaiton unit is 32 MB in NTFS

### PR DESCRIPTION
**Pull request by PiJoCoder**
format /?
 /A:size         Overrides the default allocation unit size. Default settings
                  are strongly recommended for general use.
                  ReFS supports 4096, 64K.
                  NTFS supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
                  128K, 256K, 512K, 1M, 2M.
                  FAT supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
                  (128K, 256K for sector size > 512 bytes).
                  FAT32 supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
                  (128K, 256K for sector size > 512 bytes).
                  exFAT supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
                  128K, 256K, 512K, 1M, 2M, 4M, 8M, 16M, 32M.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@PiJoCoder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DBArgenis** [comment]
@PiJoCoder the largest NTFS allocation unit is 2MB, not 32MB.

**Review by datalaunderer — COMMENTED** [review]
This PR should not go through, as the maximum AU in NTFS in Windows Server 2019 is still 2MB.

**Comment by PiJoCoder** [comment]
@DBArgenis, you are right. I just tested this by attempting a NTFS format on a partition and the maximum is 2 MB. 
I filed this because if you go to command prompt and do 
format /? 
… you will be presented with these choices that go up to 32 MB! Looks like a bug in FORMAT help

/A:size Overrides the default allocation unit size. Default settings
are strongly recommended for general use.
ReFS supports 4096, 64K.
NTFS supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
128K, 256K, 512K, 1M, 2M.
FAT supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
(128K, 256K for sector size > 512 bytes).
FAT32 supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
(128K, 256K for sector size > 512 bytes).
exFAT supports 512, 1024, 2048, 4096, 8192, 16K, 32K, 64K,
128K, 256K, 512K, 1M, 2M, 4M, 8M, **16M, 32M.**

**Comment by DBArgenis** [comment]
The 32MB mention is specific to exFAT, which is not a filesystem that we support for SQL Server

**Pull request closed without merging**
