### PR TITLE
Update what-s-new-in-ssma-for-db2-db2tosql.md

### PR DESCRIPTION
**Pull request by nilabjaball**
#sign-off

### CODE REVIEW

**Comment by PRMerger5** [comment]
@nilabjaball : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by nilabjaball** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@nilabjaball: I'm sorry - only the author of this article, @nahk-ivanov, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Merging exception per email

**Pull request merged**
