### PR TITLE
Clarified limitations of basic AGs

### PR DESCRIPTION
**Pull request by kfarlee**
Clarified that you can have multiple Basic AGs on an instance, and that Basic AGs are only supported for Standard.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@kfarlee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @kfarlee - Just a reminder to work in the private repository. To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. Thanks!

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
