### PR TITLE
Quickstart - Connect and query Managed Service for TimescaleDB on Azure

### PR DESCRIPTION
**Pull request by Rajakavitha1**
- Created a new guide to connect and query Managed Service for TimescaleDB on Azure.
- Azure Data Studio is the preferred tool to query and administer the TimescaleDB on Azure, this guide addresses the need of such users.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rothja - Can you review this PR?


If you decide to accept this new content, an internal Microsoft content creator/manager will need to own the content and open a new PR in the private repo. 

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rothja** [comment]
@Rajakavitha1 Thanks for the proposal. We will need to coordinate with the Azure Data Studio product team to discuss this suggested content and see if it should go into our product docs. I have asked @markingmyname (Mark) to reach out to the product team to share your ideas and get back to you. Thank you for your patience!

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 Thanks for the proposal. We will need to coordinate with the Azure Data Studio product team to discuss this suggested content and see if it should go into our product docs. I have asked @markingmyname (Mark) to reach out to the product team to share your ideas and get back to you. Thank you for your patience!

Thank you @rothja for considering this. Not many know that they can connect to a PostgreSQL server using Azure Data Studio that is why wanted to advocate it in the ADS documentation.

**Comment by markingmyname** [comment]
@Rajakavitha1 

We are reviewing this PR.

Unfortunately, new Microsoft content cannot be submitted via the public repo.

Once the content has been reviewed and approved, we will move this content to the private repo.

However, we will work with you to add you as a contributor to this content.

thank you.

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1
> 
> We are reviewing this PR.
> 
> Unfortunately, new Microsoft content cannot be submitted via the public repo.
> 
> Once the content has been reviewed and approved, we will move this content to the private repo.
> 
> However, we will work with you to add you as a contributor to this content.
> 
> thank you.

Thanks for the update @markingmyname !!!! I really appreciate the time and efforts you invested in reviewing external contributions to the content.

**Comment by Rajakavitha1** [comment]
Hi @markingmyname !!! I am not sure if you got an opportunity to review this PR yet!!! Just wanted to check if there is anything amiss?

**Comment by markingmyname** [comment]
@Rajakavitha1 

I thank you very much for your contribution.

We've decided to move forward with this new content.

We plan on releasing this content later this week.

If we can't this week, it will be early next week.

Thank you., again.

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1
> 
> I thank you very much for your contribution.
> 
> We've decided to move forward with this new content.
> 
> We plan on releasing this content later this week.
> 
> If we can't this week, it will be early next week.
> 
> Thank you., again.

Thank you @markingmyname  and team for the update.

**Comment by markingmyname** [comment]
This content will be live by tomorrow at the latest.

Also, I would recommend that you make an edit to the article.  I would like your alias to be tied to this content.

Thank you.

**Comment by Rajakavitha1** [comment]
> This content will be live by tomorrow at the latest.
> 
> Also, I would recommend that you make an edit to the article. I would like your alias to be tied to this content.
> 
> Thank you.

Thank you @markingmyname !!!

**Comment by markingmyname** [comment]
> > This content will be live by tomorrow at the latest.
> > Also, I would recommend that you make an edit to the article. I would like your alias to be tied to this content.
> > Thank you.
> 
> Thank you @markingmyname Mark Ghanayem FTE !!!

Thanks for being patient with us.  Thank you again for this valuable information.

**Pull request closed without merging**
