### PR TITLE
Adding EnablePowerBIReportExportUnderlyingData

### PR DESCRIPTION
**Pull request by tekulkar**
Updating description for EnablePowerBIReportExportUnderlyingData

### CODE REVIEW

**Comment by PRMerger9** [comment]
@tekulkar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by RhysSchmidtke** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@RhysSchmidtke: I'm sorry - only the author of this article, @maggiesMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@maggiesMSFT - As author on the content side, could you review the proposed changes? Thanks.

**Comment by maggiesMSFT** [comment]
sign-off

**Pull request merged**
