### PR TITLE
Audit path clarification

### PR DESCRIPTION
**Pull request by JamesFerebee**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@JamesFerebee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@JamesFerebee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @JamesFerebee! Sorry for the delay! We really appreciate you helping with our documentation. I will approve these changes.

#sign-off

**Pull request merged**
