### PR TITLE
Typo in sql-server-management-studio-changelog-ssms.md

### PR DESCRIPTION
**Pull request by agriffard**
Remove dupllicated 'the'.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@agriffard : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@agriffard - Thanks for the fix!  I see you also added a carriage return on line 660 - if you can fix that and resubmit I'll accept your update.

**Comment by PRMerger15** [comment]
@agriffard : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@agriffard - Thanks again for the edit!

#sign-off - this PR is ready to merge.

**Pull request merged**
