### PR TITLE
Updated R and Python Extension Links

### PR DESCRIPTION
**Pull request by wallig1**
I updated the introduction paragraphs to include R and Python Support. 
I updated the getting started section with links to the R and Python install sites plus the open source extension links to the source code.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@wallig1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by twright-msft — CHANGES_REQUESTED** [review]
Michelle - I'm thinking we should pull the instructions for Java out into their own article like R and Python so that there is symmetry.

On the open source extensions - would be good to have a short paragraph explaining what they are and what the use casese for them are and then a link to them.  Probably should just point to the root of the repo there rather tnan go directly to the /releases page.

**Comment by ktoliver** [comment]
Hi @wallig1 - Per the Microsoft Docs contributor guide, PMs should work in the private repo. Would you close this PR and make your updates in a new PR in the private repo instead? Thanks.

**Comment by wallig1** [comment]
This is the first time I’ve done this so I don’t even understand your instructions. Got a video to show me how?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ktoliver** [comment]
> This is the first time I’ve done this so I don’t even understand your instructions. Got a video to show me how? Get Outlook for 

@wallig1 - Understood, no worries. I'll send you email with the information. Thanks!

**Comment by dphansen** [comment]
@wright-msft @wallig1 We have a work item for the next sprint to get this done. Let us discuss in tomorrow's sync meeting. I'm closing this PR.

**Comment by wallig1** [comment]
Great!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
