### PR TITLE
Update alter-database-scoped-configuration-transact-sql.md

### PR DESCRIPTION
**Pull request by erikdarlingdata**
Reword the section on MAXDOP and add a supporting link.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@erikdarlingdata : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @erikdarlingdata for submitting this PR. Your commit will be merged along with a couple of mine. This article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 

Thanks again for this feedback, your suggestions help improve our documentation.

**Pull request merged**
