### PR TITLE
Updated the reseed documentation

### PR DESCRIPTION
**Pull request by way0utwest**
The doc currently says in 2008 R2 and earlier the next insert is new_reseed_value + current increment. This is not correct. Tested in 2014, 2016, 2017, the increment is applied in those versions. I do not have 2008R2 or 2008 to test the validity of the "or earlier" statement. It is possible this should be (or later).

Repro: 
CREATE TABLE dbo.SalesOrderHeader
( OrderKey INT IDENTITY(1, 1) 
, CustomerName VARCHAR(30)
)
GO

INSERT dbo.SalesOrderHeader (CustomerName) VALUES ('Andy')
INSERT dbo.SalesOrderHeader (CustomerName) VALUES ('Brian')
INSERT dbo.SalesOrderHeader (CustomerName) VALUES ('Steve')
GO
DBCC CHECKIDENT(SalesOrderHeader, RESEED, 20)
GO
INSERT dbo.SalesOrderHeader (CustomerName) VALUES ('Azure')
GO
SELECT * FROM dbo.SalesOrderHeader AS soh
GO

### CODE REVIEW

**Comment by PRMerger16** [comment]
@way0utwest : Thanks for your contribution! The author, @uc-msft, has been notified to review your proposed change.

**Comment by srutzky** [comment]
Hi everyone. I have some changes to make to this same page and am not sure how to proceed given this PRs status. My changes would include, and then supersede, this change. I don't see a way for me to submit a change for this particular commit. Should I just submit my change independently and let merge work its magic after this is merged? Or should mine replace this one since it include the same change?

**Comment by srutzky** [comment]
FYI: I just submitted PR #1602 with my edits of this same file.

**Comment by craigg-msft** [comment]
Thank you @way0utwest apologies for the delay.  Based on emails with @uc-msft he thought the changes looked good.  #sign-off

**Comment by PRMerger12** [comment]
@craigg-msft: I'm sorry - only the author of this article, @uc-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
