### PR TITLE
Typo "I O"→"I¥/O"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-backup-tapes-transact-sql?view=sql-server-2017

### CODE REVIEW

**Comment by PRMerger6** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
confirmed correction; thanks

**Pull request merged**
