### PR TITLE
Update sys-sp-cdc-stop-job-transact-sql.md

### PR DESCRIPTION
**Pull request by WinoskyJean**
* Job type parameter in example is capture.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@WinoskyJean : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by markingmyname — APPROVED** [review]
Approved.

Thank you for your contribution.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
