### PR TITLE
Make formatting consistent for SQL examples under "CREATE INDEX" page

### PR DESCRIPTION
**Pull request by kabirbaidhya**
Page Edited - [CREATE INDEX (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sqlallproducts-allversions)

### Changes
 - Capitalize SQL types and keywords
 - Add semi-colons to the statements that are missing them
 - Make indentation and spacing consistent across the page
 - Proper spacing in comments and in-between operators for readability.  

Related to https://github.com/MicrosoftDocs/sql-docs/pull/2979

### CODE REVIEW

**Comment by PRMerger17** [comment]
@kabirbaidhya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by pmasl** [comment]
@kabirbaidhya correct the typo in line 1062 and I can sign-off

WITH (DATA_COMPRESSION = ROWs); **should be** WITH (DATA_COMPRESSION = ROW);

**Comment by kabirbaidhya** [comment]
Sorry, my bad; fixing.

**Comment by PRMerger9** [comment]
@kabirbaidhya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@kabirbaidhya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@kabirbaidhya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kabirbaidhya** [comment]
@pmasl Done.

**Comment by jborsecnik** [comment]
@pmasl, please add `#sign-off` if this is okay to merge. Thanks.

**Comment by pmasl** [comment]
@jborsecnik yes please

**Comment by pmasl** [comment]
#sign-off

**Pull request merged**
