### PR TITLE
unit\app --> SQL\query

### PR DESCRIPTION
**Pull request by imba-tjd**
`unit\app` is an example of alternate NP, not default.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@imba-tjd : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by pmasl** [comment]
It's correct. #sign-off

**Comment by PRMerger18** [comment]
@pmasl: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by pmasl** [comment]
@MikeRayMSFT it's correct. Tried to sign-off but seems I can't 👎

**Pull request merged**
