### PR TITLE
Update mssqlserver-21892-database-engine-error.md

### PR DESCRIPTION
**Pull request by LowlyDBA**
Fix missing letter typos

### CODE REVIEW

**Comment by PRMerger17** [comment]
@LowlyDBA : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by LitKnd — APPROVED** [review]

**Comment by LitKnd** [comment]
Hi @LowlyDBA ,

Thanks for making this contribution to clarify the meaning in this article. We very much appreciate it. 

Kendra from the SQL Docs team

#sign-off

**Comment by PRMerger13** [comment]
@LitKnd: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
Thanks @ktoliver  for catching these while some of our teammates are helping us play catch up!

**Pull request merged**
