### PR TITLE
READ_WRITE_ROUTING_URL is missing description

### PR DESCRIPTION
**Pull request by taroarai**
READ_WRITE_ROUTING_URL is documented in syntax part, but it does not have discription nor link to following Docs.

Secondary to primary replica read/write connection redirection (Always On Availability Groups)
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/secondary-replica-connection-redirection-always-on-availability-groups?view=sql-server-ver15

### CODE REVIEW

**Comment by PRMerger6** [comment]
@taroarai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Reviewing.

**Comment by ktoliver** [comment]
@MikeRayMSFT Is the PR ready to merge? Thanks.

**Comment by rothja** [comment]
@MikeRayMSFT It looks like Kevin approved these changes. Can you take on last look at the content/formatting and then sign off? Thanks!

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
