### PR TITLE
Corrections & improvements to instructions for moving SQL system databases

### PR DESCRIPTION
**Pull request by philosophicles**
I know there's also a warning at the top of the page, but a second mention of file permissions in the step-by-step instructions doesn't hurt.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@philosophicles : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by philosophicles** [comment]
I have just added a second commit addressing a different section of the same page, re moving the `master` database files.

**Comment by PRMerger16** [comment]
@philosophicles : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevestein** [comment]
@philosophicles - thanks for updating and clarifying the steps.

#sign-off

**Pull request merged**
