### PR TITLE
IP address is not supported

### PR DESCRIPTION
**Pull request by taroarai**
As RFC 13373362, IP address is not supported.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@taroarai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
thanks @taroarai! #sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
