### PR TITLE
Update sql-server-linux-performance-best-practices.md for vm.legacy_va_layout issue

### PR DESCRIPTION
**Pull request by pradm**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@pradm : Thanks for your contribution! The author, @rgward, has been notified to review your proposed change.

**Comment by rothja** [comment]
@pradm Thanks! If you click on the files tab, you'll see I made a few minor changes. I probably made them after you checked. :) Hope these are OK.

**Comment by pradm** [comment]
Sir, Can we make few more changes as below, i have just added word "configuration"
"Linux O/S legacy VM layout configuration is not compatible for SQL. Make sure that **vm.legacy_va_layout** is set to 0 and **Soft Stack limit** is set to 8192. For more information, see [https://support.microsoft.com/help/4134638/sql-server-2017-terminates-and-generates-a-core-dump-on-rhel-7-4-when](https://support.microsoft.com/help/4134638/sql-server-2017-terminates-and-generates-a-core-dump-on-rhel-7-4-when)."

**Comment by pradm** [comment]
Sir, Please revert this change back as Bob Ward had suggested this does not fall under performance best practices and it might add confusion. My apologies for wasting your time.

**Comment by rothja** [comment]
@pradm Thanks. Closing pull request without merging.

**Pull request closed without merging**
