### PR TITLE
Roleremovalconnect

### PR DESCRIPTION
**Pull request by pochiraju**

### CODE REVIEW

**Comment by jborsecnik** [comment]
@anosov1960, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by pochiraju** [comment]
#sign-off

**Comment by pochiraju** [comment]
#sign-off

**Comment by markingmyname** [comment]
@jborsecnik

The owner of this article is out all this week.

@pochiraju is his colleague and has made changes.

i made @pochiraju use the sql-docs-pr repo to make changes going forward, but for now, can we sign off on this public change?

Thank you.

**Comment by markingmyname** [comment]
#sign-off

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by MikeRayMSFT** [comment]
#please-close

**Pull request closed without merging**
