### PR TITLE
Fix backupset-transact-sql.md / Syntax Error

### PR DESCRIPTION
**Pull request by OriShavit1**
Syntax error, missed "F" on FROM statement

### CODE REVIEW

**Comment by Jak-MS** [comment]
@VanMSFT 
- Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@Jak-MS This is a duplicate of #8007.

**Comment by OriShavit1** [comment]
> @Jak-MS This is a duplicate of #8007.
Hi rwest, are you certain? The latest version in #8007 has the same "ROM" keyword at line 158.

**Comment by Jak-MS** [comment]
@rwestMSFT - if this should be closed, please add `#please-close` in a comment. thanks!

**Comment by rwestMSFT** [comment]
@Jak-MS

They’re duplicates of the same issue where the script doesn’t work. I haven’t looked at the script itself yet, but I will adopt the 8007 PR into an internal PR and make sure it works.

**Pull request closed without merging**
