### PR TITLE
Update database-instant-file-initialization.md "Perform Volume Mainte…

### PR DESCRIPTION
**Pull request by itscarlo-nobnos**
…nance Tasks"

Navigation tip for completeness.

### CODE REVIEW

**Comment by itscarlo-nobnos** [comment]
#sign-off

**Comment by American-Dipper** [comment]
@WilliamDAssafMSFT - can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Hi @itscarlo-nobnos. Double-click and right-click+**Properties** have the same result here. It's not necessary to explain both, unless there's something I'm missing?

**Comment by itscarlo-nobnos** [comment]
Apologies @WilliamDAssafMSFT - that's so right! I was so myopic in what I was reading, I didn't even bother to double-click! Ugh. Disregard that suggestion.  This is my first few steps and slowly learning how to navigate around GitHub. Thanks for your response. Cheers!

**Comment by Court72** [comment]
@itscarlo-nobnos - Can this PR be closed?

**Pull request closed without merging**
