### PR TITLE
Clarified wording in new column master key dialog

### PR DESCRIPTION
**Pull request by greglow**
Just minor clarification on the wording. Also it refers to a key where I think it should say certificate instead, as the list contains certificates.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@greglow : Thanks for your contribution! The author, @jaszymas, has been notified to review your proposed change.

**Comment by jaszymas** [comment]
Please note that the key can be either a certificate (if the user selected Windows Certificate Store in step 3) or a key in Azure Key Vault (which is not a certificate). Could you  rephrase to something like this: "a certificate or an Azure Key Vault key"?

**Comment by PRMerger8** [comment]
@greglow : Thanks for your contribution! The author, @jaszymas, has been notified to review your proposed change.

**Comment by greglow** [comment]
Done

 

 

Regards,

 

Greg

 

Dr Greg Low

 

1300SQLSQL (1300 775 775) office | +61 419201410 mobile│ +61 3 8676 4913 fax

SQL Down Under | Web:  <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sqldownunder.com%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091516274&sdata=SLHeEGAMmWUY5YIwcC4oAPYr%2F9RIZdi4MNASsdzwX2I%3D&reserved=0> www.sqldownunder.com | <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgreglow.me%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091526278&sdata=IU8tnAITCjBxWafi3A9XpO9lF3PIwZJ8ad3t36lnxvs%3D&reserved=0> http://greglow.me

**Comment by jaszymas** [comment]
#sign-off

**Pull request merged**
