### PR TITLE
Supportability notes on Synapse Dedicated Pools

### PR DESCRIPTION
**Pull request by nachoalonsoportillo**

### CODE REVIEW

**Comment by Court72** [comment]
@markingmyname

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by markingmyname** [comment]
@WilliamDAssafMSFT - can I ask if these changes are acceptable?

**Comment by markingmyname** [comment]
@nachoalonsoportillo

Apologies for the delayed response

I'm verifying if these changes align with our current guidelines.

Thank you.

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @nachoalonsoportillo for taking the time to submit this PR! Good catch. Your commit will be merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 
#sign-off

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
