### PR TITLE
Fixed a minor notation error

### PR DESCRIPTION
**Pull request by saitorhan**
The note field does not appear in the note format. Fixed minor notation error here.

image

### CODE REVIEW

**Comment by PRMerger8** [comment]
@saitorhan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by saitorhan** [comment]
@VanMSFT Excuse me because of this little notation error which was in previous pull request.

**Comment by VanMSFT** [comment]
Thanks, @saitorhan!

#sign-off

**Comment by ktoliver** [comment]
Oooh, that was my typo. Apologies. Merging now.

**Pull request merged**
