### PR TITLE
Direct links to SSMS setup file in different languages

### PR DESCRIPTION
**Pull request by MikeyBronowski**
Inspired by the discussion on this thread.
https://docs.microsoft.com/en-us/answers/questions/606157/direct-link-ssms-french.html

Updating links to the direct links of the SSMS setup in different languages, so the link always downloads the latest version of the SSMS - no need to update the links after the release of a new version.

Tested and each link downloads different language version of the SSMS.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@MikeyBronowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by dzsquared** [comment]
very nice, thanks @MikeyBronowski!

#sign-off

**Review by dzsquared — APPROVED** [review]

**Review by Matteo-T — APPROVED** [review]
@dzsquared the change looks good to me. Let's make sure that we always update the evergreen link first as par of our release process (I believe we do, but let's double-check).

Thanks @MikeyBronowski !

**Pull request merged**
