### PR TITLE
Typo "[ 1**,**_...n_]"→"[ **,**_...n_]"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-partition-scheme-transact-sql?view=sql-server-ver15
#PingMSFTDoc

### CODE REVIEW

**Comment by PRMerger20** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by WilliamDAssafMSFT — APPROVED** [review]

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @hyoshioka0128  for submitting your feedback. Your suggestions help improve our documentation. This article update is in flight. After the updated article is published, GitHub will list you as an article contributor.

**Pull request merged**
