### PR TITLE
Add a missing dot for sql-server-2016-express-localdb.md

### PR DESCRIPTION
**Pull request by imba-tjd**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@imba-tjd : Thanks for your contribution to the SQL documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@imba-tjd thank you for your contribution! #sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by craigg-msft** [comment]
Thank you @imba-tjd  and @MikeRayMSFT . merging.

**Pull request merged**
