### PR TITLE
Update sql-server-linux-configure-multiple-subnet.md

### PR DESCRIPTION
**Pull request by liweiSecurity**
This document is stalled, customer can't configure SQL Server AG in multiple-subnet scenario. I had meeting session with RHEL team and figured the right now to configure the CIB file.
Please see the RFC https://sqlbuvsts01:8443/Main/SQL%20Server/_workitems#_a=edit&id=13614974 for detail

### CODE REVIEW

**Comment by PRMerger8** [comment]
@liweiSecurity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by liweiSecurity** [comment]
Hi Mike,

Please feel free to reach me if you have any queries.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM – 8:00 PM  Central Time

**Comment by liweiSecurity** [comment]
Thanks for following up. I'm going to pull your changes into the private repo before staging to make sure the code blocks all validate and render correctly.

From: Liwei Yin <liweiyin@microsoft.com>
Sent: Tuesday, July 28, 2020 9:05 AM
To: Mike Ray (SQL) <Mike.Ray@microsoft.com>; MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Hi Mike,

Please feel free to reach me if you have any queries.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

**Comment by liweiSecurity** [comment]
Thanks Mike.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

From: Mike Ray (SQL) <Mike.Ray@microsoft.com>
Sent: Tuesday, July 28, 2020 11:10 AM
To: Liwei Yin <liweiyin@microsoft.com>; MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Thanks for following up. I'm going to pull your changes into the private repo before staging to make sure the code blocks all validate and render correctly.

From: Liwei Yin <liweiyin@microsoft.com<mailto:liweiyin@microsoft.com>>
Sent: Tuesday, July 28, 2020 9:05 AM
To: Mike Ray (SQL) <Mike.Ray@microsoft.com<mailto:Mike.Ray@microsoft.com>>; MicrosoftDocs/sql-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com<mailto:sql-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Hi Mike,

Please feel free to reach me if you have any queries.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

**Comment by liweiSecurity** [comment]
I've signed off on https://github.com/MicrosoftDocs/sql-docs-pr/pull/16293. It will publish through the private repo to public and then merge. Thanks.
Mike

From: Liwei Yin <liweiyin@microsoft.com>
Sent: Tuesday, July 28, 2020 9:14 AM
To: Mike Ray (SQL) <Mike.Ray@microsoft.com>; MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Thanks Mike.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

From: Mike Ray (SQL) <Mike.Ray@microsoft.com<mailto:Mike.Ray@microsoft.com>>
Sent: Tuesday, July 28, 2020 11:10 AM
To: Liwei Yin <liweiyin@microsoft.com<mailto:liweiyin@microsoft.com>>; MicrosoftDocs/sql-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com<mailto:sql-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Thanks for following up. I'm going to pull your changes into the private repo before staging to make sure the code blocks all validate and render correctly.

From: Liwei Yin <liweiyin@microsoft.com<mailto:liweiyin@microsoft.com>>
Sent: Tuesday, July 28, 2020 9:05 AM
To: Mike Ray (SQL) <Mike.Ray@microsoft.com<mailto:Mike.Ray@microsoft.com>>; MicrosoftDocs/sql-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com<mailto:sql-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Hi Mike,

Please feel free to reach me if you have any queries.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

**Comment by liweiSecurity** [comment]
Great , thanks Mike.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

From: Mike Ray (SQL) <Mike.Ray@microsoft.com>
Sent: Tuesday, July 28, 2020 11:39 AM
To: Liwei Yin <liweiyin@microsoft.com>; MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

I've signed off on https://github.com/MicrosoftDocs/sql-docs-pr/pull/16293<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fsql-docs-pr%2Fpull%2F16293&data=02%7C01%7Cliweiyin%40microsoft.com%7C3d62fa4f8c0b4310d2f608d83314c2d8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637315511542388128&sdata=RDyF4d3x0yMn1cWBUzecQr8IundxP5jsgdcQuFkqr4s%3D&reserved=0>. It will publish through the private repo to public and then merge. Thanks.
Mike

From: Liwei Yin <liweiyin@microsoft.com<mailto:liweiyin@microsoft.com>>
Sent: Tuesday, July 28, 2020 9:14 AM
To: Mike Ray (SQL) <Mike.Ray@microsoft.com<mailto:Mike.Ray@microsoft.com>>; MicrosoftDocs/sql-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com<mailto:sql-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Thanks Mike.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

From: Mike Ray (SQL) <Mike.Ray@microsoft.com<mailto:Mike.Ray@microsoft.com>>
Sent: Tuesday, July 28, 2020 11:10 AM
To: Liwei Yin <liweiyin@microsoft.com<mailto:liweiyin@microsoft.com>>; MicrosoftDocs/sql-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com<mailto:sql-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Thanks for following up. I'm going to pull your changes into the private repo before staging to make sure the code blocks all validate and render correctly.

From: Liwei Yin <liweiyin@microsoft.com<mailto:liweiyin@microsoft.com>>
Sent: Tuesday, July 28, 2020 9:05 AM
To: Mike Ray (SQL) <Mike.Ray@microsoft.com<mailto:Mike.Ray@microsoft.com>>; MicrosoftDocs/sql-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com<mailto:sql-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/sql-docs] Update sql-server-linux-configure-multiple-subnet.md (#5241)

Hi Mike,

Please feel free to reach me if you have any queries.

Liwei Yin<mailto:liweiyin@microsoft.com>  | SQL Server Support Escalation Engineer |+1 (701) 492-9732 | Sunday-Wednesday 9:00 AM - 8:00 PM  Central Time

**Comment by MikeRayMSFT** [comment]
Merged in private repo. Leaving this PR open to see if it automatically closes after publishing and merge to public repo.

**Comment by jborsecnik** [comment]
Private repo version of this change is merged.

**Pull request closed without merging**
