### PR TITLE
Update transparent-data-encryption.md

### PR DESCRIPTION
**Pull request by HeminMSFT**
Removing TDE section was missing

### CODE REVIEW

**Comment by PRMerger13** [comment]
@HeminMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks, @HeminMSFT!

#sign-off

**Comment by PRMerger14** [comment]
@VanMSFT: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
