### PR TITLE
Removed "In public preview"

### PR DESCRIPTION
**Pull request by omarv74**
Closes #95997 - https://github.com/MicrosoftDocs/azure-docs/issues/95997
Removed "In public preview" text that references a feature that is now GA

### CODE REVIEW

**Comment by PRMerger19** [comment]
@omarv74 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@GithubMirek 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
#sign-off

**Comment by PRMerger9** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @GithubMirek

**Comment by VanMSFT** [comment]
Thanks @omarv74 for catching this! We really appreciate your help.

#sign-off

**Comment by PRMerger18** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @GithubMirek

**Pull request merged**
