### PR TITLE
Changed unique index advice to unique constraint

### PR DESCRIPTION
**Pull request by greglow-sdu**
In the advice given here, if you need to enforce uniqueness for a column that has a sequence value, the first choice should be a unique constraint, not a unique index i.e. it should be an attribute of the table design, not an index external to the table.

### CODE REVIEW

**Comment by Court72** [comment]
@MashaMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Greg, since a unique constraint is implemented as a unique index anyway, do you not consider this a semantic difference?

**Comment by greglow-sdu** [comment]
Hi Randolph,

Not, not at all. Regardless of the implementation, uniqueness is a business/logical requirement that should be part of the table design, and an attribute of the table, not an attribute of an external object like an index.

In general, I think that writing CREATE UNIQUE INDEX is a design flaw, unless you are specifically working around one of the limitations of how SQL Server implements uniqueness, which are unlikely to apply here.

We should be encouraging better design in the docs.

Regards,

Greg

Dr Greg Low

1300SQLSQL (1300 775 775) office 
SQL Down Under | Web: https://sqldownunder.com<https://sqldownunder.com/> | About Greg:  https://about.me/greg.low

**Comment by MashaMSFT** [comment]
Hi @greglow-sdu , thanks so much for your submission! #sign-off

**Pull request merged**
