### PR TITLE
Make titles (and their formatting) consistent

### PR DESCRIPTION
**Pull request by srutzky**
Made titles and formatting consistent using the following as guides:

* -- (Comment) (Transact-SQL)
* \+ (String Concatenation) (Transact-SQL)
* Percent character (Wildcard - Character(s) to Match) (Transact-SQL)

Changes:

* Made all titles use " (Transact-SQL)" where some had "-Transact-SQL". In most cases the correct formatting was in the "title" meta-data.
* Renamed "Add EQUALS" (i.e. `+=` for numbers) to be "Add and Assignment" since `=` is assignment, and "equals" implies a test (i.e. `IF`) which this isn't.
* Renamed "Slash Star Comment" to be "Slash Star (Block Comment)" because that is, well, what it is ;-)
* Renamed "+= (String Concatenation - equal)" to be "+= (String Concatenation and Assignment)" since `=` is assignment, and "equal" implies a test (i.e. `IF`) which this isn't.
* See notes in next comment re:
  * Add -&gt; Addition, Multiply -&gt; Multiplication, etc
  * Modulo -&gt; Modulus
* Improvements to the "See Also" section across various pages

### CODE REVIEW

**Comment by srutzky** [comment]
Hold on. I found more changes that need to be made. I had not realized earlier the extent of the compound assignment operators. The naming really should be consistent with pretty much all other languages out there. Here are several examples, all from Microsoft, most of it being within this new "docs" library:

1. **JScript:** [Addition Assignment Operator (+=)](https://msdn.microsoft.com/en-us/library/f6z5yhhs.aspx)
1. **C:** [C Compound Assignment](https://docs.microsoft.com/en-us/cpp/c-language/c-compound-assignment)
1. **C\#:** [+= Operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-assignment-operator)
1. **JavaScript:** [Addition Assignment Operator (+=)](https://docs.microsoft.com/en-us/scripting/javascript/reference/addition-assignment-operator-decrement-equal-javascript)
1. **C\+\+:** [Assignment Operators](https://docs.microsoft.com/en-us/cpp/cpp/assignment-operators)

**Comment by srutzky** [comment]
There are too many changes for the moment. I will resume again tomorrow and post a message indicating when complete.

**Comment by srutzky** [comment]
ALL DONE! (or so I believe 😉 ).

**Comment by srutzky** [comment]
@craigg-msft Just FYI: I am all done this PR now (unless you or a reviewer finds something to change).

**Comment by craigg-msft** [comment]
@srutzky thank you very much.  @v-thepet will review before the end of the week. Apologies for the delay been it has been a busy week with Connect() and your pr contains a fair number of files.  Thank you again @srutzky for all the time.

**Comment by srutzky** [comment]
@craigg-msft You are quite welcome. And no need to apologize about taking a few extra days. I completely understand, and nobody is waiting for these changes :wink: . It is definitely a lot of files so I didn't expect that it would get pushed through quickly.

**Comment by PRmerger** [comment]
@srutzky : Thanks for your contribution to the SQL documentation! The author, @"BYHAM", has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@srutzky Thakns again for all the work.  There are a few formatting things we want to edit and a bit of TOC edits but nothing seems critical. The easiest thing is to merge and then we can work the few remaining issues. on our side.  @v-thepet I am merging and thanks again for the review.

**Comment by srutzky** [comment]
@craigg-msft Yer welcome, and sounds good. Whatever you feel is best. Just out of curiosity, would it have worked to merely edit the files directly in branch of my fork? When I created the PR, I made sure that the "allow owners (or whoever) to make changes" was checked.

**Pull request merged**
