### PR TITLE
Removed duplicated block

### PR DESCRIPTION
**Pull request by ClaudioESSilva**
There is six paragraphs duplicated. Removed the text.

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @ClaudioESSilva  for the help.  @MightyPen please review.

**Comment by MightyPen** [comment]
This proposed change looks good. No tweaks to the change are needed.

**Comment by MightyPen** [comment]
#sign-off

**Comment by MightyPen** [comment]
@craigg-msft @ClaudioESSilva  Craig, please Approve this change. Thanks.

**Pull request merged**
