### PR TITLE
Update distributed-availability-groups.md

### PR DESCRIPTION
**Pull request by kfarlee**
Adding cautions about using Distributed AG to migrate to a new (higher) version of SQL Server

### CODE REVIEW

**Comment by PRMerger14** [comment]
@kfarlee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
Hi @kfarlee - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

**Comment by cawrites** [comment]
thx @Kevin-Farlee @ktoliver

**Pull request merged**
