### PR TITLE
Updates for CTP2.5

### PR DESCRIPTION
**Pull request by mihaelablendea**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@mihaelablendea : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@mihaelablendea : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by mihaelablendea** [comment]
#sign-off @MikeRayMSFT

**Comment by PRMerger20** [comment]
@mihaelablendea: I'm sorry - only the author of this article, @rothja, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
