### PR TITLE
Update columnstore-indexes-overview.md

### PR DESCRIPTION
**Pull request by baleng**
it seems it's possibile to use anchor links , as far i understood i need to add the anchor in the .md file.
i hope it is ok.
i added the 2 anchors referring the 2 cases mentioned , one for create clustered index (with drop existing on) and the other for dropping the CCI converting the table back to an heap.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@baleng : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@baleng : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@baleng : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@baleng thank you for your submission - I updated the label on the links. Good suggestions. I appreciate it. #sign-off

**Pull request merged**
