### PR TITLE
Delete file which was created by mistake.

### PR DESCRIPTION
**Pull request by bgianfo**
It appears this was added by accident, removing it.

### CODE REVIEW

**Comment by bgianfo** [comment]
@NicoleWilbur FYI it looks like this came from your PR?

**Comment by NicoleWilbur** [comment]
Hi,

There were one more pull request than there were files with changes due to an error on my part.

**Comment by ktoliver** [comment]
@rothja Could you review this pull request? Thanks.

**Comment by bgianfo** [comment]
@rothja simple change, should be 1 second review...

**Comment by rothja** [comment]
Sorry for the long delay as I have been out of the office recently. I apologize. #sign-off

**Comment by PRMerger17** [comment]
@rothja: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
