### PR TITLE
added examples

### PR DESCRIPTION
**Pull request by AndreasWolter**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@AndreasWolter : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AndreasWolter** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@AndreasWolter: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @AndreasWolter - This pull request was opened in the public repo. Could you submit content update in the private repo instead? Thank you! We'll close this PR.

**Pull request closed without merging**
