### PR TITLE
Added common server side items that doesn't work with AE

### PR DESCRIPTION
**Pull request by SeanGallardy**
I put a new note under the remarks sections as multiple customers have asked questions about AE not working with certain functionality and that there was nothing that specified it. While I added examples, the list is not exhaustive but does cover the common items.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@SeanGallardy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
awesome, thanks for your submission @SeanGallardy ! I modified the text a little so that it's not a note as it helps with readability. 
#sign-off

**Comment by PRMerger7** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by SeanGallardy** [comment]
Sweet – thank you Masha 😊

**Comment by PRMerger7** [comment]
@SeanGallardy: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MashaMSFT** [comment]
@ktoliver  #sign-off :)

**Comment by PRMerger9** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@MashaMSFT Thanks for the review.

**Pull request merged**
