### PR TITLE
'sp_addmergepulllsubscription' is misspelled

### PR DESCRIPTION
**Pull request by MightyPen**
`sp_addmergepulllsubscription` is misspelled.
Removing one of the three `L`s.  File is 'maintaining-an-always-on-publication-database-sql-server.md'.

By the way, this legacy article, about Replication, has one of the worst CLARITY scores in the whole SQL repo.

( GeneMi = MightyPen )

### CODE REVIEW

**Comment by PRMerger9** [comment]
@MightyPen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, just a misspelling correction, in a SQL Replication article.
Thx, G

**Comment by ktoliver** [comment]
@MashaMSFT The `ms.date` value is in 2016. Do you want to update it to current for freshness, or is it accurate as-is? Thanks.

**Comment by MashaMSFT** [comment]
@ktoliver , since no meaningful changes were made to the article, i'm okay leaving the date as 2016

**Comment by ktoliver** [comment]
Thanks @MashaMSFT We'll merge this typo correction.

**Pull request merged**
