### PR TITLE
Added Redgate entry

### PR DESCRIPTION
**Pull request by A-knight-who-says-ni**
I've added an entry for Redgate's SQL Monitor. Hopefully I've done it correctly :-)

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @A-knight-who-says-ni  @MikeRayMSFT  please review.

**Comment by MikeRayMSFT** [comment]
@craigg-msft this PR is submitted to live. Can you change to master for me? I need to make a few modifications.

**Comment by MikeRayMSFT** [comment]
@A-knight-who-says-ni -- Thank you for submitting this pull request. I've taken your changes and pushed them into our private repository for publishing. I am going to close this PR.

**Comment by craigg-msft** [comment]
Thank you @A-knight-who-says-ni .  also that is the coolest git id yet 👍 Thanks @MikeRayMSFT closing

**Pull request closed without merging**
