### PR TITLE
Update generate-series-transact-sql.md

### PR DESCRIPTION
**Pull request by YorBraakman2022**
Header says 100, example says 10

### CODE REVIEW

**Comment by PRMerger12** [comment]
@YorBraakman2022 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@YorBraakman2022 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@kendalvandyke 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by rwestMSFT** [comment]
We've got an internal PR fixing this because there were enough duplicates. Thanks for bringing this to our attention.

**Pull request closed without merging**
