### PR TITLE
Clarify Bulk-logged recovery model

### PR DESCRIPTION
**Pull request by PiJoCoder**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@PiJoCoder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PiJoCoder** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@PiJoCoder: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
Thanks @PiJoCoder - really appreciate your work in docs.

#sign-off

**Pull request merged**
