### PR TITLE
Update mssqlserver-18264-database-engine-error.md

### PR DESCRIPTION
**Pull request by brettshearer**
Pages Dumped is no longer included in the logs as shown here:  Log was backed up. Database: CW-AG-RefDb-NonEdiProd12-Trf-NZ-000012, creation date(time): 2021/06/01(15:09:20), first LSN: 71:485:1, last LSN: 71:492:1, number of dump devices: 1, device information: (FILE=1, TYPE=DISK: {'NUL'}). This is an informational message only. No user action is required.

I would love if it were included, because there is no other way to see how much data is written in backups processing without resorting to MSDB queres.

### CODE REVIEW

**Comment by Court72** [comment]
@MashaMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@brettshearer We cannot approve this PR until you have signed the license agreement. If you are unable to in the next week or so, we will update the article internally, but you will not get credit.

**Comment by rwestMSFT** [comment]
@brettshearer The source code that generates that error has not changed, so if you are seeing that output, please open a support case. You are also welcome to provide more context here if you are using an on-premises version of SQL Server so that we can follow up.

Closing this, as it is not a documentation issue.

**Comment by PiJoCoder** [comment]
I just tested backups against SQL Server 2017, SQL 2019, SQL 2022 (on-prem SQL engine). 

I see get pages dumped

## SQL 2022

```
2023-03-27 14:40:20.500 Backup       Database backed up. Database: master, creation date(time): 2023/03/27(14:39:07), pages dumped: 532, first LSN: 368:40:1, last LSN: 368:64:1, number of dump devices: 1, device information: (FILE=1, TYPE=DISK: {'c:\temp\master.bak'}). This is an informationa
2023-03-27 14:40:20.520 Backup       BACKUP DATABASE successfully processed 522 pages in 0.030 seconds (135.807 MB/sec).
```


## SQL 2019

```
2023-03-27 16:21:04.73 Backup      Database backed up. Database: master, creation date(time): 2023/03/22(11:09:39), pages dumped: 547, first LSN: 4148:312:1, last LSN: 4148:336:1, number of dump devices: 1, device information: (FILE=1, TYPE=DISK: {'d:\temp\master.bak'}). This is an informational message only. No user action is required.
2023-03-27 16:21:04.76 Backup      BACKUP DATABASE successfully processed 538 pages in 0.337 seconds (12.460 MB/sec).
```

## SQL 2017

```
2023-03-27 16:23:17.720 Backup       Database backed up. Database: master, creation date(time): 2023/03/22(11:09:40), pages dumped: 499, first LSN: 13840:424:94, last LSN: 13840:480:1, number of dump devices: 1, device information: (FILE=2, TYPE=DISK: {'d:\temp\master.bak'}). This is an informational message only. No user action is required.
2023-03-27 16:23:17.750 Backup       BACKUP DATABASE successfully processed 492 pages in 0.246 seconds (15.609 MB/sec).
```

**Pull request closed without merging**
