### PR TITLE
Add missing SQLGetTypeInfo to the list

### PR DESCRIPTION
**Pull request by traceon**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@traceon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@traceon Hello Denis,  I need a bit more info before I decide whether to Approve your interesting Pull Request #3539 .
Can you please add here a Comment explaining why you believe your changes are correct?

Thanks a lot.

**Comment by MightyPen** [comment]
@David-Engel Hi David, Do you have any insight into the changes being proposed by this ODBC PR #3539 ?
If so, I would be interested to know your thoughts on this.
Thx, G.

**Comment by David-Engel** [comment]
@v-chojas Can you confirm that this proposed change is correct? It is adding SQLGetTypeInfo to the list of functions that support both Unicode (W) and ANSI (A) versions.

**Comment by v-chojas** [comment]
@David-Engel Looks good to me.

**Comment by jborsecnik** [comment]
@MightyPen, ok to merge, or do you want more time? Thanks.

**Comment by traceon** [comment]
Hello everyone, thanks for approving and merging, and sorry for the delay - my main argument, just for the record, is as simple as this: it looks like Microsoft's ODBC headers, as well as headers that come with other well-known implementations, support this assumption that `SQLGetTypeInfo` is expected to be `SQLGetTypeInfoW` for a Unicode driver.

**Pull request merged**
