### PR TITLE
Updated the link but...

### PR DESCRIPTION
**Pull request by StingyJack**
... where codeplex is 302'ing does not appear to have these samples. 

This PR is solely to get your attention as the example repo looks to be abandoned or at least not maintained consistently.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@StingyJack : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@StingyJack - Thanks for pointing this out!   I'll take a look and update accordingly.

**Comment by stevestein** [comment]
@StingyJack - Deciding whether to retire this page until we have some up-to-date samples, or if the list of samples is still available and if they are still indeed valid. Will resolve by end of next week. Thanks again for pointing this out.

**Comment by StingyJack** [comment]
Thanks, and sorry for ringing the PR bell on this one. Some of the ones on that page look useful, they just aren't the one I was after.

**Comment by stevestein** [comment]
@StingyJack - I'm going to close this PR and no prob, thanks again for raising the issue on this article.  We're looking into creating some new samples but until then I just deleted this article so it should disappear later this afternoon.  For lack of a better target, this article will redirect to [here ](https://docs.microsoft.com/sql/relational-databases/server-management-objects-smo/how-to-create-a-visual-csharp-smo-project-in-visual-studio-net) for now. Feel free to reach out to me through mail (sstein) and I can see if I can get you hooked up with someone who can help with an example for what you're looking for.

**Pull request closed without merging**
