### PR TITLE
Update view-user-defined-functions.md

### PR DESCRIPTION
**Pull request by AssafFraenkel**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@AssafFraenkel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
private repo

**Comment by niko-neugebauer** [comment]
#sign-off

**Comment by rwestMSFT** [comment]
A reminder to @AssafFraenkel to do these changes in the private repository, please.

**Comment by rwestMSFT** [comment]
#sign-off

**Pull request closed without merging**
