### PR TITLE
Update sql-server-linux-customer-feedback.md

### PR DESCRIPTION
**Pull request by MsSQLGirl**
Update title

### CODE REVIEW

**Comment by PRMerger10** [comment]
@MsSQLGirl : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by MsSQLGirl** [comment]
@MikeRayMSFT

**Comment by MikeRayMSFT** [comment]
@rothja - Julie and I are working on this - please do not publish.

**Comment by PRMerger18** [comment]
@MsSQLGirl : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@MsSQLGirl : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Restaging in private repository. 
https://github.com/MicrosoftDocs/sql-docs-pr/pull/9566

**Pull request closed without merging**
