### PR TITLE
Add TSQL suffix to F1 keywords

### PR DESCRIPTION
**Pull request by zikato**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@zikato : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by markingmyname — CHANGES_REQUESTED** [review]
Remove all the keywords changed and just add - sys.query_store_wait_stats_TSQL - under f1_keywords

**Comment by zikato** [comment]
Ok, I'll do that. I was trying to match the syntax from https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-query-store-query-transact-sql.md

**Comment by PRMerger16** [comment]
@zikato : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by rwestMSFT — APPROVED** [review]

**Comment by rwestMSFT** [comment]
Thanks @zikato!

**Comment by rwestMSFT** [comment]
> Ok, I'll do that. I was trying to match the syntax from https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-query-store-query-transact-sql.md

We are reviewing F1 keywords across all our docset so I'll make a note of this as well. Thanks again.

**Comment by rwestMSFT** [comment]
#sign-off

**Pull request merged**
