### PR TITLE
Update report-server-executionlog-and-the-executionlog3-view.md

### PR DESCRIPTION
**Pull request by GaryAshby**
Amended TimeStart, TimeEnd, TimeDataRetrieval, TimeProcessing and, TimeRendering descriptions to make the document more readable.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@GaryAshby : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@GaryAshby Thank you for this change. It is *much* clearer now that you have made these improvements. @maggiesMSFT Maggie, I am going to approve this as the wording and descriptions seem very clear. But let me know if you have any concerns. Thank you! #sign-off

**Comment by PRMerger6** [comment]
@rothja: I'm sorry - only the author of this article, @maggiesMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by GaryAshby** [comment]
Thanks @rothja and @maggiesMSFT . I’ve delete my branch to clean up. Thanks for all your hard work. Have a wonderful day and have fun.

**Comment by maggiesMSFT** [comment]
Thanks, @GaryAshby and @rothja ! I appreciate your work!

**Pull request merged**
