### PR TITLE
Added note clarifying support for Synapse

### PR DESCRIPTION
**Pull request by willcotton-msft**
configuration options are not supported for Synapse

### CODE REVIEW

**Comment by PRMerger9** [comment]
@willcotton-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @willcotton-msft, will review and confirm with product team.
Adding @mstehrani @qixwang, please review and confirm these details about the SQL Server Query Store feature in Synapse.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @willcotton-msft  for taking the time to contribute to this documentation. A similar doc update has been pushed to clarify, [here](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver15#Options). Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by willcotton-msft** [comment]
Hi William, thanks so much for letting me know. Appreciate the work you guys do.

Have a great weekend!


Regards,
Will Cotton
Support Engineer
Azure Synapse Analytics
Customer Services and Support
Office: +1 (469) 7750368
***@***.******@***.***>
Working hours: Mon-Fri 9am-6pm CDT
If you have any feedback about my work, please let me or my manager Kevin Ledman know at ***@***.******@***.***>.
If you require urgent assistance and are unable to reach me, please reach out to ***@***.******@***.***> and we will find another engineer for you.

**Pull request closed without merging**
