### PR TITLE
Fixed section, removed self-referential link

### PR DESCRIPTION
**Pull request by jzabroski**
The content around default values for the Query Store did not belong under the header for Azure SQL Database.  They should have their own section and be easily referencable via deep URL anchor tag so that people can link from StackOverflow and other sites the list of configuration options.

The last paragraph of the article contains a self-referential link back to this page, which is confusing.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@jzabroski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by WilliamDAssafMSFT — APPROVED** [review]

**Comment by PRMerger12** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @jzabroski for this contribution. Your suggestions help improve our documentation. This article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 

I have updated your initial PR with some additional insights and merged with the latest metadata. Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by jzabroski** [comment]
You da man. 🤜 🤛

**Pull request merged**
