### PR TITLE
Update sql-server-linux-active-directory-authentication.md

### PR DESCRIPTION
**Pull request by tejasaks**
make Domain name (in capital letters) nomenclature consistent. Also added a note with respect to enabling the user account to support 128 and 256 bit AES Kerberos encryption.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@tejasaks : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Dylan-MSFT** [comment]
If you want to replace <DomainName> with CONTOSO, please do it everywhere...

**Comment by tejasaks** [comment]
I meant it specifically for that region where it should ideally be capitalized. Rest of the places capitalization doesn’t seem to matter.

~Tejas Shah | Principal Program Manager | Data Platform – SQL Server

**Comment by Dylan-MSFT** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
