### PR TITLE
Update stretch-database.md

### PR DESCRIPTION
**Pull request by mkrumpak**
Added "add"

### CODE REVIEW

**Comment by PRMerger13** [comment]
@mkrumpak : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@mkrumpak Thank you for your contribution to the content. I prefer to say "select" in place of "add," since the page in the "Enable Database for Stretch" wizard is titled "**Select** tables." Will you please make that change?

**Comment by mkrumpak** [comment]
I agree.  Yes, I will make the change shortly

**Comment by PRMerger13** [comment]
@mkrumpak : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
#sign-off

**Pull request merged**
