### PR TITLE
Update create-table-as-select-azure-sql-data-warehouse.md

### PR DESCRIPTION
**Pull request by lucaferrari77**
Hi
Ansi Joins are supported for Update and Delete operation in Dedicated SQL Pool.
I did remove the section.

Luca

### CODE REVIEW

**Comment by PRMerger12** [comment]
@lucaferrari77 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by LitKnd** [comment]
Hello, 

Thanks for submitting this PR. I have started up an email thread to kick off the review process. I am going to reassign this to my colleague. Thanks for helping make the docs better!

Kendra Little from the Database Docs Team

#reassign: @WilliamDAssafMSFT

**Comment by Court72** [comment]
@LitKnd, @WilliamDAssafMSFT  

Thanks for reviewing the proposed changes. *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by WilliamDAssafMSFT — APPROVED** [review]

**Review by WilliamDAssafMSFT — CHANGES_REQUESTED** [review]
Please update the ms.date on line 5

**Comment by jborsecnik** [comment]
@WilliamDAssafMSFT, do you want us to update the date and merge this PR?  
- PR review team

**Comment by VasiyaKrishnan** [comment]
@WilliamDAssafMSFT  - I approve the change.

**Comment by PRMerger20** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change. @LitKnd

**Review by WilliamDAssafMSFT — APPROVED** [review]
#sign-off

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@WilliamDAssafMSFT: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
