### PR TITLE
Fix dead link

### PR DESCRIPTION
**Pull request by nfd9001**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@nfd9001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@nfd9001 Thank you for this fix. I changed the link slightly to point to a subdirectory, but this was definitely a necessary change. Thanks! #sign-off

**Comment by PRMerger19** [comment]
@rothja: I'm sorry - only the author of this article, @mihaelablendea, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
