### PR TITLE
Update deploy-install-azdata-macos.md

### PR DESCRIPTION
**Pull request by justPaulo**
Support for Big Sur / M1 is needed too.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@justPaulo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by justPaulo** [comment]
Please let me know if I can help (test) on something.

**Comment by ktoliver** [comment]
@MikeRayMSFT Could you review the proposed update? If approved, we'll probably want to remove the question mark. Thanks.

**Comment by WilliamDAssafMSFT** [comment]
Hi @justPaulo - Per the engineering team, there are no plans to expand macOS support into Big Sur. If you're suggesting Big Sur be added as a feature in an upcoming release, I'd suggest [https://feedback.azure.com/forums/908035-sql-server](https://feedback.azure.com/forums/908035-sql-server) as the place to make that suggestion.

**Comment by justPaulo** [comment]
Hi @WilliamDAssafMSFT, so this means you don't have plans to add AzData support to ARM64 ? 
Thanks for the suggestion.

**Pull request closed without merging**
