### PR TITLE
Updated the IP firewall rules limit to 256

### PR DESCRIPTION
**Pull request by Peter-Msft**

### CODE REVIEW

**Comment by PRMerger4** [comment]
@Peter-Msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@VanMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by VanMSFT** [comment]
@rohitnayakmsft - Hey Rohit, can you please review these changes?

**Comment by rohitnayakmsft** [comment]
@Peter-Msft have you confirmed this change with the Sql Connectivity team? AFAIK the limit is unchanged

**Comment by PRMerger7** [comment]
@Peter-Msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Peter-Msft** [comment]
@rohitnayakmsft - The change is confirmed by connectivity team.

**Comment by rohitnayakmsft** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@rohitnayakmsft: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Peter-Msft** [comment]
@VanMSFT - Can you sign this off? Thanks

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
