### PR TITLE
Update sql-server-linux-setup-tools.md

### PR DESCRIPTION
**Pull request by brunoborges**
Separate installation of Homebrew from the installation of the actual sqlcmd package.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@brunoborges : Thanks for your contribution to the Azure documentation! The author, @rothja, has been notified to review your proposed change.

**Comment by rothja** [comment]
@brunoborges This is a good improvement. Thank you. #sign-off

**Comment by PRMerger8** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger18** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger17** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger20** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger8** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger15** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger9** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger12** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger15** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger13** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger19** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger20** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger16** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger19** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger12** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by rothja** [comment]
@craigg-msft Any idea why the system is telling me that rothja has to sign off? That would be me, right? Should I just merge this in? Thanks!

**Comment by PRMerger15** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger18** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Comment by PRMerger6** [comment]
@: Only the author, @rothja, can sign off on this pull request.

**Pull request merged**
