### PR TITLE
Update specify-default-values-for-columns.md

### PR DESCRIPTION
**Pull request by NandanHegde15**
Added a scenario for Synapse

### CODE REVIEW

**Comment by PRMerger6** [comment]
@NandanHegde15 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@julieMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by julieMSFT** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@julieMSFT: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
