### PR TITLE
Fix typos/capitalization issues

### PR DESCRIPTION
**Pull request by NathanMSFT**
Made a couple edits in line 52 to fix typo/capitalization consistency

### CODE REVIEW

**Comment by PRMerger16** [comment]
@NathanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
looks good, thanks Nathan! #sign-off

**Comment by MashaMSFT** [comment]
actually, #hold-off, let me pencil edit

**Comment by MashaMSFT** [comment]
#sign-off

**Pull request merged**
