### PR TITLE
Removed Synapse / PDW

### PR DESCRIPTION
**Pull request by mscodebum**
sp_rename is not supported by Synapse and PDW as noted here - https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql?view=sql-server-ver15

### CODE REVIEW

**Comment by PRMerger6** [comment]
@mscodebum : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@mscodebum Thanks for the feedback. @julieMSFT can you confirm and sign off if this is correct? Also, we might need to change the applies-to include. #reassign:juliemsft

**Comment by PRMerger14** [comment]
@julieMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by julieMSFT** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@julieMSFT: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
