### PR TITLE
Update enhanced-database-failover.md

### PR DESCRIPTION
**Pull request by moraja**
We need to enhance our documentation of database failover option and expand on the scenario.

more details can be found here
https://techcommunity.microsoft.com/t5/sql-server/sql-server-availability-groups-8211-enhanced-database-level/ba-p/385965

### CODE REVIEW

**Comment by PRMerger3** [comment]
@moraja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by cawrites** [comment]
@moraja  thank you for providing this information.      @Kevin-Farlee can you review this change?

**Review by kfarlee — APPROVED** [review]
This looks like a good change.  Approved.

**Comment by moraja** [comment]
Thanks Kevin for approving this PR, 
What is the next step now?

**Pull request merged**
