### PR TITLE
Work with remote data sources

### PR DESCRIPTION
**Pull request by FoxyChmoxy**
Hi @stevestein 

This is solution for issue #5159 
I added a new doc with information about how `EXEC AT` can be used and what is a difference between `OPENQUERY` and `OPENROWSET`

### CODE REVIEW

**Comment by stevestein** [comment]
@FoxyChmoxy - thanks for submitting this PR. I see content that was copied from other articles which has SEO implications. New articles need to be transferred into our private repo and reviewed so we will get to this as time permits.

Thanks.

**Comment by ktoliver** [comment]
Hi @stevestein -- I can't tell whether the content has already been moved to the private repo.  Shall we keep this pull request open? Thanks!

**Comment by rothja** [comment]
@stevestein Steve, are we pulling someone in from the product team to take a look at these suggestions after reviewing them ourselves? Thanks!

**Comment by ktoliver** [comment]
@stevestein Could you take another look at this pull request and let the PR review team know if there's any action to take?

Thanks.

**Comment by ktoliver** [comment]
Hi @rothja - Is @stevestein still on point for moving the pull request? Should we move it to the private repo? Thanks.

**Comment by rothja** [comment]
@ktoliver No, I need to take ownership of this. Thanks. #reassign:rothja

**Review by kfarlee — APPROVED** [review]
These changes look good to me.

**Comment by rothja** [comment]
Thanks, Kevin. I will do a quick edit pass on this to make sure that everything works with the formatting, since this is a bigger change. Then we can merge.

**Comment by MikeRayMSFT** [comment]
Reviewing internally. https://github.com/MicrosoftDocs/sql-docs-pr/pull/20809

**Pull request closed without merging**
