### PR TITLE
Update revert-transact-sql.md

### PR DESCRIPTION
**Pull request by nanditavalsan**
Applicable to Synapse SQL

### CODE REVIEW

**Comment by PRMerger13** [comment]
@nanditavalsan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @nanditavalsan - Contributors who work in the Product Manager role should open pull requests in the private repository for advanced quality validations and staging (you also can sign off directly in the private repo). To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. We’ll leave this PR for review in the public repo, but would you make future article updates in the private repo?  Thanks!

**Comment by PRMerger10** [comment]
@nanditavalsan, you can only sign off in the main PR conversation, not in review comments.

**Comment by ktoliver** [comment]
@VanMSFT Could you review this pull request? Thanks.

**Comment by VanMSFT** [comment]
Hey @nanditavalsan - We don't use the metadata tag ms.prod_service for reporting any longer. I'm guessing that you wanted to change the Applies to instead?

image

If you are planning to do this, please make the changes in the Private Repository.

@julieMSFT or I can help you with this. Please let us know what you want to do with this PR. Thanks!

**Comment by nanditavalsan** [comment]
Closing

**Pull request closed without merging**
