### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by greglow**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@greglow : Thanks for your contribution to the SQL documentation! The author, @JennieHubbard, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
@greglow Thank you so much for making time to propose this change!

**Comment by JennieHubbard** [comment]
#sign-off

**Comment by craigg-msft** [comment]
Thank you @greglow and @JennieHubbard

**Pull request merged**
