### PR TITLE
Corrected datatypes

### PR DESCRIPTION
**Pull request by way0utwest**
A number of columns were missing scale or incorrect data types.

FWIW, there are also 5 missing columns in this doc, but I do not know how to define them for corrections.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@way0utwest : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by julieMSFT** [comment]
@way0utwest Hi, Thank you for you input! I have reviewed your changes and will approve them Thank you for contributing to making our documentation more accurate. I will look into the additional 5 columns to have them added to the document.

**Comment by julieMSFT** [comment]
#sign-off

**Comment by julieMSFT** [comment]
@way0utwest Hi, I have added the additional 5 columns to the document. You should be able to see them later today.

**Pull request merged**
