### PR TITLE
Update and reformat query

### PR DESCRIPTION
**Pull request by IanKemp**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@IanKemp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@IanKemp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @IanKemp! Thanks for suggesting these changes. We appreciate the help with our documentation. Can you please elaborate on why these changes are needed? Thanks!

**Comment by rothja** [comment]
@IanKemp Thanks for the feedback. At this time, we think the documentation is correct, so we're closing out this change request. However, if you'd like to comment on the reason for the changes, we'll investigate further. Sorry for any confusion!

**Pull request closed without merging**
