### PR TITLE
Update dma-sku-recommend-sql-db.md

### PR DESCRIPTION
**Pull request by Fronzoli**
Both changes made in Data Collection Script section

Removed the quotes around the connection string in the sample invocation for the data collection script, those quotes stop the script from connecting to the database

Added a note about the WMI cmdlets needing to be updated to the CIM cmdlets to run the data collection script in Powershell 6 or 7.

### CODE REVIEW

**Comment by rothja** [comment]
Reassigning to @neetusingh-ms for review. Neetu, can you please review the changes on the File Changes tab and see if you approve this suggestion from @Fronzoli? Thank you! #reassign:neetusingh-ms

**Review by haitsongmsft — APPROVED** [review]

**Comment by ktoliver** [comment]
Hi @neetusingh-ms Could you review this pull request per the request from @rothja? Thanks!

**Review by neetusingh-ms — APPROVED** [review]

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
