### PR TITLE
Typo "EXIT**()**"→"EXIT **()*"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/tools/osql-utility?view=sql-server-ver15
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/osql-utility.md
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger17** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by markingmyname** [comment]
thanks for the suggestion, we'll consider it for the next article refresh

**Comment by markingmyname** [comment]
[hyoshioka0128](https://github.com/hyoshioka0128)

**Pull request closed without merging**
