### PR TITLE
Update sql-server-ver15-release-notes.md

### PR DESCRIPTION
**Pull request by amitmsft**
Removing AG reference

### CODE REVIEW

**Comment by PRMerger12** [comment]
@amitmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@MikeRayMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
checking in @MikeRayMSFT - you pushed a commit after approving. can you sign off if this is good to review and merge? thanks.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
