### PR TITLE
Update datetimeoffsetfromparts-transact-sql.md

### PR DESCRIPTION
**Pull request by fbsolo**
Text revisions to tighten and optimize the reading flow of the material. I fixed an existing bug in the first SQL Server example result set.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by rothja** [comment]
@fbsolo Thanks for your recommended improvements. There is a merge conflict that I need to resolve in this PR by choosing between your changes and the live changes. I will do my best to go through that and make the changes. There are also a few other changes that I have some questions about. I'll do that after. Thanks.

**Comment by PRMerger13** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by rothja** [comment]
@fbsolo OK, I reviewed the remaining changes and they look good. Thanks for your contribution! Signing off.

**Pull request merged**
