### PR TITLE
Update Limitations and Restrictions

### PR DESCRIPTION
**Pull request by avlane**
-   Merge Publications are limited to a maximum of 2048 articles and Transactional/Snapshot Publications are limited to 32,767 articles. For more information see Maximum Capacity Specifications: Replication Objects (https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?redirectedfrom=MSDN&view=sql-server-ver15#replication-objects)

@MashaMSFT

### CODE REVIEW

**Comment by MashaMSFT** [comment]
#sign-off thanks for your contribution @avlane!

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@MashaMSFT The list I revised appeared in a code block in preview, which means it was indented too far. It looks like adding an include file reference in the middle of a list broke the indentation. So I moved the include file to the end of the procedure. It looks OK on preview now. OK?

https://github.com/MicrosoftDocs/sql-docs/blob/519e67e1c9e1fb0868994a7388a5493bfb9acafe/docs/relational-databases/replication/publish/define-an-article.md

**Comment by MashaMSFT** [comment]
@ktoliver  i believe so but can't really tell without the preview.. let's go ahead and merge it, and verify once it goes live?

thanks!
Masha from the SQL Docs team

**Comment by ktoliver** [comment]
@MashaMSFT I've made myself a note to check this on live tomorrow. Thanks.

**Pull request merged**
