### PR TITLE
Remove 16GB memory minimum recommendation

### PR DESCRIPTION
**Pull request by briancarrig**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@briancarrig : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @DBArgenis, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
Thanks! @jborsecnik ~

**Pull request merged**
