### PR TITLE
Update master-data-services-add-in-for-microsoft-excel.md

### PR DESCRIPTION
**Pull request by farcel**
SQL Server 2016 download link points to SP1 though there is newest version released with SP2 , which is the latest. 
I put the download center link directly as I couldn't find the "go.microsoft.com" link for SQL 2016 SP2. Feel free to change it to its go link.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@farcel : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@farcel I apologize for not looking closely. After you remove the `en-us/` from the URL, I'll sign off. Thanks for catching this and making this change.

**Comment by PRMerger7** [comment]
@GitHubber17 : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@douglaslMS - The URL has been updated. Please `#sign-off` if this PR ready to merge. Thanks

**Comment by douglaslMS** [comment]
#sign-off 

FYI @GitHubber17

**Comment by PRMerger18** [comment]
@douglaslMS: I'm sorry - only the author of this article, @leolimsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
Minor note: this public PR 1216 was about SQL Server 2016, whereas the Issue 1302 is about SQL Server 2017.
.
The file.....
docs/master-data-services/microsoft-excel-add-in/master-data-services-add-in-for-microsoft-excel.md
.....contains a Downloads H2 that has a link for 2017 and another for 2016.

**Pull request merged**
