### PR TITLE
update the download page according to feedback

### PR DESCRIPTION
**Pull request by MSraye**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@MSraye : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@MSraye - Thanks for your contribution. We're reviewing this PR.

**Comment by stevestein** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@Jak-MS : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@MSraye @stevestein - made an edit to remove the future promise part of the additional content (as per guidelines).

**Pull request merged**
