### PR TITLE
Update installing-the-microsoft-odbc-driver-for-sql-server.md

### PR DESCRIPTION
**Pull request by rclaasen**
Added missing Kerberos library for Debian slim distributions.

### CODE REVIEW

**Comment by rclaasen** [comment]
This should be fixed in the deb package, of course. Extra documentation is a workaround.

**Comment by ktoliver** [comment]
Closing/reopening to get validation and do a CLA check.

**Comment by PRMerger18** [comment]
@rclaasen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
Merging now.

**Pull request merged**
