### PR TITLE
Extra Note on Tools enhancements\Management Studio

### PR DESCRIPTION
**Pull request by uriklil**
It seems to be an extra note, as it appears three notes later with a similar requirement to install .NET 4.6.1 as a pre-requisite.
I assume the right requirement is 4.6.1 and not 4.6 according to the download page.
I removed the extra note.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@uriklil : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
@stevestein please review

**Comment by CarlRabeler** [comment]
Please review – I think this is in your area.
Carl

**Comment by PRMerger15** [comment]
@stevestein : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@uriklil - thanks for catching this and making the update. I just removed the other .NET pre-req statement because this is simply installed with SSMS if needed. No action is required during install so there's no reason to mention it.

**Comment by stevestein** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@stevestein: I'm sorry - only the author of this article, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by stevestein** [comment]
@CarlRabeler - can you sign off?  Thanks!

**Comment by CarlRabeler** [comment]
@stevestein @craigg-msft why am I listed as the author of this page?

**Pull request merged**
