### PR TITLE
Update create-table-transact-sql.md

### PR DESCRIPTION
**Pull request by JediSQL**
Line 1050: Added "The reference columns must be specified in the same order that was used when specifying the columns of the primary key or unique constraint on the referenced table." See FK Not Backwards #3065 (https://github.com/MicrosoftDocs/sql-docs/issues/3065).

### CODE REVIEW

**Comment by PRMerger19** [comment]
@JediSQL : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
@pmasl Can you please review? Thank you.

**Comment by pmasl** [comment]
Thanks @JediSQL. #sign-off

**Comment by PRMerger20** [comment]
@pmasl: I'm sorry - only the author of this article, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by JediSQL** [comment]
This is my first time thru the github process for MicrosoftDocs/sql-docs. How long does it typically take before the changes show live on https://docs.microsoft.com/?

**Comment by ktoliver** [comment]
Hi @JediSQL - The changes usually are live within one business day.

**Pull request merged**
