### PR TITLE
Added missing commas and fixed inconsistent indention

### PR DESCRIPTION
**Pull request by jasonreiche**
The first image shown under Relational Databases > JSON had syntax errors.

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @rothja - Would you be able to review or reassign this pull request? Thanks.

**Comment by rothja** [comment]
#assign:rothja I'll take a look at this. Thanks!

**Comment by PRMerger8** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: rothja i'll take a look at this. thanks!

**Comment by rothja** [comment]
@jasonreiche Sorry for taking so long to review. Your change fixes obvious bugs with the missing commas and the indentation looks great! Thank you! #sign-off

**Comment by PRMerger9** [comment]
@rothja: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
