### PR TITLE
CC83302: Adding paragraph

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @HeidiSteen,
This proposed file change comes from https://github.com/MicrosoftDocs/sql-docs.zh-cn/pull/46 .
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@v-makoud : Thanks for your contribution! The author, @HeidiSteen, has been notified to review your proposed change.

**Comment by HeidiSteen** [comment]
@v-makoud, it looks like you want to rephrase the first paragraph.  I'm not sure what additional points you want to make, but your changes as-is are not grammatically correct.  Can you help me understand what the issue is?

**Comment by imba-tjd** [comment]
This PR is from local repo. The original author wanted to better translation but he mistakenly add a new paragraph instead of modifying the transtlated one.

**Comment by HeidiSteen** [comment]
I don't know that we are set up for that.  I will ask the content platform team and get back to you with the answer.  Thanks for trying to make our docs better.

**Comment by craigg-msft** [comment]
@HeidiSteen can you please add a comment on the status.

**Comment by HeidiSteen** [comment]
We should close this issue.  It's not actionable for us.

**Comment by TrishaMc** [comment]
Closing per @HeidiSteen direction.

**Pull request closed without merging**
