### PR TITLE
Change in the description of Support Version

### PR DESCRIPTION
**Pull request by MasayukiOzawa**
SQL Server 2019 is listed in the Supported source and target versions in the Detail of the download URL, but not in the docs.
https://www.microsoft.com/en-us/download/details.aspx?id=53595

### CODE REVIEW

**Comment by PRMerger8** [comment]
@MasayukiOzawa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, May 25. Merging will resume Tuesday. Authors can still review and sign off on PRs in the interim. Thanks.

**Review by aciortea — APPROVED** [review]
SQL 2019 is supported as a source and should be added the documentation. I can update in my PR as well

**Comment by MasayukiOzawa** [comment]
The information has been updated.

**Pull request closed without merging**
