### PR TITLE
Update examples-of-bulk-access-to-data-in-azure-blob-storage.md

### PR DESCRIPTION
**Pull request by suedeyloh**
Fixing data source name and code syntax

### CODE REVIEW

**Comment by PRMerger20** [comment]
@suedeyloh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @suedeyloh , thank you so much for your contribution! Yes, you are right, the name of the storage account should new invoices. Thank  you for making our docs better! #sign-off

**Comment by suedeyloh** [comment]
OOPS I bet I messed up the merge, sorry.  :-(  I was trying to figure out how to merge, and saw this was still "open."  I'm going to keep my fingers off stuff now.

Thank you, Masha, for being such a positive face of our company.  - A fellow Microsoftie :-)

**Comment by MashaMSFT** [comment]
no worries :) please feel free to contact me internally for help with writing! #sign-off

**Pull request merged**
