### PR TITLE
Improve ALTER SCHEMA, sp_rename, and sys.sql_modules

### PR DESCRIPTION
**Pull request by srutzky**
`sys.sql_modules`
--

Added link to `OBJECT_DEFINITION` page in the "Description" column for `definition`. Execute the following to see that `OBJECT_DEFINITION` is the source for the `definition` column:

    EXEC sp_helptext N'sys.sql_modules';

But even if it wasn't the source, it still outputs the same value.

`ALTER SCHEMA` and `sp_rename`
--

1. Added reference to `OBJECT_DEFINITION` function page for `sp_rename`.
1. Changed "schema-contained" to be "schema-scoped" to be consistent with [OBJECT_NAME](https://docs.microsoft.com/en-us/sql/t-sql/functions/object-name-transact-sql) and [OBJECT_SCHEMA_NAME](https://docs.microsoft.com/en-us/sql/t-sql/functions/object-schema-name-transact-sql) documentation (and most likely other pages)
1. Copied two paragraphs of **Remarks** from [sp_rename](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql) documentation and adjusted to pertain to this context
1. Removed "or view" from SSMS instructions since first new **Remarks** paragraph recommends against using `ALTER SCHEMA` on views :wink: 
1. Fixed `IMPERSONATION` permission (which doesn't exist) to be the actual `IMPERSONATE` permission
1. Please see related blog post containing explanation and example code / proof:  
  [Stored Procedure / Function / View / Trigger Definitions Can Be Wrong, Even If sp_rename Was Never Used](https://sqlquantumleap.com/2018/01/09/stored-procedure-function-view-trigger-definitions-can-be-wrong-even-if-sp_rename-was-never-used/)

`ALTER SCHEMA`
--

Relating to the advice about the need to manually update referenced objects that have been transferred / moved, please execute the following:

~~~
USE [tempdb];

GO
CREATE SCHEMA [TransferTest];
GO

CREATE TABLE [TransferTest].[MoveMe] ([Col1] INT);

GO
CREATE PROCEDURE [TransferTest].[SelectFromMoveMe]
AS
SET NOCOUNT ON;
SELECT [Col1] FROM [TransferTest].[MoveMe];
GO

EXEC [TransferTest].[SelectFromMoveMe];

ALTER SCHEMA [dbo] TRANSFER [TransferTest].[MoveMe];

SELECT * FROM [dbo].[MoveMe];

EXEC [TransferTest].[SelectFromMoveMe];
/*
Msg 208, Level 16, State 1, Procedure TransferTest.SelectFromMoveMe, Line X [Batch Start Line Y]
Invalid object name 'TransferTest.MoveMe'.
*/
~~~

### CODE REVIEW

**Comment by PRMerger3** [comment]
@srutzky : Thanks for your contribution to the SQL documentation! The author, @edmacauley, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
Thanks @srutzky for your clarity edits. #sign-off

**Comment by PRMerger18** [comment]
Only the author, @edmaca, can sign off on this pull request.

**Comment by craigg-msft** [comment]
Thank you @srutzky  and @edmacauley

**Comment by srutzky** [comment]
@edmacauley and @craigg-msft : you are quite welcome 😄 .

**Pull request merged**
