### PR TITLE
Remove legacy "Applies to" sections

### PR DESCRIPTION
**Pull request by exchange12rocks**
I found that a lot of pages still contain legacy "Applies to" sections, in addition to modern ones (tsql-appliesto-*). Those legacy sections are incorrectly formatted.

With this PR, I suggest to delete all legacy "Applies to" duplicates, leaving only those which do not duplicate information.

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @exchange12rocks we are working on cleaning up the applies approach so I would like @CarlRabeler to please review so we do not have conflicts.

**Comment by PRmerger** [comment]
@exchange12rocks : Thanks for your contribution to the SQL documentation! The author, @"edmacauley", has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
@exchange12rocks I am reviewing - at quick glance, all of the formatting fixes are great. For the removal of duplicates, I need to spend some more time on it. I intend to have this review completed by the end of next week.

**Comment by CarlRabeler** [comment]
@craigg-msft you can merge this PR

**Pull request merged**
