### PR TITLE
Update sys-fn-hadr-is-primary-replica-transact-sql.md

### PR DESCRIPTION
**Pull request by LowlyDBA**
Add language highlighting

### CODE REVIEW

**Comment by PRMerger14** [comment]
@LowlyDBA : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
#reassign:rothja Thanks @LowlyDBA for the suggestions. I'm going to edit your file to change "tsql" to "sql" per our current standards.

**Comment by rothja** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rothja: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
