### PR TITLE
Add information on configuring OpenSSL libraries

### PR DESCRIPTION
**Pull request by MitchellSternke**
Documenting this for upcoming configuration changes in vNext.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@MitchellSternke : Thanks for your contribution! The author, @tmullaney, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@meet-bhagdev - Would you review the proposed changes? Thanks

**Comment by meet-bhagdev** [comment]
Looks good. #sign-off
@vin-yu as FYI

**Comment by PRMerger7** [comment]
@meet-bhagdev: I'm sorry - only the author of this article, @tmullaney, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by rothja** [comment]
@meet-bhagdev @vin-yu @MitchellSternke I'll merge this for you. Thanks!

**Pull request merged**
