### PR TITLE
Update sql-server-connector-maintenance-troubleshooting.md

### PR DESCRIPTION
**Pull request by amitmsft**
Adding additional context for looking into Windows Event logs while troubleshooting the errors

### CODE REVIEW

**Comment by PRMerger17** [comment]
@amitmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @aliceku, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@ktoliver - thanks for the thoughtful and attentive edit.

**Pull request merged**
