### PR TITLE
Update firewall-configure.md

### PR DESCRIPTION
**Pull request by jiaqhuan**

### CODE REVIEW

**Comment by Court72** [comment]
@VanMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Hi @jiaqhuan! The changes look good, but I'm going to have @WilliamDAssafMSFT review as well for the added Azure Synapse portion.

#assign:WilliamDAssafMSFT

**Comment by WilliamDAssafMSFT** [comment]
Hi @jiaqhuan, will review and reach out.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Pull request merged**
