### PR TITLE
Update sql-server-linux-kubernetes-manage.md

### PR DESCRIPTION
**Pull request by tanaka-takayoshi**
Improve the meaning of the target name. This is not a container name (e.g. mssql-server or mssql-ha-supervisor) but a pod name.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@tanaka-takayoshi : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@SQLSourabh  - can you please review this request?

**Comment by SQLSourabh** [comment]
It makes sense to explicitly call out the target name for the failover. Tanaka-San is correct that its the Pod name and not the container name.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by MikeRayMSFT** [comment]
@tanaka-takayoshi - Thank you for this submission.
#sign-off

**Pull request merged**
