### PR TITLE
typo: databse -> database

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by TrishaMc** [comment]
@craigg-msft - Would you review the proposed changes? Thanks.

**Comment by TrishaMc** [comment]
We're in the process of pulling these commits to the private repo, so we can verify the content on staging. We'll post a new PR # shortly and then close this PR.

**Comment by Jak-MS** [comment]
The commits from this PR have been moved to the private repo for validation and automation. Thanks @nschonni for finding these. We'll review the staged content and proceed from there.

https://github.com/MicrosoftDocs/sql-docs-pr/pull/8805

**Comment by MightyPen** [comment]
@nschonni Hi Nick, I have approved this PR 1546, as private PR 8805.  :-)  However,.....
.
Please do **not rename any files** in new PRs.  Though such renames are good in theory, and to a small extent also in practice, we feel the churn of file renames is not worth the churn and downstream validations efforts that are required of us.
.
@stevestein Steve will be updating our Contributors' Guide to clarify against file renames, and against changes to config files.
.
Regular word spelling fixes are still plenty welcome.
Thanks again Nick.

**Pull request closed without merging**
