### PR TITLE
Query Notifications are built on Service Broker, which is not availab…

### PR DESCRIPTION
**Pull request by dbrownems**
…le in SQL DB (non-MI) and SQL DW

Query Notifications are built on Service Broker, which is not available in SQL DB (non-MI) and SQL DW.  Related pages may be off too.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@dbrownems : Thanks for your contribution! The author, @MightyPen, has been notified to review your proposed change.

**Comment by dbrownems** [comment]
Also not sure if this feature works-or-is-supported with Manged Instance, where Service Broker has some limitations.

**Comment by MightyPen** [comment]
@dbrownems Thank you very much for bringing this AppliesTo (and monikerRange for Versioning) mis-classification error to our attention!
I will now approve and Merge this PR 2206.

Next week I will make a corresponding edit a couple lines earlier in the .md file, to remove from the monikerRange line the snip '||=azuresqldb-current'.
And ideally I will also have time to investigate the AppliesTo and monikerRange values for the following articles:

dir /b /s *broker*.md

\docs\database-engine\availability-groups\windows\service-broker-with-always-on-availability-groups-sql-server.md
\docs\database-engine\configure-windows\sql-server-service-broker.md
\docs\relational-databases\event-classes\audit-broker-conversation-event-class.md
\docs\relational-databases\event-classes\audit-broker-login-event-class.md
\docs\relational-databases\event-classes\broker-activation-event-class.md
\docs\relational-databases\event-classes\broker-connection-event-class.md
\docs\relational-databases\event-classes\broker-conversation-event-class.md
\docs\relational-databases\event-classes\broker-conversation-group-event-class.md
\docs\relational-databases\event-classes\broker-corrupted-message-event-class.md
\docs\relational-databases\event-classes\broker-event-category.md
\docs\relational-databases\event-classes\broker-forwarded-message-dropped-event-class.md
\docs\relational-databases\event-classes\broker-forwarded-message-sent-event-class.md
\docs\relational-databases\event-classes\broker-message-classify-event-class.md
\docs\relational-databases\event-classes\broker-message-drop-event-class.md
\docs\relational-databases\event-classes\broker-remote-message-ack-event-class.md
\docs\relational-databases\performance-monitor\sql-server-broker-activation-object.md
\docs\relational-databases\performance-monitor\sql-server-broker-dbm-transport-object.md
\docs\relational-databases\performance-monitor\sql-server-broker-statistics-object.md
\docs\relational-databases\performance-monitor\sql-server-broker-to-statistics-object.md
\docs\relational-databases\performance-monitor\sql-server-memory-broker-clerks-object.md
\docs\relational-databases\server-management-objects-smo\tasks\managing-service-broker.md
\docs\relational-databases\system-catalog-views\service-broker-catalog-views-transact-sql.md
\docs\relational-databases\system-catalog-views\sys-service-broker-endpoints-transact-sql.md
\docs\relational-databases\system-dynamic-management-views\service-broker-related-dynamic-management-views-transact-sql.md
\docs\relational-databases\system-dynamic-management-views\sys-dm-broker-activated-tasks-transact-sql.md
\docs\relational-databases\system-dynamic-management-views\sys-dm-broker-connections-transact-sql.md
\docs\relational-databases\system-dynamic-management-views\sys-dm-broker-forwarded-messages-transact-sql.md
\docs\relational-databases\system-dynamic-management-views\sys-dm-broker-queue-monitors-transact-sql.md
\docs\relational-databases\system-dynamic-management-views\sys-dm-os-memory-brokers-transact-sql.md
\docs\t-sql\statements\alter-broker-priority-transact-sql.md
\docs\t-sql\statements\create-broker-priority-transact-sql.md
\docs\t-sql\statements\deny-service-broker-permissions-transact-sql.md
\docs\t-sql\statements\drop-broker-priority-transact-sql.md
\docs\t-sql\statements\grant-service-broker-permissions-transact-sql.md
\docs\t-sql\statements\revoke-service-broker-permissions-transact-sql.md
\docs\tools\ssbdiagnose\ssbdiagnose-utility-service-broker.md

Thanks again.

**Comment by MightyPen** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10404 

.....Made the necessary adjustments alluded to in the preceding comment.  Just FYI.

**Pull request merged**
