### PR TITLE
Update download-azure-data-studio.md for WSL

### PR DESCRIPTION
**Pull request by brucedkyle**
Added guidance on using Azure Data Studio in WSL. Users may try to install on WSL only to reach the following notice: 

To use Azure Data Studio with the Windows Subsystem for Linux, please install Azure Data Studio in Windows and uninstall the Linux version in WSL. You can then use the `azuredatastudio` command in a WSL terminal just as you would in a normal command prompt.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@brucedkyle : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by brucedkyle** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@brucedkyle: I'm sorry - only the author of this article, @yualan, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by markingmyname — APPROVED** [review]
Approved.

I will make a minor modification and list it below the Linux section

**Review by markingmyname — APPROVED** [review]

**Comment by PRMerger18** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
