### PR TITLE
Update sp-autostats-transact-sql.md

### PR DESCRIPTION
**Pull request by nnpcYvIVl**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@nnpcYvIVl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
approved.

**Comment by markingmyname** [comment]
#sign-off

**Comment by ktoliver** [comment]
@markingmyname - Thanks for reviewing the PR. 

Publishing in this repository is suspended until Tuesday, September 22. Merging will resume at 7 AM Pacific Tuesday.

This PR is ready to merge.

**Comment by markingmyname** [comment]
@ktoliver,

understood.  thank you for the response. :)

**Pull request merged**
