### PR TITLE
Fixing typo "temporary endpoint ot"

### PR DESCRIPTION
**Pull request by joshts0**
to "temporary endpoint on" ... or maybe "to" ?

### CODE REVIEW

**Comment by PRMerger12** [comment]
@joshts0 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @mihaelablendea - Could you review the proposed update to your article? The alert was missing a few words, so I had a go at editing for grammar, etc. Does it look good to merge? (The article in the link in that section seems to use "endpoint to the SQL Server," to I used that instead of "on.")

**Comment by WilliamDAssafMSFT** [comment]
Thanks @joshts0 for submitting this PR. Your suggestions help improve our documentation. Your commit has been merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor.

Thanks again for this feedback, your suggestions help improve our documentation.

#reassign:WilliamDAssafMSFT

**Pull request merged**
