### PR TITLE
Update tutorial-sql-server-containers-kubernetes-dh2i.md

### PR DESCRIPTION
**Pull request by birenshrestha**
$docker build -t <tagname> . (<tagname> should be sqlimage/latest since this is the tag we are using below)
az aks update -n myAKSCluster -g <myResourceGroup> --attach-acr <registry-name> (fully qualified name of registry is not acceptable here, only short name)
image: <registry-name>.azurecr.io/sqldh2i:latest (this has to be sqlimage:latest since this is what we created above)

### CODE REVIEW

**Comment by PRMerger8** [comment]
@birenshrestha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by amvin87** [comment]
These changes look good, we should change the image name to sqldh2i:latest everywhere instead of sqlimage:latest. Thank you @birenshrestha  for your feedback!

**Comment by ShannonLeavitt** [comment]
@birenshrestha could you make the requested changes and resolve the merge conflict so we can merge? Thanks.

**Comment by VanMSFT** [comment]
Hey @birenshrestha - Thanks! I'm pulling your changes into a new PR to update all the tags per @amvin87's recommendation, and also fixing the merge conflict.

@amvin87 - Amit, please check the new PR: https://github.com/MicrosoftDocs/sql-docs-pr/pull/21609

I want to make sure this is correct:

image

image

**Pull request merged**
