### PR TITLE
Update objectproperty-transact-sql.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
Added IsSystemVerified as a property name

### CODE REVIEW

**Comment by PRMerger9** [comment]
@DanielAdeniji : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by pmasl** [comment]
Hi @DanielAdeniji thanks for this. Please change:

|IsSystemVerified|Object|SQL Server verify that the function is precise and deterministic?.<br /><br /> 1 = True<br /><br /> 0 = False|  

to:

|IsSystemVerified|Object|The [!INCLUDE[ssde_md](../../includes/ssde_md.md)] can verify the determinism and precision properties of the object.<br /><br /> 1 = True<br /><br /> 0 = False|  

And I'll sign-off. 

FYI, this property applies to scalar UDFs, MSTVFs, inline TVFs, and Views.

**Comment by DanielAdeniji** [comment]
Pedro:

Yes, absolutely I am on board.

Daniel
________________________________

**Comment by DanielAdeniji** [comment]
> Hi @DanielAdeniji thanks for this. Please change:
> 
> |IsSystemVerified|Object|SQL Server verify that the function is precise and deterministic?.
> 
> 1 = True
> 
> 0 = False|
> 
> to:
> 
> |IsSystemVerified|Object|The [!INCLUDE[ssde_md](../../includes/ssde_md.md)] can verify the determinism and precision properties of the object.
> 
> 1 = True
> 
> 0 = False|
> 
> And I'll sign-off.
> 
> FYI, this property applies to scalar UDFs, MSTVFs, inline TVFs, and Views.

Yes, I am on board.

**Comment by PRMerger10** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by MashaMSFT** [comment]
Hello @DanielAdeniji and @pmasl, I've modified the language in the PR. #sign-off

**Comment by MashaMSFT** [comment]
Thanks for your contribution @DanielAdeniji !

**Pull request merged**
