### PR TITLE
Update using-azure-active-directory.md Fixed top table

### LINKED ISSUE #9688: Table at top needs fixing. Values in first column don't align.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45a0e668-ba07-ce4f-2b40-b386650dcd99
* Version Independent ID: 82d61083-b354-c135-5d3f-230555d13d57
* Content: [Using Microsoft Entra ID with the ODBC Driver - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver16)
* Content Source: [docs/connect/odbc/using-azure-active-directory.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/using-azure-active-directory.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

### PR DESCRIPTION
**Pull request by krepko7**
Fixes https://github.com/MicrosoftDocs/sql-docs/issues/9688.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@David-Engel 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by David-Engel** [comment]
This change doesn't make sense.

The previous table layout was correct. There is a keyword name, its list of possible values, its default value, and a description column. For the Authentication keyword, the description column contains another table expanding on the values and their descriptions.

With your changes, you have duplicated the keyword across multiple rows for each possible value. This is not the way the table was meant to be laid out.

**Comment by krepko7** [comment]
Yes, I agree. If we can make the first column not repeat that is better. I felt the existing layout was hard to read. Feel free to ignore the PR if you disagree. Thanks.

**Comment by David-Engel** [comment]
If you use the "Expand table" link, the existing layout looks much better:

image

I'd prefer to keep the existing layout.

**Comment by krepko7** [comment]
You are right, the expand table makes the layout look good. Thanks.

**Comment by rwestMSFT** [comment]
Thanks Kirby and David.

**Pull request closed without merging**
