### PR TITLE
update FCI requirements for domain join clusters

### PR DESCRIPTION
**Pull request by suresh-kandoth**
Per discussion with Sourabh Agarwal adding the support statement for FCI on domain joined vs workgroup cluster:

-   SQL Server failover cluster instance requires the cluster nodes to be domain joined.
    1.	SQL FCI on workgroup clusters is not supported. 
    2.	SQL FCI on Multi-Domain cluster is also not supported.  
    3.	SQL FCI on Domain + Workgroup Clusters is not supported.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@suresh-kandoth : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@MashaMSFT : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Jak-MS : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Jak-MS : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Jak-MS : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
got the bullets to render correctly after a few tries. merging.

**Pull request merged**
