### PR TITLE
adding example H for creation with password-hash

### PR DESCRIPTION
**Pull request by AndreasWolter**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@AndreasWolter : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AndreasWolter** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@AndreasWolter: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @AndreasWolter - It looks like you've worked in the private repo for this content before. Would you submit this update in a pull request in the private repo? Thanks! We'll close this PR.

**Comment by AndreasWolter** [comment]
Hi @ktoliver. I am a layman, so pardon my confusion. I thought I did work in the -pr  .... / master branch. And you are asking me to use a private repo - instead of the private repo? I am confused. sorry

**Comment by ktoliver** [comment]
> Hi @ktoliver Kristine Toliver (Aquent LLC) Vendor. I am a layman, so pardon my confusion. I thought I did work in the -pr .... / master branch. And you are asking me to use a private repo - instead of the private repo? I am confused. sorry

Hi Andreas. This pull request was opened in the public repo (sql-docs). I think you meant to use the private repo (sql-docs-pr). When you create the PR, ensure that the repo name in the URL in the browser address bar is the private repo. 

image

Let me know if I need to provide more info in email. Thanks.

**Comment by AndreasWolter** [comment]
ok, then its just odd. I remember crystal clear how I added -pr in the URL a few hours ago. Anyhow, will repeat it another day when I find time again and pay attention if anything redirects me or whatever else suspicious could explain this mistake. thanks

**Comment by AndreasWolter** [comment]
done. thank you @ktoliver

**Comment by ktoliver** [comment]
> ok, then its just odd. I remember crystal clear how I added -pr in the URL a few hours ago. Anyhow, will repeat it another day when I find time again and pay attention if anything redirects me or whatever else suspicious could explain this mistake. thanks

@AndreasWolter There is a helpful browser extension created by a Microsoft FTE which, if you install it, automatically opens the editing pane in the private repo, if there is one for the doc set and if you have permissions to work in the private repo. I've used it, and it works seamlessly. Other than that, the PR reviewer feedback is the only notification you'll see, I believe. https://review.docs.microsoft.com/en-us/help/contribute/contribute-tool-spineedit?branch=master (Microsoft-internal link)

**Comment by VanMSFT** [comment]
@ktoliver @AndreasWolter - You actually don't need that tool. Just add in `review.` to the front of docs.microsoft.com and it should get you to the private repo.

https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-edit-article-private?branch=master#workflow-for-editing-a-private-repo

**Comment by ktoliver** [comment]
@VanMSFT Agreed. I was responding to Andreas's reference to a "safety net" -- _if anything redirects me or whatever else suspicious could explain this mistake_. 👍🏻

**Pull request closed without merging**
