### PR TITLE
Spelling Fix Wave 1

### PR DESCRIPTION
**Pull request by ArieHein**
Christmas is early and you get the first of many little presents in the shape of spelling fixes. Enjoy !

### CODE REVIEW

**Comment by Jak-MS** [comment]
@markingmyname @MikeRayMSFT  - 
Can you review the proposed changes, especially any code changes. I've reviewed the non-code edits and they look good. 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@ArieHein This is the good stuff. Thank you for your contribution.

I will have to go through our entire content set to see if we can match other areas with your suggested corrections, so this PR will likely be closed, but rest assured you will get credit for this contribution.

Thank you again.

**Comment by ArieHein** [comment]
@rwestMSFT 
I have about 150 more spelling fixes, but i decided to send them in batches as its hard to review them.
What would be the best approach ?

edit: all under the relational-databases sub folder

image

**Comment by rwestMSFT** [comment]
We won't accept any fixes in the errors and events includes folder. Those come straight out of the product source code.

You can do the rest in a single PR, and I'll take care of it if you ping me in the PR comment.

I'm going to close this PR now, because we have an internal PR that will publish after the Ignite content freeze. Your name will appear in the contributor list.

**Comment by ArieHein** [comment]
@rwestMSFT
Ok, I will wait for after the freeze for it to be merged and then will open a new one with the remaining. Unless i understood you wrong.

There are about 30 spelling fixes in the error-events as well. Based on your comment, i assume its auto generated from the source code but i dare say its was either manually changed after the generation or those spelling issues are at the source code. I can make an MD file with all the details of the files, line numbers and issue and attach it to the second PR as i think it merits the PM/Devs taking a look at it to validate and fix. As a long time SQL admin, i made sure its not syntax related but pure spelling.

image

**Comment by rwestMSFT** [comment]
Go ahead and open at your leisure. You don't have to wait. The PR that I closed is what we're waiting for, that's what I meant.

> There are about 30 spelling fixes in the error-events as well [...]

We know, and we won't accept corrections on these at all. Thanks for your understanding.

**Pull request closed without merging**
