### PR TITLE
Added JSON Formatter

### PR DESCRIPTION
**Pull request by rahulkumarsingh73690**
You know understanding JSON is not easy if JSON is minified So I added JSON Best JSON Formatter For Help.

Moderator, Please Check My PR and Suggest Changes If Need

### CODE REVIEW

**Comment by PRMerger15** [comment]
@rahulkumarsingh73690 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@jovanpop-msft, when you review this PR, please consider the wording of this cross-ref, since it's apparently a third-party tool. Cite this as an "example"?  Thanks.

**Comment by MightyPen** [comment]
Closing, not accepting, not merging.

**Comment by rahulkumarsingh73690** [comment]
It's okay but at least check tool usage 😊

**Pull request closed without merging**
