### PR TITLE
Remove "What's new in 2012" link

### PR DESCRIPTION
**Pull request by MladjoA**
All features introduced in SQL Server 2012 all already documented in regular articles

### CODE REVIEW

**Comment by PRMerger19** [comment]
@MladjoA : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by MladjoA** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@MladjoA: I'm sorry - only the author of this article, @douglaslMS, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by douglaslMS** [comment]
#sign-off

**Pull request merged**
