### PR TITLE
Added a note column -Supportability

### PR DESCRIPTION
**Pull request by ujjwalpatel910**
Added a note column which says we do not support SAS Token with external data source type Hadoop as of now and workaround is to use storage access key.

RFC Filed for same : RFC request submitted #12846533 (PG responded with same)

Hence we need to update this documentation

### CODE REVIEW

**Comment by PRMerger10** [comment]
@ujjwalpatel910 : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@MashaMSFT : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@MashaMSFT : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@MashaMSFT @CarlRabeler The note was created within a code block. Should it be in the text portion of the article, or is inside the code block intended/okay? Thanks.

**Comment by ktoliver** [comment]
@MashaMSFT @CarlRabeler The note was created within a code block. Should it be in the text portion of the article, or is inside the code block intended/okay? Thanks.

**Comment by ktoliver** [comment]
@MashaMSFT @CarlRabeler The note was created within a code block. Should it be in the text portion of the article, or is inside the code block intended/okay? Thanks.

**Comment by PRMerger14** [comment]
@MashaMSFT : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
hi @ktoliver , thanks for catching that! I totally did not notice.. I moved the entire thing down to the limitations section. #sign-off again?

**Comment by PRMerger14** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@MashaMSFT : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@MashaMSFT - That looks good. Merging the PR.

**Pull request merged**
