### PR TITLE
Update token-ssis-expression.md

### PR DESCRIPTION
**Pull request by HamzaBoukraa**
Fix parenthesis.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@HamzaBoukraa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by HamzaBoukraa** [comment]
@chugugrace could you please review the changes.

**Comment by rothja** [comment]
@HamzaBoukraa Thank you for this proposed change. It looks very clear, so I am going to sign off for @chugugrace . Thank you! #sign-off

**Comment by PRMerger15** [comment]
@rothja: I'm sorry - only the author of this article, @chugugrace, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
