### PR TITLE
Updated Applies to to include Azure SQL DB

### PR DESCRIPTION
**Pull request by AndreasWolter**
line 29
old:
[!INCLUDE[tsql-appliesto-ss2008-xxxx-xxxx-xxx-md](../../includes/tsql-appliesto-ss2008-xxxx-xxxx-xxx-md.md)]
new:
[!INCLUDE[tsql-appliesto-ss2008-asdb-xxxx-xxx-md.md](../includes/tsql-appliesto-ss2008-asdb-xxxx-xxx-md.md)]

### CODE REVIEW

**Comment by PRMerger8** [comment]
@AndreasWolter : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks, Andreas!
#sign-off

**Comment by Jak-MS** [comment]
Hi @VanMSFT @AndreasWolter - Since the public repo doesn't have staging and validation tools, you'll need to manually double-check that the include is rendering correctly after the changes are live.

thanks.

**Comment by VanMSFT** [comment]
Thanks @Jak-MS!

**Pull request merged**
