### PR TITLE
Updated the script with additional steps for killing the ongoing proc…

### PR DESCRIPTION
**Pull request by ronazi**
…esses and also sp_reconfigure options

Running just those (on the current doc) will error out with multiple errors and customers will need to go back and forth in troubleshooting the errors. Hence edited the doc with detailed step by step guide.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ronazi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @ronazi - Thanks for the proposed changes.

@bluefooted - Hey Pam, do you mind taking a quick look at the proposed changes? Do you agree with providing instructions to kill all SPIDs before changing the containment option? At the very least, we will need to put a warning in place. Thanks!

**Comment by ronazi** [comment]
@VanMSFT What is the status on this?

**Comment by bluefooted** [comment]
Sorry folks, just got back from vacation! No, the kill script isn't the best way to do this, we would normally recommend something like the following script:

ALTER DATABASE Test
SET SINGLE_USER -- or RESTRICTED_USER for Managed Instance
WITH ROLLBACK IMMEDIATE;

ALTER DATABASE Test
SET containment=partial;

ALTER DATABASE Test
SET MULTI_USER;

And yes I agree, if we add this, we should also add a warning.

**Comment by PRMerger7** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks Pam!

@ronazi - I made edits to your PR based on Pam's suggestion. Thanks for the help with our documentation. Let me know if there are any issues. I will approve this PR now.

#sign-off

**Review by bluefooted — APPROVED** [review]
Looks good, thank you!

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
