### PR TITLE
Update applock-transact-sql.md

### PR DESCRIPTION
**Pull request by fbsolo**
Text revisions to tighten and optimize the reading flow of the material.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by fbsolo** [comment]
Mr. Macauley, I'd like to [message to you](https://bitvectors.blogspot.com).

Thank you!

- Frank Solomon

**Comment by edmacauley** [comment]
Thanks for your edits @fbsolo, I'll ping you at your email address on the blog.

**Comment by edmacauley** [comment]
#sign-off

**Pull request merged**
