### PR TITLE
Correct Casing of XQUERY functions

### PR DESCRIPTION
**Pull request by LarnuUK**
XQuery is case sensitive, however, the example had functions such as `INSERT`, `AS`, and `INTO` within the XQUERY statements in uppercase, causing the statement to error. Corrected casing, and validated that the statement works ([db<>fiddle](https://dbfiddle.uk/?rdbms=sqlserver_2019&sample=adventureworks&fiddle=9c381bfad77d6f099fce9faafbb35e9d) for verification).

### CODE REVIEW

**Comment by PRMerger17** [comment]
@LarnuUK : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by rothja** [comment]
@LarnuUK Thanks for the changes, and sorry for the delay. There is a merge conflict with other changes that have been made on this file. I am going to try to pull your changes into my own PR to address them and then let you know when the changes are published. Thanks for your patience.

**Comment by LarnuUK** [comment]
Thanks @rothja . Looking at the conflict, the *new* Live version also still uses `AFTER` not `after`, which is incorrect; XQUERY keywords are lowercase so `AFTER` would generate an error. Unless I missed anything else, that appears to be the only conflict here.

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@ktoliver The file changes show the whole file being replaced now. I think I'm still going to make the change manually in another PR and keep this open until I do that. Thanks.

**Comment by LarnuUK** [comment]
Yes, I see that, @rothja , looks like the merge by Kristine into my PR didn't do as expected, so making a new PR sounds like a safe bet. Alternatively, I can create a new PR and we can close this one.

**Comment by LarnuUK** [comment]
Looking at the current live version of the document, only line 94 needs changing now, @rothja , from:
```sql
AFTER (/Root/ProductDescription/Features/Material)[1]         
```
 to
```sql
after (/Root/ProductDescription/Features/Material)[1]
```

**Comment by rothja** [comment]
@LarnuUK Thom, could you make a new PR for this change on the current article? That would save a lot of time and probably get the change out faster. Thank you!

**Comment by rothja** [comment]
Merged other pull request. Closing this one.

**Pull request closed without merging**
