### PR TITLE
Update master-data-services-installation-and-configuration.md

### PR DESCRIPTION
**Pull request by KrishnakumarRukmangathan**
Adding additional requirement for the MDS App pool identity account. 
This was discussed with the MDS PG team and updated here.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@KrishnakumarRukmangathan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chugugrace — APPROVED** [review]

**Comment by chugugrace** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Alerts shouldn't be "stacked" without content between them, so I moved the new note to right after the text that describes creating the identity.

**Pull request merged**
