### PR TITLE
Update transparent-data-encryption.md

### PR DESCRIPTION
**Pull request by HeminMSFT**
Missing information on how to encrypt databases that are already part of AlwaysOn Availability Group

### CODE REVIEW

**Comment by PRMerger8** [comment]
@HeminMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
