### PR TITLE
Typo "SQL server"→"SQL Server"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/sql-server-profiler?view=sql-server-ver15
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sql-server-profiler/sql-server-profiler.md
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger12** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@markingmyname 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by markingmyname — APPROVED** [review]
thank you.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
