### PR TITLE
Update copy-into-transact-sql.md

### PR DESCRIPTION
**Pull request by VasiyaKrishnan**
Added Guidelines to the AUTO_CREATE_TABLE = ON

### CODE REVIEW

**Comment by PRMerger17** [comment]
@VasiyaKrishnan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VasiyaKrishnan** [comment]
This is high priority and would like to make the changes visible as soon as possible. @WilliamDAssafMSFT @jonburchel

**Comment by VasiyaKrishnan** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@VasiyaKrishnan: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by VasiyaKrishnan** [comment]
I am on the Microsoft Product Team and would like to ensure these changes gets reflected ASAP as it has a significant customer impact. 
#sign-off

**Comment by PRMerger12** [comment]
@VasiyaKrishnan: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
