### PR TITLE
typo: clicke -> click

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @minewiskan, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're reviewing this pull request.

**Comment by ktoliver** [comment]
@nschonni - Thank you for your submission. We are not able to accept spacing and formatting changes in the repo at this time. Could you resubmit the _typo fix only_ in a new pull request?

**Comment by nschonni** [comment]
I won't be resubmitting, feel free to fix internally

**Pull request closed without merging**
