### PR TITLE
Adding a query for Azure SQL Database, SQL users' password policies and expiration dates can be reviewed using the query below. This can be helpful to auditors to check SQL users password policies and expiration date.

### PR DESCRIPTION
**Pull request by rarandiv**
Adding a query for Azure SQL Database, SQL users' password policies and expiration dates can be reviewed using the query below. This can be helpful to auditors to check SQL users password policies and expiration date.

### CODE REVIEW

**Comment by VanMSFT** [comment]
Hi @rarandiv - Thanks for attempting to add changes to our docs! The changes here are not appropriate for this page, as only password complexity applies to Azure SQL Database. However, I think a better spot to have an example would be the [Password Policy](https://learn.microsoft.com/sql/relational-databases/security/password-policy) page. This is something I can consider for future changes to the doc. Thanks, and please let me know if you have other feedback.

**Comment by rarandiv** [comment]
@VanMSFT , Thanks for looking in to and sharing feedback, however suggested document is for [SQL Server] and not for Azure SQL Database. Let me know if you still feel it's a relevant document to update an information or should we consider updating the document where I raised a feedback.

**Comment by Court72** [comment]
@VanMSFT 

Thanks for reviewing this PR. Can you respond to the [contributor's comment](https://github.com/MicrosoftDocs/sql-docs/pull/9849#issuecomment-2243216961) and indicate what action to take on this PR? (`#sign-off` to merge or `#please-close` to close) 
	

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
> @VanMSFT , Thanks for looking in to and sharing feedback, however suggested document is for [SQL Server] and not for Azure SQL Database. Let me know if you still feel it's a relevant document to update an information or should we consider updating the document where I raised a feedback.

Yes, the auditing query works on SQL Server as well, and I would say that it's more relevant to SQL Server than Azure SQL Database, based on my previous feedback.

**Comment by VanMSFT** [comment]
Let's close this for now, but feel free to let me know if you have other feedback. Thanks.

#please-close

**Comment by rarandiv** [comment]
Created new pull request https://github.com/MicrosoftDocs/sql-docs/pull/9851 on suggested document

**Pull request closed without merging**
