### PR TITLE
Update configure-measure-group-properties.md

### PR DESCRIPTION
**Pull request by vstrien**
Description for DataAggregation property was outdated - for current SSAS versions, DataAggregation is a supported setting (according to the 20768 training). The sentence I added is a description from the 20768 trainer handbook.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@vstrien : Thanks for your contribution! The author, @minewiskan, has been notified to review your proposed change.

**Comment by Minewiskan** [comment]
@amirchandandani Can you take a look at the proposed change? If it looks ok, please let me know and I'll sign off on this PR.

**Comment by Minewiskan** [comment]
@vstrien Thanks for contributing. However, this property is actually not used. The engine ignores it. What description from the 20768 training are you referring to? Could you provide me with more detail about this training and who provided it? 
Thanks

**Comment by vstrien** [comment]
> @vstrien Thanks for contributing. However, this property is actually not used. The engine ignores it. What description from the 20768 training are you referring to? Could you provide me with more detail about this training and who provided it?
> Thanks

Sure, I am an MCT, and this is right in the Microsoft-provided Trainer Handbook for the 20768 course, page 111.
screenshot 2018-10-25 at 08 35 15

**Comment by Minewiskan** [comment]
@vstrien Thanks for letting me know. You're the second person in two weeks who suggested the same change. Now I know where it's coming from. It will take a while to look into this. Let's leave this issue open while I do some digging. Thanks for your patience.

**Comment by Minewiskan** [comment]
@vstrien I'm not able to get into the actual course, but I found it described here, https://www.microsoft.com/en-us/learning/course.aspx?cid=20768. This course is terribly outdated. I remember being consulted for help with creating the DAX module, probably seven or eight years ago. I strongly recommend not suggesting or presenting this course. You might want to bring it up with your contacts in MS Learning. I'll do what I can internally to get this course removed. I cannot merge your suggested change as stated earlier. If you could close this PR, that would be great. Again, thanks for the information. I'm sorry I cannot provide a better outcome.

**Comment by vstrien** [comment]
As requested by @Minewiskan, proposed update was incorrect.

**Pull request closed without merging**
