### PR TITLE
Add a note for DB_ID inconsistency in SQL Azure

### PR DESCRIPTION
**Pull request by tompostler**
Please ping me directly for additional context, if necessary.
I'm not sure if this is valid doc wording, but I needed to get this process started somewhere.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@tompostler : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
@tompostler - Hey Tom, thanks for submitting this! With my limited testing, I wasn't able to confirm a difference between the DB_ID and database_id from sys.databases. Can you please provide context here for the change?

**Comment by PRMerger15** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
@tompostler - Actually, I did some quick searching and there are many who report the same thing. Thanks! I made a quick edit, and will push this through. Thanks again for helping on our documentation, Tom!

#sign-off

**Pull request merged**
