### PR TITLE
Update with-common-table-expression-transact-sql.md

### PR DESCRIPTION
**Pull request by ValeriyRU**
Proposed changes for section D for script that creates dbo.MyEmployees table.
1. Change type for column ManagerID from INT to SMALLINT for it to correspond the type of column EmployeeID.
2. Add a Foreign Key FK_MyEmployees_ManagerID_EmployeeID (name can be changed): column ManagerID references column EmployeeID as is recommended for tables that store hierarchy.
The proposed script is:
CREATE TABLE dbo.MyEmployees  
(  
EmployeeID SMALLINT NOT NULL,  
FirstName NVARCHAR(30)  NOT NULL,  
LastName  NVARCHAR(40) NOT NULL,  
Title NVARCHAR(50) NOT NULL,  
DeptID SMALLINT NOT NULL,  
ManagerID SMALLINT NULL,  
 CONSTRAINT PK_EmployeeID PRIMARY KEY CLUSTERED (EmployeeID ASC),
 CONSTRAINT FK_MyEmployees_ManagerID_EmployeeID FOREIGN KEY (ManagerID) REFERENCES dbo.MyEmployees (EmployeeID)
);

### CODE REVIEW

**Comment by PRMerger3** [comment]
@ValeriyRU : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @ValeriyRU - Thanks for making these additions. The changes look good to me, but let me get someone else to verify.

@WilliamDAssafMSFT - Hey William, can you please also verify the changes to the example? https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15#d-using-a-recursive-common-table-expression-to-display-multiple-levels-of-recursion

**Comment by WilliamDAssafMSFT** [comment]
@VanMSFT Looks good to me. Thanks @ValeriyRU for the contribution! Good edits.

**Comment by VanMSFT** [comment]
Thanks, @WilliamDAssafMSFT!

#sign-off

**Pull request merged**
