### PR TITLE
Clarified parameter used in stored procedure

### PR DESCRIPTION
**Pull request by ReplTalk**
Clarified parameter used in stored procedure

### CODE REVIEW

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ReplTalk : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
@sign-off

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by Jak-MS** [comment]
Hi @MashaMSFT - merging this on the assumption that you're signing off on @stevestein 's behalf.

**Pull request merged**
