### PR TITLE
Add annotation instruction

### PR DESCRIPTION
**Pull request by jdpavek**
Previously proposed but w/ double if typo

### CODE REVIEW

**Comment by PRMerger10** [comment]
@jdpavek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@chugugrace Hi Grace,  Can you please assess this public PR #3017, about SQL Integration Services (SSIS).  I have set you as the formal Reviewer for this PR.  Can you please click the Review button, and either Approve or Reject or ..... as you see fit.

If you like the PR, put '# sign - off' into a new Comment box (_without_ the quotes or embedded spaces).  That will enable this PR to be merged.

Thanks a lot.  (GeneMi)
cc: @rothja

**Comment by chugugrace** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@chugugrace: I'm sorry - only the author of this article, @janinezhang, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@MightyPen: I'm sorry - only the author of this article, @janinezhang, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
Merging this PR #3017 now.

Janine Zhang (janinezhang) is no longer the real owner ('author') of these SSIS articles. Now the owner is Chunhua Gu (chugugrace).
chugugrace has signed off.  So I will simplify this situation and now merge this PR.
Thank you.  (GeneMi)

**Pull request merged**
