### PR TITLE
Removed some noise.

### PR DESCRIPTION
**Pull request by Protiguous**
Hopefully didn't break any formatting. (There are 2 spaces after some lines??)

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Protiguous : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by markingmyname — APPROVED** [review]
Everything still looks in order.

approved.

#sign-off

**Comment by PRMerger15** [comment]
@markingmyname, you can only sign off in the main PR conversation, not in review comments.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
