### PR TITLE
Update deny-schema-permissions-transact-sql.md

### PR DESCRIPTION
**Pull request by AssafFraenkel**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@AssafFraenkel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@AssafFraenkel - in the future, you could do these sorts of bulk updates in the private repo - all in a single PR to save on writing and review time. 

See, https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=main for more about working in the private repos.

**Comment by Jak-MS** [comment]
@VanMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
