### PR TITLE
extra "-" at the end of the signing key install

### PR DESCRIPTION
**Pull request by Guillaume-Fourrat**
xx@xx:~$ wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add –
gpg: can't open '–': No such file or directory

xx@xx:~$ wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add
OK

xx@xxi:~$ sudo apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa2048 2015-10-28 [SC]
      BC52 8686 B50D 79E3 39D3  721C EB3E 94AD BE12 29CF
uid           [ unknown] Microsoft (Release signing) <gpgsecurity@microsoft.com>

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Guillaume-Fourrat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Guillaume-Fourrat** [comment]
As indicated in issue  #3000 :
the dash is in fact correct (thanks @msebolt for pointing it out).
But in our doc we used a EnDash ASCII 0x96 instead of regular hyphen ASCII 0x2D.

So solution is either change trailing En-dash to actual hyphen
OR 
as in initial PR, delete the En-dash althogether, as the apt-key add also works with default piping redirection.

**Comment by MikeRayMSFT** [comment]
Verifying

**Comment by MightyPen** [comment]
Merge Conflict arose and must now be fixed, between this public PR #2901 versus private PR #11899 .

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/11899`

Assuming people are conscientious about doing frequent/timely GIT PULL UPSTREAM MASTER in the private repo ('sql-docs-pr'), we know this type of conflict problem is an unnecessary painful risk when Microsoft employees use the public repo ('sql-docs'). Microsoft employees should make their PRs in the private repo only.
Going forward, please use the private repo for PRs.  Thanks.

( @Guillaume-Fourrat @MikeRayMSFT @Peter-Msft @rothja )

**Pull request merged**
