### PR TITLE
adding a full name qualificaiton to the sp_setapprole infocation

### PR DESCRIPTION
**Pull request by PiJoCoder**
https://support.microsoft.com/en-us/help/263889/description-of-sql-server-blocking-caused-by-compile-locks

### CODE REVIEW

**Comment by PRMerger16** [comment]
@PiJoCoder : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @PiJoCoder , thank you so much for your contribution! The KB does add a good point!

#sign-off

**Comment by PiJoCoder** [comment]
Thanks @VanMSFT and @ktoliver. Ideally we should change all examples in DOCs to show fully-qualified calls to stored procedures. But one step at a time.

**Comment by VanMSFT** [comment]
Thanks @PiJoCoder! I agree, and will keep that in mind.

**Pull request merged**
