### PR TITLE
Update language-reference.md

### PR DESCRIPTION
**Pull request by craigdetter**
Propose adding SQL Operations Studio (preview)

### CODE REVIEW

**Comment by PRMerger7** [comment]
@craigdetter : Thanks for your contribution to the Azure documentation! The author, @edmacauley, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
Hi @craigdetter, great idea and thank you for the edit.  Can you change the url to:

https://docs.microsoft.com/sql/sql-operations-studio/download

Notice that the language string "en-us" is missing, that lets the system choose the correct language for the user.  Thanks!

**Comment by craigg-msft** [comment]
@craigdetter  can you please make the edit @edmacauley mentions?  Thanks!

**Comment by PRMerger9** [comment]
@craigdetter : Thanks for your contribution to the Azure documentation! The author, @edmacauley, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
Thank you @craigdetter .  merging.  fyi @edmacauley

**Pull request merged**
