### PR TITLE
fixed terms

### PR DESCRIPTION
**Pull request by allanhirt**
As per other PRs

1. Feature name is Always On failover cluster instance, or FCI. It's not a SQL Server failover cluster. The feature is one of the two Always On features.
2. Yes, I know the GUI is wrong. The names in the GUI didn't change in 2008 when it should have.

When Windows renamed the clustering portion of Windows Server failover cluster in 2008, it was confusing. So just saying failover cluster is both wrong and bad. You need to be explicit - FCI or WSFC since failover cluster has two meanings technically. Context is everything.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@allanhirt I resolved a merge conflict. @MashaMSFT please take a look at the proposed changes. Thank you!

**Comment by MashaMSFT** [comment]
hey @allanhirt , I've changed a few of these terms back, as things like "SQL Server" are going to be more important than "Always On" in some cases.

**Comment by allanhirt** [comment]
It’s your docs 😊

Just not a fan of inconsistency as you well know lol

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
