### PR TITLE
DRAFT: Update azure-active-directory-authentication for tablets

### PR DESCRIPTION
**Pull request by Rick-Anderson**
code is too wide for typical browser size on large monitors and way too wide for tablets and laptops.

### CODE REVIEW

**Comment by Court72** [comment]
@rick-anderson - When this PR is ready for review, take it out of draft mode by selecting "Ready for review."
   image

@David-Engel - When this PR is ready for review, can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@Rick-Anderson Please move this PR to the sql-docs-pr repository.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Please move this PR to the sql-docs-pr repository.

I tried that and I don't have permission. Per MS guidelines, ppl in other groups don't need to use the private repo. How about you look at my proposed changes the you move it to the private repo?

Or you move it to the private repo now and grant me permissions.

**Comment by rwestMSFT** [comment]
@Rick-Anderson The contributor guide has all the information you need to get permissions for `sql-docs-pr`. If you contact me internally, I'd be happy to help you out.

**Pull request closed without merging**
