### PR TITLE
Fix the F1 keywords

### PR DESCRIPTION
**Pull request by zikato**
Currently, F1 from sys.query_store_query DMV leads to this page instead of the correct one.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@zikato : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@rwestmsft

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @zikato for taking the time to submit this PR! Good catch. Your commit will be merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 

Thanks again for this feedback, your suggestions help improve our documentation.

#sign-off

**Comment by PRMerger12** [comment]
@WilliamDAssafMSFT: I'm sorry - only the author of this article, @rwestMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
