### PR TITLE
Update manage-certificates.md to reflect a process that exists.

### PR DESCRIPTION
**Pull request by cslthawkinsv**
There is no version of SQL that has an Import button or wizard in the instance Properties dialogue.  There is also no such button or wizard in the Availability Group properties dialogue.  Please update the instructions for all versions of SQL to reflect a process that is possible.  Selecting the certificate from the dropdown if it happens to be visible.

### CODE REVIEW

**Comment by cslthawkinsv** [comment]
@microsoft-github-policy-service agree company="Pentagon Federal Credit Union"

**Comment by cslthawkinsv** [comment]
The image shows the properties dialogue without any Import button.

**Comment by cslthawkinsv** [comment]
***@***.***

**Comment by cslthawkinsv** [comment]
I have tried to paste/email images but they don't show up.  It's a very easy process to replicate.  Simply open the named properties dialogues and observe there is no Import option but there is a dropdown menu.

**Comment by rwestMSFT** [comment]
@cslthawkinsv This is a screenshot from SQL Server Configuration Manager that I just took on 2022. It appears on 2019 as well.

I am closing your PR, as I cannot reproduce your issue.

Screenshot_2024-08-09_11h04m27

**Comment by cslthawkinsv** [comment]
Interesting,
Here is a screenshot showing that the import button does not exist:

**Comment by cslthawkinsv** [comment]
Here is another taken from SQL Server 2017 showing there is no import button even before TLS is configured the first time.

**Comment by rwestMSFT** [comment]
@cslthawkinsv Correct, it's not available in SQL Server 2017.

Are you visiting the properties pane of the **Protocols**, as the article describes?

**Comment by cslthawkinsv** [comment]
Randolph,
I see you are correct about the 2019 and 2022 versions.
I believe I attempted to edit the instruction page for SQL 2017.
That page now shows the edit I made (or at least the same text) in the single SQL Server Instance section but shows the Import instructions in both the failover cluster and availability group sections of the page.

Certificate management (SQL Server Configuration Manager) - SQL Server | Microsoft Learn<https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/manage-certificates?view=sql-server-2017&preserve-view=true>
https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/manage-certificates?view=sql-server-2017&preserve-view=true

This properties pane for protocols is indeed the one I’m showing.

**Comment by rwestMSFT** [comment]
Unfortunately, no images are coming through. They aren't supported if you use email.

I understand what you're saying, and the issue is related to how the underlying Markdown works. I will work with the product group to update the article to remove references to the Import button in SQL Server 2017. This may take several weeks due to the size of our current backlog.

Thank you for your contribution.

**Comment by cslthawkinsv** [comment]
Thank you for hearing me and taking action.
The feedback process is a bit of a hassle but still better than almost every other company’s document feedback process, where they even exist.

**Pull request closed without merging**
