### PR TITLE
Update migrate-dtu-to-vcore.md

### PR DESCRIPTION
**Pull request by ms-amsolo**
Adding Hyperscale specific scenario for geo-replicated databases

### CODE REVIEW

**Comment by ms-amsolo** [comment]
Hyperscale migration required geo-replication to be turned off
https://learn.microsoft.com/en-us/azure/azure-sql/database/manage-hyperscale-database?view=azuresql&tabs=azure-portal#prerequisites

**Comment by Court72** [comment]
@dimitri-furman

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ms-amsolo** [comment]
adding additional info as per the comments from Dimitri

**Comment by rwestMSFT** [comment]
@ms-amsolo Please close this and reopen it in `sql-docs-pr`.

**Comment by rwestMSFT** [comment]
Replaced by #9850.

**Pull request closed without merging**
