### PR TITLE
Update links to new content on Read-Scale for Windows AG

### PR DESCRIPTION
**Pull request by wsmelton**
Correcting incorrect reference to link I added in PR #690 
Adding new content page to the TOC for AG/Windows.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@wsmelton : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@wsmelton it seems like we've got a merge conflict - probably because we updated TOC.md while you were updating TOC.md. Can you clarify what the change is here. The new content you provided in the earlier PR is already in the live table of contents. It just came in a later PR. 

Thanks again for your contribution.

**Comment by wsmelton** [comment]
Yeah we can close this out since it already got updated... Don't know if the additional link on the other page is really necessary?

**Comment by MikeRayMSFT** [comment]
#please-close

**Comment by MikeRayMSFT** [comment]
@wsmelton -  I see the other change you were making I'll make that for you. Thanks.

**Pull request closed without merging**
