### PR TITLE
Update replace-template-parameters.md

### PR DESCRIPTION
**Pull request by divyapasa**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@divyapasa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
IMPORTANT: When this content is ready to merge, the reviewer must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger5** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Review by markingmyname — APPROVED** [review]
Thanks for yuor contribution.

**Pull request merged**
