### PR TITLE
Ite3: fix some wording issue for download page

### PR DESCRIPTION
**Pull request by MSraye**
Please use this for merge and ignore PRMerger17 and PRMerger19...

### CODE REVIEW

**Comment by PRMerger20** [comment]
@MSraye : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@Jak-MS : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Jak-MS : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Pull request merged**
