### PR TITLE
SQL Server Code Analysis revival!

### PR DESCRIPTION
**Pull request by ErikEJ**
Update walkthrough for modern Visual Studio.

@dzsquared @rwestMSFT

### CODE REVIEW

**Review by dzsquared — APPROVED** [review]

**Comment by dzsquared** [comment]
wow, thank you @erikej!

**Comment by ErikEJ** [comment]
@dzsquared You are welcome, it hurt my eyes. I also published a simpler and more modern version; https://erikej.github.io/dacfx/dotnet/2024/04/04/dacfx-rules.html

**Comment by rwestMSFT** [comment]
Taking this to an internal PR to clean up the article a little more.

Thanks, @ErikEJ!

**Comment by Court72** [comment]
@markingmyname

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ErikEJ** [comment]
Thanks, @rwestMSFT

**Pull request closed without merging**
