### PR TITLE
Added step to update serviceMetadata tag

### PR DESCRIPTION
**Pull request by Galaeci**
Without the metadata update the silverlight client was still throwing errors. Comments within the mdsWsHttpBehavior suggest that the need for this change is already part of the common knowledge around configuring MDS to use SSL.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Galaeci : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@LeoLiMSFT Please confirm whether the suggested change is correct.

**Comment by douglaslMS** [comment]
@Galaeci I am waiting to confirm this fix with the MDS product team. Meanwhile, before we can merge this PR, you'll have to resolve the merge conflicts. Shortly after you opened this PR, someone on my team did some bulk cleanup to make sure that all links used `https` and to remove the `en-us/` locale portion of any URLs that had one. Please don't undo any of these changes.

**Comment by douglaslMS** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@douglaslMS: I'm sorry - only the author of this article, @leolimsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
