### PR TITLE
Update enable-the-lock-pages-in-memory-option-windows.md

### PR DESCRIPTION
**Pull request by MashaMSFT**
#sign-off

### CODE REVIEW

**Comment by PRMerger14** [comment]
@MashaMSFT : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MashaMSFT** [comment]
@MikeRayMSFT 
Hey Mike, I got a request from CSS to add some clarity to step #7. Can you please sign off when you get the chance?
Thanks!

**Comment by MashaMSFT** [comment]
never mind, I'm a noob... closing this PR :|

**Pull request closed without merging**
