### PR TITLE
Update always-on-availability-groups-sql-server.md

### PR DESCRIPTION
**Pull request by allanhirt**
Added a note :)

### CODE REVIEW

**Comment by PRMerger3** [comment]
@allanhirt : Thanks for your contribution to the SQL documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@allanhirt thank you for your contribution. #sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by craigg-msft** [comment]
Thank you for this and the many others @allanhirt and @MikeRayMSFT

**Pull request merged**
