### PR TITLE
Update back-up-to-a-mirrored-media-set-transact-sql.md

### PR DESCRIPTION
**Pull request by rabryst**
Added space

### CODE REVIEW

**Comment by PRMerger3** [comment]
@rabryst : Thanks for your contribution to the SQL documentation! The author, @JennieHubbard, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
@rabryst Thank you for adding that space! :)

**Comment by JennieHubbard** [comment]
#sign-off

**Comment by craigg-msft** [comment]
Thank you @rabryst and @JennieHubbard. merging.

**Pull request merged**
