### PR TITLE
updated the download page for the SqlServer PowerShell Module with more examples

### PR DESCRIPTION
**Pull request by SQLDBAWithABeard**
I decided as I keep writing this out for my presentations to get it added to the documentation!! 
So I have updated the download SqlServer Module page to show how to install as admin or not, how to import specific versions and how to update

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @SQLDBAWithABeard did you get a chance to sign the cla?

**Comment by SQLDBAWithABeard** [comment]
Hi @craigcaseyMSFT I signed it straight after the PR - Do I need to do anything else?

**Comment by craigcaseyMSFT** [comment]
You might have the wrong Craig as none of this looks familiar.

**Comment by SQLDBAWithABeard** [comment]
Many apologies, it should have tagged @craigg-msft - autocorrect fail

Craig
 I signed it straight after the PR - Do I need to do anything else?

**Comment by craigg-msft** [comment]
closing and re-open to trigger a re-run of validation and cla check.

**Comment by craigg-msft** [comment]
cla not required label now shows.  merging.

**Pull request merged**
