### PR TITLE
Update data-ingestion-restore-database.md

### PR DESCRIPTION
**Pull request by vesatikkanen**
Master Pod name has changed and is now master-0 instead of mssql-master-pool-0. Code examples do not work currently (tested with: Ubuntu 18.04)

### CODE REVIEW

**Comment by PRMerger6** [comment]
@vesatikkanen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@vesatikkanen  - thank you. Verifying.

**Comment by mihaelablendea** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@mihaelablendea: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
