### PR TITLE
Consistent SQL formatting for SQL examples under page "JSON data in SQL Server"

### PR DESCRIPTION
**Pull request by kabirbaidhya**
Page Edited - [JSON data in SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017)

### Changes
 - Capitalize SQL types and keywords
 - Add semi-colons to the statements that are missing them
 - Make indentation and spacing consistent across the page for SQL & JSON examples (2 spaces for indentation)
 - Proper spacing in comments and in-between operators for readability.  
 - Markdown lint fixes: trim trailing whitespaces, add new lines and change bullets.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@kabirbaidhya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@kabirbaidhya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@jovanpop-msft - Could you review the proposed changes? Thanks.

**Comment by MightyPen** [comment]
#sign-off 

@ktoliver Hi, please Merge this now-Approved PR 3145.
Thanks.

**Comment by PRMerger17** [comment]
@MightyPen: I'm sorry - only the author of this article, @jovanpop-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
@PRMerger17  We need the rules to have some common sense here. Please merge this PR.
Thanks.

cc: @ktoliver

**Comment by kabirbaidhya** [comment]
@MightyPen Sure. Thanks for your feedback. Glad to offer help and I'm always open to contributing to #opensource to help make things better :).

**Pull request merged**
