### PR TITLE
Update json-data-sql-server.md

### PR DESCRIPTION
**Pull request by chadbaldwin**
JSON function definitions are out of order

### CODE REVIEW

**Comment by PRMerger15** [comment]
@chadbaldwin : Thanks for your contribution! The author, @jovanpop-msft, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@chadbaldwin : Thanks for your contribution! The author, @jovanpop-msft, has been notified to review your proposed change.

**Comment by stevestein** [comment]
Resolved conflict 
#sign-off

**Comment by PRMerger6** [comment]
@stevestein: I'm sorry - only the author of this article, @jovanpop-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
