### PR TITLE
Update setup-steps-for-extensible-key-management-using-the-azure-key-…

### PR DESCRIPTION
**Pull request by PhilB-MSFT**
…vault.md

Adding note not to disable original key upon rotation - will stop SQL Server recovering the DB until that version is enabled once again.  @MashaMSFT - FYI.

### CODE REVIEW

**Comment by Court72** [comment]
@rupp29

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Rupp29** [comment]
I’m on medical leave and will not be able to look into this. You may want to ping @Rajat ***@***.***> as he may know the answer.
But my first thought is that the key rotation enhancement for SQL DB does not apply to EKM….
Also, unless Rajat and the engineers built this into the engine to handle this scenario, the SQL Server Connector does not support uploading your own key (CMK).

Sorry for not being able to dive into this, but I’m not supposed to be working!

::Adrian
425.753.4998

**Comment by Court72** [comment]
#hold-off 

@kagbakpem (per @rajat-rastogi OOF message), would you take a look at the proposed changes? See [Adrian's comment](https://github.com/MicrosoftDocs/sql-docs/pull/8216#issuecomment-1299242571).

**Comment by Court72** [comment]
Adding listed `ms.reviewers`, @VanMSFT and @rwestMSFT, as well. Could you review or reassign this pull request? Thanks!

**Comment by VanMSFT** [comment]
Following up with Rajat on this.

**Comment by VanMSFT** [comment]
Pulled in changes and made updates in https://github.com/MicrosoftDocs/sql-docs-pr/pull/25772. Closing this as it's being taken care of in a private PR.

**Pull request closed without merging**
