### PR TITLE
Removed redundant important message.  Added new important message

### PR DESCRIPTION
**Pull request by ChrisLound**
Old message about not clicking ok for the PowerBI template is now redundant.
Added "important" message for setting default instance name.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@ChrisLound : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@pochiraju - Would you review the proposed changes? Thanks

**Comment by pochiraju** [comment]
What to review? I don’t see any content to review.
Thanks
Raj

**Comment by pochiraju** [comment]
Can you access this link, Raj?  https://github.com/MicrosoftDocs/sql-docs/pull/1956/files

This will show you the changes that Chris Lound is proposing.

Regards,

Jim Toland

From: Venkata Raj Pochiraju <rajpo@microsoft.com>
Sent: Friday, April 19, 2019 9:59 AM
To: MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Jim Toland <jtoland@microsoft.com>
Subject: RE: [MicrosoftDocs/sql-docs] Removed redundant important message. Added new important message (#1956)

What to review? I don't see any content to review.
Thanks
Raj

**Comment by HJToland3** [comment]
GitHubber17, how do we resolve the conflicts! How do I actually even see them?

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author, @HJToland3, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @HJToland3 I resolved the merge conflict (you select the **Resolve conflicts** button, and then select which version to keep in the UI that appears). It wasn't clear what was causing the conflict... I made sure that the resolved commit matches the original commit. And, we'll merge it now. Thanks!

**Pull request merged**
