### PR TITLE
Added missing machine learning features

### PR DESCRIPTION
**Pull request by NelGson**
Major features were missing in the SQL Server 2017 Machine Learning Services section. Those have been added. (Native scoring, Package managemen, Performance improvements for sp_execute_external_script)

### CODE REVIEW

**Comment by NelGson** [comment]
Can someone please accept this pull request?

**Comment by craigg-msft** [comment]
@HeidiSteen can you please review.  Should these / are they already added to the MLS focused topic  [What's new in SQL Server Machine Learning Services](~/advanced-analytics/what-s-new-in-sql-server-machine-learning-services.md).

**Comment by craigg-msft** [comment]
Thank you @NelGson for the content help.  Its under review.

**Comment by NelGson** [comment]
Yes, they are already included in What’s new for Machine Learning Services.

Thanks,
Nellie

**Comment by HeidiSteen** [comment]
#sign-off -- looks good

**Pull request merged**
