### PR TITLE
Update ss-linux-cluster-availability-group-create-prereq.md

### PR DESCRIPTION
**Pull request by suresh-kandoth**
update AlwaysOn XE with new docs link.

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @MikeRayMSFT - I can't find an author attribute for this include file. You've updated it several times--could you review the PR? Thanks.

**Comment by ktoliver** [comment]
If the update is approved, the PR review team can remove the locale (en-us) from the link that's added.

**Comment by ktoliver** [comment]
Hi @MikeRayMSFT - Could you take a look at this PR? Thanks.

**Comment by rothja** [comment]
@suresh-kandoth Thanks for the suggested fix. @MikeRayMSFT I think we need to make this a relative link. To make sure we do it right, can you make the change in a separate PR to make sure we put a valid relative link in there. Then we can close this without merging as fixed. Thanks!

**Comment by MikeRayMSFT** [comment]
I had a problem with the link and am fixing it now.

**Pull request closed without merging**
