### PR TITLE
Update sql-server-linux-availability-group-failover-ha.md

### PR DESCRIPTION
**Pull request by tejasaks**
Updated page with additional guidance on clearing the auto generated constraint with manual resource move operation and how to move the resource while clearing constraint at the same time.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@tejasaks : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hello @tejasaks - Contributors who work in the Product Manager role should open pull requests in the private repository for advanced quality validations and staging (you also can sign off directly in the private repo). To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. We’ll leave this PR for review in the public repo, but would you make future article updates in the private repo?  Thanks!

**Comment by VanMSFT** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@VanMSFT: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger19** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@VanMSFT - Do you want to sign off again when you're done making edits? To make sure I don't interrupt your work . . . Thanks!

**Comment by PRMerger17** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by MikeRayMSFT** [comment]
Strange because @VanMSFT is a reviewer. I updated the author and ms.author alias.

**Comment by ktoliver** [comment]
@MikeRayMSFT The PRMerger comment refers to the _contributor_, @tejasaks. The comment isn't triggered until sign-off is added, unfortunately (and it's added very sporadically).

**Pull request closed without merging**
