### PR TITLE
Add Sequel to the list of ORMs

### PR DESCRIPTION
**Pull request by JesseChavez**
This gem is a full feature ORM and more, It will allow you to connect to SQL server via ADO, ODBC, JDBC, and TinyTds.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@JesseChavez : Thanks for your contribution to the Azure documentation! The author, @MightyPen, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@MightyPen please review.

**Comment by MightyPen** [comment]
This addition seems reasonable.  It is adding a non-Msft link, but the article already has non-Msft links.

#sign-off

**Comment by MightyPen** [comment]
@craigg-msft Craig, Yes this is a fine addition. Please Approve this PR 419.

**Comment by PRMerger15** [comment]
@: Only the author, @MightyPen, can sign off on this pull request.

**Comment by PRMerger7** [comment]
@: Only the author, @MightyPen, can sign off on this pull request.

**Comment by PRMerger14** [comment]
@: Only the author, @MightyPen, can sign off on this pull request.

**Comment by PRMerger20** [comment]
@: Only the author, @MightyPen, can sign off on this pull request.

**Comment by PRMerger6** [comment]
@: Only the author, @MightyPen, can sign off on this pull request.

**Comment by PRMerger9** [comment]
@: Only the author, @MightyPen, can sign off on this pull request.

**Comment by PRMerger10** [comment]
@: Only the author, @MightyPen, can sign off on this pull request.

**Comment by MightyPen** [comment]
#sign-off

**Pull request merged**
