### PR TITLE
Update APPLIES TO in Rowset Functions

### PR DESCRIPTION
**Pull request by sqlsauce**
Some rowset functions are supported in Azure SQL Database and Azure SQL Data Warehouse, as the individual function pages indicate, so this summary should indicate that support.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@sqlsauce : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@mikeraymsft Hi Mike, this public PR #3436 seems like its narrow claim is likely true.

@julieMSFT Hi Julie, is this function valid for SQL DW (Synapse), or more directly, should we approve and merge this PR?

**Comment by julieMSFT** [comment]
@XiaoyuMSFT HI Xiaoyu, can you verify that row set functions are available in SQL DW?

**Comment by XiaoyuMSFT** [comment]
@julieMSFT  4 out of the 5 functions in this article are not supported by Azure SQL DW.  They are: •	OpenDataSource, OPENROWSET, OPENQUERY, and OPENXML.  The individual articles linked to each of these functions has the accurate APPLY TO values.

**Comment by julieMSFT** [comment]
#13012

**Comment by julieMSFT** [comment]
@mikeray I have removed the article and redirected to the top level article for rowset. https://github.com/MicrosoftDocs/sql-docs-pr/pull/13012

**Comment by julieMSFT** [comment]
@sqlsauce Thank you for bring this to our attention. This is confusing and was not very helpful. I have removed this page and redirected to the individual pages for each function. The individual pages show the product supported for each function. I will proceed with closing this PR.

**Pull request closed without merging**
