### PR TITLE
Address CSS doc update request for SQL backup/restore

### PR DESCRIPTION
**Pull request by AbhishekMallick-MS**
As per the inputs from PM, updated the text.

### CODE REVIEW

**Comment by AbhishekMallick-MS** [comment]
Hi @SudhirRaparla - Fixed supportability info specific to Azure Backup to address CSS doc ask with PM's confirmation. Request you to merge. Thanks. #sign-off

**Comment by SudhirRaparla** [comment]
@AbhishekMallick-MS  - The support for Cross-Server and Cross-Subscription is not available for Azure SQL DB yet.

**Comment by Jak-MS** [comment]
@SudhirRaparla 
- do you want to modify the PR or close it? (to close, put `#please-close` in a comment.
- if you keep it open, sign off when it's approved, and I'll review / merge.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Please make changes to the sql-docs-pr if you are staff.

**Pull request closed without merging**
