### PR TITLE
Update logins-create-manage.md

### PR DESCRIPTION
**Pull request by Max-Meng**
Synapse contains dedicated SQL pool and serverless SQL pool, there were some differences between them, but this article didn't make it clear whether it is for dedicated SQL pool or serverless SQL pool.  I have applied some modifications, to clarify a feature applies to dedicated SQL pool only, and also added a section which applies to serverless SQL pool.

### CODE REVIEW

**Comment by Court72** [comment]
@AndreasWolter

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by AndreasWolter** [comment]
Hi. I am not working on Synapse. But it sounds odd to me that there would be a sysadmin role. @kedodd can you help here?

**Comment by kedodd** [comment]
> Hi. I am not working on Synapse. But it sounds odd to me that there would be a sysadmin role. @kedodd can you help here?

@veljko-msft  As the sysadmin is mentioned for serverless, can you recommend someone to take a look?  "Add the SQL login to the [sysadmin fixed server role](/sql/relational-databases/security/authentication-access/server-level-roles) using the [ALTER SERVER ROLE](/sql/t-sql/statements/alter-server-role-transact-sql) statement.."

**Comment by ilijazagorac** [comment]
sysadmin server role exists in serverless, so this is ok.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Comment by Court72** [comment]
Thanks, @williamdassafmsft. Can you open a PR in the private repo to update the `author` and `ms.author` metadata since Andreas is no longer working on synapse?

**Comment by Court72** [comment]
Due to the upcoming conference, all merging and publishing are on hold until the morning of 5/23.

This PR is ready for merge on 5/23.

#label: "event-triaged-to-10AM"
#label: "missed-content-complete"

**Comment by WilliamDAssafMSFT** [comment]
This is not necessary.

**Pull request merged**
