### PR TITLE
Update of Sections about TCP/IP, SQLPS

### PR DESCRIPTION
**Pull request by Karl-WE**
it nearly drove me mad when I was in the situation I wanted to enable TCP/IP (uneedingly) on a SQL Server 2017, hosted on Server 2019 Core. I am adding this based on my experience because the documentation and references were incomplete. 
Thanks review and merging.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@Karl-WE Thank you very much for the suggestions to the docs, and sorry that they have not been clear about this. We are looking into it. I'm also including another expert in our networking/connectivity space, Van. @VanMSFT / @MikeRayMSFT could one of you confirm the suggested changes. Thank you!

**Comment by VanMSFT** [comment]
Thanks for the submission, @Karl-WE! I made changes to your proposal to have them more in-lined with our docs. Please let us know if there are any concerns.

@MikeRayMSFT Hey Mike - Please check the changes and see if it makes sense to merge.
@markingmyname - FYI

**Comment by Karl-WE** [comment]
Thanks I am still pending to create a PR for the counterpart #4828 since my PR and the original skewed after such a long time.

**Comment by Karl-WE** [comment]
Hi @MikeBazMSFT, will this be merged? I hope I do not have to rewrite this PR because of the long delays.
I have updated related docs are requested by @markingmyname  
#5118

**Comment by Karl-WE** [comment]
Remarks to this dated PR: we can remove text and cross reference to #5119 
I plea to remove the reference how to manage SQL on Server Core Section "Enable TCP/IP on the Instance of SQL Server"  and insert a link instead.
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/configure-sql-server-on-a-server-core-installation?view=sqlallproducts-allversions
as the section is a duplicate of this article and makes it harder to maintain.

**Comment by MikeBazMSFT** [comment]
@Karl-WE You tagged the wrong person.  I assume you wanted @MikeRayMSFT based on the discussion.

**Comment by MikeRayMSFT** [comment]
@Karl-WE thank you for the submission, and please accept my apologies for the late reply. I'm going to pull your changes into a private branch and prepare to publish. Thank you.

**Comment by MikeRayMSFT** [comment]
Pulled changes into private branch.

**Comment by Karl-WE** [comment]
thank you @MikeRayMSFT . Please be aware about the dependecies to other PRs in this matter for this PR.

**Comment by MikeRayMSFT** [comment]
I have pulled all of the changes in the following PRs together. 

MicrosoftDocs/sql-docs#5119
MicrosoftDocs/sql-docs#4827
MicrosoftDocs/sql-docs#5118
MicrosoftDocs/sql-docs#4828

If this is not complete, please let me know.

**Comment by Karl-WE** [comment]
from my point of view #4828 can be dropped from the table as it is a PR based on an old version, @markingmyname asked me to reprise 
I am thankful to be kept in the loop when the private review is done. I know it is kind of "tapping in a hornet nest" when I stumbled across this but after all I hope that no one has to suffer all the things we had with the current docs regarding SQLPS.
I am not blaming anyone, just sometimes with SaaS and docs are getting out of sync - quite naturally.

**Comment by MikeRayMSFT** [comment]
@Karl-WE would you mind emailing me: [mikeray@microsoft.com](mailto:mikeray@microsoft.com)? I would like to ask a few questions. Thank you. Mike

**Pull request closed without merging**
