### PR TITLE
Update change-the-target-recovery-time-of-a-database-sql-server.md

### PR DESCRIPTION
**Pull request by SDPMrem71**
Confusion averted

### CODE REVIEW

**Comment by PRMerger6** [comment]
@SDPMrem71 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
The typo fix looks good. @SDPMrem71 Thanks!

Merging in this repository is suspended until Tuesday, May 19. Merging will resume at 7:00 AM PT Tuesday. This PR is ready to merge. Thanks.

**Comment by ktoliver** [comment]
#sign-off so the PR is in the ready-to-merge queue for 5/19

**Comment by PRMerger15** [comment]
@ktoliver: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@ktoliver: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
