### PR TITLE
Replaced "SQL Database" with "Azure SQL Database"

### PR DESCRIPTION
**Pull request by aalamrangi**
Simply writing SQL Database could be confusing to readers not yet familiar with Azure.

Replaced all occurrences of -

- SQL Database, or

- [!INCLUDE[ssSDS](../../includes/sssds-md.md)]

to -

- [!INCLUDE[ssSDSfull](../../includes/sssdsfull-md.md)]

so that it shows up as Azure SQL Database.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@aalamrangi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @aalamrangi! We appreciate the help. I'm approving these changes.

#sign-off

**Comment by Jak-MS** [comment]
@aalamrangi @VanMSFT - because this PR is in the public repo, we can't verify that these changes will render correctly. We need to move the commits to the private repo to verify that they render. thanks. 

We will tag you @VanMSFT when the new PR is created. Assuming everything looks good on staging, we'll sign off and get this merged.

In the meantime, I'm holding off of this PR (which will be closed after the private PR is ready to go).
Thanks.
#hold-off

**Comment by Jak-MS** [comment]
the commits from this PR have been moved to https://github.com/MicrosoftDocs/sql-docs-pr/pull/11514. #please-close

**Pull request closed without merging**
