### PR TITLE
Typo "**SqlAgent@Adventure-Works.com**"→"**SqlAgent\@Adventure-Works.…

### PR DESCRIPTION
**Pull request by hyoshioka0128**
…com**"

Bold with escape characters

https://docs.microsoft.com/en-us/sql/relational-databases/database-mail/configure-database-mail?view=sql-server-ver15

### CODE REVIEW

**Comment by PRMerger17** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@stevestein - Could you review the proposed update?

Escaping the @ character here (which currently appears in the live version), makes the email address "hot," which isn't optimal in this case because it's an example email address.

**Comment by rothja** [comment]
@ktoliver I think this is not optimal but OK as a customer understands it is an example. #sign-off

**Comment by PRMerger9** [comment]
@rothja: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
