### PR TITLE
Adding clarification points for readability and understanding

### PR DESCRIPTION
**Pull request by PiJoCoder**
This is based on user feedback. Sections:

PFS/GAM/SGAM ordering
Row offset
Row overflow

### CODE REVIEW

**Comment by PRMerger9** [comment]
@PiJoCoder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Per review from @bluefooted 

Thanks @PiJoCoder 

#sign-off

**Comment by PRMerger16** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @rothja, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by rothja** [comment]
#sign-off

**Pull request merged**
