### PR TITLE
typo: Trailing `.md` extension on `.aspx` link

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author, @mzaman1, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@nschonni - thanks for catching these!

#sign-off

**Comment by PRMerger19** [comment]
@stevestein: I'm sorry - only the author of this article, @mzaman1, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mzaman1** [comment]
#sign-off

**Pull request merged**
