### PR TITLE
IP address is not supported

### PR DESCRIPTION
**Pull request by taroarai**
As RFC 13373362, IP address is not supported, and SSMS 17 was producing the same message as localhost, it should mention IP address in the note. SSMS 18 has bug which does not stop customer to use IP address, so it should mention in this.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@taroarai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
thanks @taroarai! #sign-off

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
