### PR TITLE
Update serverproperty-transact-sql.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
Added a new item PathSeparator.  Availed in MS Windows 17 to support Linux.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@DanielAdeniji : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @DanielAdeniji! Made a small change and approved.

#sign-off

**Comment by DanielAdeniji** [comment]
Van:-

Thanks so very much Family.

Daniel
________________________________

**Comment by PRMerger16** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@DanielAdeniji: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
