### PR TITLE
Azure Data Studio Tutorial Charts

### PR DESCRIPTION
**Pull request by aandino-dev**
I think that azuredatastudio have a great feature to visualize the data out the box. I tried to help adding some documentation to this topic. I tried to use these feature several times in the beta and there no documentation for these great feature.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@aandino-dev : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@aandino-dev - thanks for putting this together. Because it's a new article, there's a bit more to the process than simply accepting and merging it in, so we'll get back to you soon after an initial internal review.

Thanks!

**Comment by ktoliver** [comment]
@aandino-dev

**Comment by aandino-dev** [comment]
@yualan, @ktoliver  thanks I will work with the request.

**Comment by craigg-msft** [comment]
@aandino-dev thank you for your time.  The way interpret the last few communications, you will rework the content and submit a new PR, so I am closing this one as it has been open a while.  Thank you

**Pull request closed without merging**
