### PR TITLE
Removed extract description of data

### PR DESCRIPTION
**Pull request by way0utwest**
extract creates a dacpac with schema. No user data is included. Export gets data into a bacpac file with schema.

### CODE REVIEW

**Comment by dzsquared** [comment]
Hiya!
We don't talk about it much, but you *can* include data in a dacpac if you add specific properties.
For example, if you added /p:ExtractAllTableData=true, your dacpac would contain the data for all of your tables as well.

Alternatively, you could add properties for /p:TableData=SalesLT.Customer and /p:TableData=SalesLT.Address, which would cause your dacpac to only contain the data for those 2 tables.

**Comment by way0utwest** [comment]
That's interesting, I found other places where it says dacpac is only data. This only mentions schema for dacpac (https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-ver16) and this says only objects (https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/extract-a-dac-from-a-database?view=sql-server-ver16)

I think this is cool, and I learned something. I suspect other files need to be updated to note data, and this likely needs a little guidance. Feel free to reject this and I'll try to come up with something better that explains this.

**Comment by Court72** [comment]
@dzsquared

If the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

If this PR should be closed instead, enter a `#please-close` comment.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
I'm going to close this one, Steve, based on Drew's feedback. Thanks for the contribution.

**Comment by dzsquared** [comment]
@way0utwest - I've noted the issues with the pages you linked that incorrectly describe the limitations on dacpacs/extract.  Will message you via other channels to validate if I'm sufficiently clearing it up. :)

**Pull request closed without merging**
