### PR TITLE
Changes and additions to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by taroarai**
Customer request, could you consider adding instructions for domain participation in Ubuntu 18.04?

### CODE REVIEW

**Comment by PRMerger15** [comment]
@taroarai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by tejasaks — APPROVED** [review]
#sign-off

**Comment by PRMerger19** [comment]
@tejasaks, you can only sign off in the main PR conversation, not in review comments.

**Comment by tejasaks** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@tejasaks: I'm sorry - only the author of this article, @Dylan-MSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by VanMSFT** [comment]
Hi @ktoliver - Can you please help merged? Much appreciated. Thanks!

@taroarai - Thanks Taro!

**Comment by Dylan-MSFT** [comment]
#sign-off

**Pull request merged**
