### PR TITLE
docs: readability

### PR DESCRIPTION
**Pull request by gh0st**
The way the syntax highlighting was formatted was making me want to slam my head through my desk.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@gh0st : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Hi @craigg-msft - can you review or re-assign this one? thanks.

**Comment by craigg-msft** [comment]
Thank you @gh0st

**Comment by gh0st** [comment]
You're welcome! When's the next release planned? It's going to be fun seeing these changes published.

**Pull request merged**
