### PR TITLE
fix: Remove ".md" from absolute links

### PR DESCRIPTION
**Pull request by nschonni**
Prepend "/sql/" since the are part of this docset

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by nschonni** [comment]
I have "Allow edits from maintainers." so feel free. I probably won't get to this till the evening

**Comment by nschonni** [comment]
Took a quick look, but since it's part of the old 2014 docs, these don't really have local relate links. Searching in the repo for "docs.microsoft.com/sql/" I got 362 hits, so maybe that stuff is better for a separate cleanup

**Comment by douglaslMS** [comment]
@nschonni The 2014 docs are just another folder in the repo, so relative paths should work like any other. But the pathing is tricky, so I'll accept your changes to use the absolute path.

**Comment by douglaslMS** [comment]
#sign-off

**Pull request merged**
