### PR TITLE
Update suspend-an-availability-database-sql-server.md

### PR DESCRIPTION
**Pull request by nqg04789**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@nqg04789 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by MikeRayMSFT — APPROVED** [review]
Approved based on documentation in https://docs.microsoft.com/en-us/powershell/module/sqlps/suspend-sqlavailabilitydatabase?msclkid=bdb78dfcbcd711ecbaca15fb40cded75&view=sqlserver-ps

**Comment by MikeRayMSFT** [comment]
With thanks to @nqg04789 

#sign-off

**Comment by PRMerger7** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
