### PR TITLE
Update OpenShift quickstart

### PR DESCRIPTION
**Pull request by cblecker**
- Fix links to OpenShift storage docs for Azure
- Don't suggest provisioning a custom storage class, as one comes preconfigured in OpenShift
- Remove static fsGroup
- Ensure fsGroup will be rewritten if it doesn't match
- Add required NET_BIND_SERVICE capability

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rwestMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@cblecker Thanks for your contribution. I will ask a PM to review it in the next few days.

**Review by amvin87 — APPROVED** [review]

**Comment by amvin87** [comment]
Hi @rwestMSFT just approved these changes we can go ahead and update the article please.

**Comment by rwestMSFT** [comment]
The changes from this PR will be included in an internal refresh. When that happens, this PR will automatically close.

@cblecker Thanks for your contribution! You can expect to see the updated article in the next day or so.

**Pull request closed without merging**
