### PR TITLE
update release note for SSDT for VS2017 15.9.2

### PR DESCRIPTION
**Pull request by MSraye**
update release note for SSDT for VS2017 15.9.2

### CODE REVIEW

**Comment by PRMerger20** [comment]
@MSraye : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevestein** [comment]
#hold-off 

DO NOT MERGE YET

**Comment by stevestein** [comment]
#sign-off

**Comment by stevestein** [comment]
@jborsecnik - same here. please merge.

**Pull request merged**
