### PR TITLE
add commend on AKV FW

### PR DESCRIPTION
**Pull request by yochananrachamim**
in case of AKV FW is enabled it will block access to the AKV and databases will be dropped, this is common mistake done by customers and this is not clear from the document that this is what is going to happen.

### CODE REVIEW

**Comment by aliceku** [comment]
I agree a note about AKV FW is helpful, but here this note is inserted in the section about keys, not key vaults.  This needs to move up to the key vault section.  I can make the change in the right place if that helps.

**Comment by yochananrachamim** [comment]
@aliceku - Thank you! That would be very helpful

**Comment by aliceku** [comment]
I made the change, going through the process now

**Comment by aliceku** [comment]
@yochananrachamim the change is now live you can delete this pull request.

**Pull request closed without merging**
