### PR TITLE
Improved one sentence

### PR DESCRIPTION
**Pull request by Exorust**
Edited a sentence to be more grammatically correct

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Exorust : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
#hold-off
@Exorust This change is a good idea, and I would like to approve it. But there is one minor blocking problem: There is a SPACE character missing at the start of the sentence that you edited.  The text is near the following - see the words "instances.This":
.
"distinct instances.This is easily achieved using docker, but each container"
.
Please add the necessary space, and then I can approve it.  And, remember to @ mention me after you add the space!

**Comment by PRMerger18** [comment]
@Exorust : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by rothja** [comment]
@Exorust Thank you for the change. I'm signing off on it. #sign-off.

**Pull request merged**
