### PR TITLE
Update isdate-transact-sql.md

### PR DESCRIPTION
**Pull request by victren**
a date or time value from datetime2 value will return 0.
for example:
select isdate('0001-01-01') as d, isdate('10:19:41.1777') as t
result:
d           t
----------- -----------
0           0

(1 row affected)

### CODE REVIEW

**Comment by PRMerger4** [comment]
@victren : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@victren : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by cawrites** [comment]
@victren thank you for providing this update.

**Pull request merged**
