### PR TITLE
data types fix; remarks simplify; more links added;

### PR DESCRIPTION
**Pull request by gotqn**
the view types are different; links were move from remarks section to "see also" section; also "database" and "server" firewall rules objects links were added in order to have full picture of the functionalities available;

### CODE REVIEW

**Comment by PRMerger15** [comment]
@gotqn : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Cc @VanMSFT - This submission is similar to PR #1814. Thanks

**Comment by CarlRabeler** [comment]
@GitHubber17 please assign to @VanMSFT

**Comment by PRMerger10** [comment]
@VanMSFT : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks again for the suggested changes, @gotqn!

Verified. #sign-off

**Comment by PRMerger12** [comment]
@VanMSFT: I'm sorry - only the author of this article, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
