### PR TITLE
Correct RBAC permissions required

### PR DESCRIPTION
**Pull request by nachoalonsoportillo**

### CODE REVIEW

**Comment by Court72** [comment]
@WilliamDAssafMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @nachoalonsoportillo, reviewing and reaching out internally. Will update.

**Comment by WilliamDAssafMSFT** [comment]
This looks good, thanks @nachoalonsoportillo! 

#sign-off

**Comment by Jak-MS** [comment]
@nachoalonsoportillo @WilliamDAssafMSFT - I'll merge this, but noticed what might be an extraneous 'and' in this line:

image

if that should be removed, please submit a new PR to do so. thanks

**Pull request merged**
