### PR TITLE
updating SqlClient docs

### PR DESCRIPTION
**Pull request by JRahnama**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@JRahnama : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@jrahnama

Should this PR have been opened in the private repo instead of the public repo?

Thanks.

**Comment by Court72** [comment]
@david-engel

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by David-Engel** [comment]
#please-close

**Pull request closed without merging**
