### PR TITLE
Provide link to the docs listing the iso data formats

### PR DESCRIPTION
**Pull request by simonsabin**
No one knows the iso formats off their head. Made it a nice link to the date time styles on the cast and convert page

### CODE REVIEW

**Comment by PRMerger10** [comment]
@simonsabin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@jaszymas Could you review the proposed change? If the PR is approved, the PR review team can remove the `en-us` locale from the docs.microsoft.com URL before merging the PR. Thanks.

**Comment by VanMSFT** [comment]
Hi @simonsabin! Thank you so much! I'll approve this PR.

#sign-off

**Comment by PRMerger6** [comment]
@VanMSFT: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Thanks @VanMSFT

**Pull request merged**
