### PR TITLE
Join database to second secondary

### PR DESCRIPTION
**Pull request by tboggiano**
Based on a support case I had open with Microsoft you have to after the direct seeding of the database is completed on the second secondary join database to the secondary.  I had to do this each of the 8 times I created a distributed AG.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@tboggiano : Thanks for your contribution to the SQL documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@tboggiano : Thank you for the contribution. Can you make a couple of small changes?
Please change:
 "seoncdary of the second availabilty"
to 
 "secondary of the second availability"

After that we can sign-off on the change and you will be attributed for the update.

Otherwise I'm happy to update the article directly with your suggestion, but you will not be attributed.

Again, thank you for the contribution.

**Comment by MikeRayMSFT** [comment]
@tboggiano thank you for your submission. We appreciate your efforts to improve our content! #sign-off

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
