### PR TITLE
Added: Accessing the classification metadata

### PR DESCRIPTION
**Pull request by giladmit**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@giladmit : Thanks for your contribution! The author, @giladm, has been notified to review your proposed change.

**Comment by giladmit** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@giladmit: I'm sorry - only the author of this article, @giladm, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@giladmit - If you are the listed author for an Azure technical article, you need to use the private repository (azure-docs-pr) for all content updates and new articles. 

Closing this pull request so that you can make updates in the private repo. Thanks.

**Pull request closed without merging**
