### PR TITLE
Update download-sql-server-management-studio-ssms.md

### PR DESCRIPTION
**Pull request by thomasbragaloni**
updating Applies to section as PDW does not support SSMS. now reflecting the intended

### CODE REVIEW

**Comment by PRMerger6** [comment]
@thomasbragaloni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@thomasbragaloni @dnethi 
Here in PR 2264:

Caution: 'sql-docs-pr/docs/docfx.json' specifies the default OPS Versioning monikers for all 'docs/ssms/' articles. Here is the default:

`">= aps-pdw-2016 || = azure-sqldw-latest || = azuresqldb-current || >= sql-server-2016 || = sqlallproducts-allversions"`

Any SSMS article that does Not apply to PDW must therefore have its own metadata line that omits PDW, probably something like the following example line, near the top inside the .md file:

`monikerRange: "= azure-sqldw-latest || = azuresqldb-current || >= sql-server-2016 || = sqlallproducts-allversions"`

It is not enough to remove PDW from the INCLUDE AppliesTo that the .md references.

@markingmyname Hi Mark, you might want to initiate a general review of the alignments between AppliesTo vs docfx.json vs monikerRange, for all docs/ssms/ articles.  I suspect that some of the variety is misaligned.

Thanks. GeneMi. 2019/June/12 10:22am.

**Comment by rothja** [comment]
@thomasbragaloni Thanks for your patience as we look at the best way to address this. @dnethi @markingmyname , can you confirm that SSMS does not work for PDW? If so, we might need to look at some of the versioning aspects that Gene mentioned. I can help with that too. I assigned @markingmyname  to this PR as well. Thank you!

**Comment by markingmyname** [comment]
@Matteo-T for awareness

**Comment by PRMerger16** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
@rothja - confirmed that SSMS does not support PDW.  will need to revisit the "Applies To" so it is correct.

**Comment by markingmyname** [comment]
@thomasbragaloni,

We will update the SSMS articles with the first [include](https://docs.microsoft.com/en-us/sql/sql-server/applies-to-includes?view=sql-server-2017#sql-server-applies-to-non-version-specific) in the list.

Please close this PR, as I will reference it in the new one.

Thank you.

**Comment by Jak-MS** [comment]
re: instructions form @markingmyname - #please-close

**Pull request closed without merging**
