### PR TITLE
For better understand with the cursor contents

### PR DESCRIPTION
**Pull request by chanmmn**
Loop through and no output could be misleading. Added some script to get the contents from the cursor. Hope you guys are fine with it.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@chanmmn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@chanmmn Thank you for the feedback and apologies for the long delay. I tested your code changes out with the 2012 AdventureWorks database, and I found a few more things needed to get this to work. First, the column names seem to be wrong, and the variables you use need to be declared. Could you do the following:

1. Go to this pull request https://github.com/MicrosoftDocs/sql-docs/pull/2303

1. Click on the File Changed tab.

1. Click the pencil icon next to the file we're editing here

1. Change the code sample to the following:

```
DECLARE @EmployeeID as nvarchar(256)
DECLARE @Title as nvarchar(50)

DECLARE Employee_Cursor CURSOR FOR  
SELECT LoginID, JobTitle   
FROM AdventureWorks2012.HumanResources.Employee  
WHERE JobTitle = 'Marketing Specialist';  
OPEN Employee_Cursor;  
FETCH NEXT FROM Employee_Cursor;  
FETCH NEXT FROM Employee_Cursor INTO @EmployeeID, @Title;  
WHILE @@FETCH_STATUS = 0  
   BEGIN  
      Print '   ' + @EmployeeID + '      '+  @Title 
      FETCH NEXT FROM Employee_Cursor;  
   END;  
CLOSE Employee_Cursor;  
DEALLOCATE Employee_Cursor;  
GO  
```

Thank you!!

**Comment by PRMerger15** [comment]
@chanmmn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chanmmn** [comment]
Thank you @rothja I have followed the steps and changed the code. 
Please verify.

**Comment by rothja** [comment]
@chanmmn Sorry, again, for the long delay. That looks great, and thank you for working with me on the update! #sign-off

**Pull request merged**
