### PR TITLE
Update create-function-sql-data-warehouse.md

### PR DESCRIPTION
**Pull request by vvasic-msft**
Note for serverless was in wrong place.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@vvasic-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vvasic-msft** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@vvasic-msft: I'm sorry - only the author of this article, @julieMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by julieMSFT** [comment]
#sign-off

**Pull request merged**
