### PR TITLE
Update scalar-udf-inlining.md

### PR DESCRIPTION
**Pull request by kwparkgsl**
Update inlineable scalar UDFs requirements

### CODE REVIEW

**Comment by PRMerger19** [comment]
@kwparkgsl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by joesackmsft** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@joesackmsft: I'm sorry - only the author of this article, @s-r-k, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by kwparkgsl** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@kwparkgsl: I'm sorry - only the author of this article, @s-r-k, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
