### PR TITLE
Typo: MULTISUBMIT -> MULTISUBNET

### PR DESCRIPTION
**Pull request by nschonni**
Closes https://github.com/MicrosoftDocs/feedback/issues/377

Also appears to be an issue in all the translations as well https://github.com/search?q=org%3AMicrosoftDocs+SQL_COPT_SS_MULTISUBMIT_FAILOVER&type=Code

### CODE REVIEW

**Comment by PRMerger14** [comment]
@nschonni : Thanks for your contribution! The author, @MightyPen, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
We do want this good fix!
#sign-off

**Comment by MightyPen** [comment]
@nschonni Thanks for this subMIT vs subNET fix  :-)

**Comment by nschonni** [comment]
Thanks for landing ❤️ , I'm not sure how the i18n flow works, but I'm going to assume you'll fix the downstream translation repos from this since they also have the same typo

**Pull request merged**
