### PR TITLE
Updated SQLPS installation and remarks

### PR DESCRIPTION
**Pull request by Karl-WE**
some processes in docs still use SQLPS and I've recently installed SQL 2017 on Server 2019. SQLPS was not part of it. I update this doc to complete the documentation. 
Credits: https://sqlpadawan.com/2018/08/01/how-to-install-sql-server-sqlps-powershell-module/

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Related PR: https://github.com/MicrosoftDocs/sql-docs/pull/4827

**Comment by markingmyname** [comment]
@Karl-WE 

Investigating.  Apologizes for the delay.

Once I hear back, I will update this PR.

**Comment by markingmyname** [comment]
@Karl-WE 

SQLPS is part of the *core* SQL Setup – so, even if you just install the Engine, you get it. I do not know if you installed some random stuff (down in the feature tree, like SDK or Back Compat stuff… or pretty obscure things), but I know that Engine carries SQLPS. 

I would NOT recommend installing the ancient PowerShellTools.MSI (it shipped until SQL2014 or maybe SQL2016, as part of the so-called Feature Pack). The process outlined in the referenced article (=install 3 MSIs) is correct. 

Please don’t install the SQLPS module. Install the SQLServer module instead.

I have to reject this PR.

**Comment by Karl-WE** [comment]
> @Karl-WE
> 
> SQLPS is part of the _core_ SQL Setup – so, even if you just install the Engine, you get it. I do not know if you installed some random stuff (down in the feature tree, like SDK or Back Compat stuff… or pretty obscure things), but I know that Engine carries SQLPS.
> 
> I would NOT recommend installing the ancient PowerShellTools.MSI (it shipped until SQL2014 or maybe SQL2016, as part of the so-called Feature Pack). The process outlined in the referenced article (=install 3 MSIs) is correct.
> 
> Please don’t install the SQLPS module. Install the SQLServer module instead.
> 
> I have to reject this PR.

Hello @markingmyname thanks for the review. I can assure you it was reproducible that SQLPS was missing, reproducibly on the following scenario:

Server 2019 core
SQL Server 2017 (RTM) from customer VLSC

It took me a lot of time to investigate this problem see related #4827 and hoped the efforts would be dealing out. I specificially we can correct my PR if it is correct to say it is not included but I did describe well what to do if it IS missing.

I was not feeling well about installing this old packages but please triage the issue and let us then decide how to help people that run into the same spike of "missing" documentation. 

Can we agree?

**Comment by Karl-WE** [comment]
@ktoliver since @markingmyname is not responding after the close is anyone free to review my concern / issue, even more as I wouldn't have spent so much time for this PR plus related #4827 if SQLPS wasn't missing by default.
Thank you for your time.

**Comment by markingmyname** [comment]
Hi, @Karl-WE 

I reopened this PR to continue our conversation.

I apologize for the delayed response.

I recently made some updates to both the [SQL Server PowerShell] article(https://docs.microsoft.com/en-us/sql/powershell/sql-server-powershell?view=sql-server-ver15) and the [Install the SQL Server PowerShell module article](https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module?view=sql-server-ver15) describing the purpose between SQLPS and SQLServer modules.  

However, if I understand you right, are you stating that SQLPS is installed with SQL engine?

**Comment by Karl-WE** [comment]
Hi @markingmyname your articles are fine. But both advice users how to install sqlserver module. All docs are clear SQLPS is deprecated, also you outlined my documented workaround, found on the web might not be a good solution. 

My point is that we reproed that SQLPS was missing with the above scenario.

L Thus I spent the time to document this workaround if other users facing the same issue. Sqlserver module is not sufficient for the task described in #4827. In fact it needs SQLPS.

**Comment by markingmyname** [comment]
@Karl-WE,

I believe I understand more clearly that you are trying to just bring to light a special situation where you have offered the workaround.

If that is the case, I can think of adding a Considerations and Limitations section that could offer this information. 

However, this PR is not out of sync with the master branch.  Would it be too much trouble to ask for you to update this Pr with the latest version of the article and add an H2 titled -  Limitations and Considerations - and then offer your workaround there?

After that, I will discuss with the parties involved if that is accepted.

Thank you.

**Comment by Karl-WE** [comment]
Aye @markingmyname 

since I would like to create a new PR based on "all servers" if needed who will update the changes to the subsequent versions?

image
If I don't have to care about this, I will create a new PR on this article, okay?
https://docs.microsoft.com/SQL/powershell/download-sql-server-ps-module

**Comment by markingmyname** [comment]
@Karl-WE 

The metadata will take care of versioning.

Just choose the latest version of the PS file and update that.  

Please let me know when you have completed this.

Thank you.

**Comment by markingmyname** [comment]
Closing PR as since this is out of sync with the current version, @Karl-WE will create a new PR to be reviewed.

**Comment by Karl-WE** [comment]
"Closing PR as since this is out of sync with the current version, @Karl-WE will create a new PR to be reviewed."
Done. Unfortunately we should update several articles, or at least cross reference them.

**Pull request closed without merging**
