### PR TITLE
Update for version 17

### PR DESCRIPTION
**Pull request by v-makouz**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@v-makouz : Thanks for your contribution to the Azure documentation! The author, @genemi, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@v-makouz : Thanks for your contribution to the Azure documentation! The author, @genemi, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@v-makouz I am almost ready to enter my '# s i g n - o f f' for this PR 353.    My only potential concern is that some of the new code lines are very loooong.    Long code lines display poorly, and do not full print either.    So I ask.....
Does the syntax of the programming language allow you to move the back half of each looong line to the next line, to have two shorter lines?    If Yes, can you please make those changes, rebuild, and then re-ping me for s i g n - o f f?    But if No, just ping me to inform me the answer is No, and then I will s i g n  o f f.
Thank you.
(MightyPen = genemi)

**Comment by v-makouz** [comment]
As these are command line instructions that users will be copying into their terminal it is best not to break them up, but I can move the comment above the line instead of after so that will reduce the length somewhat.

**Comment by PRMerger17** [comment]
@v-makouz : Thanks for your contribution to the Azure documentation! The author, @MightyPen, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@v-makouz Thank you for the tweaks you made based on my little feedback.
#sign-off

**Comment by v-makouz** [comment]
Should not be merged until Driver 17 release
#hold-off

**Comment by craigg-msft** [comment]
@v-makouz and @MightyPen 
I thought this was to be very soon. closing, please work the changes through the private repo.

**Pull request closed without merging**
