### PR TITLE
VBS enclaves in Azure SQL Database Elastic Pools

### PR DESCRIPTION
**Pull request by Pietervanhove**

### CODE REVIEW

**Comment by Court72** [comment]
@jaszymas

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Pietervanhove** [comment]
Hi Courtney,

Jakub is my colleague and I'm taking over this feature from him.
This means I also take ownership of the documentation.
So, normally the review of Jakub is not necessary.

Can this immediately be reviewed by the review team?

Regards,
Pieter
________________________________

**Comment by ShannonLeavitt** [comment]
Hi @Pietervanhove - If you're taking over for Jakub, please open a new PR in the private repo. There, you can add your changes and also update the ms.author and author metadata with your information. I'll close this public-repo PR now, but if you need to reopen it for some reason, you can do so by adding a `#please-open` command.

**Comment by Pietervanhove** [comment]
Hi Shannon,

Which private repo do you mean?

Regards,
Pieter
________________________________

**Comment by Jak-MS** [comment]
@Pietervanhove here's some more information.

repo: `sql-docs-pr`  https://github.com/MicrosoftDocs/sql-docs-pr

> Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.
>
> After you make your changes in the private repo, review the articles on staging, and fix any validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 
> 
> Read about [authors working in the public repo](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=main) for more information. 
>
> If you need help getting set up to work in the private repo, see [Get started contributing to the Microsoft Learn platform](https://review.learn.microsoft.com/en-us/help/get-started/?branch=main&tabs=learn).

**Pull request closed without merging**
