### PR TITLE
Change important section for the download page

### PR DESCRIPTION
**Pull request by MSraye**
Change important section for the download page

### CODE REVIEW

**Comment by PRMerger13** [comment]
@MSraye : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
If the PR is approved for merging, safelinks in the update content will need to be replaced with standard URLs that don't include locale (unless the link is intended to go to a language-specific version). Thanks.

**Comment by MSraye** [comment]
The links are intended to go to a language-specific version(we only have en-us version)

**Comment by markingmyname** [comment]
@MSraye,

Since I cannot view the preview link in this PR, can you send that to me for me to review?

If the links you used are for specific locales, i want to see something.

**Pull request merged**
