### PR TITLE
Permission correction

### PR DESCRIPTION
**Pull request by AndreasWolter**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@AndreasWolter : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AndreasWolter** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@AndreasWolter: I'm sorry - only the author of this article, @markingmyname, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by markingmyname** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @AndreasWolter - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. In the future, would you make content updates in the private repo? Thanks!

**Comment by AndreasWolter** [comment]
Hi
That must have been by mistake

I usually add -pr and use the master branch
So in this case I forgot? Or is there anything else that went wrong?

Thanks
Andreas

-----------------------------------------------
Andreas Wolter | Senior Program Manager
MCM, MCSM | Data Platform Security
Twitter<https://twitter.com/AndreasWolter> | Linkedin<https://www.linkedin.com/in/andreaswolter/>

**Pull request merged**
