### PR TITLE
Changing SSAS Account User Rights

### PR DESCRIPTION
**Pull request by ericbu**
Changing SSAS Account User Rights from SeIncreaseQuotaSizePrivilege (which doesn't exist) to SeIncreaseQuotaPrivilege

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ericbu : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
@ericbu - Thanks Eric! We really appreciate the contribution!
Verified
#sign-off

**Comment by PRMerger17** [comment]
@VanMSFT: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
