### PR TITLE
SSDT Offline Layout when using a full version of Visual Studio 2017

### PR DESCRIPTION
**Pull request by Jonathan811**
More detail on if you can add the SSDT offline layout to an existing Visual Studio 2017 offline layout.

Recommend creating a separate offline layout for SSDT and any full version of Visual Studio 2017.

SSDT: Analysis Services, SSIS and SSRS projects in Visual Studio 2017

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Jonathan811 : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by stevestein** [comment]
@Jonathan811 - I shortened the note a bit, and updated the format so it appears in a note block.

**Comment by stevestein** [comment]
#sign-off

**Pull request merged**
