### PR TITLE
Fix missing / misleading statements, and formatting for BACKUP CERTIFICATE

### PR DESCRIPTION
**Pull request by srutzky**
1. Updated "Arguments" section to conform to most other pages:
    1. Added "certname" argument.
    2. Added argument name to each option.
    3. Added "WITH PRIVATE KEY" argument as it mirrors `CREATE CERTIFICATE`.
    4. Corrected default path description (tested in SQL Server 2017 CU14 and 2019 CTP 2.4).
    5. Added LocalDB info to path description (tested in SQL Server Express LocalDB 2012 SP4).

2. Updated "Remarks" section:
    1. Passwords are to protect private keys, not certificates.
    2. Added info about private key file format.
    3. Clarified that restoring a certificate does not require the private key.
    4. Added info about restoring a private key to an existing certificate via `ALTER CERTIFICATE`.

3. Added links to CERTENCODED, CERTPRIVATEKEY, CERT_ID, and CERTPROPERTY functions in "See Also" section.

These updates are related to updates proposed for `CREATE CERTIFICATE` and `ALTER CERTIFICATE` via #1972 , and to the following post: https://sqlquantumleap.com/2019/04/22/can-a-certificates-private-key-be-imported-restored-from-a-binary-literal-hex-bytes/

### CODE REVIEW

**Comment by PRMerger13** [comment]
@srutzky : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by srutzky** [comment]
Ooops, forgot to post the test code. Will update this comment with a link to it in a few minutes...

**Comment by VanMSFT** [comment]
Reviewed. Thanks again @srutzky!
#sign-off

**Comment by srutzky** [comment]
You're welcome 😺

**Pull request merged**
