### PR TITLE
typo: Designe**r -> Designer**

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@nschonni : Thanks for your contribution! The author, @minewiskan, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @nschonni - The diff view shows a large block of changed content but provides no details. Did you make any changes other than changing "Designe\*\*r" to "Designer\*\*"? Delete trailing spaces or add blank lines, etc.? We need to be able to review the specific revisions you are proposing. Diffchecker.com doesn't pick up changes in whitespace. Thanks!

**Comment by ktoliver** [comment]
_Updated_: @nschonni - Thank you for your submission. We are not able to accept spacing and formatting changes in the repo at this time. Could you resubmit the _typo fix only_ in a new pull request?

**Comment by nschonni** [comment]
I won't be resubmitting, feel free to fix internally

**Pull request closed without merging**
