### PR TITLE
Tweak sqlcmd best practices

### PR DESCRIPTION
**Pull request by jzabroski**
The current best practice recommends -X.  -X1 is even safer.

Added section on correctness to best practices.  Feedback welcome.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@jzabroski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
@jzabroski, thanks for the contribution.

Made a small edit to your contribution.

approved.

#sign-off

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
