### PR TITLE
SSIS in VS2022 pre contact

### PR DESCRIPTION
**Pull request by yewanxuan**

### CODE REVIEW

**Comment by Court72** [comment]
@yewanxuan 

Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/sql-docs/pull/8286#issuecomment-1321379774)? 

After the CLA is signed, someone can review your pull request. Thanks!

**Comment by yewanxuan** [comment]
@microsoft-github-policy-service agree [company="microsoft"]

**Review by chugugrace — APPROVED** [review]

**Comment by yewanxuan** [comment]
@microsoft-github-policy-service agree

**Review by chugugrace — APPROVED** [review]

**Review by chugugrace — APPROVED** [review]

**Comment by chugugrace** [comment]
#sign-off

**Review by chugugrace — APPROVED** [review]

**Comment by Court72** [comment]
Hi @chugagrace,

The changes made in this PR are extensive enough that they'll need to be moved to the private repo for staging and other checks.

Let us know if you'd like assistance with opening a PR in the private repo.

Thanks!
#hold-off

**Comment by yewanxuan** [comment]
> Hi @chugagrace,
> 
> The changes made in this PR are extensive enough that they'll need to be moved to the private repo for staging and other checks.
> 
> Let us know if you'd like assistance with opening a PR in the private repo.
> 
> Thanks! #hold-off

Hi, @Court72. Need your help. My Microsoft GitHub can't access in due to 2step verify. I lost recover code and my phone. Could you take a look at it, and give advice how to resolve?

**Comment by Court72** [comment]
Closing this PR since the changes have been made in the private repo.

**Pull request closed without merging**
