### PR TITLE
Adjustment for read-scale availability in standard

### PR DESCRIPTION
**Pull request by MSFTPawelM**
Change the support for read-scale availability groups in Standard edition to No - Standard edition only includes support for Basic availability groups that don't offer any readable secondaries, so in fact we will throw an error when trying to create a readable secondary in Basic availability group. This causes confusion for customers: https://feedback.azure.com/forums/908035-sql-server/suggestions/39254050-documentation-update-read-scale-availability-grou

### CODE REVIEW

**Comment by PRMerger17** [comment]
@MSFTPawelM : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Thanks, @MSFTPawelM reviewing.

**Comment by MikeRayMSFT** [comment]
@kfarlee can you please verify?

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
