### PR TITLE
Corrected some inconsistencies

### PR DESCRIPTION
**Pull request by dbaduck**
Unique Resource Names to Uniform Resource Names
Added the real command for the aliases illustrated.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@dbaduck : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
#sign-off

**Comment by PRMerger12** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @markingmyname

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
