### PR TITLE
Update create-external-data-source-transact-sql.md

### PR DESCRIPTION
**Pull request by kbartashevich**
Undocumented functionality was added.

The functionality was discovered while troubleshooting "The target principal name is incorrect." problem that normally indicates the domain trust relationship issue. Interesting enough, TrustServerCertificate property does NOT accept True/true value; only "yes" value made it.

### CODE REVIEW

**Comment by kbartashevich** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@WilliamDAssafMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kbartashevich for contacting Microsoft with a contribution to our product documentation. It could take from a few business days to a few weeks to confirm your change internally. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

By opening a pull request, you're helping the authors add your approved change directly to the documentation. If the article is updated with your commit, GitHub will list you as an article contributor.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @kbartashevich for taking the time to draft this content improvement. 
The example of using SQL Managed Instance and PolyBase to connect to SQL Database hyperscale through a private endpoint is not currently an officially supported solution, we can't document it. 
Also, the key_value_pairs syntax is not valid in context of Data Virtualization for SQL Managed Instance. While used in elastic query for connections over ODBC, the key value pair syntax is not for access to Azure blob storage or ADLS Gen2. 
We won't be moving forward with this PR but we welcome future communication and contributions.

**Pull request closed without merging**
