### PR TITLE
Update sys-dm-fts-parser-transact-sql.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
Alter permission scoped on contextual database is sufficient.

### CODE REVIEW

**Comment by rwestMSFT** [comment]
Thank you for identifying this article for review. It will be updated in an internal PR, and this PR will automatically close.

**Comment by DanielAdeniji** [comment]
Tracey Torble & Randolph West:-

What is the best approach to follow the proposed and stay aware of it's internal journey through final disposition.

We will much prefer if it does no remain a black box "forever".

In health and wholeness,

Daniel
________________________________

**Comment by rwestMSFT** [comment]
@DanielAdeniji If it gets closed here, the internal PR has already been merged and will be published at the next available publish window. So as I write this, your change is already live, along with the additional changes I made to refresh the article.

**Comment by DanielAdeniji** [comment]
Randolph:-

I made a more precise change post my original edit.

The secondary change reads:

The minimum permission required is "create fulltext catalog".

Earlier, I had suggested that one needs the alter permission.

The alter permission is a database level permission.

And, will be over-arching and exaggerate the actual needs.

I have attached a bit more documentation and test code.

A developer should be able to read through the sample code and get closer to y read of the base security requirements.

I will be more cognization of markdown best practices when editing articles in the future.

Sincerest of gratitude for granting me the hearing.

As well as for your open mind and providing me more documentation and guidance.

One can imagine it is a cold and raining Friday in Seattle.

Sorry to be the cause of more anxiety,

Daniel




________________________________

**Comment by rwestMSFT** [comment]
@DanielAdeniji Rest assured that your careful attention with respect to improving our articles is no cause for anxiety. In fact, with this one, I was able to refresh a very old article and make it follow our new style guidelines, as well as incorporate your permission feedback.

Regarding your intent to add sample code, we follow a standard template for our T-SQL articles, meaning that if you wanted to add example code, the best place for that is at the end of the article in the Examples section.

That all being said, there was a merge conflict with this particular pull request, so I pulled it into an internal PR, made additional changes to it, and took into account your notes.

When that internal PR was merged, this one was closed by the automated publication process, which is an indication that your contribution was only hours away from publication.

**Comment by DanielAdeniji** [comment]
Randolph:-

The sample code is for the benefit of the technical writer and developers that have to crosscheck the changes.

The peer reviewers so to speak.

The quality of my code is not up to per; especially in the middle of a long week.

The attached code will both be unnecessary and distract from the subject matter and its conciseness.

Again, I stole enough of your time and grace,

Daniel

________________________________

**Comment by rwestMSFT** [comment]
@DanielAdeniji I thank you for your time, and I will make the requisite permissions correction for the article, following your new information provided. Take care.

**Pull request closed without merging**
