### PR TITLE
Update create-type-transact-sql.md

### PR DESCRIPTION
**Pull request by ramakoni1**
Merging info from KB - 2009217 before redirecting

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ramakoni1 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @CarlRabeler

**Comment by ramakoni1** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@ramakoni1: I'm sorry - only the author of this article, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @ramakoni1 - This pull request was opened in the public repo. Would you submit the content update in a pull request in the private repo instead? Thanks! We'll close this pull request.

**Pull request closed without merging**
