### PR TITLE
Update sys-sysprocesses-transact-sql.md

### PR DESCRIPTION
**Pull request by acucirianu**
CMD column length is changed in SQL Server 2019

### CODE REVIEW

**Comment by PRMerger19** [comment]
@acucirianu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@acucirianu Thank you! Did you verify this by looking at the definition of this view in SSMS?

**Comment by acucirianu** [comment]
Hi Jason. Yes I had verified this
[image: image.png]

Issue was observed when I tried to use an script that extract data from
sp_who into temporary table. So, for CMD column has char(16) and I get
exception:

Msg 8152, Level 16, State 13, Procedure sp_WHO, Line 79 [Batch Start Line 0]
String or binary data would be truncated.

_______________
Regards
Andrei Cucirianu <acucirianu@gmail.com>


În vin., 6 dec. 2019 la 18:26, Jason Roth <notifications@github.com> a
scris:

**Comment by rothja** [comment]
@acucirianu Thanks for the extra information, and for improving the docs! #sign-off

**Pull request merged**
