### PR TITLE
Update create-credential-transact-sql.md

### PR DESCRIPTION
**Pull request by FonsecaSergio**
Adding note regarding SAS secret
 The **SHARED ACCESS SIGNATURE secret** should not have the leading **?**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@FonsecaSergio : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@VanMSFT : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @FonsecaSergio - I added a period after your sentence change.
#sign-off

**Comment by VanMSFT** [comment]
#hold-off

**Comment by PRMerger14** [comment]
@VanMSFT : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
