### PR TITLE
Updated TransparentNetworkIPResolution value in md

### PR DESCRIPTION
**Pull request by pvnkmr17**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@pvnkmr17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@pvnkmr17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@pvnkmr17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@pvnkmr17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by David-Engel** [comment]
@pvnkmr17 Where did you get this information? That's not the behavior I see in the ODBC driver, nor does the code appear to do anything differently for TNIR against Azure SQL endpoints. I believe the existing documentation is accurate.

**Comment by pvnkmr17** [comment]
@David-Engel I was troubleshooting the timeout issue in our systems and found the below links.

https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.8
https://docs.microsoft.com/en-us/sql/connect/odbc/using-transparent-network-ip-resolution?view=sql-server-ver15

**Comment by David-Engel** [comment]
> I was troubleshooting the timeout issue in our systems and found the below links.
> 
> https://docs.microsoft.com/en-us/archive/blogs/dataaccesstechnologies/connection-timeout-issue-with-net-framework-4-6-1-transparentnetworkipresolution
> https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.6.1

Those two links only apply to the System.Data.SqlClient data provider for .NET. The ODBC driver is based on different code and doesn't have that particular behavior.

> https://docs.microsoft.com/en-us/sql/connect/odbc/using-transparent-network-ip-resolution?view=sql-server-ver15

This link is the page you are editing and is accurate as-is. Since the ODBC driver doesn't have the same behavior here, these edits aren't accurate.

**Pull request closed without merging**
