### PR TITLE
Update deploy-install-azdata-installer.md

### PR DESCRIPTION
**Pull request by uc-msft**
Added missing azdata MSI link

### CODE REVIEW

**Comment by PRMerger9** [comment]
@uc-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by uc-msft** [comment]
#sign-off @MikeRayMSFT

**Comment by PRMerger9** [comment]
@uc-msft: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Review by MikeRayMSFT — APPROVED** [review]

**Pull request merged**
