### PR TITLE
update limitations section

### PR DESCRIPTION
**Pull request by shkale-msft**
clarified that create statistics on external tables is not supported on Azure SQL Database.

### CODE REVIEW

**Comment by shkale-msft** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@shkale-msft : Thanks for your contribution to the SQL documentation! The author, @barbkess, has been notified to review your proposed change.

**Comment by barbkess** [comment]
@shkale-msft Thanks - are you a Microsoft Employee?  If so, in the future, can you make these edits through https://github.com/microsoftdocs/sql-docs-pr? 

One quick edit -- please change the "is" to "are" in the sentence "on external tables is".

**Comment by shkale-msft** [comment]
Thanks @barbkess! I have addressed your review comments.

**Comment by shkale-msft** [comment]
#sign-off

**Pull request merged**
