### PR TITLE
Add "higher versions" for Auditpol utility

### PR DESCRIPTION
**Pull request by rezazein**
Auditpol.exe utility is available in higher versions of Windows after Vista and Server 2008.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@rezazein : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @rezazein! I'll approve these changes.

#sign-off

**Comment by PRMerger10** [comment]
@VanMSFT: I'm sorry - only the author of this article, @davidtrigano, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Thanks @VanMSFT

**Pull request merged**
