### PR TITLE
Update dbcc-checkdb-transact-sql.md

### PR DESCRIPTION
**Pull request by baleng**
we produce the 3 files (txt,log,mdmp)not only the txt file when a dump is created once corruption is discovered

### CODE REVIEW

**Comment by v-dirichards** [comment]
@rwestMSFT 

Can you review the proposed changes?
 
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.
 
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-dirichards** [comment]
@rwestMSFT 

Can you review the proposed changes?
 
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.
 
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@v-dirichards @baleng This PR should be moved to the private `sql-docs-pr` repo.

**Comment by rwestMSFT** [comment]
Replaced by internal PR.

**Pull request closed without merging**
