### PR TITLE
Updating support policy for Azure Storage Accounts

### PR DESCRIPTION
**Pull request by jrowlandjones**
After an escalation today there is a need to update and clarify the support for the wasb:// interface when accessing azure storage. The previous version was unclear and had errors in examples.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jrowlandjones : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @jrowlandjones - Contributors who work in the Product Manager role should open pull requests in the private repository for advanced quality validations and staging (you also can sign off directly in the private repo). To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. We’ll leave this PR for review in the public repo, but would you make future article updates in the private repo?  Thanks!

**Comment by jrowlandjones** [comment]
Thank you Kristine,

Duly noted and will do this in future.

Did you let the change through as-is? I can't see the PR anywhere.

Kind Regards, JRJ

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by jrowlandjones** [comment]
Thank you @CarlRabeler and @ktoliver for the guidance and support.

**Pull request merged**
