### PR TITLE
Update database-copy.md

### PR DESCRIPTION
**Pull request by xitzee**
Statement regarding copying db while connecting using private endpoit doesnt seem to be true anymore. I was able to copy db between servers with public access disabled without any issue, using only t-sql.

### CODE REVIEW

**Comment by Court72** [comment]
@WilliamDAssafMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @xitzee for contacting Microsoft with feedback about our product documentation. You may be right, but it could take from a few business days to a few weeks to confirm your change internally, test, and verify documentation broadly. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

By opening a pull request, you're helping the author add your approved change directly to the documentation. If the article is updated with your commit, GitHub will list you as an article contributor.

Thanks again for submitting your feedback. Your suggestions help improve our documentation. Standby for more info.

**Comment by rajeshsetlem** [comment]
@xitzee, can you please confirm what authentication mechanism (SQL Authentication or AAD) you used for connecting to source SQL Database that was copied ?

**Comment by xitzee** [comment]
Hello, it was AAD. Both cases same account

czw., 13 lip 2023, 01:31 użytkownik rajeshsetlem ***@***.***>
napisał:

**Comment by rajeshsetlem** [comment]
Thanks @xitzee. Will try to reproduce the scenario and update docs as necessary.

**Comment by rwestMSFT** [comment]
@rajeshsetlem Do we have any feedback on this issue?

**Comment by rwestMSFT** [comment]
@xitzee We're taking this change to an internal PR, and will let you know when the updated article is published. Thanks for your feedback!

**Pull request closed without merging**
