### PR TITLE
Update what-s-new-in-sql-server-2022.md

### PR DESCRIPTION
**Pull request by MikeyBronowski**
Removed "Preview" from SSMS 19.0 mention as it's no longer in preview.

### CODE REVIEW

**Comment by Court72** [comment]
@MikeRayMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by MikeRayMSFT — APPROVED** [review]

**Comment by MikeRayMSFT** [comment]
#sign-off

With thanks to @MikeyBronowski

**Comment by American-Dipper** [comment]
@MikeRayMSFT, are you sure this is correct? I don't see "download-sql-server-management-studio-ssms-19.md" in the repo. Thanks. 

Please sign off again.

**Comment by American-Dipper** [comment]
#hold-off

**Comment by rwestMSFT** [comment]
This PR has been replaced by an internal PR, due to the merge conflict. This PR will close automatically when the internal PR is merged. Thanks for your contribution.

**Pull request closed without merging**
