### PR TITLE
Add support for key version on the key vault

### PR DESCRIPTION
**Pull request by DBAlberto**
…vault.md

The option:
PROVIDER_KEY_NAME = 'ContosoRSAKey0/1a4d3b9b393c4678831ccc60def75379'
 for the specific key version was tested
you could refer to https://docs.microsoft.com/en-us/answers/questions/378951/index.html

### CODE REVIEW

**Comment by PRMerger14** [comment]
@DBAlberto : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, May 25. Merging will resume Tuesday. Authors can still review and sign off on PRs in the interim. Thanks.

**Comment by Rupp29** [comment]
#sign-off

**Comment by ktoliver** [comment]
@Rupp29 Can you check my edits for technical accuracy?

@DBAlberto Thanks for contributing to the documentation. Would you take a moment to sign the Contributor License Agreement (CLA) for contributing? The additional commit of an edit pass moved the pull request into CLA-check status, and it looks like you haven't signed one for this repository. After you sign the CLA, we can merge the pull request. Thanks.

**Comment by Rupp29** [comment]
#sign-off

**Comment by ktoliver** [comment]
#hold-off to remove from the ready-to-merge queue pending contributor signing the CLA

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @DBAlberto; merging now.

**Pull request merged**
