### PR TITLE
Update full-text-search.md

### PR DESCRIPTION
**Pull request by awickham10**
Syntax error in "Recruitment scenario-searching for job candidates that have experience working with SQL Server" example.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@awickham10 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
#sign-off 

@Jak-MS Hi, can you please Merge this now-Approved PR 3321 now.  Thanks.

**Comment by PRMerger19** [comment]
@MightyPen: I'm sorry - only the author of this article, @pmasl, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
Just merge it.

**Pull request merged**
