### PR TITLE
Add download link for MDS 2019 CTP Add-In

### PR DESCRIPTION
**Pull request by v-redu**
Add download link for MDS 2019 CTP Add-In

### CODE REVIEW

**Comment by PRMerger7** [comment]
@v-redu : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@craigg-msft - Could you review the proposed changes? The listed author @LeoLiMSFT isn't showing up in the **Assignees** box as Microsoft-internal. Thank you.

**Comment by craigg-msft** [comment]
the change looks good.  #sign-off @v-redu its preferable if you make changes through the internal repo rather than the external. it looks like Leo has changed his git id to @lrtoyou1223 I will follow-up with him.

**Comment by PRMerger9** [comment]
@craigg-msft: I'm sorry - only the author of this article, @leolimsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Jak-MS** [comment]
Hi @v-redu - for future reference:

Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Pull request merged**
