### PR TITLE
Update what-s-new-in-sql-server-2022.md

### PR DESCRIPTION
**Pull request by dplessMSFT**
@WilliamDAssafMSFT I am proposing breaking up the performance table into 'Query Store and IQP' topics and 'Intelligent Performance' topics similar to existing content. Currently there is too much in that one table and it's hard to tell which features are grouped together.

I am also suggesting moving XML Compression to the management table, this is a PR I have already sent, but I am reflecting it here as well.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@dplessMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@dplessMSFT - as Microsoft FTE, you should ideally be making content changes through the private repo. 

> Read about [authors working in the public repo](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=main) for more information. 
>
> If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-local?branch=main).


IMPORTANT: When this content is ready to merge, the content owner should add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by dplessMSFT** [comment]
#sign-off

**Comment by PRMerger8** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @MikeRayMSFT

**Review by WilliamDAssafMSFT — APPROVED** [review]

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Comment by PRMerger14** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @MikeRayMSFT

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
