### PR TITLE
message_id does not exist and message_enqueue_time it´s now part of t…

### PR DESCRIPTION
**Pull request by enriquecatala**
…he queue definition

there is a bug in the table definition showed here.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@enriquecatala : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, March 2. Merging will resume Tuesday. Authors can still review and sign off on PRs in the interim. Thanks.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @enriquecatala for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 
    
By opening a pull request, you're helping the author add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor.

Thanks again, your suggestions help improve our documentation.

**Comment by PRMerger20** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @enriquecatala, a doc update is in flight.

**Pull request merged**
