### PR TITLE
Typos: Fix instances where "principle" should be "principal".

### PR DESCRIPTION
**Pull request by adyavanapalli**
# Summary

I noticed while looking at [IS_ROLEMEMBER (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/is-rolemember-transact-sql?view=sql-server-ver15) that "principal" was mistakenly spelled "principle".

I fixed that instance and combed through this repository to find other instances of this error and fixed those instances as well.

I also noticed that in [sp_lock (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-lock-transact-sql?view=sql-server-ver15), there's a sentence that reads:

> APP: An identifier unique to the application resource being locked. In the format **_DbPrincipleId_**:<first two to 16 characters of the resource string><hashed value>.

I believe this should also be `DbPrincipalId`, but I wasn't sure whether this was intentional and whether changing this would break other things, so I left it alone. Some guidance on this would be appreciated. Thank you!

### CODE REVIEW

**Comment by PRMerger12** [comment]
@adyavanapalli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@adyavanapalli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@adyavanapalli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@adyavanapalli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@adyavanapalli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
Hi @adyavanapalli -- great catch, thanks!
#sign-off

**Comment by adyavanapalli** [comment]
Hi @maggiesMSFT, before this is merged, could you address what I mentioned earlier:

> I also noticed that in [sp_lock (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-lock-transact-sql?view=sql-server-ver15), there's a sentence that reads:
> 
> > APP: An identifier unique to the application resource being locked. In the format **_DbPrincipleId_**:<first two to 16 characters of the resource string>.
> 
> I believe this should also be `DbPrincipalId`, but I wasn't sure whether this was intentional and whether changing this would break other things, so I left it alone. Some guidance on this would be appreciated. Thank you!

**Comment by maggiesMSFT** [comment]
Hi, @adyavanapalli -- good question. I've asked and will get back to you. We could actually sign off on this PR, and then create a separate PR for that one instance.

**Comment by adyavanapalli** [comment]
@maggiesMSFT Sure, that works for me 👍🏾.

**Comment by adyavanapalli** [comment]
@maggiesMSFT When are changes deployed to the live website? I didn't find any sort of CI/CD process inside this repository.

**Comment by maggiesMSFT** [comment]
Hi, @adyavanapalli -- checked with the product team, got the OK to fix DbPrincipleId so making that change today.

**Pull request merged**
