### PR TITLE
Added a tip about Azure user sessions to Remarks section

### PR DESCRIPTION
**Pull request by shkale-msft**
Azure user sessions behave a bit different than box user sessions. They will only see information about their database user sessions. While the admin can see information about all authenticated sessions.

### CODE REVIEW

**Comment by shkale-msft** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@shkale-msft : Thanks for your contribution to the SQL documentation! The author, @JennieHubbard, has been notified to review your proposed change.

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by JennieHubbard** [comment]
@shkale-msft Thank you Shreya!

**Comment by JennieHubbard** [comment]
#sign-off

**Pull request merged**
