### PR TITLE
Update sys-dm-geo-replication-link-status-azure-sql-database.md

### PR DESCRIPTION
**Pull request by sqlworldwide**
Correct spelling.
acknowledgement  should read acknowledgment

### CODE REVIEW

**Comment by PRMerger17** [comment]
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Using the GitHub UI to resolve the merge conflict leaves dubious results in the diff view; the sentence now doesn't match live or master in the private repo. I'd like to close the pull request to avoid any trouble, and I'll remove the "e" (legitimate update; Acrolinx agrees) in a separate effort. I'll close the PR. 

@sqlworldwide Thank you for the fix, and would you take a moment to sign the Contributor License Agreement (CLA) for future contributions. (A CLA check is triggered when a PR exceeds a threshold for commits and so on.)

**Comment by ktoliver** [comment]
Replacement PR merged in the private repo. Thanks again.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
