### PR TITLE
Update install instructions with note about IE issue

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Charles-Gagnon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by yualan** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Thanks for your contribution @Charles-Gagnon .

**Pull request merged**
