### PR TITLE
DMV not supported update

### PR DESCRIPTION
**Pull request by shohamMSFT**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@shohamMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@WilliamDAssafMSFT - Could you review the proposed update to your article? Note that references to future functionality can't be merged, per the internal contributor guide. If the update is approved, we'll need to adjust the last sentence.

**Comment by ktoliver** [comment]
Thanks.

**Comment by ktoliver** [comment]
@shohamMSFT I see that you're a PM and have worked in the private repository before. Would you submit this update in the private repo instead? Note the guidance in the internal CG that precludes referring to future functionality in the content. We'll close this pull request. Thank you.

**Review by WilliamDAssafMSFT — COMMENTED** [review]
I know this PR is already closed but if we resubmit, in general we will always avoid anything like this: "...will address this in the future." We should never make future promises in docs. If you have a reference to a known issues article or Features By Version article or something similar, this might be a place to link it though.

**Pull request closed without merging**
