### PR TITLE
Added active database deletion

### PR DESCRIPTION
**Pull request by saitorhan**
"Cannot drop database TestData because it is currently in use." Added solution code for error

### CODE REVIEW

**Comment by PRMerger20** [comment]
@saitorhan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by saitorhan** [comment]
Hi! Does pull request has any problem? How can I fix them for merging?
Thanks.

**Comment by MikeRayMSFT** [comment]
@saitorhan - thank you for the submission. I will have engineering review this.

**Comment by MikeRayMSFT** [comment]
@saitorhan 

After a review with engineering we've decided not to publish this update because there may be risks associated with killing sessions in this way. The kill command is documented at [KILL (Transact-SQL)](https://docs.microsoft.com/sql/t-sql/language-elements/kill-transact-sql). Perhaps providing a link to that command and maybe even the example there would be an appropriate update. 

#please-close

**Pull request closed without merging**
