### PR TITLE
Update download-sql-server-management-studio-ssms.md

### PR DESCRIPTION
**Pull request by pituach**
SSMS is supporting PDW as it is updated in other documents. It was forgotten in this document to be updated, so I updated it

### CODE REVIEW

**Comment by PRMerger19** [comment]
@pituach : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@dnethi can you pelase review.

**Comment by craigg-msft** [comment]
I verified with @dnethi. setting ready-to-merge

**Comment by craigg-msft** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@craigg-msft: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by pituach** [comment]
> @craigg-msft: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

By the way, I tried to contact @stevestein before I edit it myself. I did not find his name on Microsoft close groups on yammer so I sent him a message on linkedin.

In general(not specifically this case), I think that you need to make the procedure a bit more simple, at least for Microsoft MVP. For example please give us (MVPs) a direct channel to the "PR review team". But maybe this is a discussion that should be done in other close channels (which we don't have now) for example a group at yammer MVP or at Azure Advisors where the content is by definition under NDA.

**Pull request merged**
