### PR TITLE
Update restore-and-recovery-overview-sql-server.md

### PR DESCRIPTION
**Pull request by pmasl**
This clarifies the database availability state during Phase 3, where Fast Recovery only exists for a service restart, but not for cases where a database is set OFFLINE/ONLINE without an instance restart.

### CODE REVIEW

**Comment by jborsecnik** [comment]
@MashaMSFT, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by pmasl** [comment]
Hi @MashaMSFT - not getting rid of me that easily :)

**Comment by pmasl** [comment]
@jborsecnik @MashaMSFT any ET of when this can be merged?

**Comment by pmasl** [comment]
@jborsecnik @MashaMSFT any ET of when this can be merged?

**Comment by pmasl** [comment]
Maybe @dplessMSFT can help review?

**Comment by pmasl** [comment]
Maybe @rwestMSFT can review to merge? It's old behavior, just never got around to documenting

**Comment by rwestMSFT** [comment]
Thanks, Pedro. This article needs a refresh anyway, so when my internal PR is approved, this one will autoclose and you'll get credit.

**Pull request closed without merging**
