### PR TITLE
Update reference-azdata-bdc-hdfs.md

### PR DESCRIPTION
**Pull request by akumaranchath**
Corrected typo: from-path is misspelled as from_path

### CODE REVIEW

**Comment by WilliamDAssafMSFT** [comment]
reassign:WilliamDAssafMSFT

**Comment by WilliamDAssafMSFT** [comment]
Thanks @akumaranchath  for submitting this PR. Your suggestions help improve our documentation. Your commit has been merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 

Thanks again for this feedback, your suggestions help improve our documentation.

#sign-off

**Comment by PRMerger19** [comment]
@WilliamDAssafMSFT: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by WilliamDAssafMSFT** [comment]
#reassign:WilliamDAssafMSFT

**Pull request merged**
