### PR TITLE
Update datediff-transact-sql.md

### PR DESCRIPTION
**Pull request by brunom**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@brunom : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @brunom, thanks for submitting your content suggestion! Would you mind clarifying the reasoning behind this change? Thanks! @pmasl  FYI

**Comment by brunom** [comment]
Hi Masha, The old version was just wrong. https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql documents that the accuracy is 100 nanoseconds.

**Comment by pmasl** [comment]
The statement in the docs is correct as-is. The statements shown under datepart boundaries  all have 1 ys diff. Perhaps @brunom is misreading the doc. It just says the following examples differ in time by one microsecond (.0000001 second). It has no bearing on the data type precision.

**Comment by brunom** [comment]
@pmasl as it stands, the docs are in contradiction. "one microsecond" is not ".0000001 second". Previously in the same sentence it says that dates are "adjacent" which to me means you cannot represent a date in between, so the difference must be the accuracy of the data type.

**Comment by pmasl** [comment]
@brunom you are correct there is one extraneous zero as I counted. In this case might as well change the example, @MashaMSFT please merge the PR.

**Comment by MashaMSFT** [comment]
#sign-off thanks @pmasl

**Pull request merged**
