### PR TITLE
Update overview-and-usage-scenarios.md

### PR DESCRIPTION
**Pull request by AaronBertrand**
Added a high-profile case study Microsoft and SentryOne collaborated on earlier this year.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@AaronBertrand : Thanks for your contribution! The author, @jodebrui, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@AaronBertrand Thank you for your submission! There is a minor issue: the link in your added bullet's text include a locale node, namely 'en-us/'. Only in rare cases can we allow a locale node. In the current case, the locale node must be removed before the addition could be made live.
It is for JodeBrui to decide about the added bullet more generally, after the locale node is removed by Aaron.
CC: @jodebrui

**Comment by PRMerger13** [comment]
@AaronBertrand : Thanks for your contribution! The author, @jodebrui, has been notified to review your proposed change.

**Comment by AaronBertrand** [comment]
Thanks, I made a new commit with the change, but I mean I didn't have to go too far down the page to [find a counter-example that violates your own rule](https://i.stack.imgur.com/DTrb1.png) :-)

**Comment by MightyPen** [comment]
@AaronBertrand Aaron, I will accept and merge this public PR 1035 now.  Thank you.
And the other 'en-us/' occurrences you found should not have slipped through into our system, but occasionally there are reasons why it happens.  :-)

**Pull request merged**
