### PR TITLE
Updated create-a-database.md

### PR DESCRIPTION
**Pull request by 1Oozaru1**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@1Oozaru1 : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
@1Oozaru1 Thank you for your contribution, but I do not think this adds clarity.

**Comment by GitHubber17** [comment]
@CarlRabeler - Would you add a comment like `#sign-off` or `#please-close` to indicate how the review team should take action on this request? Thanks

**Comment by CarlRabeler** [comment]
#please-close

**Pull request closed without merging**
