### PR TITLE
Added limitation about compression settings

### PR DESCRIPTION
**Pull request by greijer**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@greijer : Thanks for your contribution to the SQL documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@edmacauley can you please review.

**Comment by edmacauley** [comment]
Thanks for the edits and additional info #sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by craigg-msft** [comment]
Thank you @greijer and @edmacauley merging.

**Pull request merged**
