### PR TITLE
Add example for changing the service owner

### PR DESCRIPTION
**Pull request by thenath**
I couldn't easily find an example of how to do this, so I thought it would be a useful addition.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@thenath : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by rwestMSFT** [comment]
@thenath Thank you for your suggestion. I'm approving this for now, and then we'll follow up with a refresh of the article in the next day or so.

#sign-off

**Comment by PRMerger18** [comment]
@rwestMSFT: I'm sorry - only the author of this article, @WilliamDAssafMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Pull request merged**
