### PR TITLE
Update permission requirement

### PR DESCRIPTION
**Pull request by AndreasWolter**

### CODE REVIEW

**Comment by AndreasWolter** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
@rwestMSFT

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@AndreasWolter You can’t sign off PRs anymore by the way.

**Comment by AndreasWolter** [comment]
I know @rwestMSFT . Although in the online course that I looked at it still said one should do it.
So I am just using this as a final comment to make clear I am done. Out of habit, but also for clarity.
Open for suggestions though

**Comment by rwestMSFT** [comment]
@AndreasWolter It won't make any difference except generate error messages. The reviewers already ping the page author, and that's the best you can hope for now as an external contributor.

**Comment by AndreasWolter** [comment]
Ok. Then if it won't hurt you, leave me the fun and habit :)

**Pull request closed without merging**
