### PR TITLE
Update sql server name in docker installation

### PR DESCRIPTION
**Pull request by eshy**
Name should be the same for all code commands, one instance was using sqlrhel instead of sql1

### CODE REVIEW

**Comment by PRMerger8** [comment]
@eshy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by amvin87** [comment]
Thank you @eshy. Can we merge this change please.

**Review by amvin87 — APPROVED** [review]

**Comment by PRMerger12** [comment]
@rwestMSFT: I'm sorry - only the author of this article, @amvin87, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by amvin87** [comment]
#sign-off

**Pull request merged**
