### PR TITLE
typo: Cleanup additional common issues

### PR DESCRIPTION
**Pull request by nschonni**
Some leftover from find/replace fixes in the t-sql folder

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@tfosmark : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@nschonni Nick, thanks again.  Plenty of good fixes here in PR 1471.
But there is an oddity that I do not understand:
Why does the GitHub DIFF highlight "HIPPA_Audit", on both left/red and right/green, when they look identical to the human eye when viewing the DIFF in a browser?
. . . . . (See DIFF for following file.) . . . . .
docs/2014/relational-databases/security/auditing/create-a-server-audit-and-server-audit-specification.md

**Comment by nschonni** [comment]
They should all be changing from "HIPPA_Audit" -> "HIPAA_Audit". Double "A" instead of double "P"
I'll try and summarize the changes next time. I usually do that for single file cleanups, but I just threw this one over the fence :stuck_out_tongue:

**Pull request merged**
