### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by psachin**
"elect" should be "select"

### CODE REVIEW

**Comment by PRMerger12** [comment]
@psachin : Thanks for your contribution! The author, @rgward, has been notified to review your proposed change.

**Comment by rothja** [comment]
@psachin I think that "elect" might have been intentional here. But a more clear word would be "choose". I'm going to change it to "choose" and merge this in. Thanks for your feedback!

**Comment by PRMerger9** [comment]
@rothja : Thanks for your contribution! The author, @rgward, has been notified to review your proposed change.

**Comment by rothja** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@rothja: I'm sorry - only the author of this article, @rgward, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
