### PR TITLE
Update hints-transact-sql-join.md

### PR DESCRIPTION
**Pull request by AssafFraenkel**

### CODE REVIEW

**Comment by PRMerger4** [comment]
@AssafFraenkel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@VanMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger19** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks for catching this, @AssafFraenkel! All of the hints article in that section should apply to MI. I added some more changes to this PR. We really appreciate your help on our documentation.

#sign-off

**Pull request merged**
