### PR TITLE
Created note for curl not installed warning

### PR DESCRIPTION
**Pull request by saitorhan**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@saitorhan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by saitorhan** [comment]
@prmerger19: Hi! I'm new at Microsoft docs making a contribution. May I ask that, what can I change for merging my this pull request?
Thanks.

**Comment by v-andreaco** [comment]
@saitorhan 

The author of this article has received a request to review your suggested changes. If they approve, the PR can be merged.

**Comment by saitorhan** [comment]
@v-andreaco 
So much thanks for explanation :)

**Comment by VanMSFT** [comment]
Thanks @saitorhan! We appreciate the additions. I'll approve this change.

#sign-off

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
