### PR TITLE
Update about-change-data-capture-sql-server.md

### PR DESCRIPTION
**Pull request by jasonhorner**
adding details about the sp's and views that can be used to cleanup and monitor replication. can someone check the links I wasn't sure if they were pathed correctly

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@jasonhorner : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by rothja** [comment]
@jasonhorner Thanks for this suggested change. I am going to run this by some people internally before publishing. Thanks for your patience.

**Comment by rothja** [comment]
@jasonhorner Thanks, again, for this change. I am going to try to make a minor edit to your suggestion and to resolve the merge conflict. + @assign:MaraSteiu FYI

**Comment by PRMerger16** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: marasteiu fyi

**Comment by PRMerger15** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@jasonhorner I was having trouble making all the necessary changes here to publish, so I am pushing your commits on our private repo and it should publish soon from there. I am closing this PR, but your changes will publish and you should be listed as a collaborate on the article when it does. Thanks!

**Pull request closed without merging**
