### PR TITLE
Adding the option to use VNet peering

### PR DESCRIPTION
**Pull request by dolevshor**
Adding the option (and recommended way) to connect VNets with VNet peering (global peering supported with MI too: https://azure.microsoft.com/en-us/updates/global-virtual-network-peering-support-for-azure-sql-managed-instance-now-available/) and not only with VPN gateway.

### CODE REVIEW

**Comment by Court72** [comment]
@ferno-ms 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by dolevshor** [comment]
@ferno-ms Appreciate your time to review the proposed changes.

**Comment by sasapopo** [comment]
Change looks good. Signing off.

**Review by sasapopo — APPROVED** [review]

**Comment by Jak-MS** [comment]
@dolevshor @sasapopo 

PRMerger will only accept sign off / approval from the listed 'author'. However, if you are a Microsoft employee authorized to update this content, you can send a request to [techdocprs@microsoft.com](mailto:techdocprs@microsoft.com) for this PR to be merged.  Include your role, and an explanation of why the PR should be merged without approval from the listed author.

**Pull request merged**
