### PR TITLE
Update automated-backups-overview.md

### PR DESCRIPTION
**Pull request by MilanMSFT**
Removed Note, since the Backup storage redundancy change is now available for all clouds.
> [!NOTE]
> Backup storage redundancy change for SQL Managed Instance is currently available only for the Public cloud via Azure Portal.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@MilanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MilanMSFT** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@MilanMSFT: I'm sorry - only the author of this article, @SudhirRaparla, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by SudhirRaparla** [comment]
#sign-off

**Pull request merged**
