### PR TITLE
Update sql-server-express-localdb.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
This is probably not the best way but I had a customer ask when this page will be updated for VS 2022. It would be helpful to indicate what 2022 uses.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rwestMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@Rick-Anderson It's not clear from your edit what the intent is. Are you saying that your customers are asking which version of LocalDB is supported in VS 2022? Or are you saying that they want to know in which version of Visual Studio that SQL Server 2022 LocalDB will be supported?

**Comment by Rick-Anderson** [comment]
> This is probably not the best way but I had a customer ask when this page will be updated for VS 2022. ***It would be helpful to indicate what 2022 uses.***

Does that answer it? 

Mostly they want to know that VS22 uses SQL Server Express 2019.

I didn't see in the doc any correlation between VS version and SQL Server Express version.

**Comment by rwestMSFT** [comment]
Because you wrote "2022" without a qualifier, it wasn't clear at first, no.

The article needs a refresh, so I've created a new internal PR that includes a note about VS 2019-2022. Thanks for raising this.

This PR will automatically close once the internal one is merged.

Please submit future PRs through the private repo in future. It'll make collaboration a lot easier, thanks!

**Comment by Rick-Anderson** [comment]
>Please submit future PRs through the private repo in future. It'll make collaboration a lot easier, thanks!

I prefer to do everything public, like git was intended and how I do all my work in https://github.com/dotnet/AspNetCore.Docs

Private has a place for when it needs to be private.

**Comment by rwestMSFT** [comment]
Regardless of your preferences, that’s not how this repo works. We have validation, preview and review steps that can only take place on the private repo, due to its complexity. If you decline to use that because of an arbitrary preference, understand that your PRs will slide down the priority list and will take much longer to resolve. You’re more than welcome to discuss this further with my manager, who you can find using internal tools. Thanks again for your contribution.

**Comment by Rick-Anderson** [comment]
I like to think of myself as a customer of VS, not an insider. I prefer to use the tools and language customers use, which helps foster customer involvement.

>We have validation, preview and review steps that can only take place on the private repo, due to its complexity.

What _validation, preview and review steps that can only take place on the private repo, due to its complexity_. ?

We do all that publicly in  https://github.com/dotnet/AspNetCore.Docs except for Acrolinx, which we run client side in VSC.

**Comment by rothja** [comment]
@Rick-Anderson, Hey, Rick. Long time since we spoke (in-person or virtually!). I think the .NET repos being public only have a unique style of contribution compared to a lot of our other doc repos where there is the public/private split. It's a lot easier, in our experience, to introduce problems into the docs when we get public repos because there is no preview link, build validation, or PR review team reviews that help to maintain our quality. For internal writers, we have to go through the standard private workflow in these cases. Thanks for understanding!

**Comment by Rick-Anderson** [comment]
> ... because there is no preview link, build validation, or PR review team reviews that help to maintain our quality. For internal writers, we have to go through the standard private workflow in these cases. Thanks for understanding!

But that's just how you set up the private repo. There's nothing inherent to private repo's that prevents any of those features.

To get **_more_** customer engagement, you need to do **_more_** work openly. 

I'd really like to see MS move away from the "_Do all work in private even though most of it could be done publicly_" to _Only do what can't be done in public privately_. That's we do.

cc @jeffwilcox

**Pull request closed without merging**
