### PR TITLE
Fix the answer in FAQ which wrongly indicates that R is supported by Azure SQL databases

### PR DESCRIPTION
**Pull request by StanislawSwierc**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@StanislawSwierc : Thanks for your contribution to the Azure documentation! The author, @jeannt, has been notified to review your proposed change.

**Comment by jeannt** [comment]
@StanislawSwierc I apologize for the delay in replying to the merge request. The PM sent me a request for the same change at about the same time, and that change should already be live. (Let me know if not!)

**Comment by craigg-msft** [comment]
@jeannt  so should I close this PR?
thanks

**Comment by jeannt** [comment]
@craigg-msft No; please merge -- I just approved it. He copied my changes into a separate topic.

**Pull request merged**
