### PR TITLE
Update sys-dm-hadr-auto-page-repair-transact-sql.md

### PR DESCRIPTION
**Pull request by kpuls**
Separated paragraph and fixed punctuation above table.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@kpuls : Thanks for your contribution to the SQL documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@MikeRayMSFT please review.

**Comment by MikeRayMSFT** [comment]
@kpuls thank you for your contribution. #sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by craigg-msft** [comment]
Thank you @kpuls  and @MikeRayMSFT

**Pull request merged**
