### PR TITLE
Update store-json-documents-in-sql-tables.md

### PR DESCRIPTION
**Pull request by chadbaldwin**
Typo in sample query

### CODE REVIEW

**Comment by PRMerger6** [comment]
@chadbaldwin : Thanks for your contribution! The author, @jovanpop-msft, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@chadbaldwin Thanks for noticing this. Since you added AVG(, I think that line now has mismatched parentheses. Will you please review?

**Comment by douglaslMS** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@douglaslMS: I'm sorry - only the author of this article, @jovanpop-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
