### PR TITLE
Create sql-server-compliance.md

### LINKED ISSUE #4616: Document SQL standard compliance
Does Microsoft SQL Server fully support SQL:1999, SQL:2003, SQL:2006, SQL:2008, SQL:2011 and SQL:2016?

What standards are fully supported?
What standards are partially supported?
What standards are are not supported?
What functionality differs from that one of the standard?
What is functionally equivalent?

PostgreSQL have a [SQL conformance](https://www.postgresql.org/docs/current/features.html) page documents [supported features](https://www.postgresql.org/docs/current/features-sql-standard.html), [unsupported features](https://www.postgresql.org/docs/current/unsupported-features-sql-standard.html), and [limits in conformance](https://www.postgresql.org/docs/current/xml-limits-conformance.html).
Firebird have a [SQL conformance](https://www.firebirdsql.org/en/sql-conformance/) page.
MySQL have a page on [MySQL Differences from Standard SQL](https://dev.mysql.com/doc/refman/8.0/en/differences-from-ansi.html)
Oracle have a [Oracle and Standard SQL](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Oracle-and-Standard-SQL.html) chapter in their documentation.

Wikipedia have a incomplete article on [SQL compliance](https://en.wikipedia.org/wiki/SQL_compliance) with a comparison table.

### PR DESCRIPTION
**Pull request by vanillajonathan**
Document the compliance of SQL Server to the SQL standards.

Fixes Issue #4616

### CODE REVIEW

**Comment by ktoliver** [comment]
@vanillajonathan Thanks for your pull request. It will be assigned for review by the content team shortly.

**Comment by MightyPen** [comment]
@vanillajonathan Hello Jonathan, Thank you for creating this PR #4665 , as this might make for an excellent new documentation article.
But first, can you please provide some context for this?

- From where did you obtain this info?

All articles need a paragraph of explanatory text at the top of the introduction. For instance, these table rows involve "compliance" _with what_?  (Maybe with ANSI-? standards for the SQL language, or exact what?)?
- Can you please enter such a paragraph into either (a) An update of your draft article, or (b) Into another Comment box (one like this comment box, here in this PR)?

- What does 'Unknown' mean in the third column with the label 'Microsoft SQL'?
  - Does 'Unknown' mean you do not know, or nobody knows, or it would be impossible to determine, or what does 'Unknown' mean?

- How can our SQL Server documentation writing staff accurately reassess possible updates to this article when SQL Server vNext is eventually released?  What master source of accuracy did you reference when drafting this SQL 2019 article?
  - I suspect that the draft article should have a clickable link to the master source of accuracy for general Structure Query Language compliance requirements.

A minor point: for our markdown tables, we always include both an opening '|' and a closing '|' character on each row.

As a practical matter for easier scan-ability for our customers, we will likely modify your draft to divide the one enormous markdown table into several smaller tables. We will also insert several \#\# H2 title headers.


It will be very helpful if you can provide the above requested info.

Thanks a lot Jonathan.

cc: @rothja , @MikeRayMSFT , @ktoliver 

. .

**Comment by MightyPen** [comment]
@vanillajonathan I see now that the earlier GitHub Issue #4616 gives some info about webpages hosted by other companies, that have some kind of SQL compliance requirements. But I do not see a link to the master source of truth about SQL standards.

Microsoft's "Docs" website has some articles that seem to be related to this draft:

- `https://docs.microsoft.com/sql/database-engine/configure-windows/common-criteria-compliance-enabled-server-configuration-option?view=sql-server-ver15` 

- `https://docs.microsoft.com/openspecs/sql_standards/ms-sqlstandlp/89fb00b1-4b9e-4296-92ce-a2b3f7ca01d2`

**Comment by vanillajonathan** [comment]
@ktoliver Thanks, the article is more of a rough draft right, hence most features are specified as "Unknown", and even for the features that are specified as "Yes", I don't really don't know if they adhere 100% to the standard, nor which edition of the SQL standards. It needs lots of work to mark up which features are supported and to what extend. By doing the outline, I would hope that someone who knows their stuff (I surely don't) can fill in the information.

@MightyPen 

> From where did you obtain this info?

I gleaned at the links mentioned in the issue and wanted something similar for SQL Server so threw together a Markdown table. The features are documented in the SQL standard documents but I do not have access them, because they cost money.

> All articles need a paragraph of explanatory text at the top of the introduction. For instance, these table rows involve "compliance" with what? (Maybe with ANSI-? standards for the SQL language, or exact what?)?

The compliance would be to the features defined in the SQL standards, such as SQL:2016, but some features in SQL Server might not have full support for the features as defined in SQL:2016 an might only be compliant to SQL:2011 or SQL:2008, then this could be mentioned.

> Can you please enter such a paragraph into either (a) An update of your draft article, or (b) Into another Comment box (one like this comment box, here in this PR)?

The article have "Allow edits from maintainers" enabled, so feel free to improve the article.

> What does 'Unknown' mean in the third column with the label 'Microsoft SQL'?

"Unknown" in the column means that I do not know, I am sure someone else knows. So someone with expertise in SQL Server needs to change this to "Yes", "No", "Partially" or something like "Yes, SQL:2008". Please fill in if you feel you know and can help.

> How can our SQL Server documentation writing staff accurately reassess possible updates to this article when SQL Server vNext is eventually released? What master source of accuracy did you reference when drafting this SQL 2019 article?

They can add an additional column to the table, to have one column represent SQL Server 2019 and a column next to it representing SQL Server vNext.

The article was inspired by the [Supported Features article in the PostgreSQL documentation](https://www.postgresql.org/docs/current/features-sql-standard.html) as well as the [SQL conformance article in the Firebird SQL documentation](https://www.firebirdsql.org/en/sql-conformance/). So I created a similar table in Markdown syntax and did a very poor job at filling it in.

> I suspect that the draft article should have a clickable link to the master source of accuracy for general Structure Query Language compliance requirements.

My understanding is that all the features are documented in the SQL:2016 or ISO/IEC 9075:2016 and related documents from previous editions and these are not public available on the web and have to be purchased.

> A minor point: for our markdown tables, we always include both an opening '|' and a closing '|' character on each row.

Okay, I can do that adjustment. The article is open for edits, so anyone can chip in.

> As a practical matter for easier scan-ability for our customers, we will likely modify your draft to divide the one enormous markdown table into several smaller tables. We will also insert several ## H2 title headers.

Yeah, that sounds good.

Thanks!

**Comment by MikeRayMSFT** [comment]
@vanillajonathan - thank you for this submission and for answering @MightyPen 's questions. 

I'm going to engage with some members of the product group to evaluate your submission. 

Thanks again.

**Comment by MikeRayMSFT** [comment]
@vanillajonathan I consulted with @pmasl who noted:

>Standards support docs already exists in https://docs.microsoft.com/en-us/openspecs/sql_standards/ms-sqlstandlp/89fb00b1-4b9e-4296-92ce-a2b3f7ca01d2. Specifically, the PR refers to the current SQL standard (ISO/IEC 9075:2008), which is already documented here: https://docs.microsoft.com/en-us/openspecs/sql_standards/ms-tsqliso11/60cb661b-8fad-4d05-831f-1d5bc60bc1a2
> A short URL is https://aka.ms/sqlstandards.

With this in mind, it seems that the best answer is to make sure appropriate links are placed in the documentation. 

Is there a place you might recommend placing these links?

Thanks,
Mike

**Comment by vanillajonathan** [comment]
@MikeRayMSFT That documentation is rather difficult to comprehend, there are lots of links to PDFs and lots of sub-chapters. That documentation might be good when you want to dig deep into a particular function, but is less useful to get overview/glance of the implemented functionality in regards to the SQL standards. Looking at the PostgreSQL and the Firebird documentation is much easier. I still think we should have a presentation in a table format because it is just so much easier to comprehend and make it so much more user friendly.

**Comment by MikeRayMSFT** [comment]
@vanillajonathan - thank you for the follow up and I understand your point about presentation of the content. I appreciate the example table you propose. We're looking at options that meet our customer's requirements.

**Comment by MikeRayMSFT** [comment]
@vanillajonathan 

Thank you very much for submitting this article. We will not be able to include it in the docs. 

After reviewing your proposal and our business requirements, we have decided that the standards support documentation will remain as published at [SQL Server Standards Support](https://docs.microsoft.com/en-us/openspecs/sql_standards/ms-sqlstandlp/89fb00b1-4b9e-4296-92ce-a2b3f7ca01d2). This presentation meets compliance requirements, obligations, and is aligned with the standards documentation provided by other commercial database vendors. 
[SQL Server technical documentation]( https://docs.microsoft.com/sql/sql-server/) is published in an open publishing system. This system supports broad community contribution to our documentation set. The documentation is subject to frequent changes as the product is updated, technology improves, and use cases evolve. However, the standards are relatively static, and our implementation of the standards in the design of the SQL Server relational database management system is also stable. To ensure that the way standards are implemented is documented, we provide the SQL Server Standards Support documentation in a system that is carefully vetted and updated only as required. 

The request you submitted highlights a need to link the content in [SQL Server technical documentation]( https://docs.microsoft.com/sql/sql-server/) to the applicable standards and we plan to add additional links as appropriate. For the short term, we have already made that link available from the landing page for [Transact-SQL Reference (Database Engine)](https://docs.microsoft.com/sql/t-sql/language-reference#t-sql-compliance-to-sql-standard). We are also evaluating publishing the standards content in way that is more searchable.  

Thank you, again for your proposal.

**Comment by vanillajonathan** [comment]
@MikeRayMSFT I am sure your extensive standard documents ticks every checkbox for compliance requirements and obligations, but it is not very useful. Other standard documents provided by other database vendors offers presentation formats that are much easier to to get an overview of which features are compliant to the standards, features deviate from the standard and which standard features are not implemented.

In a comment above in this thread are links to the documentation of PostgreSQL and Firebird which shows how other vendors make their information available in a much more user friendly way.

The way the documentation is presented by Microsoft is only good for fulfilling compliance requirements and obligations.

I would like to request that the team responsible for the SQL compliance documentation should append a feature table in addition to the existing documentation.

**Comment by pmasl** [comment]
@vanillajonathan as mentioned, we are also evaluating publishing the standards content in way that is more searchable than downloading a file and using Word/PDF search functionality. To establish expectation, that is not a process with a short turnaround. Thank you for the feedback.

**Comment by vanillajonathan** [comment]
Yeah it would be good if it was more searchable, but it would also be good nice if it was presented in such a way that you quickly get an overview of compliance against all the features in the SQL standards, such overview could be presented in a table, if I may suggest.

**Pull request closed without merging**
