### PR TITLE
Update on TSQL for Rename a Database

### PR DESCRIPTION
**Pull request by marcosfreccia**
To update the name of the database, it needs to be in single user mode. The documentation shows correctly for the GUI part, but not for the T-SQL.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@marcosfreccia : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@CarlRabeler please review

**Comment by CarlRabeler** [comment]
@marcosfreccia made changes in another PR: https://github.com/MicrosoftDocs/sql-docs-pr/pull/7558
changes live now - please review and if you have any questions or have additional changes, please file in git issue. Thanks for bringing this to my attention.
Carl

**Comment by CarlRabeler** [comment]
#please-close

**Pull request closed without merging**
