### PR TITLE
Missing paren on PRINT

### PR DESCRIPTION
**Pull request by LowlyDBA**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@LowlyDBA : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@LowlyDBA Hello John, Thank you for bring this concern to our attention. In the future, it is helpful if these public PRs include more text to explain the PR. For example, why do you believe this is a source code bug? The challenge is that - I am told this code sample worked when we tested it a year ago.  On what version of Python did you encounter a problem?  What was the error message?

Please, can you enter a brief follow-up Comment to tell us a those kinds of information.  And in the Comment, @ notify me directly so I will know.
To be clear, I suspect your concern is correct.  I just want a bit more info.

Thank you very much.
MightyPen

**Comment by LowlyDBA** [comment]
@MightyPen Sure thing, no problem.

As of Python 3, [print is a function](https://docs.python.org/3.0/whatsnew/3.0.html#print-is-a-function) so it requires parentheses when used:

image

**Comment by MightyPen** [comment]
I sent email to PyTalk for a point of clarification:
Were parentheses ALLOWED before version 3 pf Python?

**Comment by MightyPen** [comment]
#sign-off

**Pull request merged**
