### PR TITLE
Clarify how to get started after installation

### PR DESCRIPTION
**Pull request by MsSQLGirl**
Update the first step of the Use the Machine Learning extension section to clarify on how a user can get started once they install the Machine Learning extension.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@MsSQLGirl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @MsSQLGirl - PMs should work in the private repository, per the contributor guide. We'll leave this PR for review in the public repo, but would you submit future content updates in the private repo? Thanks!

**Comment by ktoliver** [comment]
@dphansen Would you review the proposed update to your article? Thanks.

**Review by dphansen — APPROVED** [review]
Looks good!

**Pull request merged**
