### PR TITLE
Should be "professional" not "technician"

### PR DESCRIPTION
**Pull request by greglow**
as per Microsoft's own naming

### CODE REVIEW

**Comment by PRMerger14** [comment]
@greglow : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
Thank you @greglow Can you please point me to what Microsoft source you are referencing?  We reviewed some internal style guides and they did not indicate the need for a language update but it could very well be one source is behind others, it would not be the first time.  Thank you for your time!

**Comment by greglow** [comment]
Hi Craig

Microsoft’s certification program for these people is called the Microsoft Certified Professional program. There is info on it everywhere. No-one calls database people technicians. Technicians generally repair hardware. I think when referring to a certified person, the naming should align directly with Microsoft’s own naming for these people. Yesterday I asked a room full of people about the term technician. None thought it was appropriate.

https://en.m.wikipedia.org/wiki/Microsoft_Certified_Professional

Regards,

Greg

Dr Greg Low
1300SQLSQL (1300 775 775) office | +61 419201410 mobile│ +61 3 8676 4913 fax
SQL Down Under | Web: www.sqldownunder.com
________________________________

**Comment by craigg-msft** [comment]
Thanks @greglow .  I do not think either options in anyway affects the readability or knowledge gained from the content.  We also do not have an official take on the term or this usage of either of those words and since the proposed changes are consistent, I will go ahead and merge them.

**Pull request merged**
