### PR TITLE
samples rows

### PR DESCRIPTION
**Pull request by pricardo03**
I change the inserts to simplify the demo code

### CODE REVIEW

**Comment by PRMerger18** [comment]
@pricardo03 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@pricardo03 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@shkale-msft - Would you review the proposed updates to your article? Thanks.

**Comment by ktoliver** [comment]
> @shkale-msft - Would you review the proposed updates to your article? Thanks.


Hi @pricardo03 - In this comment, I ask the article author (@shkale-msft) to review (consider whether to approve) the content updates in your pull request. There's no further action for you unless the author requests changes or input to what you submitted in the pull request.

**Pull request merged**
