### PR TITLE
change a typo from "fron" to "from"

### PR DESCRIPTION
**Pull request by Powerhelmsman**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Powerhelmsman : Thanks for your contribution! The author, @MightyPen, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@powerhelmsman Thank you for this fix.  Nice catch. We will Merge it into our master documentation source.  (GeneMi , 2018/09/26 10:05am)

**Comment by MightyPen** [comment]
@PRMerger18 First, please do Merge this good PR 1004.
.
As an aside, I looked at all three internal Help documentation articles that the TOC filter box can find, and none of them list the special # keywords we Writers are supposed to use - given that we cannot use '# sign - off'.  So I can only use this freeform textual mode of communication.  If there is a # keyword I am supposed to use here, can you tell me what the keyword is?  Thanks.
.
https://review.docs.microsoft.com/en-us/help/contribute/contribute-vendor-public-prs?branch=master
.
https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master
.
https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master

**Comment by MightyPen** [comment]
#sign-off

**Pull request merged**
