### PR TITLE
Fix "Search Condition" note about code page conversions

### PR DESCRIPTION
**Pull request by srutzky**
The current note regarding code page conversions with respect to non-Unicode expressions is incorrect in several ways. The new wording is a little longer, but accurate.

Please see the following two posts for a detailed explanation (with examples) of why this change is being made:

1. [Which Collation is Used to Convert NVARCHAR to VARCHAR in a WHERE Condition? (Part A of 2: “Duck”)](https://sqlquantumleap.com/2017/12/08/which-collation-is-used-to-convert-nvarchar-to-varchar-in-a-where-condition-part-a-of-2-duck/)
1. [Which Collation is Used to Convert NVARCHAR to VARCHAR in a WHERE Condition? (Part B of 2: “Rabbit”)](https://sqlquantumleap.com/2017/12/11/which-collation-is-used-to-convert-nvarchar-to-varchar-in-a-where-condition-part-b-of-2-rabbit/)

### CODE REVIEW

**Comment by PRMerger3** [comment]
@srutzky : Thanks for your contribution to the SQL documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
Thank you @srutzky  @edmacauley please review.

**Comment by edmacauley** [comment]
Makes sense to me, thanks @srutzky for another edit

**Comment by edmacauley** [comment]
#sign-off

**Comment by PRMerger9** [comment]
Only the author, @rickbyh, can sign off on this pull request.

**Comment by edmacauley** [comment]
@craigg-msft will need to merge this probably

**Comment by craigg-msft** [comment]
Thank you @srutzky and @edmacauley

**Comment by srutzky** [comment]
@edmacauley and @craigg-msft : you are welcome.

**Pull request merged**
