### PR TITLE
Remove issues that appeared fixed but actually marked as duplicate

### PR DESCRIPTION
**Pull request by yualan**

### CODE REVIEW

**Comment by yualan** [comment]
#sign-off @stevestein

**Comment by PRMerger19** [comment]
@yualan: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger7** [comment]
@yualan : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
#sign-off

**Comment by stevestein** [comment]
Merging...

**Pull request merged**
