### PR TITLE
ROLLBACK TRANSACTION: Corrected typo

### PR DESCRIPTION
**Pull request by BraveJhawk**
will is -> will be

### CODE REVIEW

**Comment by PRMerger18** [comment]
@BraveJhawk : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@BraveJhawk Thanks for catching our typo. In our current writing, we try to avoid the future tense, for simplicity and for the sake of localization. Would you mind revising to "the nested transaction **is** rolled back" ? Thanks!

**Comment by douglaslMS** [comment]
@BraveJhawk Thanks, Sean.

**Comment by douglaslMS** [comment]
#sign-off

**Pull request merged**
