### PR TITLE
Update sample-unattended-install-redhat.md

### PR DESCRIPTION
**Pull request by tanaka-takayoshi**
Add "-eu" option to the unattended installation script. "-eu" optoin enables to stop when any error happens during the script.

If this PR can be merged, I can add this option to the script for other platforms (SUSE and Ubuntu).

### CODE REVIEW

**Comment by PRMerger3** [comment]
@tanaka-takayoshi : Thanks for your contribution to the SQL documentation! The author, @edmacauley, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
Thank you @tanaka-takayoshi great option for the script, if you'd like to add that for the others it'd be great.  Thanks again.

**Comment by edmacauley** [comment]
#sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by edmacauley** [comment]
Er... "The author, @edmacauley, has been notified to review your proposed change."

**Comment by edmacauley** [comment]
Oh, I see the problem.  My bad, I've got my microsoft alias set to my github alias.  I will fix in an internal PR.

**Comment by edmacauley** [comment]
Hi @tanaka-takayoshi, I've applied your proposed change to all three scripts internally because of the need to change some goofed up metadata.  Would you mind closing this PR?  Thanks again!

**Comment by tanaka-takayoshi** [comment]
Thanks @edmacauley, I'm closing the PR.

**Pull request closed without merging**
