### PR TITLE
Update create-external-table-transact-sql.md

### PR DESCRIPTION
**Pull request by sommarskog**
Removed SCHEMA_NAME and OBJECT_NAME, as they only apply to Azure SQL Database. (See also Issue #7885)

### CODE REVIEW

**Comment by Jak-MS** [comment]
@WilliamDAssafMSFT - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
@sommarskog FYI I was unable to confirm that SCHEMA_NAME and OBJECT_NAME are not supported in SQL Server the last time around. I am still investigating this but at this time I don't have enough information. If you have other confirmation that these two arguments are not supported in _any_ version of SQL Server, please add. 
Closing as I am tracking in an internal effort.

**Comment by sommarskog** [comment]
SCHEMA_NAME and OBJECT_NAME are used in Azure SQL Database, but it is not present in the box product - I get syntax errors when I try to use them. When it comes to Azure Managed Instance, I cannot vouch for anything, since I don't have access to MI. However, SCHEMA_NAME and OBJECT_NAME are not present in the syntax graph for SQL Server.

If my edit would remove that text also from Azure SQL Database, my apologies. But I don't think they should appear in the version for SQL Server.

**Comment by WilliamDAssafMSFT** [comment]
An update: Confirmed that the arguments SCHEMA_NAME and OBJECT_NAME are currently used only for the SQL DB sharing feature. Looks like we do have some places to clean these up in the arguments list. Thanks @sommarskog for pointing this out. A doc update is in flight. Your feedback makes the docs better for everyone, once again!

**Pull request merged**
