### PR TITLE
Simplified. No need for the Task Manager Step

### PR DESCRIPTION
**Pull request by PhilipElder**
Removed the extra steps.

Server Core on Server 2019: Import-Module SQLPS works just fine.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@PhilipElder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
Since the changes are approved, signing off and merging.  Thanks!

**Comment by rothja** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@rothja: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
