### PR TITLE
typo: Hiearchy -> Hierarchy

### PR DESCRIPTION
**Pull request by nschonni**
- Hieararchy -> Hierarchy
- Evaulation -> Evaluation
- Datbase -> Database

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @mashamsft, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @nschonni - We need to be able to see exactly what updates you are proposing in the pull request. In the first article, **docs/2014/2014-toc/glossary.md**, the diff view shows the entire file as "changed" but no details are available. Can you delineate what revisions you made and/or make revisions in a way that they show up in the line item in the GitHub diff view?

**Comment by ktoliver** [comment]
@nschonni - Thank you for your submission. We are not able to accept spacing and formatting changes in the repo at this time. Could you resubmit the _typo fixes only_ in a new pull request?

**Comment by nschonni** [comment]
I won't be resubmitting, feel free to fix internally

**Pull request closed without merging**
