### PR TITLE
fix: Add extension to `~/` link

### PR DESCRIPTION
**Pull request by nschonni**
Flagged in https://github.com/MicrosoftDocs/sql-docs/pull/1148#pullrequestreview-167039831 but didn't get fixed before the PR landed

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @MightyPen, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@nschonni Hi Nick, My PR 1148 comment was only a HowTo FYI for the future.  My teammate Doug L. created another PR to fix the 1148 links.

We do Not like to have links start with '~', nor with '/sql/' (except in uncommon special cases).  We prefer relative pathing according to the GitHub folder structure.
Also, the '.md' extension is needed when relative pathing is used, but '.md' is forbidden in any other syntax.

I am calling for this PR 1164 to be permanently Closed, partly because it has become a duplicated given Doug L.'s very recent private PR.
Thanks.

**Comment by MightyPen** [comment]
#please-close

**Comment by nschonni** [comment]
> We do Not like to have links start with '~', nor with '/sql/' (except in uncommon special cases). We prefer relative pathing according to the GitHub folder structure.
> Also, the '.md' extension is needed when relative pathing is used, but '.md' is forbidden in any other syntax.

Yup, that original PR was a little fake an partially because the issue tracker isn't open on this repo https://github.com/MicrosoftDocs/sql-docs/pull/1148#issue-224454082

**Pull request closed without merging**
