### PR TITLE
Update sql-server-linux-shared-disk-cluster-red-hat-7-configure.md

### PR DESCRIPTION
**Pull request by tanaka-takayoshi**
Required ``sudo`` for ``systemctl``.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@tanaka-takayoshi : Thanks for your contribution to the SQL documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@tanaka-takayoshi thank you for your contribution!
#sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by craigg-msft** [comment]
thank you @tanaka-takayoshi  and @MikeRayMSFT

**Pull request merged**
