### PR TITLE
Update performance-guidance.md

### PR DESCRIPTION
**Pull request by azarboon**
I haven't seen many tips regarding optimizing connection pools, so I've added them here to inform readers.

### CODE REVIEW

**Comment by ttorble** [comment]
@WilliamDAssafMSFT 

Can you review the proposed changes?  

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.  

#label:"aq-pr-triaged" 
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @azarboon for contacting Microsoft with a contribution to our product documentation. These topics of connection pooling and retry logic are discussed elsewhere in the Azure SQL Database context, good idea to mention and link to them here as well.  Since connection pooling is enabled by default in ADO.NET, I think this guidance to "use connection pooling libraries" could be more clear. I'll review and pull your commit internally and make edits. I'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

By opening a pull request, you're helping the authors add your approved change directly to the documentation. If the article is updated with your commit, GitHub will list you as an article contributor.

Thanks again for this feedback. Your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
A doc update including this commit will be merged today. Thanks @azarboon for this contribution to Microsoft docs - this will help everyone, everywhere. The article and GitHub will list you as an article contributor.

**Comment by azarboon** [comment]
@ttorble @WilliamDAssafMSFT, thank you for being supportive. Four days have already passed but still I can't see the edit in the "live" branch. Do you know why?

**Pull request merged**
