### PR TITLE
Update sp-enum-login-for-proxy-transact-sql.md

### PR DESCRIPTION
**Pull request by TomasFrank4**
Extension of result set.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@VanMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Thanks @TomasFrank4! We appreciate the help.

Verified, and made small update to text.

#sign-off

**Comment by VanMSFT** [comment]
#hold-off

**Comment by VanMSFT** [comment]
#sign-off

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
