### PR TITLE
Update sys-dm-exec-requests-transact-sql.md

### PR DESCRIPTION
**Pull request by olahallengren**
Added information that statement_sql_handle and statement_context_id is NULL if Query Store is not enabled for the database.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@olahallengren : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@olahallengren - thanks for updating and clarifying this.

**Comment by stevestein** [comment]
#sign-off

**Comment by olahallengren** [comment]
Thank you.

**Pull request merged**
