### PR TITLE
Adding a link to Slow I/O t-shooting

### PR DESCRIPTION
**Pull request by PiJoCoder**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@PiJoCoder : Thanks for your contribution! The author, @julieMSFT, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@PiJoCoder : Thanks for your contribution! The author, @julieMSFT, has been notified to review your proposed change.

**Comment by julieMSFT** [comment]
@PiJoCoder Hi Joseph, I am reviewing this.

**Comment by julieMSFT** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@Jak-MS : Thanks for your contribution! The author, @julieMSFT, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Jak-MS : Thanks for your contribution! The author, @julieMSFT, has been notified to review your proposed change.

**Pull request merged**
