### PR TITLE
Update sys-dm-geo-replication-link-status-azure-sql-database.md

### PR DESCRIPTION
**Pull request by sqlworldwide**
The existing description of `last_replication` column is incorrect. I worked with @dimitri-furman and his team to come up with a new language for this column.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by dimitri-furman — APPROVED** [review]

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Comment by WilliamDAssafMSFT** [comment]
Thanks @sqlworldwide for the collaboration on this PR. Your suggestions help improve our documentation. Your commit has been merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 

Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by ktoliver** [comment]
Now it's merged. 🚀

**Pull request merged**
