### PR TITLE
Adding in data exposed video

### PR DESCRIPTION
**Pull request by jeroenterheerdt**
Data Migration Assistant was discussed in [this Data Exposed episode](https://channel9.msdn.com/Shows/Data-Exposed/Data-Migration-Assistant/). This is a quick PR to add this video to the doc page.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@jeroenterheerdt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jeroenterheerdt** [comment]
@HJToland3 - Data Exposed is a Channel9 show that we started back up. I think it is a good idea to have the video show up in the docs pages as well. let me know if you want to discuss.

**Comment by HJToland3** [comment]
#sign-off

**Comment by HJToland3** [comment]
@jeroenterheerdt, I just reviewed and approved. Thank you!

**Pull request merged**
