### PR TITLE
Support Windows Server 2019

### PR DESCRIPTION
**Pull request by rikat-ms**
Supported operating system for OLE DB Driver for SQL Server should contain Windows Server 2019 like any other drivers/tools for SQL Server.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@rikat-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by pmasl** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
