### PR TITLE
Updated failover to match correct failover procedural steps

### PR DESCRIPTION
**Pull request by SeanGallardy**
1. Changed the steps to match correct procedure based on research and PGG talks
2. Updated notes that the settings isn't failover specific

### CODE REVIEW

**Comment by PRMerger18** [comment]
@SeanGallardy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SeanGallardy** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@SeanGallardy: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
