### PR TITLE
Update connect-query-vscode.md

### PR DESCRIPTION
**Pull request by joe-ratzer**
Small change to make the alignment of the INSERT example consistent

### CODE REVIEW

**Comment by joe-ratzer** [comment]
> @microsoft-github-policy-service agree

**Comment by American-Dipper** [comment]
@joeratzer  - In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just a few minutes: https://cla.microsoft.com. Thank you.

**Comment by joe-ratzer** [comment]
> @microsoft-github-policy-service agree

**Comment by joe-ratzer** [comment]
> @joeratzer - In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just a few minutes: https://cla.microsoft.com. Thank you.

@microsoft-github-policy-service agree

**Comment by dzsquared** [comment]
❤️ thanks @joeratzer!
#sign-off

**Pull request merged**
