### PR TITLE
Update connectivity-architecture.md

### PR DESCRIPTION
**Pull request by ruimaiaMSFT**
Added 20.38.152.24 gateway for UAE Central, as it was missing

C:\Users\ruimaia>nslookup rmuae.database.windows.net Server:  xxxxxxxxxxx
Address:  fe80::1

Non-authoritative answer:
Name:    cr5.uaenorth1-a.control.database.windows.net
Address:  20.38.152.24
Aliases:  rmuae.database.windows.net
          rmuae.privatelink.database.windows.net
          dataslice2.uaenorth.database.windows.net
          dataslice2uaenorth.trafficmanager.net

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rohitnayakmsft 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rohitnayakmsft** [comment]
We are no longer adding individual Gateway IPs. We only update the Gateway IP address subnets as we get them from Azure Networking.

**Comment by Court72** [comment]
> We are no longer adding individual Gateway IPs. We only update the Gateway IP address subnets as we get them from Azure Networking.

Thanks, @rohitnayakmsft. Should this PR be closed? If so, enter a comment, `#please-close`.

**Comment by ruimaiaMSFT** [comment]
> We are no longer adding individual Gateway IPs. We only update the Gateway IP address subnets as we get them from Azure Networking.

This gateway is not documented on individual Gateway IPs nor included Gateway IP address subnets for this region. Should it remain like this? We have a working non documented gateway (as per my understanding).

**Comment by rohitnayakmsft** [comment]
@ruimaiaMSFT Thanks for your feedback & reporting this issue! We are working on automating the update for CIDR list so it is up to date. I will check in to the UAE North ranges and update it shortly. Suggest we close this PR for now.

**Comment by Court72** [comment]
Closing per https://github.com/MicrosoftDocs/sql-docs/pull/8965#issuecomment-1554822250

**Pull request closed without merging**
