### PR TITLE
calc columns are now supported in the 1200 mode

### PR DESCRIPTION
**Pull request by dgosbell**
Calculated columns are now supported in 1200 mode models or higher (SQL 2016 or Azure AS)

### CODE REVIEW

**Comment by craigg-msft** [comment]
some of the web hooks for auto validation do not seem to be running.  closing pr and will re-open to see if it triggers them.

**Comment by craigg-msft** [comment]
Thank you @dgosbell   @Minewiskan please review and sign off.

**Comment by craigg-msft** [comment]
@Minewiskan please take another look and sign off if you think the current state should be merged, or if it should be closed as you are updating the topic in another PR.

**Comment by Minewiskan** [comment]
Removed the note in a separate PR.

**Comment by craigg-msft** [comment]
Thank you @dgosbell and @Minewiskan closing.

**Pull request closed without merging**
