### PR TITLE
Added csvPath parameter

### PR DESCRIPTION
**Pull request by ChrisLound**
Added csvPath parameter and description

### CODE REVIEW

**Comment by PRMerger10** [comment]
@ChrisLound : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@craigg-msft - GitHub isn't recognizing the listed author of this article. Can you review or reassign? Thanks.

**Comment by ChrisLound** [comment]
Hey Raj,

I believe notifications are going to you, but it seems you are not being recognised via @pochiraju<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpochiraju&data=02%7C01%7CChris.Lound%40microsoft.com%7C14e9a8c813be492b090908d69b5615a5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636867191360947265&sdata=bcKeqXXffuBsUi1H1b%2B9hhygjW7vgDHR1grUUm6i4Hs%3D&reserved=0>,…

**Comment by craigg-msft** [comment]
@HJToland3 please review

**Comment by craigg-msft** [comment]
internally emailed the author, including a suggestion on how to link the git id.

**Comment by guerrajames** [comment]
Better chance of whatever accounts I have cuz I never authorized them

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by HJToland3** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@HJToland3: I'm sorry - only the author of this article, @pochiraju, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Pull request merged**
