### PR TITLE
Added RDBMS option for Managed Instance

### PR DESCRIPTION
**Pull request by danimir**
Added RDBMS option for Managed Instance

### CODE REVIEW

**Comment by PRMerger19** [comment]
@danimir : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@danimir : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by danimir** [comment]
#sign-off

**Comment by PRMerger17** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @WilliamDAssafMSFT

**Comment by Jak-MS** [comment]
@WilliamDAssafMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
@danimir - you're contributing to docs enough that you should really be using the private repos.

Here's how to get set up:

> Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.
>
> After you make your changes in the private repo, review the articles on staging, and fix any validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 
> 
> Read about [authors working in the public repo](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=main) for more information. 
>
> If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-local?branch=main).

**Comment by danimir** [comment]
@jak-MS - I've only contributed to Azure docs. What would be the PR directory for SQL docs, would you know? Thanks!

**Pull request closed without merging**
