### PR TITLE
Fixed spelling mistake in hints-transact-sql-table.md

### PR DESCRIPTION
**Pull request by olimorris**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@olimorris : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@olimorris Oli, since the default language for the docs is US English (EN-US), we use the US spelling for words like "behavior" and many others. We localize our docs into many languages, but for better or for worse, not into EN-UK.

**Comment by olimorris** [comment]
@douglaslMS Apologies I genuinely had no idea that was a US spelling.

**Comment by douglaslMS** [comment]
@olimorris No worries! Sometimes a genuine misspelling can lead to dangerous ambiguity or misunderstandings, so we appreciate your attention to detail.

**Comment by douglaslMS** [comment]
#please-close

**Pull request closed without merging**
