### PR TITLE
Change AUTO definition for DW complevel

### PR DESCRIPTION
**Pull request by XiaoyuMSFT**

### CODE REVIEW

**Comment by XiaoyuMSFT** [comment]
@julieMSFT - Could you review this change I made directly at the online website?

**Comment by ktoliver** [comment]
#hold-off

**Comment by ktoliver** [comment]
Hi @XiaoyuMSFT Could you explain what this PR does and why it was created in the public repository? Thanks!

**Comment by ktoliver** [comment]
@XiaoyuMSFT - This pull request was created in the public repo. Would you create a pull request in the private repo instead? We'll close this PR. Thanks.

**Comment by ktoliver** [comment]
cc @MightyPen @craigg-msft @rothja @MikeRayMSFT

**Pull request closed without merging**
