### PR TITLE
Master

### PR DESCRIPTION
**Pull request by da-art85**
Unified pull request submission

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @da-art85 - Thank you for your contribution. Would you take a moment to sign the Contributor License Agreement (CLA)? After the CLA is signed, someone can review your pull request. Thanks!

**Review by da-art85 — COMMENTED** [review]
[ipython.txt](https://github.com/MicrosoftDocs/sql-docs/files/6250263/ipython.txt)
- https://github.com/docker/machine/is:pr/4862 /
[curl.yml]--(url)

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@da-art85 Thank you for signing the CLA.

Resolving the merge conflicts shows that two of the updated articles have changed substantially since this pull request was opened.  

Unexpected diffs in two of the articles demonstrates to me that it's problematic for the pull request to be coming not from a branch, but from the contributor's instance of master, and merging into live, as this repo does, complicates things more. Going to live, the diff needs to be clear and understood.

What I suggest, given the unexpected diff for two of the updated files, is closing this pull request and submitting the updates in a new PR that is submitted from a user-created branch (not named master), and using the latest version of master in this repository.

Alternatively, I would be happy to create a PR (using the structure I just identified) that contains the original updates, and then request the article authors to review and approve.

@rothja could you take a look and advise? Thanks.

**Comment by ktoliver** [comment]
#hold-off

**Pull request closed without merging**
