### PR TITLE
Update backup-transact-sql.md

### PR DESCRIPTION
**Pull request by FonsecaSergio**
Fix sample from MI BACKUP

BACKUP DATABASE Sales
TO URL = 'https://mystorageaccount.blob.core.windows.net/myfirstcontainer/Sales_20160726.bak'
WITH STATS = 5, COPY_ONLY;

### CODE REVIEW

**Comment by PRMerger10** [comment]
@FonsecaSergio : Thanks for your contribution! The author, @mashamsft, has been notified to review your proposed change.

**Comment by allenwux** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@allenwux: I'm sorry - only the author of this article, @mashamsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MashaMSFT** [comment]
Hi @FonsecaSergio , thank  you so much for your contribution! #sign-off

**Pull request merged**
