### PR TITLE
Updated last_sent_lsn, last_sent_time, last_received_lsn, last_receiv…

### PR DESCRIPTION
**Pull request by ccurtmath1**
…ed_time

Updated last_sent_lsn, last_sent_time, last_received_lsn, last_received_time, better descriptive describing where (primary or secondary) these columns report useful information.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ccurtmath1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger18** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @ccurtmath1 for submitting this PR! Nice addition. I've added a couple commits for style and phrasing. Ours commit will be merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 

Thanks again for this feedback, your suggestions help improve our documentation.

#sign-off

**Pull request merged**
