### PR TITLE
Update backupset-transact-sql.md

### PR DESCRIPTION
**Pull request by SQLSourabh**

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@SQLSourabh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SQLSourabh** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@SQLSourabh: I'm sorry - only the author of this article, @LitKnd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by LitKnd** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@LitKnd Oops, I mistook your hold off for a sign off. I made some style edits but will take no further action. Apologies. #hold-off

**Comment by ktoliver** [comment]
(Actually, I saw an earlier notification. My glasses are working correctly. 👍🏼 )

**Comment by LitKnd** [comment]
Hi @ktoliver ,

Sorry for the confusion-- I had a "haven't had enough coffee" moment earlier and signed off too soon :)

**Comment by MikeRayMSFT** [comment]
#please-close

**Pull request closed without merging**
