### PR TITLE
Update sys-dm-database-encryption-keys-transact-sql.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
View added in SQL Server 2008 ( 10 ).

### CODE REVIEW

**Comment by Court72** [comment]
@rwestMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Our documentation generally references currently supported versions of SQL Server. This addition is not necessary. Thanks for the contribution though, @DanielAdeniji.

#please-close

**Comment by DanielAdeniji** [comment]
Mr. Randolph West ( @Randolph West MSFT )

The distinction was not regarding whether SQL Server is supported or not.

It is to illuminate when the sys.dm_database_encryption_keys view was added to SQL Server.

It is a hard line that is helpful in determining why a Query that references the sys.dm_database_encryption_keys does not work.

Alas, specific columns have lineage information.

And, I personally think that is a good thing; in that it does not constrain knowledge to currently supported versions.


  1.  encryptor_type
     *   Applies to: SQL Server (SQL Server 2012 (11.x) through current version).
  2.  encryption_state_desc
     *   Applies to: SQL Server 2019 (15.x) and later.
  3.  encryption_scan_state
     *   Applies to: SQL Server 2019 (15.x) and later.
  4.  encryption_scan_modify_date
     *   Applies to: SQL Server 2019 (15.x) and later.

When a currently supported version rolls off the supported list, it is very hard to go back and update each object.

And, for that reason, it is always good to add information that provides baseline data; such as this one.

Daniel

________________________________

**Comment by rwestMSFT** [comment]
@DanielAdeniji

Columns have lineage, yes. We try to document when they were added, for supported versions of SQL Server and Azure SQL.

We do not specify in which version an object was added, if the object was added prior to the earliest supported version of SQL Server. This is an unnecessary burden on the team. SQL Server 2008 has been out of support for a number of years, and SQL Server 2012 went out of support in July this year.

If we accept this PR, then we would set a precedent for reviewing thousands of articles, and we don't have the time or the capacity for that. For this reason, I am rejecting the change.

**Pull request closed without merging**
