### PR TITLE
(AzureCXP) Corrected Syntax error while using service principal

### PR DESCRIPTION
**Pull request by HarithaMaddi-MSFT**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@HarithaMaddi-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @HarithaMaddi-MSFT - Thanks for making these changes. Can you please expand on what this is in reference to?

image

**Comment by VanMSFT** [comment]
Hi @HarithaMaddi-MSFT - Following up on my question. Can you please clarify?

**Comment by VanMSFT** [comment]
Closing this for now as there has been no response.

**Pull request closed without merging**
