### PR TITLE
add suspend senario

### PR DESCRIPTION
**Pull request by taroarai**
We have a customer who try to upgrade major version, and they faced suspend after manual failover to new primary. They want to know what to do to suspended DB, so I added one line to address that.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@taroarai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @taroarai , thanks for your contribution! Let me confirm on my end that this is expected, and then I can approve the change :) Thanks!

Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @taroarai , thanks for your patience, and apologies for the delay :) This addition helps with clarity, thank you for making our docs better!. #sign-off

**Comment by jborsecnik** [comment]
This pull request is for the Live branch. We can't merge to Live. Would you resubmit your changes to the master branch? Thanks.

**Pull request merged**
