### PR TITLE
Refactored example query

### PR DESCRIPTION
**Pull request by wdhenrik**
Refactored example query to include Last Run Finish Date Time and Last Run Duration Seconds.  Updated description to account for changes.

Used block comment style to allow different line breaks for query formatting tools or run in a single line.

### CODE REVIEW

**Comment by wdhenrik** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@VanMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Thanks @wdhenrik!

@rwestMSFT for review

**Comment by VanMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs/issues/9705

**Comment by rwestMSFT** [comment]
@wdhenrik Perfect, thank you. I will incorporate your PR into an internal one we have open.

**Comment by rwestMSFT** [comment]
This PR will close automatically when our internal PR is merged, and you will get credit. The updated article will publish in the next day or so. Thank you again for your contribution.

**Pull request closed without merging**
