### PR TITLE
Update accelerated-database-recovery-concepts.md

### PR DESCRIPTION
**Pull request by joannapea**
1. removed "Currently in public preview" since this is GA for SQLDW. 
2. renamed "SQL Data Warehouse" to "Synapse Analytics SQL pools".

### CODE REVIEW

**Comment by PRMerger12** [comment]
@joannapea : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @joannapea - This pull request was opened in the public repo. PMs should work in the private repo, per the contributor guide. Would you submit this content update in the private repo? We'll close this PR. Thanks.

**Comment by joannapea** [comment]
> Hi @joannapea - This pull request was opened in the public repo. PMs should work in the private repo, per the contributor guide. Would you submit this content update in the private repo? We'll close this PR. Thanks.

Hi @ktoliver  can you please help me find the source article in the private repo? I can't seem to find it. Thank you.

**Comment by ktoliver** [comment]
@joannapea - Link sent in Teams.

**Pull request closed without merging**
