### PR TITLE
Update alter table table_constraint

### PR DESCRIPTION
**Pull request by shkale-msft**
Added ON DELETE CASCADE of edges. This is a new feature in CTP2.3 of SQL Server 2019 release.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@shkale-msft : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by shkale-msft** [comment]
Hi, I am Shreya Verma, PM with the SQL Server team and the graph feature. Made a quick edit in the documentation for a new feature that we released with CTP2.3

**Comment by shkale-msft** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@shkale-msft: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by GitHubber17** [comment]
Hi @shkale-msft - We'll merge this PR. Please note that Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules. 

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master). 

Thank you

**Pull request merged**
