### PR TITLE
Update resource-limits.md

### PR DESCRIPTION
**Pull request by cbenkler**
Added clarification to the IO latency duration range to make clearer that IO requests exceeding the range are possible. (Although not as clear as I'd like - using "compromise language" based on comment from NNikolic intended to balance clarity with pragmatism).

### CODE REVIEW

**Comment by Jak-MS** [comment]
@vladai78 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by kendra-little** [comment]
I don't think expecting storage performance for a database transaction log to respond in faster than 60 seconds is unreasonable. 
Sincerely,
Reasonable customer who can read these public comments

**Comment by cbenkler** [comment]
Hi Kendra,

I can understand how you would think that I was referring to you given that you don't have context of all the conversations regarding this change. I was not referring to you nor was I referring to any customer in particular, but rather the general notion of "if we use language _____ that opens the door for an unreasonable customer..." which was a part of some of those discussions. Your support ticket was certainly a catalyst for the change, but once decided to make the change there must be very broad-scope consideration. It wasn't about you.

Regardless, thank you for raising - I agree that I should have chosen my words more carefully.

**Comment by rwestMSFT** [comment]
This PR will be closed automatically when the internal PR is merged.

**Pull request closed without merging**
