### PR TITLE
Typo "**@failover_mode=**"→"**\@failover_mode=**"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
bold with escape characters

https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-setreplfailovermode-transact-sql?view=sql-server-2017

### CODE REVIEW

**Comment by PRMerger8** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Verified the update.

@hyoshioka0128 Thanks for submitting the fix.

**Pull request merged**
