### PR TITLE
Update SSIS 2019 for Linux doc

### PR DESCRIPTION
**Pull request by yidetu**
Update SSIS 2019 for Linux doc with right repository

### CODE REVIEW

**Comment by yidetu** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@yidetu: I'm sorry - only the author of this article, @lrtoyou1223, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ShannonLeavitt** [comment]
Hello @rothja - Would you review the proposed updates and indicate whether the PR can be merged? Thanks!

**Comment by PRMerger9** [comment]
@yidetu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@yidetu Thank you for catching this and letting us know. However, I think we have a bigger change to make here, because the article needs to work for both 2017 and 2019 content based on the version selector on docs. The easiest way is to just instruct the user to first install SQL Server. Based on their version, they would have configured the appropriate repo. I'm going to add some suggestions for this change to your PR and you can accept them and still remain the contributor on this request. Thank you! @Vanmsft FYI

**Comment by PRMerger16** [comment]
@yidetu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by yidetu** [comment]
Jason, thanks for reviewing the change. I didn't aware that this doc is for both versions.
You suggested change is not ideal.  Install SQL engine for Linux is not a prerequisite of install SSIS. So it's not reasonable to put install SQL Server as first step.
I've updated the doc with a moniker switch. Please help to take a look.

**Comment by rothja** [comment]
@yidetu Your change looks good. But I suggest adding one moniker to the 2019 condition in case the user selects "all versions" in the filter list. In that case, I think showing the 2019 example makes sense rather than both lines which would be potentially confusing:

```
::: moniker range="= sql-server-linux-2019 || = sql-server-2019 || = sqlallproducts-allversions"
```

Can you make that change to both 2019 sections? Then I think this is great. Thank you!

**Comment by PRMerger14** [comment]
@yidetu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by yidetu** [comment]
Thanks for the suggestion, updated.

**Comment by rothja** [comment]
@yidetu Perfect. Thanks for patiently working with me through this. #sign-off @vanmsft FYI.

**Comment by PRMerger15** [comment]
@rothja: I'm sorry - only the author of this article, @lrtoyou1223, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
@rothja @yidetu Jason & Yide, there is no such Versioning moniker named 'sql-server-2019', thus PR **13294** in the public repo 'sql-docs-pr' has failed.

You must mean moniker 'sql-server-ver15' (as in SELECT \@\@VERSION returns a value of "15.whatever".

**Comment by yidetu** [comment]
I've updated to "::: moniker range=">= sql-server-linux-ver15 || >= sql-server-ver15 || =sqlallproducts-allversions"", thanks Gene.

**Comment by rothja** [comment]
@MightyPen I'm sorry I didn't catch that when reviewing.

**Pull request merged**
