### PR TITLE
Create powershell-extension.md

### PR DESCRIPTION
**Pull request by SQLvariant**
Adding documentation for the PowerShell extension so that it is available in the Docs site.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@SQLvariant : Thanks for your contribution! The author, @aanelson, has been notified to review your proposed change.

**Comment by yualan** [comment]
@stevestein  we would like to get Aaron's page included under extensions in Azure Data Studio docs. Are there additional things Aaron should consider?

We can take this change for master as it's not behind a release flag. You can treat this separately from the in-flight pr set for tomorrow

**Comment by Jak-MS** [comment]
Hi @SQLvariant , @yualan and @stevestein - can you submit this to the private repo so we can use the staging and validation tools there? 

Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master). 

We'll close this PR. Thank you.

**Comment by SQLvariant** [comment]
> Hi @SQLvariant , @yualan and @stevestein - can you submit this to the private repo so we can use the staging and validation tools there?
> 
Already done.

**Pull request closed without merging**
