### PR TITLE
Updated int, bigint, smallint, and tinyint (Transact-SQL) page

### PR DESCRIPTION
**Pull request by LHuss**
"MyIntColumn" in Examples section to properly reflect the largest possible integer

Previous value was 214483647 instead of 2147483647

### CODE REVIEW

**Comment by craigg-msft** [comment]
@LHuss thank you for the content contribution.

**Comment by craigg-msft** [comment]
@BYHAM please review

**Comment by BYHAM** [comment]
#sign-off

**Comment by craigg-msft** [comment]
Thank you @BYHAM and @LHuss

**Pull request merged**
