### PR TITLE
Fix technical inaccuracies in DBCC CHECKIDENT doc

### PR DESCRIPTION
**Pull request by srutzky**
1. No rows due to `DELETE` statement behaves the same as if rows are present
1. No behavior difference between various versions of SQL Server (I have tested on SQL Server 2005, 2008 R2, 2012, 2017, and 2019 CTP 2.2)
1. Fixed typo in example C: "increment" was used instead of "identity"

For full details and example code as proof, please see:

[How Does DBCC CHECKIDENT Really Work When Resetting the Identity Seed (RESEED)?](https://sqlquantumleap.com/2019/01/31/how-does-dbcc-checkident-really-work-when-resetting-the-identity-seed-reseed/)

( https://sqlquantumleap.com/2019/01/31/how-does-dbcc-checkident-really-work-when-resetting-the-identity-seed-reseed/ )

### CODE REVIEW

**Comment by PRMerger20** [comment]
@srutzky : Thanks for your contribution! The author, @uc-msft, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@srutzky : Thanks for your contribution! The author, @uc-msft, has been notified to review your proposed change.

**Comment by srutzky** [comment]
I did not realize that there were merge conflicts. Those have now been resolved.

**Comment by Jak-MS** [comment]
@uc-msft - can you take a look at these submitted changes? thanks.

**Comment by MashaMSFT** [comment]
Hi @srutzky , thank you so much for your contribution, and sorry for the long delay! Your corrections are accurate, thanks for noticing and improving it :) #sign-off

**Comment by PRMerger15** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @uc-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
