### PR TITLE
Update dbcc-shrinkdatabase-transact-sql.md

### PR DESCRIPTION
**Pull request by hdharshana**
Modified the syntax for WAIT_AT_LOW_PRIORITY

### CODE REVIEW

**Comment by jborsecnik** [comment]
@WilliamDAssafMSFT, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@hdharshana It's not clear whether this PR, or #8317, is the correct edit.

Please let me or @WilliamDAssafMSFT know which one is the correct version.

**Review by WilliamDAssafMSFT — APPROVED** [review]

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Comment by WilliamDAssafMSFT** [comment]
Bringing this PR from the public PR into the private repo, where it needs to be.

**Pull request closed without merging**
