### PR TITLE
Updated code examples

### PR DESCRIPTION
**Pull request by hristochr**
Updated code examples with column names from AdventureWorks2012 database.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@hristochr : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@hristochr Thank you for your efforts to bring this article up to date. The real problem, however, is that the article says "AdventureWorks" when in fact the DimEmployee table is in the AdventureWorksDW (or in this case, the AdventureWorksDW2012) database. Since the DimEmployee table still exists, we prefer to fix the original error, instead of changing the tables and fields. I will create a separate PR for this and let you know. Then I will ask you to close this PR.

**Comment by douglaslMS** [comment]
Chris, Today I fixed this issue by changing all occurrences of "Uses AdventureWorks" in this article to "Uses AdventureWorksDW," since that's the database in which the DimEmployee table lives. The updated page will be published later today. After you review the changes, please close this PR. Thank you for bringing this to our attention!

**Comment by douglaslMS** [comment]
@hristochr Please close this PR after you review the changes that I made and published in a separate PR. 

[WHERE (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/queries/where-transact-sql?view=sql-server-2017)

**Comment by craigg-msft** [comment]
closing.  thank you

**Pull request closed without merging**
