### PR TITLE
Update download-odbc-driver-for-sql-server.md

### PR DESCRIPTION
**Pull request by krishnamsft20**
Version number is wrong. It should be 18.2.2.1

### CODE REVIEW

**Comment by Jak-MS** [comment]
@David-Engel 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by krishnamsft20** [comment]
Sorry for making a mistake on my correction.

What I found was the link for 18.3.1.1 ended up installing 18.2.2.1. I think we need to clarify this or update link.

Thank you,


Krishna Bhurtel
SUPPORT ENGINEER
Office: +1 (469) 7750067
***@***.******@***.***>
9 AM - 6 PM CST
Manager: Mike Mitchell
***@***.******@***.***>
[Microsoft]

**Comment by David-Engel** [comment]
> What I found was the link for 18.3.1.1 ended up installing 18.2.2.1. I think we need to clarify this or update link.

@krishnamsft20 Are you sure? I just used the download link from this page, [Download Microsoft ODBC Driver 18 for SQL Server (x64)](https://go.microsoft.com/fwlink/?linkid=2242886) and installed 18.3.1.1.

Are you viewing the English version of the page? Perhaps one of the non-English pages has an issue?

Relatedly, I do see an incorrect version right above the link that I will fix:
> Version ~~18.2.1.1~~ 18.3.1.1 is the latest general availability (GA) version. The Microsoft ODBC Driver 18 for SQL Server can be installed side by side with Microsoft ODBC Driver 17 for SQL Server.

**Comment by krishnamsft20** [comment]
You are correct. I installed it on another computer and it did install 18.3.1.1

Thank you,

Krishna Bhurtel
SUPPORT ENGINEER
Office: +1 (469) 7750067
***@***.******@***.***>
9 AM - 6 PM CST
Manager: Mike Mitchell
***@***.******@***.***>
[Microsoft]

**Comment by David-Engel** [comment]
#please-close

**Pull request closed without merging**
