### PR TITLE
Update sys-availability-replicas-transact-sql.md

### PR DESCRIPTION
**Pull request by zhang-z**
Current doc says: 0 is manual failover, 1 is automatic failover. But I queried from my SQL 2016 server, it returns opposite result:
```
failover_mode  failover_mode_desc
0              AUTOMATIC
```

And I saw several lines in source code "\SQL16\Sql\Ntdbms\scripts\usa\metaview.sql":
```
failover_mode = wr.failover_mode,
failover_mode_desc = CASE
  WHEN (wr.failover_mode = 0) THEN CAST('AUTOMATIC' AS nvarchar(60))
  WHEN (wr.failover_mode = 1) THEN CAST('MANUAL' AS nvarchar(60))
  ELSE CAST (NULL as nvarchar(60))
  END,
```
So I think it's the doc that needs correction.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@zhang-z : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@zhang-z - thank you again for this submission. Reviews are a little delayed while everyone comes back from holiday. Thanks for your patience.

**Comment by MikeRayMSFT** [comment]
After review, it appears that this change is not correct. #please-close

**Comment by zhang-z** [comment]
@MikeRayMSFT , could you give more details about why you think this change is not correct? When I queried my SQL 2016, the result showed as:

failover_mode  failover_mode_desc
0              AUTOMATIC

**Comment by MikeRayMSFT** [comment]
@zhang-z - upon further review, we realize that your submission is precisely correct. We are thankful for your submission, and your follow up question. We appreciate the detail in your submission.

Thanks for helping us improve our documentation.

**Comment by ktoliver** [comment]
@MikeRayMSFT - Is the pull request ready to merge? Thanks.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
