### PR TITLE
Update sql-database-project-extension.md

### PR DESCRIPTION
**Pull request by ryoma-nagata**
typo
[!VIDEOhttps://channel9.msdn.com/Shows/Data-Exposed/Build-SQL-Database-Projects-Easily-in-Azure-Data-Studio/player?WT.mc_id=dataexposed-c9-niner]
->[!VIDEO](https://channel9.msdn.com/Shows/Data-Exposed/Build-SQL-Database-Projects-Easily-in-Azure-Data-Studio/player?WT.mc_id=dataexposed-c9-niner)

### CODE REVIEW

**Comment by PRMerger6** [comment]
@ryoma-nagata : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dzsquared** [comment]
thank you, @ryoma-nagata!

**Review by dzsquared — APPROVED** [review]

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Per the contributor guide, the correct syntax is: 

image

I've updated the PR and will merge it. Thanks!

**Pull request merged**
