### PR TITLE
Update isjson-transact-sql.md

### PR DESCRIPTION
**Pull request by JoeEdwardsGitHub**
Clearly my comment is not to be published, I am just highlighting that the note appears no longer to be valid. Please can this be verified and the note removed.

### CODE REVIEW

**Comment by Court72** [comment]
@uc-msft 

Can you review the question in https://github.com/MicrosoftDocs/sql-docs/pull/8164#issue-1402434868? 

If you make changes that you want to be published, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MikeRayMSFT** [comment]
Confirming with @chuckheinzelman

**Comment by MikeRayMSFT** [comment]
Still following up. Re-sent request for review.

**Comment by MikeRayMSFT** [comment]
Hi Joe, Thanks for the submission. At this moment we won't be publishing the update. See: 

image


#please-close

**Comment by JoeEdwardsGitHub** [comment]
@MikeRayMSFT, I just retested it and it works fine. I should clarify that I am using a Serverless pool. Perhaps you tried in a dedicated pool and the behaviour is different?

image

**Comment by MikeRayMSFT** [comment]
Thanks.

**Comment by mstehrani** [comment]
Thanks @JoeEdwardsGitHub, we've updated the note in documentation that it is not supported in *Dedicated pools. It should reflect publicly within a few days. Closing this issue now, thank you.

**Comment by mstehrani** [comment]
#please-close

**Pull request closed without merging**
