### PR TITLE
Typos database

### PR DESCRIPTION
**Pull request by MikeyBronowski**
- fixed typos in *database*
- added *sql* formatting to blocks of T-SQL code 
- added *;* at the end of the T-SQL command

### CODE REVIEW

**Comment by PRMerger14** [comment]
@MikeyBronowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@rothja Would you be able to either review the PR or collect the approvals that are needed? Thanks.

**Comment by rothja** [comment]
@MikeyBronowski These changes look like good improvements. Thanks for taking the time to make them. #sign-off

**Comment by PRMerger19** [comment]
@rothja: I'm sorry - only the author of this article, @swinarko, @MashaMSFT, @jaszymas, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
