### PR TITLE
Setting the ASDW flag correctly.

### PR DESCRIPTION
**Pull request by TwoUnder**
This function is not yet supported in Azure SQL Data Warehouse/Azure Synapse Analytics.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@TwoUnder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TwoUnder** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@TwoUnder: I'm sorry - only the author of this article, @rothja, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by TwoUnder** [comment]
Wrong branch.

**Pull request closed without merging**
