### PR TITLE
Update restore-statements-transact-sql.md

### PR DESCRIPTION
**Pull request by amtwo**
Statement about clearing cache implies the entire cache gets cleared, but this is not accurate. The cache is only *partially* cleared. Only the database being replaced by the restore has it's cache cleared.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@amtwo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@bluefooted - can you review?

**Comment by bluefooted** [comment]
Thanks for the heads-up! @amtwo is correct in that only the plan cache for the database is cleared, but the entire paragraph needs reworking. We don't actually throw that error when you restore a database since we're not clearing the entire plan cache. I think we should remove everything except the first two sentences. @MikeRayMSFT can we do that directly in this PR or should we accept this one and then file a new PR in the private repo?

**Comment by amtwo** [comment]
@MikeRayMSFT I'm happy to make another commit under this PR with the added change @bluefooted suggests, if that's easiest. Let me know what you prefer.

**Comment by PRMerger19** [comment]
@amtwo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by amtwo** [comment]
I pushed the additional change @bluefooted suggested to remove those additional sentences

**Comment by bluefooted** [comment]
Looks good to me @amtwo thank you! @MikeRayMSFT this is good to go.

**Comment by bluefooted** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@bluefooted: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jborsecnik** [comment]
@MikeRayMSFT, ok to merge?

**Pull request merged**
