### PR TITLE
Update use-sql-server-connector-with-sql-encryption-features.md

### PR DESCRIPTION
**Pull request by pefaro**
Clean up the instuctions regarding to creating the SECRET

### CODE REVIEW

**Comment by PRMerger14** [comment]
@pefaro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @pefaro! Thanks for suggesting these changes. I'll approve them.

#sign-off

**Comment by PRMerger20** [comment]
@VanMSFT: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
