### PR TITLE
Clarification of Data/Log file Englightment

### PR DESCRIPTION
**Pull request by PiJoCoder**
The file enlightment is the mechanism to copy the data from the PMEM device to RAM. It is not the mechanism to directly access the pages in the PMEM device. Those are accessed directly via a pointer. This is based on a presentation by the PG developer

### CODE REVIEW

**Comment by PRMerger17** [comment]
@PiJoCoder : Thanks for your contribution! The author, @DBArgenis, has been notified to review your proposed change.

**Review by briancarrig — APPROVED** [review]

**Comment by PRMerger14** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
fixed merge conflict. thanks for your contribution Joseph! #sign-off

**Comment by PRMerger14** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @DBArgenis, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by DBArgenis** [comment]
Can we please hand off ownership of this article to @briancarrig? I shouldn't have to approve his edits - as the PM he's the authority on the subject :) cc/ @MashaMSFT

**Pull request merged**
