### PR TITLE
Update primary-and-foreign-key-constraints.md

### PR DESCRIPTION
**Pull request by JinnaF**
extra "that"

### CODE REVIEW

**Comment by PRMerger3** [comment]
@JinnaF : Thanks for your contribution to the SQL documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@edmacauley  please review.

**Comment by edmacauley** [comment]
Thanks for catching that that mistake! ;)  #sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by craigg-msft** [comment]
Thank you @JinnaF and @edmacauley merging.

**Pull request merged**
