### PR TITLE
Fixed array out of bounds exception

### PR DESCRIPTION
**Pull request by DeanBecker**
One line change fixing an out of bounds array access issue.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@DeanBecker : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by TrishaMc** [comment]
@craigg-msft: Please confirm that this PR is ready for merge. Thank you.

**Comment by craigg-msft** [comment]
assigned to @MashaMSFT to investigate after the holidays. @DeanBecker I was only able to take a quick / scan, can you please provide a little detail on why you made the change?  Thank you for your time.

**Comment by DeanBecker** [comment]
@craigg-msft Scanning through the documentation and I saw this as an out of bounds access: the array initialisation is in the line above the access, the array is initialised with length of 1 and the immediate access is trying to access position 2 (1 in a zero-based index).

Isolated code before which throws an exception: https://dotnetfiddle.net/UHoHW0
Code after, which executes: https://dotnetfiddle.net/cuGZSz

**Comment by MashaMSFT** [comment]
Hi @DeanBecker , thanks for your contribution! Sorry for the delay, I'm still investigating this. Thanks!

**Comment by MashaMSFT** [comment]
Hi @DeanBecker , thanks again for your contribution! This seems correct. #sign-off

**Comment by PRMerger15** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
