### PR TITLE
Update integration-services-ssis-in-a-cluster.md

### PR DESCRIPTION
**Pull request by baleng**
just to be clearer

### CODE REVIEW

**Comment by PRMerger20** [comment]
@baleng : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@chugugrace 

Could you review the proposed changes to your article?

Thanks!

**Comment by ktoliver** [comment]
@MightyPen - Would you be able to review the proposed update? Thanks.

**Comment by MightyPen** [comment]
#sign-off

@ktoliver

**Comment by PRMerger9** [comment]
@MightyPen: I'm sorry - only the author of this article, @chugugrace, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Thanks @MightyPen

**Pull request merged**
