### PR TITLE
two new columns, wrong version availability.

### PR DESCRIPTION
**Pull request by PawJershauge**
The columns **is_inlineable** and **inline_type** are NOT available from SQL version 2017 (14.x), they are first available from SQL version 2019 (15.x)

I have also requested the Creation of sssql19-md.md, so we can [include].

### CODE REVIEW

**Comment by PRMerger8** [comment]
@PawJershauge : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by stevestein** [comment]
#sign-off

**Comment by stevestein** [comment]
@PawJershauge - Thanks for catching and updating this!

**Comment by PawJershauge** [comment]
Your welcome.

**Pull request merged**
