### PR TITLE
Call out data type for values

### PR DESCRIPTION
**Pull request by way0utwest**
data type of value must match

### CODE REVIEW

**Comment by PRMerger14** [comment]
@way0utwest : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
@way0utwest - Thanks, Steve!

@rohitnayakmsft - Another to verify. Thanks!

**Comment by ktoliver** [comment]
@rohitnayakmsft Could you review this pull request? Thanks!

**Comment by rohitnayakmsft** [comment]
#sign-off

**Comment by PRMerger5** [comment]
@rohitnayakmsft: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
