### PR TITLE
bdc subcommnad was missing in few places

### PR DESCRIPTION
**Pull request by rl-msft**
bdc subcommnad was missing in few places also correcting URL http://jmespath.org/ , it had extra ']' character

### CODE REVIEW

**Comment by PRMerger20** [comment]
@rl-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by jborsecnik** [comment]
Note: The link at the last change doesn't work for me. Should it? Thanks.

**Comment by rl-msft** [comment]
@jborsecnik  the link should be 

http://jmespath.org/

which is working for me

**Comment by jborsecnik** [comment]
Thanks.

**Pull request merged**
