### PR TITLE
link Microsoft Container Registry official announcement

### PR DESCRIPTION
**Pull request by fowl2**
Thought it might be better to use an Microsoft website for the link.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@fowl2 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Admin note: If the PR is approved, the locale should be removed from the microsoft.com URL before merging. The PR review team can do this.

**Comment by PRMerger12** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @fowl2! I'll approve this. Thank you so much for helping us with our documentation!

#sign-off

**Pull request merged**
