### PR TITLE
Update Apache configuration for PHP 7.3

### PR DESCRIPTION
**Pull request by faustog94**
The line for installing libapache was outdated and that makes installing php 7.2 packages. I just changed it to php 7.3.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@faustog94 : Thanks for your contribution! The author, @ulvii, has been notified to review your proposed change.

**Comment by ulvii** [comment]
@yitam, @david-puglielli, please take a look

**Comment by MightyPen** [comment]
@GitHubber17 Hi Beth, I do not understand the status of this aging PR 1946?
Jenny Tam ( @yitam ) "approved" this PR in April 17, as a formal Reviewer, but.....
_What should Jenny do next,. or whomever, to get this PR Merged?_

Thanks.  GeneMi

**Comment by GitHubber17** [comment]
@mightypen @yitam - We apologize for this oversight. We'll merge the PR now. Thank you for alerting the review team.

**Pull request merged**
