### PR TITLE
Added link to feature matrix for unsupported features

### PR DESCRIPTION
**Pull request by simonsabin**
Finding unsupported features is not obvious the matrix doesn't come up in search results

### CODE REVIEW

**Comment by PRMerger7** [comment]
@simonsabin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@simonsabin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MikeRayMSFT — APPROVED** [review]

**Comment by MikeRayMSFT** [comment]
Thanks, @simonsabin #sign-off

**Comment by PRMerger7** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @David-Engel, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
