### PR TITLE
Updated JSON intro page

### PR DESCRIPTION
**Pull request by jovanpop-msft**
Addressed some comments from visitors

### CODE REVIEW

**Comment by jovanpop-msft** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@jovanpop-msft: I'm sorry - only the author of this article, @douglaslMS, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger18** [comment]
@jovanpop-msft : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
#sign-off

**Pull request merged**
