### PR TITLE
Update datetime-transact-sql.md

### PR DESCRIPTION
**Pull request by kscale**
fix error

### CODE REVIEW

**Comment by PRMerger16** [comment]
@kscale : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by MikeRayMSFT** [comment]
Investigating. The behavior appears different depending on the locale ID. Verifying.

**Comment by MikeRayMSFT** [comment]
@kscale  - thank you for the submission, datetime functions differently, depending on the locale of the instance of SQL Server. For some cases, the example works as written, so we will not publish the proposed update. 

Pease use these alternative data types:

See this note from the article:

> [!NOTE]  
>  Use the **time**, **date**, **datetime2** and **datetimeoffset** data types for new work. These types align with the SQL Standard. They are more portable. **time**, **datetime2** and **datetimeoffset** provide more seconds precision. **datetimeoffset** provides time zone support for globally deployed applications.

**Comment by MikeRayMSFT** [comment]
#please-close

**Comment by MikeRayMSFT** [comment]
We have an internal updating being reviewed to clarify the sample for the international audience: https://github.com/MicrosoftDocs/sql-docs-pr/pull/21392

**Pull request closed without merging**
