### PR TITLE
Update set-parseonly-transact-sql.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
Noted that "set parseonly" is not conditional.

### CODE REVIEW

**Comment by Court72** [comment]
@WilliamDAssafMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Hi @DanielAdeniji I'm having trouble understanding the use case or value add of this addition on top of Line 45, `The setting of SET PARSEONLY is set at parse time and not at execute or run time.` Can you provide more detail on why this is necessary?

**Comment by DanielAdeniji** [comment]
William:-

Attached SQL.

Spoken of here.

https://learningintheopen.org/2023/03/23/transact-sql-set-commands-set-parseonly-on/

Link<https://learningintheopen.org/2023/03/23/transact-sql-set-commands-set-parseonly-on/>

I was trying to skip running a SQL if a database is missing.

And, was evaluating raiserror and throw statements.

Saw that if the system sees "set parseonly on", even when it is within a no-op such ( 1=0), the script will not still stumble.

So it is me trying to raise awareness that whenever "set parseonly on" is seen, it is the end of the story.

Thank you for your care,

Daniel
________________________________

**Comment by rwestMSFT** [comment]
I'm closing this PR, because the article already sufficiently explains this. Thanks for your contribution, @DanielAdeniji.

**Pull request closed without merging**
