### PR TITLE
Update create-availability-group-transact-sql.md

### PR DESCRIPTION
**Pull request by asavioliMSFT**
The note below for the REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT is a little bit misleading and can make us think it is only possible to change this configuration, using the ALTER AVAILABILITY GROUP, on SQL 2022, when actually what changed on 2022 is that we are able to set it for a distributed availability groups. Changing this option with the ALTER statement is possible since SQL 2017

"
Not supported for CREATE AVAILABILITY GROUP. However, beginning with SQL Server 2022 (16.x), you can use ALTER AVAILABILITY GROUP to set REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT "

### CODE REVIEW

**Comment by Court72** [comment]
@mikeraymsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MikeRayMSFT** [comment]
Thank you @kfarlee or @tarynpratt - please confirm?
#assign-reviewer: @tarynpratt

**Comment by MikeRayMSFT** [comment]
#assign-reviewer: #kfarlee

**Comment by kfarlee** [comment]
#sign-off

**Comment by MikeRayMSFT** [comment]
#sign-off

**Review by MikeRayMSFT — APPROVED** [review]

**Pull request merged**
