### PR TITLE
Update durability-for-memory-optimized-tables.md

### PR DESCRIPTION
**Pull request by sidesw1pe**
Fixed another typo. Sorry not sure how to update original pull request.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@sidesw1pe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by markingmyname — APPROVED** [review]
Fixed conflict.

**Comment by markingmyname** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @sidesw1pe - Could you take a moment to sign the Contributor License Agreement (CLA)? Resolving a merge conflict moved the pull request over the threshold for requiring the PR creator to sign one. Select the "sign now" link in this comment: 

image


Thanks!

**Comment by ktoliver** [comment]
> Fixed another typo. Sorry not sure how to update original pull request.

For next time: 

1. At the top of the pull request, select **Files changed**.

   image

1. On the right side of the article header, select the three dots, and then select **Edit file**.

   image

**Comment by PRMerger10** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@sidesw1pe Thanks!

**Pull request merged**
