### PR TITLE
Update lesson-5-1-copying-the-lesson-4-package.md

### PR DESCRIPTION
**Pull request by weiplanet**
Typos on Step #4 and Step #5

### CODE REVIEW

**Comment by PRMerger6** [comment]
@weiplanet : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger5** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @chugugrace, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
