### PR TITLE
Make the description of last_commit column more clear

### PR DESCRIPTION
**Pull request by btasdoven**
We have had few CRIs and questions regarding the exact meaning of last_commit time on the primary database. It seems from the documantation that the explanation is not clear.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@btasdoven : Thanks for your contribution to the SQL documentation! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by CarlRabeler** [comment]
@craigg-msft 
I am the author - why the comment above?

**Comment by craigg-msft** [comment]
Thank you @btasdoven and @CarlRabeler . merging.

**Pull request merged**
