### PR TITLE
Update azure-sql-python-quickstart.md

### PR DESCRIPTION
**Pull request by Oury-MSFT**
remove word install before pydantic

### CODE REVIEW

**Comment by Court72** [comment]
@bobtabor-msft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Oury-MSFT** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@Oury-MSFT 
PRMerger will only accept sign off from the listed 'author'. However, if you are a Microsoft employee authorized to update this content, you can send a request to [techdocprs@microsoft.com](mailto:techdocprs@microsoft.com) for this PR to be merged.  Include your role, and an explanation of why the PR should be merged without approval from the listed author.

**Comment by rwestMSFT** [comment]
Checking with @David-Engel to see if we can just merge this.

**Comment by rwestMSFT** [comment]
Closed as duplicate of https://github.com/MicrosoftDocs/sql-docs/pull/9273.

**Pull request closed without merging**
