### PR TITLE
Add links to new JDBC Driver 7.4 for SQL Server.

### PR DESCRIPTION
**Pull request by glancyd**
Add links to new JDBC Driver 7.4 for SQL Server.

Update sample pom.xml file to reflect updated version.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@glancyd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@danimir Hi, You still need to enter `#sign-off` (8 characters) into this Pull Request 2666, for it to proceed to eventually go live on Docs.

**Comment by rjagiewich** [comment]
@MightyPen - Would you [add a hash comment](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-automation?branch=master) like `#sign-off` to indicate the action to take on this PR?  Thanks.

**Comment by MightyPen** [comment]
@rjagiewich Hi Rebecca, the creator of this public repo PR 2666 has chosen to Close it, instead of merging it.

I am unsure whether @glancyd knows about what Closing vs # sign - off all mean, but I have no reason to doubt that "Dave" knows.
So I will not do anything further to affect this PR.
Thanks (GeneMi)

cc: @glancyd

**Pull request closed without merging**
