### PR TITLE
Update sql-server-backup-to-url.md

### PR DESCRIPTION
**Pull request by Hemin-MSFT**
Supported format for Credential Name: [Storage Account URL]/[Container] Container path with folders is not supported at this point.

As that will require to create Credential with Name: [Storage Account URL]/[Container Account]/[Folder] and that leads to caching issues after SQL Service restart because of how Credential name is parsed.

### CODE REVIEW

**Comment by WilliamDAssafMSFT** [comment]
Thanks @hemin-msft for taking the time to make this edit to the BACKUP TO URL content. 
Adding @HugoMSFT to review.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Hemin-MSFT** [comment]
Hello, any update on this PR?

**Comment by Court72** [comment]
> Thanks @Hemin-MSFT for taking the time to make this edit to the BACKUP TO URL content. Adding @HugoMSFT to review.

@HugoMSFT 
Have you gotten a chance to review the changes in this PR? Thanks!

**Comment by HugoMSFT** [comment]
> > Thanks @Hemin-MSFT for taking the time to make this edit to the BACKUP TO URL content. Adding @HugoMSFT to review.
> 
> @HugoMSFT Have you gotten a chance to review the changes in this PR? Thanks!

Adding @SudhirRaparla to the conversation since he's overseeing backup to URL, I'm the PM responsible for S3.

**Comment by Hemin-MSFT** [comment]
Hello all, any update on this PR?

**Comment by SudhirRaparla** [comment]
@Hemin-MSFT - We are reviewing this PR. will reach out to you to get more information on the reason behind this change.

**Comment by WilliamDAssafMSFT** [comment]
Per @hemin-MSFT and @SudhirRaparla holding off on this.

**Pull request closed without merging**
