### PR TITLE
Using a real table in the Indexed Views verboten feature list

### PR DESCRIPTION
**Pull request by daiplusplus**
The current table under the "The SELECT statement in the view definition must not contain the following Transact-SQL elements:" bullet  is not a real table without any logical ordering or grouping which makes it hard to read.

This PR changes it to 3 separate tables: to keep functions separate from language elements and source column restrictions, and the middle table now groups language elements by their parent `SELECT` sub-clause. I feel this is much more readable - and it adds possible suggestions for alternative approaches - and makes it clear that while `COUNT` cannot be used, we can still use `COUNT_BIG`, which isn't immediately clear when reading the article as-is.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@WilliamDAssafMSFT 
- Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @jehoel for contacting Microsoft with feedback about our product documentation. It could take a few weeks to confirm your change internally. This one will take some testing as we're adding helpful technical guidance where none existed before. In particular, further detail I believe is needed for mathematical functions like STDEV and AVG that are deterministic when used without the OVER or ORDER BY clauses. This detail is helpful and a good addition to the Docs.

 You can continue to make updates here as desired. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

By opening a pull request, you're helping the author add your approved change directly to the documentation. If the article is updated with your commit, GitHub will list you as an article contributor.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @daiplusplus for making these recommendations, this article did need some attention. In progress with some updates.

**Comment by WilliamDAssafMSFT** [comment]
Ready for review. Would like my colleague @rwestMSFT to take a look before we merge.

**Review by rwestMSFT — APPROVED** [review]

**Comment by WilliamDAssafMSFT** [comment]
Reviews are in, and this PR is a winner. @daiplusplus looks like our system is prompting a CLA, please confirm so we can publish.

**Comment by rwestMSFT** [comment]
Because of the merge conflict, I'm closing this and recreating it internally, with @daiplusplus's suggested changes.

#please-close

**Pull request closed without merging**
