### PR TITLE
Added linux support information for SQL Managed Database backups

### PR DESCRIPTION
**Pull request by cyberprune**
Added linux support information for SQL Managed Database backups. The feature is only supported in Windows. See reference at https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2022?view=sql-server-ver16#unsupported-features-and-services

### CODE REVIEW

**Comment by cyberprune** [comment]
Resolves #9121

**Comment by ShannonLeavitt** [comment]
@MashaMSFT 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by cyberprune** [comment]
#sign-off - whoops, this wasn't meant for me

**Comment by MashaMSFT** [comment]
Hi @cyberprune , thanks for your submission! For a bit more clarity, rather than specifying Linux supportability in the limitations section, we're updating the Applies To to indicate this article is applicable to Windows only. This change will be live either this week or next. I'll go ahead and close this PR but please feel free to comment should you need anything further, and please continue helping improve our documentation! 

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Pull request closed without merging**
