### PR TITLE
Resolve syncing conflicts from FromPrivateRepo to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from FromPrivateRepo to live.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@huypub : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@huypub : Thanks for your contribution! The author, @HJToland3, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@huypub : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by HJToland3** [comment]
@huypub - Can you help clarify for me the specific changes that I am being asked to review?

**Comment by huypub** [comment]
@HJToland3 
It should be due to i merged the PR : https://github.com/MicrosoftDocs/sql-docs-pr/pull/7839.

**Comment by MightyPen** [comment]
@MikeRayMSFT , @rothja
PRs 7844 & 7827, in the private repo 'sql-docs-pr', will likely make these minor Conflicts go away the next time that the Private repo is merged into the Public repo (nightly merges, I think).

**Comment by PRMerger14** [comment]
@huypub : Thanks for your contribution! The author, @jejiang, has been notified to review your proposed change.

**Pull request merged**
