### PR TITLE
Update sys-master-files-transact-sql.md

### PR DESCRIPTION
**Pull request by VladDBA**
Hello SQL Server Docs Team,

From what I've seen and tested, max_size cannot be set to 0.
The combination of values for a file to not be allowed to grow is max_size = -1 and growth = 0.

Testing:
```SQL
/*Create a test database*/
CREATE DATABASE [FileConfigTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileConfigTest', FILENAME = N'E:\VSQL\Data\FileConfigTest.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FileConfigTest_log', FILENAME = N'E:\VSQL\TLog\FileConfigTest_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
```

Check the files and validate current size, max_size, and growth.
```SQL
SELECT DB_NAME(database_id) AS db,
       [name],
       [type_desc],
       size,
       size * 8 AS sizeKB,
       max_size,
       growth,
       growth * 8 AS growthKB
FROM   sys.master_files
WHERE  database_id = DB_ID(N'FileConfigTest');
```
image

Now I'll try and set max_size to 0.

```SQL
ALTER DATABASE [FileConfigTest] MODIFY FILE ( NAME = N'FileConfigTest', MAXSIZE = 0)
ALTER DATABASE [FileConfigTest] MODIFY FILE ( NAME = N'FileConfigTest', MAXSIZE = 0 , FILEGROWTH = 0 )
```
Both of these two commands fail with the same error message:
```
Msg 5040, Level 16, State 1, Line 26
MODIFY FILE failed. Size is greater than MAXSIZE.
```
At this point the data file remains unchanged.

This is a bit of a bonus, and I have no idea why it returns an error, I just tried it out because I was curious if I can set growth to 0 when max_size = size.
```SQL
ALTER DATABASE [FileConfigTest] MODIFY FILE ( NAME = N'FileConfigTest', MAXSIZE = 8192KB , FILEGROWTH = 0 )
```
And the error message is:
```
Msg 5169, Level 16, State 3, Line 31
FILEGROWTH cannot be greater than MAXSIZE for file 'FileConfigTest'.
```

It doesn't make much sense since `FILEGROWTH = 0` , but I digress from the point of this pull request.

Going back to my "max_size cannot be 0" test - the only way to set the file to not grow is to set  ` MAXSIZE = UNLIMITED` and `FILEGROWTH = 0`.
```SQL
ALTER DATABASE [FileConfigTest] MODIFY FILE ( NAME = N'FileConfigTest', MAXSIZE = UNLIMITED , FILEGROWTH = 0 )
```
This works and the result can be checked with the query used earlier.
image

And, at this point, I can re-run the command to set max_size = size (even max_size> size ) without any error.
```SQL
ALTER DATABASE [FileConfigTest] MODIFY FILE ( NAME = N'FileConfigTest', MAXSIZE = 8192KB , FILEGROWTH = 0 )
```
image

But I still cannot set max_size to 0.
```SQL
ALTER DATABASE [FileConfigTest] MODIFY FILE ( NAME = N'FileConfigTest', MAXSIZE = 0 , FILEGROWTH = 0 )
```
Error message:
```
Msg 5040, Level 16, State 1, Line 31
MODIFY FILE failed. Size is greater than MAXSIZE.
```

Test environment:
```
Microsoft SQL Server 2019 (RTM-CU22-GDR) (KB5029378) - 15.0.4326.1 (X64) 
	Aug 18 2023 14:05:15 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22621: )
```

Have a great weekend!

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rwestMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Thanks, @VladDBA! This article hasn't been refreshed in a while, and contained some other incorrect information, so I'll replace your PR with an internal one that takes your changes into account.

Once the internal PR is merged, this will automatically close, and you can expect the updated article to be published within the next business day.

We appreciate your ongoing contributions to improve our documentation.

**Comment by VladDBA** [comment]
Thanks, @rwestMSFT! Happy to help!

**Comment by rwestMSFT** [comment]
Update: still awaiting internal sign-off.

**Pull request closed without merging**
