### PR TITLE
Update drop-sensitivity-classification-transact-sql.md

### PR DESCRIPTION
**Pull request by C-Lion**
Corrects typos mentioned in https://github.com/MicrosoftDocs/feedback/issues/813

### CODE REVIEW

**Comment by PRMerger14** [comment]
@C-Lion : Thanks for your contribution! The author, @giladmit, has been notified to review your proposed change.

**Comment by s3cur17y15m34n1ngl355** [comment]
Thank you for the quick action! Happy to help.

**Comment by ktoliver** [comment]
Looks correct (update matches other uses in the file and repo); merging typo fixes

**Comment by C-Lion** [comment]
Awesome! Also glad to be of service.

**Pull request merged**
