### PR TITLE
Update deploy-on-aks.md

### PR DESCRIPTION
**Pull request by suresh-kandoth**
add reference to AKS troubleshooting article: https://docs.microsoft.com/en-us/azure/aks/troubleshooting

### CODE REVIEW

**Comment by PRMerger20** [comment]
@suresh-kandoth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ShannonLeavitt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@suresh-kandoth Thank you! I made a minor change to the link.

**Pull request merged**
