### PR TITLE
Wrong link to failover

### PR DESCRIPTION
**Pull request by BIGabor**
Wrong link for [Failover to a secondary availability group]. fixed

### CODE REVIEW

**Comment by ktoliver** [comment]
@MashaMSFT - Could you review the proposed change?

Thanks.

**Comment by PRMerger19** [comment]
@BIGabor : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @BIGabor , thank you so much for your contribution and for making our docs better! You are correct, this link should be updated. #sign-off

**Pull request merged**
