### PR TITLE
Adding version of image without png transparency

### PR DESCRIPTION
**Pull request by LowlyDBA**
Which will show properly on the doc site's dark theme, whereas right now it displays poorly.

### CODE REVIEW

**Comment by craigg-msft** [comment]
@markingmyname please review

**Comment by markingmyname** [comment]
@LowlyDBA May I ask what article are you referring to?

**Comment by LowlyDBA** [comment]
https://docs.microsoft.com/en-us/sql/reporting-services/reports/publishing-reports-to-a-report-server?view=sql-server-2017

**Comment by markingmyname** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@markingmyname: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by markingmyname** [comment]
@craigg-msft I am the author of this article, and yet it won't let me approve the sign-off.  Can i ask why, sir?

Thank you.

**Comment by tfosmark** [comment]
@markingmyname The file is an image, which means there's no metadata for PRMerger to query. In the future, you can email the PR review team if your approval is not accepted and we'll be glad to help.

Merging now.

**Pull request merged**
