### PR TITLE
Added missing [internal_type] and [internal_type_desc] values for "sys.internal_tables"

### PR DESCRIPTION
**Pull request by srutzky**
Found (and formatted) the missing items using the following query (executed in SQL Server 2019, CTP 2.3):

```sql
;WITH cte AS
(
    SELECT DISTINCT -- NOT IN list populated with IDs on current doc page
           IIF(tab.[internal_type] NOT IN (201, 202, 203, 205, 206, 207, 208, 209, 210, 236),
               '*',
               ' ') AS [Missing],
           tab.[internal_type],
           tab.[internal_type_desc]
    FROM  msdb.sys.internal_tables tab -- [msdb] has more internal table types than [master]
)
SELECT *,
       IIF(cte.[Missing] = '*',
           CONCAT(N'<br /><br /> ', cte.[internal_type], N' = **',
                          LOWER(REPLACE(cte.[internal_type_desc], N'_', N'\_')), N'**'),
           N'') AS [TypeFormattedForDoc],
       IIF(cte.[Missing] = '*',
           CONCAT(N'<br /><br /> ', REPLACE(cte.[internal_type_desc], N'_', N'\_')),
           N'') AS [TypeDescFormattedForDoc]
FROM   cte
ORDER BY cte.[internal_type];
```
which returned the following (first 3 columns only):

```
Missing     internal_type     internal_type_desc
*           3                 QUERY_DISK_STORE_QUERY_HINTS
*           4                 QUERY_DISK_STORE_QUERY_TEMPLATE_PARAMETERIZATION
*           6                 QUERY_DISK_STORE_WAIT_STATS
            201               QUEUE_MESSAGES
            208               FILESTREAM_TOMBSTONE
            210               TRACKED_COMMITTED_TRANSACTIONS
*           220               CONTAINED_FEATURES
*           225               FILETABLE_UPDATES
*           240               QUERY_DISK_STORE_QUERY_TEXT
*           241               QUERY_DISK_STORE_QUERY
*           242               QUERY_DISK_STORE_PLAN
*           243               QUERY_DISK_STORE_RUNTIME_STATS
*           244               QUERY_DISK_STORE_RUNTIME_STATS_INTERVAL
*           245               QUERY_CONTEXT_SETTINGS
```

Also properly escaped underscores in values (but just for these two table cells; I did not review the rest of the page for unescaped underscores).

### CODE REVIEW

**Comment by PRMerger8** [comment]
@srutzky : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@srutzky - thanks for updating this. We're not typically escaping underscores unless they're causing problems with rendering (for example, an underscore with whitespace to the left or right of it). 

If you can update so this PR only contains the missing types that would bve great.  

Thanks!

**Comment by srutzky** [comment]
@stevestein I can, but can't non-escaped underscores cause formatting problems? Doesn't that increase the chances of unexpected formatting by leaving it up to the parser? That's why I have been added them. But I can stop doing that if it's not necessary.

**Comment by stevestein** [comment]
If the formatting looks incorrect when viewing the file then escape the underscore, but if it renders ok we're leaving as is. So not necessary unless you actually see formatting issues.

**Comment by PRMerger14** [comment]
@srutzky : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by srutzky** [comment]
@stevestein The changes you requested have been made. Please review.

**Comment by stevestein** [comment]
@srutzky - looks good. Thanks for updating!

#sign-off

**Pull request merged**
