### PR TITLE
Attention for different collation between database and CDC table colum

### PR DESCRIPTION
**Pull request by suyouquan**
I am SQL Server support engineer and I worked with SQL server product team about the collation difference of database and column could data corruption in CDC, so I add one Attention section. please help add it into the article.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@suyouquan : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@suyouquan : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by suyouquan** [comment]
Perfect, thank you Rothja.

**Comment by rothja** [comment]
#sign-off

**Pull request merged**
