### PR TITLE
Add "See Also" links

### PR DESCRIPTION
**Pull request by JediSQL**
Add "See Also" links for SESSION_CONTEXT and sp_set_session_context.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@JediSQL : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, March 2. Merging will resume Tuesday. Authors can still review and sign off on PRs in the interim. Thanks.

**Comment by PRMerger7** [comment]
@WilliamDAssafMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Comment by WilliamDAssafMSFT** [comment]
Thanks @JediSQL for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 
    
By opening a pull request, you're helping the author add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor.

Thanks again, your suggestions help improve our documentation. A doc update is in flight. May the force be with you.

**Pull request merged**
