### PR TITLE
Clarify the RECOMPILE option

### PR DESCRIPTION
**Pull request by PiJoCoder**
there is a "private" plan created for each execution of a query when RECOMPILE is used. That plan is discarded immediately after execution and does not affect any plan already cached for this query if query was run with no hints.

### CODE REVIEW

**Comment by douglaslMS** [comment]
@PiJoCoder Joseph, the quotation marks around "private" cause a question or a problem at localization. Can you please remove the quotes? Also, is it possible that _temporary_ is a better word? Thanks.

**Comment by douglaslMS** [comment]
@PiJoCoder ping

**Comment by craigg-msft** [comment]
Thank you @PiJoCoder

**Comment by PiJoCoder** [comment]
Thanks Craig and Douglas

**Pull request merged**
