### PR TITLE
Fix Report Viewer version number

### PR DESCRIPTION
**Pull request by bdenhollander**
Change the version number to match the NuGet package.
https://www.nuget.org/packages/Microsoft.ReportingServices.ReportViewerControl.WebForms/150.900.148

### CODE REVIEW

**Comment by PRMerger20** [comment]
@bdenhollander : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@RhysSchmidtke Could you please look at this PR and see if you approve? If so, we can merge in the change. Thank you @bdenhollander for the suggestion. @maggiesMSFT if you can verify the change, that would also work. I'm assigning you as well. #assign:maggiesMSFT.

**Comment by PRMerger8** [comment]
maggiesMSFT. is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by rothja** [comment]
#assign:maggiesMSFT

**Comment by maggiesMSFT** [comment]
Thanks, @bdenhollander !
#sign-off

**Comment by PRMerger19** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @RhysSchmidtke, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by RhysSchmidtke** [comment]
#sign-off

**Pull request merged**
