### PR TITLE
Update configuring-storage-for-memory-optimized-tables.md

### PR DESCRIPTION
**Pull request by kfarlee**
Clarifying the recommendations for sizing the memory-optimized-data storage

### CODE REVIEW

**Comment by PRMerger12** [comment]
@kfarlee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kfarlee** [comment]
MikeRay has context on this change.  I missed assigning him to review this PR.

**Comment by PRMerger18** [comment]
@MikeRayMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
