### PR TITLE
Update download-sql-server-management-studio-ssms.md

### PR DESCRIPTION
**Pull request by bergano65**
1. "last"- can be interpreted as next versions aren't publicly available. probably formulate as suggested
2. isn't clear what can you download from localized pages

### CODE REVIEW

**Comment by PRMerger12** [comment]
@bergano65 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@dnethi 

Would you review the proposed changes to your article?

Thank you

**Comment by markingmyname** [comment]
@bergano65 

We appreciate your feedback, but we are going to leave it as-is for now.

thank you.

@ktoliver 

#please-close

**Pull request closed without merging**
