### PR TITLE
Update sp-getapplock-transact-sql.md

### PR DESCRIPTION
**Pull request by rjk**
Added sentence explaining what @LockTimeout value of -1 means, from https://docs.microsoft.com/en-us/sql/t-sql/statements/set-lock-timeout-transact-sql?view=sql-server-ver15.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@rjk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by MikeRayMSFT — APPROVED** [review]
It's consistent with the referenced doc. I'm going to approve.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @markingmyname, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
