### PR TITLE
Update Network Packet Size documentation to reflect various SSL limit…

### PR DESCRIPTION
**Pull request by simonxjx**
…ations

### CODE REVIEW

**Comment by PRMerger10** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@simonxjx: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
