### PR TITLE
Update sql-graph-overview.md (folder specification and link to Match clausula)

### PR DESCRIPTION
**Pull request by pricardo03**
It is important to note that they are a special type of table and are stored in a specific folder for their purpose.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@pricardo03 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@shkale-msft Is this pull request still in progress, or should it be closed? 

Thanks.

**Comment by shkale-msft** [comment]
Please close this without merging. This is not the right place for the suggested changes and we cannot include them here.

**Comment by ktoliver** [comment]
Thanks @shkale-msft

**Pull request closed without merging**
