### PR TITLE
Update_extended_events_target_armaha

### PR DESCRIPTION
**Pull request by aravindmahadevan-ms**
This change in doc is with regards to a discussion which already happened , and confirmed that Azure blob storage isn't the target supported yet, but the SSMS shows incorrect messages.. I can send more details through email if required, kindly let me know.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@aravindmahadevan-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@MightyPen - Could you review the proposed update to your article?

If you approve the update, the PR review team can edit before merging. To align with Microsoft style, I suggest this, indented under the list item:

```
> [!NOTE]
> You can't use Azure Blob Storage as a data storage target in an on-premises instance of SQL Server.
```

Thanks.

**Comment by MightyPen** [comment]
@markingmyname  Hi Mark,
The new sentence in this public PR #5488 is probably technically accurate.
But I would recommend that the line be cleaned a bit, to be closer to the following:

- Not quite:  _"SQL Server on premise does not support Azure blob storage as data storage target."_
- Slightly better might be: _"SQL Server on-premises does not support an Azure Storage blob as a data storage target."_

Overall, I am not confident anything like this new `!NOTE` is needed.  The article does not really imply that Azure Storage blobs are supported for this.
On the other hand, customer @aravindmahadevan-ms says that SSMS might be giving people the impression that Az Storage blobs might be supported? And the customer is offering to supply details of a relevant conversation.

I am reAssigning this public PR to you.  Thanks. G

CC: @aravindmahadevan-ms 
. .

**Comment by aravindmahadevan-ms** [comment]
Thanks Gene Milener.
Attaching the email, where we had the communication with SSMS Dev/SQL PG folks.

Regards,
Aravind

**Comment by PRMerger12** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
Edited "Note."

Thank you, @MightyPen, for the suggestion.

Thank you, @ktoliver, for the suggestion.

Thank you, @aravindmahadevan-ms, for the contribution.

**Comment by markingmyname** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@markingmyname: I'm sorry - only the author of this article, @MightyPen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by markingmyname** [comment]
@MightyPen assigned this to me.

I approve.

Please #sign-off

**Comment by PRMerger13** [comment]
@markingmyname: I'm sorry - only the author of this article, @MightyPen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
