### PR TITLE
CSharp → C#

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/connect/ado-net/step-4-connect-resiliently-to-sql-with-ado-net?view=sql-server-2017

### CODE REVIEW

**Comment by PRMerger16** [comment]
@hyoshioka0128 : Thanks for your contribution! The author, @MightyPen, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Verified code fence correction. Thank you

**Comment by MightyPen** [comment]
@GitHubber17 Hi Beth, I suspect something went wrong with this public PR 1798.  I do not understand how this PR got merged, as I never signed off on it.  Maybe the problem is that this PR never got formally Assigned to me, and instead I just received an @ notification email?

I thought that All public PRs required Writer approval before Merge.  We have to be extra careful with public PRs, for at least a couple different reasons.  One reason is that we need to check the rightness of the change.  Another is that any Merge Conflicts involving a public PR are trickier to resolve.

Also, I am reluctant to ever accept a public PR that lacks a textual paragraph explain Why the change is being suggested.  This public PR has no such explanation.

The incorrectness of this change can be foreseen in the Contributors' Guide article of filename = '**code-in-docs.md**', which lists `csharp` and the only programming language specification code for the C# programming language.

The markdown change is incorrect, and must be undone somehow.  I will create a private repo PR to manually reverse this change.
This is not a big problem, as the only temporary damage is the loss of C# syntax colorization in the live article, until I manually reverse this change.  My concern is more about the process going forward.

Thanks.  GeneMi.  2019/03/21  10:25am.

**Comment by GitHubber17** [comment]
@MightyPen &nbsp;Hi Gene, I appreciate the alert about this issue. Most pull requests require review and approval by the article author, but we do proactively merge "minor or purely editorial" changes. I apologize for the incorrect assessment in this case. If you would prefer that we follow a specific process for certain requests, please contact our review alias. Thank you.

**Comment by MightyPen** [comment]
@GitHubber17 I had forgotten this handling of the simplest PRs was part of the service.  This 1798 was a rare glitch, so I am all in favor of your team continuing to merge ahead on the simple ones.
Indeed, the simplicity of this errant change also meant that its effects were minor, and it was easy to reverse. (PR 9547).
Thanks a lot.

**Pull request merged**
