### PR TITLE
Format registry key paths

### PR DESCRIPTION
**Pull request by jgscherber**
The path was showing up as having line-break between entries instead of path separators. I also added code formatting around the paths to separate them visually from the description text.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@jgscherber : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jgscherber** [comment]
Also, would it be appropriate to add something about how on 64-bit machines, the keys will be split - with 32 bit keys being under Computer\HKEY_LOCAL_MACHINE\SOFTWARE\\**WOW6432Node**\ODBC\ODBC.INI

**Comment by PRMerger20** [comment]
@jgscherber : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jgscherber** [comment]
@MightyPen your requested changes have been made

**Comment by jborsecnik** [comment]
@mightypen, have these changes been made elsewhere? Merge this or close? Thanks.

**Comment by jborsecnik** [comment]
Please add a #-*comment* for clarity.

**Comment by MightyPen** [comment]
#sign-off

**Pull request merged**
