### PR TITLE
Update sp-addlinkedserver-transact-sql.md

### PR DESCRIPTION
**Pull request by akikawa1123**
fix aad authentication sample

### CODE REVIEW

**Comment by Court72** [comment]
@markingmyname

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@akikawa1123 This is still under review. Thank you for your patience.

**Comment by rwestMSFT** [comment]
Confirmed! Thank you for your contribution.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
