### PR TITLE
The systranschemas table is also used for Change Data Capture

### PR DESCRIPTION
**Pull request by pituach**
I am answering question regarding CDC in the forum and the objects which created when enabling CDC, and I wanted to give a link to the doc of each object, but I notice that CDC is not mentioned here.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@pituach : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@WilliamDAssafMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @pituach for taking the time to submit this PR! Good catch. Your commit will be merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Pull request merged**
