### PR TITLE
Update enable-and-configure-filestream.md

### PR DESCRIPTION
**Pull request by mchrupczalski**
Added PowerShell script to list all instances, current FILESTREAM AccessLevel and allow to change it

### CODE REVIEW

**Comment by PRMerger9** [comment]
@mchrupczalski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
Note that to reference an image in an MD file, the image file must be added to the repository. Thanks.

**Comment by PRMerger8** [comment]
@mchrupczalski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@mchrupczalski  - I appreciate the comprehensive sample and documentation submission. We are reviewing this and will reply or update on this thread.

**Comment by MikeRayMSFT** [comment]
@mchrupczalski  - thank you again for the submission. 

After reviewing the submission, we have decided not to include it in Microsoft documentation. It would be great if you could post it publicly in your own repository or in other publicly sharable script libraries. One public project that may be an appropriate platform for sharing is [dbatools](https://dbatools.io/join-us/).  

Thank you again.

**Comment by MikeRayMSFT** [comment]
#please-close

**Pull request closed without merging**
