### PR TITLE
Update setup-steps-for-extensible-key-management-using-the-azure-key-…

### PR DESCRIPTION
**Pull request by hemintshah**
…vault.md

### CODE REVIEW

**Comment by PRMerger8** [comment]
@hemintshah : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Rupp29** [comment]
#sign-off

**Comment by ktoliver** [comment]
@hemintshah @Rupp29 Could you identify the meaning of the acronym _FCI_? I'll make a few edits for Microsoft style before merging the PR, but I can't track down what FCI might refer to. Thanks.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Rupp29** [comment]
I was thinking about that, FCI: “Failover Cluster Instance”.


::Adrian
425.753.4998

**Comment by ktoliver** [comment]
@Rupp29 Thanks! I see a mix of capitalization in the content; I went with all lowercase, as in https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/failover-cluster-instance-storage-spaces-direct-manually-configure?tabs=windows2012 and the TOC:

image

OK? Thanks.

**Pull request merged**
