### PR TITLE
Merging info from KB:168335

### PR DESCRIPTION
**Pull request by ramakoni1**
Merging info from https://support.microsoft.com/authoring/article/168335?locale=en

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ramakoni1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ramakoni1** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ramakoni1: I'm sorry - only the author of this article, @MightyPen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ramakoni1** [comment]
wrong branch - closing pull request.

**Pull request closed without merging**
