### PR TITLE
Added step for answering SSMS dialog popup if it occurs

### PR DESCRIPTION
**Pull request by greglow**
Added step for answering SSMS dialog popup if it occurs (re: AE query parameters)

### CODE REVIEW

**Comment by PRMerger20** [comment]
@greglow : Thanks for your contribution! The author, @jaszymas, has been notified to review your proposed change.

**Comment by jaszymas** [comment]
Hi Greg. I agree with your suggestion to add a new step. Could you please:
- Change "click **Yes**" to "click "**Enable**" in your suggested edits (the button's name is Enable).
- Also change Step 7.1 from "Enable Parameterization for Always Encrypted" to "Make sure Parameterization for Always Encrypted is enabled". This is because it will likely already be enabled at this point. I feel, however, we should still prompt the reader to check/make sure, as enabling parameterization is critical for the following steps.

**Comment by PRMerger7** [comment]
@greglow : Thanks for your contribution! The author, @jaszymas, has been notified to review your proposed change.

**Comment by greglow** [comment]
OK, have modified this PR

 

Regards,

 

Greg

 

Dr Greg Low

 

1300SQLSQL (1300 775 775) office | +61 419201410 mobile│ +61 3 8676 4913 fax

SQL Down Under | Web:  <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sqldownunder.com%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091516274&sdata=SLHeEGAMmWUY5YIwcC4oAPYr%2F9RIZdi4MNASsdzwX2I%3D&reserved=0> www.sqldownunder.com | <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgreglow.me%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091526278&sdata=IU8tnAITCjBxWafi3A9XpO9lF3PIwZJ8ad3t36lnxvs%3D&reserved=0> http://greglow.me

**Comment by jaszymas** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@rjagiewich : Thanks for your contribution! The author, @jaszymas, has been notified to review your proposed change.

**Pull request merged**
