### PR TITLE
The username in ktpass command must be lower-case

### PR DESCRIPTION
**Pull request by liweiSecurity**
Discussed with Dylan in RFC https://sqlbuvsts01:8443/Main/SQL%20Server/_workitems#_a=edit&id=13358332

### CODE REVIEW

**Comment by PRMerger14** [comment]
@liweiSecurity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@ShannonLeavitt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Dylan-MSFT** [comment]
Liwei, I cannot reproduce this issue on my instance, and I do not use a lowercase entry in my keytab...

**Comment by rothja** [comment]
@liweiSecurity Should we close this PR, or do you want to connect to @Dylan-MSFT to provide more details or compare configurations. Thanks!

**Comment by PRMerger16** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @liweiSecurity for making these changes!

#sign-off

**Comment by PRMerger16** [comment]
@VanMSFT: I'm sorry - only the author of this article, @Dylan-MSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
