### PR TITLE
Update how-to-compare-and-synchronize-the-data-of-two-databases.md

### PR DESCRIPTION
**Pull request by AdamCaviness**
VS automation for NewDataComparison is no longer in a menu named SQL but instead under Tools.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@AdamCaviness : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
@AdamCaviness

Thank you for your contribution.

approved.

**Review by markingmyname — APPROVED** [review]

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
