### PR TITLE
Update create-login-transact-sql.md

### PR DESCRIPTION
**Pull request by MartinLBuchanan**
To Julie at Microsoft: (1) I added some additional transaction verbiage that is also a logical consequence, put the content in the header so it will apply to all versions. (2) Microsoft's business model should NOT be to insist that its customers fix the documentation when problems are pointed out. That is what good technical writers are for! I'm losing considerable $$$ per hour when doing free technical writing for Microsoft rather than working for my client.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@MartinLBuchanan : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
@MartinLBuchanan - Hi Martin! Sorry for the delay. We really appreciate your assistance with updating the doc. It is very helpful to have a community member like yourself help provide feedback on any of our documentation issues, and really appreciate your efforts on editing the docs!

#sign-off

@julieMSFT

**Comment by VanMSFT** [comment]
Related to https://github.com/MicrosoftDocs/sql-docs/issues/1923

**Comment by jborsecnik** [comment]
Changes verified.

**Pull request merged**
