### PR TITLE
AzDOS extension install ssis devops tools

### PR DESCRIPTION
**Pull request by WendyYes**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@WendyYes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger16** [comment]
@WendyYes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by chugugrace — APPROVED** [review]

**Comment by chugugrace** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
