### PR TITLE
Make page current and less painful to digest

### PR DESCRIPTION
**Pull request by ErikEJ**
This page made something that should be simple into an IT nightmare - this is an attempt to remedy this (and move forward now that all VS 2019 extensions are no longer i beta)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@ErikEJ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
@ErikEJ,

Reviewing the changes suggested.

I did approve the changes in your other PR.

Thank you.

**Comment by markingmyname** [comment]
Morning, @ErikEJ,

We cannot approve these changes as it seems you removed SSDT for the VS 2017 sections. SSDT for VS2017 is still under support, and new releases are upcoming so that we can remove that content.

However, we are currently discussing improving the content in this article currently.

Thank you for bringing this to our attention.

**Comment by ErikEJ** [comment]
I just wish there was less technical details about for example offline deployment, it makes the product look bad.

**Pull request closed without merging**
