### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pkral**
Three typos in 17.9 section.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@pkral : Thanks for your contribution! The author, @"stevestein", has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@stevestein - Would you review the proposed changes? Thanks.

**Comment by stevestein** [comment]
@pkral - thanks for the edits!

@ktoliver - updates are good.
#sign-off

**Comment by PRMerger8** [comment]
@stevestein: I'm sorry - only the author of this article, @"stevestein", can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
