### PR TITLE
Update columnstore-indexes-overview.md

### PR DESCRIPTION
**Pull request by giraom**
The b in b-trees mean self-balancing, not binary.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@giraom : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@MikeRayMSFT – Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by rwestMSFT** [comment]
Excellent find. Can we modify the change to `B-tree` instead of `b-tree`? Then we can get this approved ASAP.

**Comment by giraom** [comment]
Sure that is fine!

**Review by giraom — COMMENTED** [review]
Looking good

**Pull request closed without merging**
