### PR TITLE
Update service-tier-hyperscale-replicas.md

### PR DESCRIPTION
**Pull request by AbdullahMSFT**
@williamdassafMSFT

### CODE REVIEW

**Comment by AbdullahMSFT** [comment]
@williamdassafMSFT

**Comment by jborsecnik** [comment]
@yorek, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
#assign:WilliamDAssafMSFT

**Comment by yorek** [comment]
This seems to be merged already, is my review still needed? Btw I'm not the owner of Geo-Replicas, so I'll need to find who's the PM for that.

**Comment by AbdullahMSFT** [comment]
I am the PM @yorek

**Comment by WilliamDAssafMSFT** [comment]
Thanks @yorek, GitHub automatically notified you because you are still listed as the author of this article. We continuously publish so if you see anything we can always update.

**Pull request merged**
