### PR TITLE
Update create-external-data-source-transact-sql.md

### PR DESCRIPTION
**Pull request by ragatilao**
Added example to reference a readable secondary replica of Always On Availability Group

### CODE REVIEW

**Comment by PRMerger16** [comment]
@ragatilao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by WilliamDAssafMSFT** [comment]
Thanks for taking the time to create this PR, @ragatilao. This is a good addition to the documentation. I'm going to pull your commit here into another internal PR. It will be merged along with other changes to improve this example including adding the CREATE DATABASE SCOPED CREDENTIAL example. This article update is in flight. After the updated article is published, GitHub will list you as an article contributor, and I'll comment here to let you know when it's landed.

Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
@ragatilao Thanks again for the time you took to create a pull request. Your commit was included in a large edit to CREATE EXTERNAL DATA SOURCE that has now been reviewed by the product team and published: https://docs.microsoft.com/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-ver16&tabs=dedicated#g-create-external-data-source-to-reference-a-readable-secondary-replica-of-always-on-availability-group-1 GitHub lists you as an article contributor. Thanks again for this feedback, your suggestions help improve our documentation.

**Pull request closed without merging**
