### PR TITLE
Update doc for target readiness workflow in DMA

### PR DESCRIPTION
**Pull request by hitenjava**
The version of DMA (4.2) that supports these changes is already live.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@hitenjava : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Comment by hitenjava** [comment]
@TrishaMc Please take a look. Thanks!

**Comment by GitHubber17** [comment]
@hitenjava @pochiraju - Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules. 

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master). 

We'll close this PR. Thank you.

**Comment by hitenjava** [comment]
I merged it into the private repo already. Sorry, should have mentioned the PR repo pull request - https://github.com/MicrosoftDocs/sql-docs-pr/pull/8963/

**Comment by GitHubber17** [comment]
@hitenjava - Thank you. The changes merged into the private repo will be live soon.

**Comment by hitenjava** [comment]
Oh ok, so those get merged automatically (or by someone) and I don't need to update the public repo?

**Comment by GitHubber17** [comment]
Correct :)

**Pull request closed without merging**
