### PR TITLE
Fix example A and example output to be table

### PR DESCRIPTION
**Pull request by SvenAelterman**
Added [] around CURRENT_TIMESTAMP, otherwise the query syntax is not accepted (by SQL 2017) at least).
Also added some spaces after the commas separating columns.
PS: I only modified example A's output to be in table format. Not sure if it was desired, but it seems to make sense to me to match the output to what the query would return. Otherwise maybe modify the query to have multiple `SELECT` statements?

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @SvenAelterman   @BYHAM please review.

**Comment by SvenAelterman** [comment]
@BYHAM Sure, will take me a few hours though

**Comment by BYHAM** [comment]
#sign-off

**Comment by craigg-msft** [comment]
Thank you @BYHAM  and @SvenAelterman

**Pull request merged**
