### PR TITLE
CC88812: Fixing link to SQL Server data Tools

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @douglaslMS,
This proposed file change comes from https://github.com/MicrosoftDocs/sql-docs.it-it/pull/85 .
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@v-makoud : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by douglaslMS** [comment]
This PR was not authored by an FTE. Reopening.

**Comment by douglaslMS** [comment]
@v-makoud Martin, I realized that I can make the small change in this repo with the permissions that I have. So I fixed the URL and merged the pull request. Thank you!

**Comment by v-maudel** [comment]
Thanks @douglaslMS 

Fixed in this PR: https://github.com/MicrosoftDocs/sql-docs-pr/pull/8529

**Pull request merged**
