### PR TITLE
Added warning about requirements

### PR DESCRIPTION
**Pull request by SeanGallardy**
Added a warning about some basic requirements or items to watch out for when restoring master, either to another different server or as part of a disaster recovery exercise. The warning is about supportability when the master database is restored to an instance that may or may not have all the same features and functionality of the original.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@SeanGallardy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
thanks @SeanGallardy ! I modified the text slightly, if you're okay with the changes, please sign off :)  ... though I suspect it may not let you

**Comment by SeanGallardy** [comment]
Yep, you made it read much better 😊 I can’t signoff, I don’t have any power here 😝

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @cawrites, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
