### PR TITLE
Update alter-user-transact-sql.md

### PR DESCRIPTION
**Pull request by himanshu-ram-punjabi**
Replace the syntax as WITH NAME instead of WITHNAME during ALTER USER.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@himanshu-ram-punjabi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by fenxu** [comment]
Docs Build status updates of commit _[c23d77b](https://github.com/himanshu-ram-punjabi/sql-docs/commits/c23d77b0266a0af08a230662dbf701f205c26c53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/t-sql/statements/alter-user-transact-sql.md](https://github.com/himanshu-ram-punjabi/sql-docs/blob/patch-4/docs/t-sql/statements/alter-user-transact-sql.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202206271053043129-7737/BuildReport?accessString=a3a3d30502950ed178dd2df43dc2e5f9d35c056cd982abaa9bc46eb5c3355d25).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Court72** [comment]
@VanMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MikeRayMSFT** [comment]
Closing and reopening to see if it launches validation.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by MikeRayMSFT** [comment]
#assign: MikeRayMSFT

**Comment by PRMerger3** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @VanMSFT

**Pull request closed without merging**
