### PR TITLE
Update sys-dm-db-xtp-checkpoint-stats-transact-sql.md remove column d…

### PR DESCRIPTION
**Pull request by ronking-zhu**
comment removed

### CODE REVIEW

**Comment by Court72** [comment]
@rwestMSFT

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@ronking-zhu This is not an appropriate edit. The heading states "2016 and later".

#please-close

**Comment by ronking-zhu** [comment]
@rwestMSFT ,  That's the issue part, this column only exist in SQL 2022, but not exist in SQL 2016, 2017, 2019. 
db_in_checkpoint_only_mode | bit | True if database is in in-memory OLTP checkpoint-only mode.

**Comment by rwestMSFT** [comment]
@ronking-zhu Removing the column is not the appropriate solution. Please open this PR in the private `sql-docs-pr` repo, and I'll be happy to show you how we normally approach this.

**Comment by rwestMSFT** [comment]
@ronking-zhu Since you didn't create a new PR, I took the liberty of creating one for you, and adding the following comment to the section in question.

In future, please create all your PRs in the `sql-docs-pr` repository, not in `sql-docs`.

Screenshot 2024-07-08 at 11 09 42

**Pull request closed without merging**
