### PR TITLE
Update sys-query-store-runtime-stats-transact-sql.md

### PR DESCRIPTION
**Pull request by rdewolfe**
Specifying that the writes are also expressed in 8kb pages just like the reads are.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@rdewolfe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rwestMSFT** [comment]
@rdewolfe Thank you. I have submitted a small correction. Once you approve that, I can approve this change and you will receive credit for your contribution.

**Comment by rdewolfe** [comment]
I don't see any changes for me to approve, but I'm fine with whatever MSFT folks think is best

**Comment by rwestMSFT** [comment]
> I don't see any changes for me to approve, but I'm fine with whatever MSFT folks think is best

It was in your fork of the repository. You can take a look here: https://github.com/rdewolfe/sql-docs/pull/1

**Comment by PRMerger12** [comment]
@rdewolfe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rwestMSFT** [comment]
@rdewolfe All good. The first time is always the trickiest. Thanks again.

**Comment by rwestMSFT** [comment]
#sign-off

**Pull request merged**
