### PR TITLE
Supportability - Azure Synapse Serverless SQL Pool

### PR DESCRIPTION
**Pull request by charithcaldera**
GRANT Database Scoped Credential Permissions works on Azure Synapse Analytics Serverless SQL Pool.
This is also required when a SQL user needs to access the data in external storage account.

Example : 

CREATE LOGIN Mary WITH PASSWORD = '**********';
CREATE USER Mary FROM LOGIN Mary;
ALTER ROLE db_datareader ADD MEMBER Mary; 

--CRAETE DB SCOPED CREDENTIALS 
CREATE DATABASE SCOPED CREDENTIAL WorkspaceIdentity
WITH IDENTITY = 'Managed Identity';
GO

GRANT REFERENCES ON DATABASE SCOPED CREDENTIAL::[WorkspaceIdentity] TO [Mary];

### CODE REVIEW

**Comment by PRMerger16** [comment]
@charithcaldera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@VanMSFT, There is no specific change provided here. Should we close this PR? Thanks.

Thanks.

**Comment by charithcaldera** [comment]
@jborsecnik 
The suggestion is to make this document available for Azure Synapse Serverless SQL Pool. 
I have been communicating with one of the PMs for Serverless internally and this PR is created based on that.

**Comment by VanMSFT** [comment]
@charithcaldera - Thanks! Can you clarify if it only applies to SQL Pools, or all of Azure Synapse?

@WilliamDAssafMSFT to confirm and make changes to the applies to when he gets back.

#reassign:WilliamDAssafMSFT

**Comment by azaricstefan** [comment]
> The suggestion is to make this document available for Azure Synapse Serverless SQL Pool.

I don't see the change in the moniker on top of the page? Only a space? Did you forgot to commit?

**Comment by PRMerger-2** [comment]
@charithcaldera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by charithcaldera** [comment]
> @charithcaldera - Thanks! Can you clarify if it only applies to SQL Pools, or all of Azure Synapse?
> 
> @WilliamDAssafMSFT to confirm and make changes to the applies to when he gets back.
> 
> #reassign:WilliamDAssafMSFT

Azure Synapse Analytics has both Dedicated SQL Pool and Serverless SQL pool. 
This syntax works for Serverless SQL pool and I need to verify internally if this is supported in Dedicated SQL pool.

If this not supported to Dedicated SQL Pool in Synapse Analytics, 
I think we will need to add a note that this is only supported for Serverless SQL Pool.

**Comment by charithcaldera** [comment]
> > The suggestion is to make this document available for Azure Synapse Serverless SQL Pool.
> 
> I don't see the change in the moniker on top of the page? Only a space? Did you forgot to commit?

Sorry i was only made the suggestion and i just made the changes in to "Applies to" section.

**Review by azaricstefan — APPROVED** [review]

**Comment by PRMerger4** [comment]
@charithcaldera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by azaricstefan — APPROVED** [review]

**Comment by charithcaldera** [comment]
@VanMSFT  Any update ?

**Comment by WilliamDAssafMSFT** [comment]
@charithcaldera I am back in the office and can help here. I see in one of your above comments "I need to verify internally if this is supported in Dedicated SQL pool." Is this confirmed?

**Comment by charithcaldera** [comment]
> @charithcaldera I am back in the office and can help here. I see in one of your above comments "I need to verify internally if this is supported in Dedicated SQL pool." Is this confirmed?

Hello @WilliamDAssafMSFT 
I tested this in both Dedicated SQL pool and Serverless SQL pool, but in Dedicated SQL pool, we are getting a error and same works in Serverless SQL Pool. 

As a result of that, i have upadted the document with below additional comment 

"GRANT Database Scoped Credential Permissions is only supported for serverless SQL pools in Azure Synapse Analytics." 

GRANT REFERANCES ON DATABASES - SERVERLESS AND DEDICATED POOLS

**Comment by WilliamDAssafMSFT** [comment]
@charithcaldera I've made some additional changes necessary to bring the article up to date for the moniker and applies to tags.
#sign-off

**Comment by charithcaldera** [comment]
> @charithcaldera I've made some additional changes necessary to bring the article up to date for the moniker and applies to tags. #sign-off

Hello @WilliamDAssafMSFT , 
Thank you, 

I hope we can publish this soon. 
please let me know if anything required from my end.

**Comment by WilliamDAssafMSFT** [comment]
@charithcaldera all set. Thanks again for making taking the time to create this PR. Should be live later today.

**Comment by charithcaldera** [comment]
> @charithcaldera all set. Thanks again for making taking the time to create this PR. Should be live later today.

Thank you @WilliamDAssafMSFT & @VanMSFT  for all the help

**Pull request merged**
