### PR TITLE
Update Azure Data Studio extension documentation

### PR DESCRIPTION
**Pull request by laurajjiang**
Referencing VS Code extension documentation to update Azure Data Studio documentation.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@laurajjiang : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
@laurajjiang 

Approved.

Please sign-off. :)

**Comment by laurajjiang** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@laurajjiang: I'm sorry - only the author of this article, @markingmyname, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
