### PR TITLE
Update create-database-scoped-credential-transact-sql.md

### PR DESCRIPTION
**Pull request by jpers36**
'MANAGED IDENTITY' option for CREATE DATABASE SCOPED CREDENTIAL is currently undocumented.  Can we add this documentation?

### CODE REVIEW

**Comment by jborsecnik** [comment]
@VanMSFT, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Following up with @GithubMirek to confirm.

**Comment by VanMSFT** [comment]
Need input from Azure Synapse Product Team

**Comment by VanMSFT** [comment]
Per internal confirmation, I am approving this. Thanks @jpers36!

#sign-off

**Pull request merged**
