### PR TITLE
Update querying-extended-stored-procedures-installed-in-sql-server.md

### PR DESCRIPTION
**Pull request by emad-almousa**
Hello,

this paragraph is not accurate:

> [!IMPORTANT]  
>  Information will be returned for only those extended stored procedures that the logged in user owns or has permissions to. Only members of the **sysadmin** fixed server role and the **db_owner**, **db_securityadmin**, and the **db_ddladmin** fixed database roles can view information for all extended stored procedures.  

I tried listing all extended stored procedures with account granted SYSADMIN role and account that has only login (authentication) permission to the database engine. both accounts are returning the same set of information results. So no special permission is required to be granted to list MASTER database extended stored procedures (all of them).

in SQL Server Management Studio execute the following:

sp_helpextendedproc 

name	dll
sp_add_trusted_assembly	(server internal)
sp_AddFunctionalUnitToComponent	(server internal)
sp_alter_nt_job_mem_configs	(server internal)
sp_audit_write	(server internal)
sp_autoindex_cancel_dta	(server internal)
sp_autoindex_invoke_dta	(server internal)
sp_availability_group_command_internal	(server internal)
sp_begin_parallel_nested_tran	(server internal)
sp_bindsession	(server internal)
sp_build_histogram	(server internal)
sp_cdc_set_scheduler_job	sp_cdc_set_scheduler_job extended procedure
sp_certificate_add_issuer	(server internal)
sp_certificate_drop_issuer	(server internal)
sp_certificate_issuers	(server internal)
sp_change_tracking_waitforchanges	(server internal)
sp_cleanup_all_average_column_length_statistics	(server internal)
sp_cleanup_all_openrowset_statistics	(server internal)
sp_cleanup_all_user_data_in_master	(server internal)
sp_cloud_update_blob_tier	(server internal)
sp_collect_backend_plan	(server internal)
sp_commit_parallel_nested_tran	(server internal)
sp_configure_automatic_tuning	(server internal)
sp_control_dbmasterkey_password	(server internal)
sp_copy_data_in_batches	(server internal)
sp_create_asymmetric_key_from_external_key	(server internal)
sp_create_format_type	(server internal)
sp_create_format_type_synonym	(server internal)
sp_create_openrowset_statistics	(server internal)
sp_create_parser_version	(server internal)
sp_createorphan	(server internal)
sp_cursor	(server internal)
sp_cursorclose	(server internal)
sp_cursorexecute	(server internal)
sp_cursorfetch	(server internal)
sp_cursoropen	(server internal)
sp_cursoroption	(server internal)
sp_cursorprepare	(server internal)
sp_cursorprepexec	(server internal)
sp_cursorunprepare	(server internal)
sp_delete_backup_file_snapshot	(server internal)
sp_delete_database_engine_configuration_internal	(server internal)
sp_delete_http_namespace_reservation	(server internal)
sp_describe_first_result_set	(server internal)
sp_describe_parameter_encryption	(server internal)
sp_describe_undeclared_parameters	(server internal)
sp_diagnostic_showplan_log_dbid	(server internal)
sp_drop_format_type	(server internal)
sp_drop_openrowset_statistics	(server internal)
sp_drop_parser_version	(server internal)
sp_drop_storage_location	(server internal)
sp_drop_trusted_assembly	(server internal)
sp_droporphans	(server internal)
sp_dw_physical_manifest_file_table_insert	(server internal)
sp_dw_physical_upsert	(server internal)
sp_enable_sql_debug	(server internal)
sp_enclave_send_keys	(server internal)
sp_execute	(server internal)
sp_execute_external_script	(server internal)
sp_execute_flight_query	(server internal)
sp_execute_remote	(server internal)
sp_executesql	(server internal)
sp_executesql_metrics	(server internal)
sp_external_governance_initiate_synchronization	(server internal)
sp_external_policy_refresh	(server internal)
sp_fido_build_basic_histogram	(server internal)
sp_fido_build_histogram	(server internal)
sp_fido_execute_graph_request	(server internal)
sp_fido_get_CS_rowset_row_count	(server internal)
sp_fido_get_remote_storage_size	(server internal)
sp_fido_glm_server_execute_batch	(server internal)
sp_fido_glms_execute_command	(server internal)
sp_fido_glms_get_storage_containers	(server internal)
sp_fido_glms_set_storage_containers	(server internal)
sp_fido_glms_unregister_appname	(server internal)
sp_fido_indexstore_update_topology	(server internal)
sp_fido_indexstore_upgrade_node	(server internal)
sp_fido_remove_retention_policy	(server internal)
sp_fido_set_ddl_step	(server internal)
sp_fido_set_retention_policy	(server internal)
sp_fido_set_tran	(server internal)
sp_fido_setup_endpoints	(server internal)
sp_fido_setup_glms	(server internal)
sp_fido_tran_abort	(server internal)
sp_fido_tran_begin	(server internal)
sp_fido_tran_commit	(server internal)
sp_fido_tran_get_state	(server internal)
sp_fido_tran_set_token	(server internal)
sp_flush_log	(server internal)
sp_force_slog_truncation	(server internal)
sp_fulltext_getdata	(server internal)
sp_fulltext_keymappings	(server internal)
sp_fulltext_pendingchanges	(server internal)
sp_generate_external_table_statistics_description_and_hash	(server internal)
sp_generate_openrowset_statistics_props	(server internal)
sp_generate_trident_table_manifest	(server internal)
sp_get_database_scoped_credential	(server internal)
sp_get_dmv_collector_views	(server internal)
sp_get_endpoint_certificate	(server internal)
sp_get_external_table_cardinality	(server internal)
sp_get_fido_lock	(server internal)
sp_get_fido_lock_batch	(server internal)
sp_get_file_splits	(server internal)
sp_get_migration_vlf_state	(server internal)
sp_get_openrowset_statistics_additional_props	(server internal)
sp_get_openrowset_statistics_cardinality	(server internal)
sp_get_query_template	(server internal)
sp_get_table_card_est_and_avg_col_len	(server internal)
sp_get_total_openrowset_statistics_count	(server internal)
sp_getbindtoken	(server internal)
sp_getschemalock	(server internal)
sp_http_generate_wsdl_complex	(server internal)
sp_http_generate_wsdl_simple	(server internal)
sp_internal_alter_nt_job_limits	(server internal)
sp_manage_distributed_transaction	(server internal)
sp_md_discovery_stats_staleness_detection	(server internal)
sp_migrate_user_to_contained	(server internal)
sp_new_parallel_nested_tran_id	(server internal)
sp_OACreate	odsole70.dll
sp_OADestroy	odsole70.dll
sp_OAGetErrorInfo	odsole70.dll
sp_OAGetProperty	odsole70.dll
sp_OAMethod	odsole70.dll
sp_OASetProperty	odsole70.dll
sp_OAStop	odsole70.dll
sp_polybase_authorize	(server internal)
sp_polybase_join_group	(server internal)
sp_polybase_leave_group	(server internal)
sp_polybase_show_objects	(server internal)
sp_PostAgentInfo	(server internal)
sp_prepare	(server internal)
sp_prepexec	(server internal)
sp_prepexecrpc	(server internal)
sp_process_memory_leak_record	(server internal)
sp_publish_database_to_syms	(server internal)
sp_query_store_clear_hints	(server internal)
sp_query_store_clear_message_queues	(server internal)
sp_query_store_consistency_check	(server internal)
sp_query_store_flush_db	(server internal)
sp_query_store_force_plan	(server internal)
sp_query_store_remove_plan	(server internal)
sp_query_store_remove_query	(server internal)
sp_query_store_reset_exec_stats	(server internal)
sp_query_store_set_hints	(server internal)
sp_query_store_unforce_plan	(server internal)
sp_rbpex_exec_cmd	(server internal)
sp_rda_deauthorize_db	(server internal)
sp_rda_get_rpo_duration	(server internal)
sp_rda_reauthorize_db	(server internal)
sp_rda_reconcile_batch	(server internal)
sp_rda_reconcile_columns	(server internal)
sp_rda_reconcile_indexes	(server internal)
sp_rda_set_query_mode	(server internal)
sp_rda_set_rpo_duration	(server internal)
sp_rda_test_connection	(server internal)
sp_release_all_fido_locks	(server internal)
sp_release_fido_lock	(server internal)
sp_releaseschemalock	(server internal)
sp_remote_data_archive_event	(server internal)
sp_repl_generate_subscriber_event	sp_repl_generate_subscriber_event extended procedure
sp_repl_generate_sync_status_event	sp_repl_generate_sync_status_event extended procedure
sp_repl_generateevent	replgenerateevent extended procedure
sp_replcmds	replcmds extended procedure
sp_replcounters	replcounters extended procedure
sp_replddlparser	sp_replddlparser extended procedure
sp_repldone	repldone extended procedure
sp_replflush	replflush extended procedure
sp_replhelp	sp_replhelp extended procedure
sp_replsendtoqueue	sp_replsendtoqueue extended proc
sp_replsetsyncstatus	replsetsyncstatus extended procedure
sp_repltrans	repltrans extended procedure
sp_replwritetovarbin	sp_replwritetovarbin extended proc
sp_reserve_http_namespace	(server internal)
sp_reset_connection	(server internal)
sp_reset_dtc_log	(server internal)
sp_reset_inactive_duration_flag	(server internal)
sp_reset_session_context	(server internal)
sp_resyncexecute	(server internal)
sp_resyncexecutesql	(server internal)
sp_resyncprepare	(server internal)
sp_resyncuniquetable	(server internal)
sp_rollback_parallel_nested_tran	(server internal)
sp_server_diagnostics	(server internal)
sp_set_blob_ringbuffer_memory	(server internal)
sp_set_data_processed_limit	(server internal)
sp_set_database_engine_configuration_internal	(server internal)
sp_set_def_format_type_default_target	(server internal)
sp_set_def_format_type_extractor	(server internal)
sp_set_def_format_type_md_preprocessor	(server internal)
sp_set_distributed_feedback_context	(server internal)
sp_set_distributed_query_context	(server internal)
sp_set_format_type_ls_syntax	(server internal)
sp_set_msdtc_network	(server internal)
sp_set_parser_version_default_target	(server internal)
sp_set_parser_version_extractor	(server internal)
sp_set_parser_version_md_preprocessor	(server internal)
sp_set_session_context	(server internal)
sp_set_session_resource_group	(server internal)
sp_SetOBDCertificate	(server internal)
sp_setuserbylogin	(server internal)
sp_show_external_table_average_column_length_statistics	(server internal)
sp_show_openrowset_statistics	(server internal)
sp_showinitialmemo_xml	(server internal)
sp_showmemo_xml	(server internal)
sp_shutdown_feedback_client_connection	(server internal)
sp_sm_detach	(server internal)
sp_spaceused_remote_data_archive	(server internal)
sp_start_fixed_vlf	(server internal)
sp_start_flight_server	(server internal)
sp_start_glm_server	(server internal)
sp_start_user_instance	(server internal)
sp_stop_flight_server	(server internal)
sp_testlinkedserver	(server internal)
sp_trace_create	(server internal)
sp_trace_generateevent	(server internal)
sp_trace_setevent	(server internal)
sp_trace_setfilter	(server internal)
sp_trace_setstatus	(server internal)
sp_trident_create_credential_to_access_internal_md_storage	(server internal)
sp_try_set_session_context	(server internal)
sp_unprepare	(server internal)
sp_update_logical_pause_deactivation_params	(server internal)
sp_update_logical_pause_flag	(server internal)
sp_update_user_instance	(server internal)
sp_upgrade_vdw_configuration_parameters	(server internal)
sp_verify_database_ledger	(server internal)
sp_verify_database_ledger_from_digest_storage	(server internal)
sp_xa_commit	(server internal)
sp_xa_end	(server internal)
sp_xa_forget	(server internal)
sp_xa_forget_ex	(server internal)
sp_xa_init	(server internal)
sp_xa_init_ex	(server internal)
sp_xa_prepare	(server internal)
sp_xa_prepare_ex	(server internal)
sp_xa_recover	(server internal)
sp_xa_rollback	(server internal)
sp_xa_rollback_ex	(server internal)
sp_xa_start	(server internal)
sp_xcs_mark_column_relation	(server internal)
sp_xml_preparedocument	(server internal)
sp_xml_removedocument	(server internal)
sp_xp_cmdshell_proxy_account	(server internal)
xp_availablemedia	xpstar.dll
xp_cmdshell	(server internal)
xp_copy_file	xpstar.dll
xp_copy_files	xpstar.dll
xp_create_subdir	xpstar.dll
xp_delete_file	xpstar.dll
xp_delete_files	xpstar.dll
xp_dirtree	xpstar.dll
xp_enum_oledb_providers	xpstar.dll
xp_enumerrorlogs	xpstar.dll
xp_enumgroups	xplog70.dll
xp_fileexist	xpstar.dll
xp_fixeddrives	xpstar.dll
xp_get_tape_devices	xpstar.dll
xp_getnetname	xpstar.dll
xp_instance_regaddmultistring	xpstar.dll
xp_instance_regdeletekey	xpstar.dll
xp_instance_regdeletevalue	xpstar.dll
xp_instance_regenumkeys	xpstar.dll
xp_instance_regenumvalues	xpstar.dll
xp_instance_regread	xpstar.dll
xp_instance_regremovemultistring	xpstar.dll
xp_instance_regwrite	xpstar.dll
xp_logevent	xplog70.dll
xp_loginconfig	xplog70.dll
xp_msver	xplog70.dll
xp_msx_enlist	xpstar.dll
xp_passAgentInfo	xpstar.dll
xp_prop_oledb_provider	xpstar.dll
xp_qv	xpsqlbot.dll
xp_readerrorlog	xpstar.dll
xp_regaddmultistring	xpstar.dll
xp_regdeletekey	xpstar.dll
xp_regdeletevalue	xpstar.dll
xp_regenumkeys	xpstar.dll
xp_regenumvalues	xpstar.dll
xp_regread	xpstar.dll
xp_regremovemultistring	xpstar.dll
xp_regwrite	xpstar.dll
xp_replposteor	replposteor extended procedure
xp_servicecontrol	xpstar.dll
xp_sprintf	xplog70.dll
xp_sqlagent_enum_jobs	xpstar.dll
xp_sqlagent_is_starting	xpstar.dll
xp_sqlagent_monitor	xpstar.dll
xp_sqlagent_notify	xpstar.dll
xp_sqlagent_param	xpstar.dll
xp_sqlmaint	xpstar.dll
xp_sscanf	xplog70.dll
xp_subdirs	xpstar.dll
xp_sysmail_activate	xpstar.dll
xp_sysmail_attachment_load	xpstar.dll
xp_sysmail_format_query	xpstar.dll

### CODE REVIEW

**Comment by Court72** [comment]
@VanMSFT

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Thanks, @emad-almousa! You're correct, the note is wrong, and I can verify the same results. https://learn.microsoft.com/sql/relational-databases/system-stored-procedures/sp-helpextendedproc-transact-sql

However, I would probably just delete the note altogether, or even delete this page. @rwestMSFT - Perhaps these set of docs are a good candidate to clean up the duplication?

https://learn.microsoft.com/en-us/sql/relational-databases/extended-stored-procedures-programming/querying-extended-stored-procedures-installed-in-sql-server

**Comment by rwestMSFT** [comment]
Yes, let's take this internal and remove the article.

**Comment by rwestMSFT** [comment]
@emad-almousa Because we deleted the article you revised, your name won't appear on the contributor list for the remaining article, but you will be able to see your contribution in the commit history once this goes live later today.

**Pull request closed without merging**
