### PR TITLE
Update dynamic-data-masking.md

### PR DESCRIPTION
**Pull request by NandanHegde15**
Added a limitation of dynamic data masking not supported in External tables

### CODE REVIEW

**Comment by PRMerger8** [comment]
@NandanHegde15 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @NandanHegde15 - Thanks for making these changes.

@DavidTrigano - Hey David, can you help confirm this?

**Comment by VanMSFT** [comment]
@DavidTrigano - Hey David, can you please help check this? Thanks!

**Comment by VanMSFT** [comment]
Hi @NandanHegde15 - Thank you for your contribution! As this has been updated already, I will go ahead and close this PR. Thank you so much for helping with our documentation.

image

**Pull request closed without merging**
