### PR TITLE
Update steps on joining Linux to AD

### PR DESCRIPTION
**Pull request by slaymaker1907**
Update docs to mention extra steps for SLES 12 and to also mention quirk with hostname when using realmd.

Added section describing RDNS prereqs.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@slaymaker1907 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @slaymaker1907!

#sign-off

**Comment by PRMerger17** [comment]
@VanMSFT: I'm sorry - only the author of this article, @Dylan-MSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by VanMSFT** [comment]
@ktoliver - Hi again Kristine! Please help merge. Thanks!

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
