### PR TITLE
Added a delegation section

### PR DESCRIPTION
**Pull request by KrishnakumarRukmangathan**
Added the delegation section which talks about the support under open delegation and constrained delegation scenarios. The CSS team, PG team and CSS Windows Directory services team worked internally to come to this conclusion.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@KrishnakumarRukmangathan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@chugugrace Would you review the proposed addition to your article? Thanks!

**Comment by chugugrace** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
