### PR TITLE
Update contained-availability-groups-overview.md

### PR DESCRIPTION
**Pull request by guzmanda**
Corrected text "access those databases by four part name" to "access those databases by three part name".

### CODE REVIEW

**Comment by PRMerger17** [comment]
@guzmanda : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@kfarlee, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged"

**Comment by rothja** [comment]
@Kevin-Farlee Kevin, could you take a look at the recommended change in this public PR (file changes tab). If you approve, you can `#sign-off`. Otherwise, provide some feedback in the comments.

@guzmanda Dan, thanks for your recommendation, and sorry for the delay!

**Comment by MashaMSFT** [comment]
Hi @guzmanda , thanks so much for your submission! I've pulled your changes into a private PR, so while I close out this PR, you will still be marked as a contributor for your commit :) Thanks so much for improving our docs! Hope you have a great day :)

Masha from the SQL Docs team

**Pull request closed without merging**
