### PR TITLE
Updating change log for SSRS 2017 April CU

### PR DESCRIPTION
**Pull request by edugonz**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@edugonz : Thanks for your contribution! The author, @casualoak, has been notified to review your proposed change.

**Comment by casualoak** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @casualoak, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
