### PR TITLE
Formatting changes.

### PR DESCRIPTION
**Pull request by Protiguous**
Removed trailing whitespace.
Added ```sql.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Protiguous : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by markingmyname** [comment]
@Protiguous 

We appreciate the attempt to help us clean up the docs and keep it concise; however, we are currently making updates to the T-SQL articles in the tsql folder. 

I know you are new at this, and these are your first changes, but can I ask you to hold off on making any edits to the tsql files for two weeks?

Because once these changes go through, your PRs will show out of sync, and you will have to recreate them.

**Comment by markingmyname** [comment]
I will review the ones already submitted verify if they get approved.

But please hold off on any more tsql files for 2 weeks.

Thank you.

**Comment by markingmyname** [comment]
Please do not remove the spacing, as in markdown, and a "double-space" creates a new line.

Since we are editing these files now, I will close and reject these changes.

Please review this article again in August 2020 to see if any other changes need to be made.

Thank you.

**Comment by Protiguous** [comment]
Not a problem. I'm looking forward to the new documentation.

**Pull request closed without merging**
