### PR TITLE
Fix Kevin's path after the relocation.

### PR DESCRIPTION
**Pull request by RadoslavGatev**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@RadoslavGatev : Thanks for your contribution to the Azure documentation! The author, @rickbyh, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
Thank you @RadoslavGatev .  @edmacauley can you please review.

**Comment by edmacauley** [comment]
Thank you @RadoslavGatev for fixing that pesky Kevin.  @craigg-msft it looks good #sign-off

**Comment by PRMerger10** [comment]
@edmacauley: Only the author, @BYHAM, can sign off on this pull request.

**Comment by craigg-msft** [comment]
Thank you @RadoslavGatev and @edmacauley

**Pull request merged**
