### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by mihaelablendea**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@mihaelablendea : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by mihaelablendea** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@mihaelablendea: I'm sorry - only the author of this article, @rothja, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mihaelablendea** [comment]
@rothja could you please sign off? The AKS version has to be at least 1.12 for a single node AKS cluster to accommodate more than 16 disks.

**Comment by rothja** [comment]
#sign-off

**Pull request merged**
