### PR TITLE
Update guidelines-for-online-index-operations.md

### PR DESCRIPTION
**Pull request by tmmueller**
Typo: truncation -> transaction

### CODE REVIEW

**Comment by PRMerger3** [comment]
@tmmueller : Thanks for your contribution to the SQL documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@edmacauley please review.

**Comment by edmacauley** [comment]
Thank you @tmmueller for the good catch.  #sign-off

**Comment by craigg-msft** [comment]
Thank you @tmmueller  and @edmacauley

**Pull request merged**
