### PR TITLE
Fix parentheses

### PR DESCRIPTION
**Pull request by imba-tjd**
From https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/143
Fix https://github.com/MicrosoftDocs/sql-docs/issues/4769

### CODE REVIEW

**Comment by PRMerger12** [comment]
@imba-tjd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MladjoA** [comment]
@imba-tjd , thanks again. We are going to merge this change soon.

**Comment by MladjoA** [comment]
#sing-off

**Comment by MladjoA** [comment]
#sign-off

**Comment by ktoliver** [comment]
Publishing is suspended until Tuesday, May 19. Merging will resume 7:00 AM PT Tuesday. 
This PR is ready for merge.

**Pull request merged**
