### PR TITLE
ssdt 15.9.10 release information

### PR DESCRIPTION
**Pull request by WendyYes**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@WendyYes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by chugugrace** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@chugugrace: I'm sorry - only the author of this article, @dzsquared, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by dzsquared** [comment]
this went through the correct repo (sql-docs-pr) and can be closed 
#please-close

**Pull request closed without merging**
