### PR TITLE
Consistent file names in Alpine-related snippet

### PR DESCRIPTION
**Pull request by estambakio-sc**
This commit fixes file names in Alpine-related snippet.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@estambakio-sc : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@David-Engel Hi David,  Do you have any assessment of this PR #4104 ?
Thanks.

**Comment by MightyPen** [comment]
@v-makouz Hi again Maxim, here is another PR, #4104, that is somewhat like PR #4070, and which also needs you to asses / Close / Merge etc.

Thanks.  GeneMi = MightyPen

**Comment by MightyPen** [comment]
@estambakio-sc Hello Egor, We like this PR #4104, and are now merging it.
Thank you very much for providing the important updates to us.

Thank you for submitting this PR. We hope to hear from you again.

**Comment by MightyPen** [comment]
Just now, v-Makouz and I (GeneMi) further updated this article, with the following Commit here in the public repo:

- `https://github.com/MicrosoftDocs/sql-docs/commit/297243e5688fdba4a988b903dfc66925d48dc56a#diff-f7c89af2a4f2093d966dce03e08938cf`

Thanks.

**Pull request merged**
