### PR TITLE
Update datetimeoffsetfromparts-transact-sql.md

### PR DESCRIPTION
**Pull request by fbsolo**
Text revisions to tighten and optimize the reading flow of the material.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
Found a typo on line 100, Thisg :)

**Comment by PRMerger7** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@MightyPen can you please review

**Pull request merged**
