### PR TITLE
Added examples of doing defaults inline

### PR DESCRIPTION
**Pull request by nycdotnet**
When using things like SQL Server Data Tools, it's helpful to be able to create named defaults inline.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@nycdotnet : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@nycdotnet Hello Steve, We like your two Transact-SQL code examples that you want to have added to our documentation article. We are having them added. Thanks for submitting them.
However,.....
The precise markdown syntax that we need for adding the examples is not quite present in this PR 1660.
Further, when I looked at the article today, I saw several unrelated pieces of the article that warrant improvement. So I decided to create a PR (9134) in our private repo. PR 9134 adds your T-SQL examples with the triple-backtick syntax that we need, and makes numerous other smaller improvement.

By this coming Friday or Monday, you should be able to view the raw markdown for this article (in repo 'sql-docs'), and see an HTML comment that mentions the code examples were provided by 'nycdotnet'.

Now I am permanently Closing this public PR 1660, in favor of private PR 9134.
Thanks a lot.

CC: @ktoliver

**Comment by MightyPen** [comment]
Closing now.

**Comment by nycdotnet** [comment]
ty

**Pull request closed without merging**
