### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by pkral**
The existing links refers to its own section. Change it to refer to the Protection Levels section on the same page.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@pkral : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@pkral Thank you for tidying this up. Please note my small request for a revision.

**Comment by PRMerger14** [comment]
@pkral : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
#sign-off

**Pull request merged**
