### PR TITLE
Fix typo in EMPTYFILE

### PR DESCRIPTION
**Pull request by blueelm-alex**
ENPTYFILE -> EMPTYFILE

### CODE REVIEW

**Comment by PRMerger19** [comment]
@blueelm-alex : Thanks for your contribution! The author, @pmasl, has been notified to review your proposed change.

**Comment by rjagiewich** [comment]
@blueelm-alex I couldn't see any change to the content. Which typo did you fix? Thanks.

**Comment by pmasl** [comment]
@rjagiewich second line. Approved. Thank you!

**Comment by pmasl** [comment]
#sign-off

**Pull request merged**
