### PR TITLE
Update ss-force-failover-read-scale-out.md

### PR DESCRIPTION
**Pull request by NaneFlores**
ADD note with the error if you tried to make falover without "FORCE_FAILOVER_ALLOW_DATA_LOSS" . ADD note because REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT can be change only in Enterprise Edition.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@MikeRayMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MikeRayMSFT** [comment]
@NaneFlores  -thank you for the submission. I'm pulling this PR over to the private repository to validate before we sign off.

I'll close the public PR at this time. #please-close

**Comment by MikeRayMSFT** [comment]
@NaneFlores - thank you again for the submission.

This feature availability isn't tied to Availability Groups as a whole, which are specific to Enterprise Edition. A Basic Availability group (on Standard Edition) doesn't support read-scale out. 

See [Basic Availability Groups | Limitations](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-ver16#limitations)

CC: @kfarlee

**Comment by NaneFlores** [comment]
Thank you for reply @MikeRayMSFT .

But If I want to create a read-scale solution for only DR and not ready to read on replica? AG Read-Scale isn't supported?

**Pull request closed without merging**
