### PR TITLE
Update database-experimentation-assistant-configure-replay.md

### PR DESCRIPTION
**Pull request by john-sterrett**
SSMS 17.9.1 is the latest version of SSMS to include dreplay.exe. DReplay.exe is required to communicate with the distributed replay controller or client.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@john-sterrett : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Thanks so much for your contribution @john-sterrett ! #sign-off

**Comment by PRMerger18** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @pochiraju, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MashaMSFT** [comment]
@ktoliver fyi

**Pull request merged**
