### PR TITLE
Improve sample code to indicate a range is created

### PR DESCRIPTION
**Pull request by SvenAelterman**
Incrementing the firewall end IP address by just 1 may create a false impression that they are individual IPs rather than a range. The description wasn't helpful either.
Also removed "Windows" from "Windows Azure": It hasn't been called that in a while I think. 
Also added some spaces between stored procedure parameter values, to be consistent with T-SQL docs (https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/specify-parameters)

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @SvenAelterman  for the contribution to content.

**Comment by craigg-msft** [comment]
@BYHAM please review.

**Comment by BYHAM** [comment]
Thank you for submitting this. @SvenAelterman Didn't you include these #65 changes in your #66 submission. (Which I have accepted.) If you agree, please cancel this one (#65).

**Comment by SvenAelterman** [comment]
@BYHAM: note quite, there are two different articles, one for server-level and one for database-level. So yes, I made almost the same changes but that's because I believe both articles could be improved by making these changes.

**Comment by BYHAM** [comment]
@SvenAelterman Ah. I didn't spot that right away. Thank you. Yes, I agree with the changes in the second topic, too, and I have accepted them.

**Comment by BYHAM** [comment]
#sign-off

**Comment by BYHAM** [comment]
@craigg-msft Was not a duplicate after all. Just similar.

**Pull request merged**
