### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by imba-tjd**
The link after `For more information about`

### CODE REVIEW

**Comment by PRMerger17** [comment]
@imba-tjd : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@imba-tjd : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@imba-tjd - Thanks for the update!

**Comment by stevestein** [comment]
#sign-off

**Pull request merged**
