### PR TITLE
Update how-to-install-custom-security-extensions.md

### PR DESCRIPTION
**Pull request by RichardSinden**
Correcting case for MachineKey config in later versions of SSRS and Power BI

### CODE REVIEW

**Comment by PRMerger15** [comment]
@RichardSinden : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@maggiesMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
Hi, @RichardSinden -- thanks for your suggested edits! Running them by the devs to confirm.

**Comment by rwestMSFT** [comment]
This issue was resolved in this internal PR: https://github.com/MicrosoftDocs/sql-docs-pr/pull/25402.

**Pull request closed without merging**
