### PR TITLE
Update the length of CMD

### PR DESCRIPTION
**Pull request by HEMANTHSQL**
Updating the length of CMD from 16 to 26 as we are seeing values with length more than 16 like XIO_LEASE_RENEWAL_WORKER

### CODE REVIEW

**Comment by PRMerger12** [comment]
@HEMANTHSQL : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@HEMANTHSQL : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @HEMANTHSQL! Thanks for making this suggestion. However, the old value is correct and we will not make this change. See the following screenshot:

image

We'll close this for now, but please feel free to comment further.

**Comment by VanMSFT** [comment]
Re-open to change cmd length correctly for SQL 2019

**Comment by VanMSFT** [comment]
Discussed with @HEMANTHSQL. Editing the article to reflect new data type for cmd for SQL Server 2019.

#sign-off

**Pull request merged**
