### PR TITLE
Sql docs pr.master

### PR DESCRIPTION
**Pull request by mariyaali**
https://supportability.visualstudio.com/AzureSynapseAnalytics/_wiki/wikis/AzureSynapseAnalytics/499728/Rename-SQL-Pool-not-working

### CODE REVIEW

**Comment by PRMerger14** [comment]
@mariyaali : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mariyaali** [comment]
@WilliamDAssafMSFT

**Comment by ktoliver** [comment]
Hi @WilliamDAssafMSFT - Could you take a look at this pull request? Thanks!

**Comment by WilliamDAssafMSFT** [comment]
Hi @mariyaali! 
First off, sorry that this one is so delayed. Looks like it slipped under Ron's radar and wasn't assigned to me. Feel free to ping @WilliamDAssafMSFT manually in your PRs to get them attention.

Assuming this PR is still needed: 
MSFT employees on product teams can’t merge directly into sql-docs, we have to use the sql-docs-pr repository to make edits. Also, point at the `master` repo, not `live`. I know, the edit button on docs leads you straight to sql-docs. Entirely possible you've already installed this since July :) but just in case: to prevent creating PRs against sql-docs, you can install use this [browser extension in the Edge browser](https://review.docs.microsoft.com/en-us/help/contribute/contribute-tool-spineedit?branch=master) to redirect GitHub edit button links to use the -pr repo.

**Pull request closed without merging**
