### PR TITLE
Text update: Update ERRORFILE reference

### PR DESCRIPTION
**Pull request by raunakjhawar**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@raunakjhawar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@kevinvngo Kevin, can you take a look at these suggestions. If you agree, I can help get the merge conflicts resolved. Thanks for the feedback @raunakjhawar !

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@kevinvngo Kevin, hello. Could you take a look at the proposed changes in the public PR? If you are not the right contact, please let me know who to reach out to (and we can also reassign the article owner in that case). Thank you!

**Pull request closed without merging**
