### PR TITLE
REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT=0 with 3 replicas incorre…

### PR DESCRIPTION
**Pull request by dbrownems**
…ctly indicates automatic failover

### CODE REVIEW

**Comment by PRMerger6** [comment]
@dbrownems : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hey @MashaMSFT - Can you check this one? Thanks

**Comment by VanMSFT** [comment]
Following up with Product Team.

**Comment by VanMSFT** [comment]
Still waiting for an answer from the Product Team.

**Comment by VanMSFT** [comment]
Another follow-up with the Product Team

**Review by kfarlee — CHANGES_REQUESTED** [review]
In discussing this with the engineers that own the code, the original text is correct.
REQUIRED_SECONDARIED_TO_COMMMIT only impacts the completion of commits.  It does not change the type or conditions for failover.  With REQUIRED_SECONDARIES_TO_COMMIT=0 (the default for years), you can complete the failover, but you do have a risk of data loss if the failover target was not synchronized.

**Comment by dbrownems** [comment]
So if you set a replica to AUTOMATIC_FAILOVER mode but set  REQUIRED_SECONDARIES_TO_COMMIT=0 you can get automatic failover with the possibility of data loss?  If so shouldn't the doc mention that?

**Comment by kfarlee** [comment]
There is an !IMPORTANT box below which states "When REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT is 0 there is risk of data loss. "
That seems clear, however I'll add comments about possibility of data loss to the table wherever the SECONDARIES_TO_COMMIT = 0.

**Comment by MashaMSFT** [comment]
Hi @dbrownems , thank you so much for your submission, and our apologies for the delay! We've processed a change in the private repo to clarify this. As such, we're going to close out this PR, but thank you so much for your contribution!

I hope you have a wonderful rest of your day, and thank you for improving our docs :)
Masha from the SQL Docs team

**Pull request closed without merging**
