### PR TITLE
Update sys-database-scoped-configurations-transact-sql.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
The column is_value_default was added in MS SQL Server Version v2017.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@DanielAdeniji : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger15** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @DanielAdeniji! I made a quick change, and will approve this.

#sign-off

**Comment by DanielAdeniji** [comment]
Van:-

Thanks so very much.

In health and wholeness,

Daniel
________________________________

**Comment by PRMerger3** [comment]
@DanielAdeniji: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by DanielAdeniji** [comment]
Kristine Toliver & Van To:-

I checked sys.database_scoped_configurations (Transact-SQL). ( Link<https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-scoped-configurations-transact-sql?view=sql-server-ver15> )

It appears that the change is not quite in.

BTW, the change is

**is_value_default**|**bit** |Specifies whether the value set is the default value. Added in SQL Server 2017.|

That is "Added in SQL Server 2017."


[cid:b1454b5e-791e-4dad-88e5-969a50d5aa6a]

Thanks,

Daniel

________________________________

**Comment by DanielAdeniji** [comment]
Kristine:-

I am not pushing for it.

Or in any rush.

I received an email notification that it was merged and live.

I got mistakenly between live and published.

My anxiety is rooted in the fact that the change might have been lost.

Please take care of self and your loved ones above all.

And, sane, as well.

Which I am obviously failing at.

Daniel

________________________________

**Pull request merged**
