### PR TITLE
chore: Add initial gitattributes file

### PR DESCRIPTION
**Pull request by nschonni**
Didn't normalize the line endings since the diff was more than 5K files. That can get done afterwards by folder or as a big-bang on your internal repo by running `git add --renormalize .`

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@nschonni - Thanks for pointing this out. We currently don't accept public contributions to update files related to the repo configuration. I passed this information to our repo admins for consideration.

Thanks

**Comment by nschonni** [comment]
@stevestein that's OK, but it is something added to all the new repos https://github.com/MicrosoftDocs/feedback/issues/362#issuecomment-402889434 this repo was just setup before the templates got changed

**Comment by stevestein** [comment]
@nschonni - thanks for the link to the original issue. The repo admins for the SQL content will review.

**Comment by MightyPen** [comment]
For my own info, here is an article-link on GitHub that outlines the steps for handling lin endings:
.
https://help.github.com/articles/dealing-with-line-endings/

**Comment by nschonni** [comment]
https://www.edwardthomson.com/blog/advent_day_21_renormalizing_line_endings.html from the Azure DevOps group is also good too since I didn't know about the `--renormalize` flag before

**Pull request closed without merging**
