### PR TITLE
Replacing with "opaque box"

### PR DESCRIPTION
**Pull request by marktab**
Per https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/black-box replacing with "opaque box"

### CODE REVIEW

**Comment by PRMerger10** [comment]
@marktab : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@marktab Thank you! #sign-off

**Comment by PRMerger18** [comment]
@rothja: I'm sorry - only the author of this article, @s-r-k, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
