### PR TITLE
Update openrowset-transact-sql.md

### PR DESCRIPTION
**Pull request by waldyd**
Add additional example for csv files using MSDASQL Provider.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@waldyd : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @waldyd ,

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same. My apologies for the delay in initial response. 

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by PRMerger18** [comment]
@MashaMSFT : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@MashaMSFT : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @waldyd , thanks for your patience as we verified a few things on our end. I modified your example to add that the driver is necessary. Other than that, your example is great, and we appreciate your contribution! #sign-off 

Thanks again and I hope you have a wonderful rest of your day :)

**Comment by PRMerger16** [comment]
@Jak-MS : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Pull request merged**
