### PR TITLE
Update hints-transact-sql-query.md

### PR DESCRIPTION
**Pull request by lschmidt-chwy**
Corrected trace flag.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rwestMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
This PR is being reviewed by the product group. The trace flags are similar but not equivalent.

**Comment by rwestMSFT** [comment]
This PR is being closed, as the documented behaviour is correct. The language in the article will be updated in the future to clarify the use of TF 9481 and TF 2312.

**Comment by rwestMSFT** [comment]
#please-close

**Pull request closed without merging**
