### PR TITLE
Fix step 8 which requires the service be restarted

### PR DESCRIPTION
**Pull request by Matticusau**
For any changes to take effect we need to restart the SSDE service as we cannot log out the service account.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@Matticusau : Thanks for your contribution to the SQL documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@MightyPen can you please review.

**Comment by MightyPen** [comment]
@Matticusau Thank you for this correction, it will avoid confusion for our customers!
@craigg-msft Craig, I recommend we approve and Merge this public PR 240.
#sign-off

**Comment by craigg-msft** [comment]
Thank you @Matticusau  and @MightyPen

**Pull request merged**
