### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by nachoalonsoportillo**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@nachoalonsoportillo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rwestMSFT** [comment]
Hi Nacho, I believe at least one of these changes has already been made in a different PR. Do you mind refreshing your branch and double-checking this, so we can get it signed off?

**Comment by nachoalonsoportillo** [comment]
That's correct @rwestMSFT. It was indeed integrated as part of another PR. You can sign this one off. Thanks!

**Comment by rwestMSFT** [comment]
Fixed in another PR.

#please-close

**Pull request closed without merging**
