### PR TITLE
Update sql-server-on-azure-vm-iaas-what-is-overview.md

### PR DESCRIPTION
**Pull request by v-savila**
The Azure Portal GUI allows SQL Server 2014 SP3 SQL Server on Azure VM to be deployed, but the documentation says SP2 (see https://dev.azure.com/msft-skilling/Content/_workitems/edit/118749)

### CODE REVIEW

**Comment by MashaMSFT** [comment]
thanks @v-savila ! #sign-off

**Comment by Jak-MS** [comment]
@v-savila @MashaMSFT - can you address the merge conflicts? we'll need those resolved before we can review and merge. thanks.

**Comment by Jak-MS** [comment]
@MashaMSFT - after the merge conflicts are resolved, can you sign off again?

#hold-off

**Comment by Jak-MS** [comment]
cc @MicrosoftDocs/public-repo-pr-review-team

**Comment by MashaMSFT** [comment]
Hi @v-savila thanks for your submission! I'm going to pull your changes into the private repository to address these issues :) Thanks!

**Pull request closed without merging**
