### PR TITLE
Update docs to use lsb_release rather than hard coded distro

### PR DESCRIPTION
**Pull request by EvanCarroll**
Now we're not 16.04 specific.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@EvanCarroll : Thanks for your contribution to the SQL documentation! The author, @edmacauley, has been notified to review your proposed change.

**Comment by EvanCarroll** [comment]
Actually do not commit this. It's not currently working because Microsoft doesn't package SQL Server for 17.04. Lol.

> When there is a convention.. **BREAK IT.** - Microsoft.

**Comment by EvanCarroll** [comment]
There we go, now it should be fixed

**Comment by edmacauley** [comment]
Proposed changes to the automated install script don't work.  Two examples: the script must still be run with sudo and the sql server conf line fails as mssql is not in the sudoers list.  This is on a stock Ubuntu 16.04.  Current live script does work, in the author's opinion, changes to sample-unattended-install-ubuntu.md should not be merged.

Pinging @rothja as he's the author of the other article in this PR.

**Comment by edmacauley** [comment]
I do see what you mean by running sqlcmd as root, let me see if I can get a working version of the script, however.

**Comment by rothja** [comment]
@EvanCarroll Thanks for the detailed suggestions you've provided in these files. Ed and I are reviewing your changes, and we'll probably have a few tweaks to your recommendations before publishing. I have a few questions for you. 

First, I see you're adding a new repository that takes the output from lsb_release. So you have that there to anticipate Microsoft creating new binaries specifically for the verison you currently running that is greater than 16.04?

Second, is your only concern about running the script as root that we do some things as root that could be avoided, such as launching sqlcmd? Otherwise, most of the actions require sudo during the installation process anyway, right?

I think you're removing some of the apt-get update calls. I believe those are necessary to refresh the package lists before attempting to install. If that is not the case, let me know.

We might have other questions as we go through your changes. Thanks, again for helping to make the content better.

**Comment by EvanCarroll** [comment]
> mssql is not in the sudoers list. 

We're not running sudo as mssql, you run the script as any user. It runs the system utilities required as root, and the server and the client *as* `mssql`. @edmacauley

**Comment by edmacauley** [comment]
Hi Thanks again for these changes.  Right now we're going to need to not make most of your proposed changes.  I have incorporated your changes w/ sudo and they should be published live soon.  We cannot change the version language or repos at this time, we only officially support Ubuntu 16.04 right now.  The product team will need to review before we can make those changes and I don't have a timeframe for that right now.
#please-close

**Comment by rothja** [comment]
@EvanCarroll One of the problems we have at the moment is that many people are out for the holidays and we'll need to get some consensus on some of your suggestions. I'm out for the next week and a half as well. But I'll put this on my calendar to keep investigating your suggestions and talking to others about your repository recommendations. Thanks, again.

**Comment by EvanCarroll** [comment]
A couple of things, `mssql-tools` is i only in 16.04, and the method used in the dotnet distros of writing to files in sources.d rather than using apt-add-repository is better imho.

**Pull request closed without merging**
