### PR TITLE
Update dynamic-data-masking.md

### PR DESCRIPTION
**Pull request by Peter-Msft**
small typo fix

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Peter-Msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Peter-Msft** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@Peter-Msft: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@VanMSFT I usually merge typo fixes directly, but could you verify that the date should be updated? The **ms.date** attribute indicates the last time the article was reviewed for accuracy overall. Please check. Thanks!

**Comment by VanMSFT** [comment]
Thanks @ktoliver - I'm fine with merging as-is because we haven't done a full review on the article.

**Comment by ktoliver** [comment]
> Thanks @ktoliver - I'm fine with merging as-is because we haven't done a full review on the article.

Right. The contributor changed the date along with the typo fix. I'll revert the date and then merge. Thanks.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks, all.

**Comment by Peter-Msft** [comment]
@ktoliver @VanMSFT - Thanks for clarification on the date. I was not really sure if I should update it, but understand how it works now. Cheers!

**Comment by ktoliver** [comment]
@Peter-Msft - You bet. It's intuitive to change the date as last updated. 👍

**Pull request merged**
