### PR TITLE
Added Important Message

### PR DESCRIPTION
**Pull request by ChrisLound**
Added "Important" message for setting instance name to MSSQLServer for default instance when configuring the inventory database

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ChrisLound : Thanks for your contribution! The author, @HJToland3, has been notified to review your proposed change.

**Comment by HJToland3** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@GitHubber17 : Thanks for your contribution! The author, @HJToland3, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@GitHubber17 : Thanks for your contribution! The author, @HJToland3, has been notified to review your proposed change.

**Comment by HJToland3** [comment]
#sign-off

**Comment by GitHubber17** [comment]
@hjtoland3 - The PR is now merged. Thanks!

**Pull request merged**
