### PR TITLE
Update dma-sku-recommend-sql-db.md

### PR DESCRIPTION
**Pull request by robertlyson**
Hi 👋

The current link redirects to .NET 5 and this version won't let users run `SqlAssessment.exe`. Replaced with the link for 3.1.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@robertlyson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ajithkr-ms** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ajithkr-ms: I'm sorry - only the author of this article, @aciortea, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
