### PR TITLE
Value for adExecuteRecord missing

### PR DESCRIPTION
**Pull request by paweston70**
Added the value for **adExecuteRecord** 0x200 (512) to the ExecuteOptionEnum list.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@paweston70 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@paweston70 Thank you for this. How did you find the missing value? Testing or some other way?

**Comment by paweston70** [comment]
Hi Jason,

No problem at all! In fact, it was bugging me, so I had to have a look
around! I found it in some old documentation on a couple of sites (just to
confirm).

I didn't order the table, mind you - I suppose that will need doing, too.

PS: it is possible to plug the DLL into a classic ASP page and use the
constant values from that to confirm, also. I'll take a look in the morning
and see if I can find the method for that.

Kind regards,
Paul.

**Comment by rothja** [comment]
@paweston70 Paul, thanks for doing the research! Considering there is nothing but a blank there now, I think I will approve this based on your research. If you want to verify with more tests, that is great. Thanks, again, for helping us have better docs!

#sign-off

**Comment by paweston70** [comment]
Sorry Jason,

Indidnt managento get back to you today, too much on. I'll send you a link
to identifying the values tomorrow. It works, however - tested in code
today.

I think developers owe it to each other to keep the documentation up to
date as much as possible. I love the new approach of using repos to manage
doccos.

Good luck Jason.

Kind regards,
Paul.

**Comment by rothja** [comment]
Thank you! Just noting the additional change we made on this in a subsequent PR #6405. Thanks, again!

**Pull request merged**
