### PR TITLE
Update lesson-1-creating-database-objects.md

### PR DESCRIPTION
**Pull request by dadwill**
There was Lowercase letter in the query leading to error while Creating StoredProcedure. So , changes that and added a comment.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@dadwill : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by MikeRayMSFT** [comment]
@dadwill - thank you for this submission. We have to delete comments from the example because they are not localized.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request closed without merging**
