### PR TITLE
Update partner-hadr-sql-server.md

### PR DESCRIPTION
**Pull request by necamsbd**
Content changes to add entry for NEC HA/DR offerings for SQL Server.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@necamsbd : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@necamsbd - do you have a trademark or image you would like to have included in the first column? I don't see it in this pull request. Would you like to add it?

**Comment by necamsbd** [comment]
Hi Mike,

Yes, we have trademark on ExpressCluster and would like to add it.

Thank you,
George

**Comment by necamsbd** [comment]
Hi Mike,

Can you explain how to add the logo image (see attached)?   When I tried to upload the image last time I got an error saying I didn’t have permission.

Thank you,
George

**Comment by MikeRayMSFT** [comment]
@necamsbd It may be easiest to email the image to me. I sent my contact information in email.

Mike

**Comment by MikeRayMSFT** [comment]
@necamsbd - thank you for the submission. In order to facilitate the addition of the artwork, I manually updated your content. I will close this now.

**Comment by craigg-msft** [comment]
Thank you @necamsbd  and @MikeRayMSFT  closing

**Pull request closed without merging**
