### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by Blake-Madden**
Mostly misspellings

### CODE REVIEW

**Comment by Court72** [comment]
@blake-madden - Thanks for these fixes! I noticed instances where `containerd` has been changed to `contained`. I don't think those were typos. Can you confirm and revert those changes as necessary?

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Blake-Madden** [comment]
> @Blake-Madden - Thanks for these fixes! I noticed instances where `containerd` has been changed to `contained`. I don't think those were typos. Can you confirm and revert those changes as necessary?

@Court72 Sorry about that. I rolled those changes back.

**Comment by Court72** [comment]
@rwestMSFT 

Can you review the proposed changes? They fix some typos, but a few of the changes are in error code files.

**Comment by rwestMSFT** [comment]
@Blake-Madden Thank you for your contribution.

A number of these corrections include fixes to content generated from product source code. Therefore, they will be "wrong" again the next time the Markdown is generated, which renders your efforts moot.

We therefore won't be accepting this PR as-is, but I will speak to my colleagues and try to take into account some of the more obvious corrections.

**Comment by rwestMSFT** [comment]
@Blake-Madden Following on from my previous comment, we will be giving you credit for the changes you provided (your name will appear in the contributor list at the top of each article where we used your suggested edit).

We found an additional 80 articles with similar issues, so we do appreciate your contribution.

**Comment by Blake-Madden** [comment]
Awesome, thanks!

**Pull request closed without merging**
