### PR TITLE
Wording is confusing

### PR DESCRIPTION
**Pull request by thesqlpro**
"This service provide without user intervention – all from availability group setup, configuring database mirroring endpoints"
This wording is a little confusing. Are you saying that the service is provided this without user intervention?

### CODE REVIEW

**Comment by PRMerger15** [comment]
@thesqlpro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
The update looks correct. @mihaelablendea Can you confirm? Thanks.

**Comment by rothja** [comment]
@mihaelablendea Hello. Could you review the suggested changes in this pull request and see if you agree? If so, you can sign off. If not, let @thesqlpro know your ideas. + @MikeRayMSFT. Thank you!

**Comment by MightyPen** [comment]
@thesqlpro Hello Ayman, Thank you for both catching this error and fixing it for us and all Microsoft customers!
I like this PR #4711, and I am merging it now.

cc: @mihaelablendea

**Pull request merged**
