### PR TITLE
Update sql-server-connector-maintenance-troubleshooting.md

### PR DESCRIPTION
**Pull request by amitmsft**
Added information for 401 and 404 errors

### CODE REVIEW

**Comment by PRMerger8** [comment]
@amitmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@aliceku Can you please take a look at the changes @amitmsft is suggesting here? If you approve, please sign off in this PR. Thank you!

**Comment by jborsecnik** [comment]
@aliceku, can you review this PR? Thanks.

**Comment by rothja** [comment]
@VanMSFT Can you review this for @aliceku? Thanks!

**Comment by VanMSFT** [comment]
@jaszymas - Hey Jakub, can you help review this? Thanks!

**Pull request merged**
