### PR TITLE
Update columnstore-indexes-described.md

### PR DESCRIPTION
**Pull request by greenmodulus**
Just added space in first sentence

### CODE REVIEW

**Comment by PRMerger20** [comment]
@greenmodulus : Thanks for your contribution! The author, @mikeraymsft, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@greenmodulus - thanks for the fix!
#sign-off

**Comment by PRMerger18** [comment]
@stevestein: I'm sorry - only the author of this article, @mikeraymsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by stevestein** [comment]
update is fine. merging...

**Pull request merged**
