### PR TITLE
Update operators-in-expressions-report-builder-and-ssrs.md

### PR DESCRIPTION
**Pull request by JMCARY**
updated, table presentation merges left and right columns

### CODE REVIEW

**Comment by PRMerger15** [comment]
@JMCARY : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Hey, @JMCARY -- thanks for catching that!
#sign-off

**Comment by maggiesMSFT** [comment]
Hi, @jborsecnik -- what needs to happen to this PR, so it can be merged?

**Comment by maggiesMSFT** [comment]
Thanks, @jborsecnik !

**Pull request merged**
