### PR TITLE
Add missing option to command

### PR DESCRIPTION
**Pull request by dbadavekc**
add --generate-ssh-keys to the end of line 29. Without it, we receive the following message: "An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you"

### CODE REVIEW

**Comment by PRMerger19** [comment]
@dbadavekc : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by dbadavekc** [comment]
Edited initial comment to add more detail

**Comment by MikeRayMSFT** [comment]
@dbadavekc thank you for this submission! 
Our document has been updated but we still don't have the --generate-ssh-keys instructions in it.

I'm validating and will update.

**Comment by MikeRayMSFT** [comment]
Thank you - @dbadavekc for this submission.

**Pull request merged**
