### PR TITLE
Using AKV behind proxy

### PR DESCRIPTION
**Pull request by stummsft**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@stummsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@VanMSFT Hi Van,
This looks like an important public PR #3047 from a Microsoft employee, about **Security**. This PR 3047 is aging without getting the attention it needs/deserves. So I have added you as a Reviewer & Assignee to this PR.

Maybe you could glance at this PR, and help it make progress?
Thanks.  (GeneMi)

cc: @aliceku @stummsft

**Comment by VanMSFT** [comment]
@jaszymas - Hey Jakub, do you mind verifying the requested additions in this PR? Thanks!

**Comment by rothja** [comment]
@jaszymas Hello. Van is out of the office this month. Could you please take a look at the file changes in this PR and verify the change? If you approve, we can merge and publish. @stummsft Sorry for the delay. If you have internal confirmation of your changes, we can probably move ahead. Thanks!

**Comment by jaszymas** [comment]
The engineering team has reviewed the change and it looks good. Thank you for submitting it.

**Comment by jaszymas** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@jaszymas: I'm sorry - only the author of this article, @aliceku, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
