### PR TITLE
Update querying-data-in-a-system-versioned-temporal-table.md

### PR DESCRIPTION
**Pull request by JediSQL**
Modified the "AS OF" example to demonstrate the value of using AT TIME ZONE to convert a local time zone value for the SYSTEM_TIME expression. also added AT TIME ZONE for Next Steps (please check I did that correctly).

### CODE REVIEW

**Comment by rwestMSFT** [comment]
@JediSQL Thanks - if you can break that out into a completely separate example, I think it'll be an even better contribution!

**Comment by Court72** [comment]
@rwestMSFT 

Thanks for reviewing the proposed changes. 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@JediSQL I am closing this PR, because we identified that both articles you reference (see #8763) needed refreshment. Your changes will be incorporated into the refresh. You can expect to see the updated articles in the next day or so.

**Comment by rwestMSFT** [comment]
@JediSQL Thanks - I'll still comment here once I've refreshed all the articles in this area, because some of them haven't been looked at in a while.

**Comment by rwestMSFT** [comment]
@JediSQL We ran into an issue with the syntax and I've had to roll these changes back. I'll comment here once I've refreshed all the articles in this area, because some of them haven't been looked at in a while.

**Pull request closed without merging**
