### PR TITLE
Update dh2i-high-availability-tutorial.md

### PR DESCRIPTION
**Pull request by aravindmahadevan-ms**
Updating all the DH2i document links as they were broken/out dated.

OLD URL
https://dh2i.com/dxenterprise-availability-groups/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-dxadmin-client-ui-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-software-dxcli-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-ubuntu-installation-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-azure-extension-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-azure-marketplace-image-for-linux-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-rhel-centos-installation-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-azure-extension-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-azure-marketplace-image-for-linux-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-dxadmin-client-ui-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-mssql-availability-groups-with-dxadmin-quick-start-guide/ https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-0-software-azure-load-balancer-quick-start-guide/ https://dh2i.com/wp-content/uploads/DxEnterprise-v20-Admin-Guide.pdf https://dh2i.com/docs/20-0/dxenterprise/dh2i-dxenterprise-20-software-dxcli-guide/

New URL's Summary: 

https://dh2i.com/dxenterprise-high-availability/
https://support.dh2i.com/docs/guides/dxenterprise/general/dxe-admin-guide/ https://support.dh2i.com/docs/guides/dxenterprise/general/dxe-dxcli-guide/ https://support.dh2i.com/docs/guides/dxenterprise/installation/dxe-linux-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/azure/az-vm-extensions-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/azure/az-marketplace-linux-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/installation/dxe-linux-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/azure/az-vm-extensions-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/azure/az-marketplace-linux-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/general/dxe-admin-guide/ https://support.dh2i.com/docs/guides/dxenterprise/sql_server/mssql-ag-dxadmin-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/azure/az-load-balancer-qsg/ https://support.dh2i.com/docs/guides/dxenterprise/general/dxe-admin-guide/ https://support.dh2i.com/docs/guides/dxenterprise/general/dxe-dxcli-guide/

### CODE REVIEW

**Comment by Court72** [comment]
@amitkh-msft 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@Court72 this can be signed off.

**Comment by Court72** [comment]
@amitkh-msft,

Can you `#sign-off` when you're ready to publish these changes? Thanks!

**Comment by rwestMSFT** [comment]
@Court72 Please go ahead and sign this off. I don't have permission.

**Pull request merged**
