### PR TITLE
Clarifying that ALTER TABLE ALTER COLUMN requires UPDATE

### PR DESCRIPTION
**Pull request by dbrownems**
EG 
use tempdb
go
revert 
go
if exists(select * from sys.database_principals where name = 'fred')
  drop user fred
go
drop table if exists tablename
go
create user fred without login

create table tablename(id int, variablename varchar(20))
go
grant select on tablename to fred 
--grant update on tablename to fred  --uncomment to clear error
grant alter on schema::dbo to fred

execute as user='fred'
  ALTER TABLE dbo.tablename ALTER COLUMN variablename datetime2
revert

### CODE REVIEW

**Comment by PRMerger15** [comment]
@dbrownems : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@dbrownems Thank you. I'm taking a look at your suggested change. #reassign:rothja

**Comment by rothja** [comment]
@dbrownems Thanks for this clarification! #sign-off

**Comment by PRMerger9** [comment]
@rothja: I'm sorry - only the author of this article, @CarlRabeler, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
