### PR TITLE
Fix code block

### PR DESCRIPTION
**Pull request by yoichinak**
English pages are OK. However, the Japanese translation misses the end of the code block and stops.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@yoichinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PiJoCoder** [comment]
@MashaMSFT could you take a look or engage someone from review team to check?

**Comment by MashaMSFT** [comment]
Hello! Thanks for bringing this to our attention! This actually seems to be a localization issue vs an article issue, so I don't believe merging this change is the appropriate method to resolve this. Let me research this a bit further...

Thanks!
Masha from the SQL Docs team

**Comment by rothja** [comment]
#assign:mashamsft Masha, I'm adding you as an assignee since you're looking into whether there is anything we can do on our end. If it is a localization issue and we've reported it, we probably would close this PR. Thank you!

**Comment by PRMerger10** [comment]
@MightyPen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@yoichinak Hello Yoichi, Thank you for these fixes, handily provided by you here in your PR #4738!
I like these changes, and I will now Merge your PR.

cc: @MashaMSFT

**Pull request merged**
