### PR TITLE
Update database-copy.md

### PR DESCRIPTION
**Pull request by kv-prajapati**
Fixed the "Remove-AzSqlDatabase" URI

### CODE REVIEW

**Comment by PRMerger12** [comment]
@kv-prajapati : Thanks for your contribution! The author(s) have been notified to review your proposed change. @LitKnd

**Comment by Court72** [comment]
@rothja, @MashaMSFT  

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

Note that the `author` and `ms.author` metadata should be updated in the private repo to reflect the current author.

Thanks!

#label:"aq-pr-triaged"

**Comment by rothja** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@rothja: I'm sorry - only the author of this article, @LitKnd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
