### PR TITLE
Grammatical changes to dma-overview.md

### PR DESCRIPTION
**Pull request by edorado93**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@edorado93 : Thanks for your contribution! The author, @HJToland3, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Merging grammar fixes

@edorado93 Thanks

**Comment by HJToland3** [comment]
#sign-off

@ktoliver, please let me know if you need any other form of acknowledgement.  Thanks!

**Comment by ktoliver** [comment]
@HJToland3 - Nothing else is needed. PR reviewers might directly merge public repo PRs that fix typos, spelling errors, grammar, and broken links, per @tysonn. Thank you.

**Pull request merged**
