### PR TITLE
Warning for FCI Nodes with different SQL builds

### PR DESCRIPTION
**Pull request by taiyebzakir**
Modified Warning section and added this note:

When you have Distribution DB in FCI, then make sure all participating nodes are on the same build.  We don’t recommend setup where one node is on SQL Version lower than SQL Server 2016 SP2-CU3 or SQL Server 2017 CU6 and other node on SQL Version greater than SQL Server 2016 SP2-CU3 or SQL Server 2017 CU6. From SQL Server 2016 SP2-CU3 and SQL Server 2017 CU6 version onwards we have added support for Distribution DB in Availability group and to achieve that new objects (tables, stored procedures) have been added to Distribution database. If your Distribution DB is in FCI and you are going through phased migration (and cannot upgrade all nodes to same SQL Version) then for that narrow timeframe we recommend you to do activities like adding a new subscriber/subscription/publisher/publication on the node with higher SQL Version.

### CODE REVIEW

**Comment by cawrites** [comment]
@taiyebzakir we will review this change.

**Comment by cawrites** [comment]
@Kevin-Farlee can you review this change?

**Comment by Kevin-Farlee** [comment]
You send me a link to the PR?

**Comment by ktoliver** [comment]
> You send me a link to the PR? 

@Kevin-Farlee https://github.com/MicrosoftDocs/sql-docs/pull/6751

**Comment by kfarlee** [comment]
This looks good to me.  I approve.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
> This looks good to me. I approve.

Thanks @Kevin-Farlee. I've edited for grammar and Microsoft style. Does this look good to merge or does it need further revision?

https://github.com/MicrosoftDocs/sql-docs/pull/6751/files

Thanks.

**Pull request merged**
