### PR TITLE
Adding comment on Builtin\Administrator account

### PR DESCRIPTION
**Pull request by clayton006**
Adding wording around the Builtin\Administrator account and the results of removing that from the current versions of SQL Server on Linux.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@clayton006 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by amvin87** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@amvin87: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by VanMSFT** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @ktoliver! I edited the text.

#sign-off

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
