### PR TITLE
DMS goes to quiet period for 90 minutes if Polybase Engine is restart…

### PR DESCRIPTION
**Pull request by macarv-ms**
…ed more than twice.

I believe most customers that are going to try scale out group will probably be facing this behavior during installation, and it might generate some confusion if not documented.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@macarv-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by macarv-ms** [comment]
@PiJoCoder can you check?

**Comment by PiJoCoder** [comment]
@macarv-ms  - sent you an email with comments

**Comment by PRMerger12** [comment]
@macarv-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by macarv-ms** [comment]
Thanks @PiJoCoder! Updated as per your review.

**Comment by PiJoCoder** [comment]
Looks great

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
