### PR TITLE
Add documentation to install SQL Server on Linux (Debian based distribution)

### PR DESCRIPTION
**Pull request by ChristianGrimberg**
Hello and nice to meet you.

I write this documentation to install SQL Server in Linux into Debian based distributions.
> I copy the content of the documentation of Ubuntu instalation guide, and changes the comands (_there are some changes_) and I change each point from Ubuntu to Debian 9 reference.

I hope you check this before, and please share with all the community.

> Thanks for all, and sorry for my english :pray: 
> Microsoft :heart: Linux and SQL Server Rocks :muscle:

### CODE REVIEW

**Comment by PRMerger18** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by rothja** [comment]
@ChristianGrimberg Hello, and thank you for this submission. I'm not sure why it was closed automatically on you. However, I'm not sure we can publish this in Docs, because Debian 9 is not one of the three tested/supported distributions of SQL Server on Linux. This might make a great blog post though if you had a blog? I'll double check with the product team and leave this open while I do. Thanks, and sorry for the answer.

**Comment by PRMerger8** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by ChristianGrimberg** [comment]
Nice to meet you @rothja and thank you for your answer honestly. I'm going to write a blog (_I'll upload it as a Gist_) about the implementation of SQL Server in Linux distributions based on Debian, which usually exists a lot of them that can make use this very popular database .

When I have the Gist ready, I will be sharing them in this conversation as well. Once again, thank you very much and a special greeting to the entire team.
> Sorry for my bad English.

**Comment by rothja** [comment]
@ChristianGrimberg Thank you for understanding! I'll let you know if I here anything different. Maybe you could post the link here after you blog about it? Also, your English is excellent! :) Thanks !

**Pull request closed without merging**
