### PR TITLE
chore: Cleanup Microsoft links

### PR DESCRIPTION
**Pull request by nschonni**
Ran script from MS Docs Authoring Pack.
- HTTP -> HTTPS
- Removes link locale

### CODE REVIEW

**Comment by ktoliver** [comment]
@craigg-msft @MikeRayMSFT @rothja @MightyPen - Could you review the PR? If you accept the submission, PR reviewers can move the commit to the private repo for validation and staging. Thanks.

**Comment by MightyPen** [comment]
@nschonni Hi Nick, This public PR 2451 looks pretty good.  I looked through about 25% of it.  The hassle is that the GitHub Differ often tells us only that there was a change somewhere in this or that large paragraph; without highlighting the changed characters in the paragraph.  It is therefore a tiring challenge for the human eye to be thorough.
We are considering approving this PR.

@v-thepet Hi Theano, This PR 2451 could be closely related to CATS work you had been doing. Could you spend 5-10 minutes looking at this 'Files changed' tab, and then enter a new Comment here to say whether your samplings suggest we Approve vs Disapprove?  If you cannot work on this type of PR, I will understand, just tell me so. Thanks.

**Comment by nschonni** [comment]
PS: this is the script part that I mentioned used for this https://github.com/microsoft/vscode-docs-authoring/tree/develop/docs-markdown#cleanup-scripts
You can see what regexes it runs here https://github.com/microsoft/vscode-docs-authoring/blob/9feda42b85b962e0418dd46fb2effb815f14a9f9/docs-markdown/src/controllers/cleanup-controller.ts#L536 in case you want to run it manually instead

**Comment by rothja** [comment]
@v-thepet Theano, have you had a chance to look at Gene's question on this PR? Thanks!

**Comment by MikeRayMSFT** [comment]
Due to the many merge conflicts, I think we'll need to close this, and run again in a new copy of the repository. @nschonni  could you do that, and open a new PR? I'll watch for it and review it quickly.

**Comment by nschonni** [comment]
I'll rebase this and ping you when I'm home

**Comment by nschonni** [comment]
@MikeRayMSFT I've rebase this and force pushed to resolve the conflicts

**Comment by ktoliver** [comment]
We're in the process of pulling these commits to the private repo, so we can verify the content on staging. We'll post a new PR # shortly and then close this PR.

**Comment by ktoliver** [comment]
@nschonni @MightyPen @MikeRayMSFT @rothja - Private repo PR 11506 replaces this PR. We'll validate the updated URLs on staging in the private repo PR and reach out to content owners if needed. We'll close this PR now. Thanks!

**Pull request closed without merging**
