### PR TITLE
Added note about avoiding the Azure account error

### PR DESCRIPTION
**Pull request by angdesign**
Per feedback from Alan, deleting the old install directory before installing the latest version helps avoid the issue of not being able to connect to your Azure account for the resource explorer.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@angdesign : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@angdesign : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by angdesign** [comment]
Text moved to the 'Move user settings' region

**Comment by yualan** [comment]
This looks good to me, let's take this change Steve :) Thanks Andrew!

**Comment by stevestein** [comment]
@angdesign - Thanks for making the update! And thanks @yualan for the review.

#sign-off

**Pull request merged**
