### PR TITLE
Update sqldev-operationalize-the-model.md

### PR DESCRIPTION
**Pull request by CastielWong**
"PredictTipBatchMode" should be "PredictTip" since only the “PredictTip.sql” Stored Procedure was downloaded. 
Either change the name in this document or update and rename "PredictTip.sql" file inside "https://raw.githubusercontent.com/Azure/Azure-MachineLearning-DataScience/master/Misc/RSQL/" to keep consistent

### CODE REVIEW

**Comment by PRMerger13** [comment]
@CastielWong : Thanks for your contribution! The author, @HeidiSteen, has been notified to review your proposed change.

**Comment by HeidiSteen** [comment]
#sign-off on the update.  Thanks @CastielWong!

**Comment by HeidiSteen** [comment]
#hold-off

**Comment by HeidiSteen** [comment]
#hold-off  sorry just remembered there is an embargo on PR sign-off for the next couple hours.

**Comment by HeidiSteen** [comment]
#sign-off

**Pull request merged**
