### PR TITLE
ParallelUploadDownload changes

### PR DESCRIPTION
**Pull request by briancarrig**
Changes for deprecating ParallelUploadDownload

### CODE REVIEW

**Comment by PRMerger15** [comment]
@briancarrig : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@briancarrig : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@briancarrig : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
pulled this change into private PR 18065, closing public PR

**Pull request closed without merging**
