### PR TITLE
Update configure-distributed-availability-groups.md

### PR DESCRIPTION
**Pull request by BIGabor**
Distrubuted AOG status check query changed.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@BIGabor : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @BIGabor , thank you so much for your contribution! Let me confirm that there are no issues with this script - and so far there seem to be none, and then we can approve it :) Thanks!

**Comment by BIGabor** [comment]
> 
> 
> Hi @BIGabor , thank you so much for your contribution! Let me confirm that there are no issues with this script - and so far there seem to be none, and then we can approve it :) Thanks!

Ok. Included more columns compare to original query, those are usable when you are waiting for a sync. Lag seconds, etc.

**Comment by MashaMSFT** [comment]
Hi @BIGabor , thanks again for your submission! I did some research and it looks like the intent of the query during this step is to be super simple - we just want to show that we're ready for the next step. Additionally complexity in the result set may detract from the goal, and/or cause unnecessary confusion. As such, though the query you've provided is really helpful in other scenarios, it would be considered out of scope for this particular step.  However, since you've also submitted this query as a Git Issue also, it is visible to anyone who visits the page, and so they may benefit from it, without adding it to the documentation. 

Having said that, the query you've written would be a useful addition to this doc, under a "explore health of a distributed ag" heading: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/dynamic-management-views-and-system-catalog-views-always-on-availability-groups?view=sql-server-ver15

Did you want to add it there? Or if not, I can add it there as well :)
Either way, I'm going to proceed with closing out this particular PR, but please feel free to comment if you need anything else!

Thanks again for helping improve our documentation!
Masha from the SQL Docs team

**Comment by BIGabor** [comment]
Hi Masha

ok, I will do some testing on weekend, and yes, that end of log lsn should
be changed to last redone lsn. Plus I have another script for step 4, to
check status on secondary(forwarder) too. Testing on weekend with failover,
and I will share it.
Another problem with this simple script. No dbname, no replicaname, just
ids. But who knows which id belongs to which server. This failover is
timecritic, I don't want to execute  individual lookup scripts. We have
more groups, with more dbs, that's why filtering for distributed is good. I
want to know, which db is in which state, ok, not in step 4. If you have
big delays in step 4, that's a problem. And it would be more simple, if the
same script could be used for both. So I would like to display all the
required info in case of problem. If it's in sync, it's ok, than you need
only two columns. Ag.name, and state. But if you have problems, I need db
name, lsn, lag secs(not in step 4), etc. Plus we have async replicas too in
normal AGs belongs to distributed AG replica. If those are not in sync
state, doesn't matter. The primary and secondary(forwarder) distributed
nodes should be in sync only during this failover.
So feedback on next Monday.

Regards,
Gabor

**Pull request closed without merging**
