### PR TITLE
Update create-server-audit-transact-sql.md

### PR DESCRIPTION
**Pull request by JMNetwalker**
I added some updates in the documentation due to several options are not supported in Azure SQL Managed Instance

### CODE REVIEW

**Comment by Court72** [comment]
@sravanisaluru

Can you review the proposed changes? Note that the validation warning must be resolved and the "Notes" on lines 76, 83, 87, 91, and 100 need to use Markdown `[!NOTE]` syntax before merging.

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by JMNetwalker** [comment]
Thanks Team,

I’ve done the changes. Could you please review it?

Thanks,

Jose Manuel Jurado Diaz
Escalation Engineer

***@***.***
Data & Governance Platform (DGP) Delivery Excellence
Work : +34 913919455 | ***@***.******@***.***>
Madrid, Spain (Central European Summer Tme)  aka.ms/DGP<http://aka.ms/dgp>
[A white butterfly on a green background  Description automatically generated]  “the smallest change can lead to the biggest transformation…”

**Comment by rwestMSFT** [comment]
The notes don't follow our style guide.

I'll review this next week, once the content freeze is over for our Ignite conference.

#reassign:rwestMSFT

**Comment by JMNetwalker** [comment]
Thanks Team,

I followed up and resolved the recommendations. Please, let me know what I need to change it is important because it is not well documented what are possible to use in SQL Server and Azure SQL Managed Instance.

Thanks,

Jose Manuel Jurado Diaz
Escalation Engineer

***@***.***
Data & Governance Platform (DGP) Delivery Excellence
Work : +34 913919455 | ***@***.******@***.***>
Madrid, Spain (Central European Summer Tme)  aka.ms/DGP<http://aka.ms/dgp>
[A white butterfly on a green background  Description automatically generated]  "the smallest change can lead to the biggest transformation..."

**Comment by rwestMSFT** [comment]
@JMNetwalker I wasn't aware that you're a Microsoft employee. I will move your changes to an internal PR and close this one.

**Pull request closed without merging**
