### PR TITLE
Update select-transact-sql.md

### PR DESCRIPTION
**Pull request by HugoKornelis**
See https://github.com/MicrosoftDocs/sql-docs/issues/4764

### CODE REVIEW

**Comment by PRMerger17** [comment]
@HugoKornelis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hey @HugoKornelis - Thanks for this, but `column_positio` and `[ ,...n ]` should not be removed. It is part of the syntax. https://docs.microsoft.com/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql. I think carets make more sense in this case.

**Comment by HugoKornelis** [comment]
Hi Van To,

Please read the issue I raised earlier and its comments. Then carefully 
review my proposed change. You will see that |column_position| and |[ 
,...n ]| are both included in the detailed description of the ORDER BY, 
on page 
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15

My proposed change makes it clear that users should check that page for 
the syntax details. This solves issue 4764.

Frankly, it really should not be this difficult for users to contribute 
a simple improvement to your documentation.

Regards,
Hugo

Op 21-10-2020 om 15:56 schreef Van To:

**Comment by PRMerger9** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks, @HugoKornelis! I see your point. I'll go ahead and approve the changes. Thanks again for taking the time on this.

#sign-off

**Pull request merged**
