### PR TITLE
typo: Deactive -> Deactivate

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by TrishaMc** [comment]
Hi @craigg-msft:
You're listed as a contributor on all of these articles. Would you review the proposed changes? 
Thanks,
Trisha

**Comment by markingmyname** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@markingmyname: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
