### PR TITLE
typo: Missing forward slash in URL

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
Thank you @nschonni for fixing that typo. #sign-off

**Comment by PRMerger16** [comment]
@edmacauley: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by stevestein** [comment]
@nschonni , @edmacauley - thanks!

#sign-off

**Comment by PRMerger10** [comment]
@nschonni : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by nschonni** [comment]
@ktoliver thanks for fixing the part I missed

**Pull request merged**
