### PR TITLE
AlwaysOn is not availability groups

### PR DESCRIPTION
**Pull request by rabryst**
Plus, there's a space.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@rabryst : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@VanMSFT Hi Van, This aging (30 days old) public PR 2395 removes a couple improper space characters.
Also, it changes "AlwaysOn" to two words "Always On".
Also, it alters one H2:

```
BEFOR: ## Considerations for AlwaysOn and Database Migration
AFTER: ## Considerations for Availability Groups and Database Migration
```

If you agree with all these small changes, can you please Sign Off (or somehow get this PR merged), for the PM @jaszymas .
Thanks. G.

**Comment by MightyPen** [comment]
#sign-off 

MashaMSFT and I agree, sign off.
@PRMerger20   Can you, or anyone, please merge this PR today.

**Comment by PRMerger10** [comment]
@MightyPen: I'm sorry - only the author of this article, @jaszymas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
@PRMerger10 We need a better answer than this. Can you please work with TysonN to get us a better answer.  Thank you.

**Comment by MightyPen** [comment]
Exception email has now been sent, to 'techdocprs'.  Thanks.

**Pull request merged**
