### PR TITLE
Update linked-servers-database-engine.md

### PR DESCRIPTION
**Pull request by denniwil**
Removing outdated reference to Access and Excel as this was only supported when using the Microsoft.Jet.OLEDB.4.0 OLE DB provider. Modern versions of Access and Excel use the Microsoft.ACE.OLEDB.12.0 OLE DB provider which is not supported for server-side, non-interactive user use.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@denniwil : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @denniwil for contacting Microsoft with feedback about our product documentation. It could take from a few business days to a few weeks to confirm your change internally. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

By opening a pull request, you're helping the author add your approved change directly to the documentation. If the article is updated with your commit, GitHub will list you as an article contributor.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
@denniwil It is possible to create a linked server using ACE12 to an .xlsx file using SQL Server 2019, so we won't be publishing this change, but could you be more detailed on the incompatibilities or unsupported scenarios you mention?

**Comment by WilliamDAssafMSFT** [comment]
Published in https://github.com/MicrosoftDocs/sql-docs-pr/pull/20668

**Pull request closed without merging**
