### PR TITLE
Typo in azure link

### PR DESCRIPTION
**Pull request by alekseybochkov**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@alekseybochkov : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @edmacauley, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by edmacauley** [comment]
Good catch @alekseybochkov thank you for fixing this.  #sign-off

**Pull request merged**
