### PR TITLE
Adding guidance around ALTER TABLE for CHECK CONSTRAINTs

### PR DESCRIPTION
**Pull request by Jehoel**
Details provided by (former?) SQL Server team member David Browne here: https://dba.stackexchange.com/a/298456/10044 (while it's about Temporal Tables, it also applies to CHECK constraints).

I stress that this is only a first-draft - as the language I used is not exactly complimentary to SQL Server I'm prepared for it to be fully rewritten by someone in a _corporate-speak_-compliant manner.

-----------

I was wondering if maybe this guidance could be rewritten to a smaller boilerplate paragraph (as one of those purple advisories) and added to every `sql-docs` article that uses `ALTER TABLE` or takes a Schema Modification lock, such as enabling/disabling `SYSTEM_TIME` in temporal tables.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@Jehoel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@Jehoel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Jehoel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by WilliamDAssafMSFT** [comment]
Thanks @Jehoel for the time and attention paid to our documentation. I will close this PR and incorporate your commits into a PR to add additional guidance here. A doc update is in review. When published, GitHub will list you as an article contributor. Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by Jehoel** [comment]
@WilliamDAssafMSFT Alrighty - I assume you'll `@`-me in your PR so I get notified?

**Comment by WilliamDAssafMSFT** [comment]
@Jehoel Internally, we develop in a preview repository which is not visible to the public, and allows us to work in and preview the merged doc changes in a private repository and site build. I'll ping back here when the doc update is live.

**Comment by WilliamDAssafMSFT** [comment]
@Jehoel Updated guidance is in place: https://docs.microsoft.com/en-us/sql/relational-databases/tables/disable-check-constraints-with-insert-and-update-statements

**Pull request closed without merging**
