### PR TITLE
Typo "Azure blob storage"→"Azure Blob Storage"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-server-audit-transact-sql?view=sql-server-ver15

### CODE REVIEW

**Comment by PRMerger8** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@VanMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hey @hyoshioka0128 - Thanks for making this change. Blob is supposed to be capitalized, but storage should not be. https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction

I've made the changes and will approve this PR. Thanks for your contribution!

#sign-off

**Comment by ktoliver** [comment]
Hi @VanMSFT The Microsoft Cloud Style Guide (internal resource) currently says to capitalize "Storage" in "Azure Blob Storage." The entry was updated last year; it previously said to use "Azure Blob storage." If you have a chance to look at the entry in the style guide, could you let me know if you agree?

**Pull request closed without merging**
