### PR TITLE
Depending on physical_name it would render a conversion error

### PR DESCRIPTION
**Pull request by FreddyAngarita**
I Addded try_cast to substring part because it avoids to generate an error if it encounters a value that is not convertible to int

### CODE REVIEW

**Comment by PRMerger20** [comment]
@FreddyAngarita : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@FreddyAngarita Thank you for the suggestion. @ronortloff Ron, could you take a look at this public PR suggestion and see if you approve or have comments? Thank you!

**Comment by ronortloff** [comment]
@FreddyAngarita have you hit an error using the example or trying to enhance the code to make it more robust?  Try_cast in this case could cause someone to miss data when an error may be a valid outcome.

**Comment by FreddyAngarita** [comment]
> @FreddyAngarita have you hit an error using the example or trying to enhance the code to make it more robust? Try_cast in this case could cause someone to miss data when an error may be a valid outcome.

Yes When I tried this command on a table that may have "exotic" names it redenred an error. So i needed to add the try_cast to continue query execution

**Comment by julieMSFT** [comment]
@FreddyAngarita Since this was a work around due to your "exotic" names we do not feel the article needs updating and may cause data to be missed. Thank you for submitting the change to Microsoft Docs. We hope to hear from you again. I will go ahead and close this PR.

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
#please-close

**Pull request closed without merging**
