### PR TITLE
Resolve syncing conflicts from FromPrivateRepo to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from FromPrivateRepo to live.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@huypub : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Resolved merge conflict to reflect https://github.com/MicrosoftDocs/sql-docs-pr/pull/19584.

**Comment by ktoliver** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ktoliver: I'm sorry - only the author of this article, @vasubhog, @yualan, @WilliamDAssafMSFT, @cawrites, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
We'll merge this conflict resolution PR.

**Pull request merged**
