### PR TITLE
Update tedious connection config

### PR DESCRIPTION
**Pull request by David-Engel**
Tedious connection config options changed. The docs need to be updated to reflect the new config format.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@David-Engel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@David-Engel, this pull request is for the live branch. We can't merge to Live. Would you resubmit your changes to the master branch? Thanks.

**Comment by David-Engel** [comment]
@jborsecnik I thought that was the process and tried to select master, but there was no master branch in the list:

Branches

**Comment by David-Engel** [comment]
@jborsecnik Here's my entire list. Which branch should I use?

Branches

**Comment by jborsecnik** [comment]
@David-Engel, for help, see https://docs.microsoft.com/en-us/contribute/.

**Comment by David-Engel** [comment]
> @David-Engel, for help, see https://docs.microsoft.com/en-us/contribute/.

@jborsecnik I've read that. It's not helpful here. How can I submit to the master branch when it does not exist?

@MightyPen This is the fix for issue #2389. Feel free to take my change and apply it to the private repo.

**Comment by MightyPen** [comment]
This fix was transferred to private repo PR 11187.

**Pull request closed without merging**
