### PR TITLE
add details for oracle in release notes page

### PR DESCRIPTION
**Pull request by MSraye**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@MSraye : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
CAUTION:
This PR 1857 is Not ready to be accepted.

I see 'en-us/' as a node in some of the 'microsoft.com' links that are added by this PR 1857: but such locale nodes are not allowed.  Please just remove those locale nodes.

Thanks. GeneMi.

**Comment by MightyPen** [comment]
@stevestein @MSraye 
CAUTION:
This PR 1857 is Not ready to be accepted.

I see 'en-us/' as a node in some of the 'microsoft.com' links that are added by this PR 1857: but such locale nodes are not allowed. Please just remove those locale nodes.

Thanks. GeneMi.

**Comment by ktoliver** [comment]
Hi @MightyPen - The [pull request quality criteria](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master) mentions removing locales from some specific Microsoft URLs:

image

There are some other Microsoft domains in which links won't work if you remove the locale. We wouldn't be able to know if that the case for these microsoft.com download links without testing them, either on staging or on the live site. FYI.

**Comment by MSraye** [comment]
+Junxiao

**Comment by MSraye** [comment]
Hi,

The msi installer contains many language packs and will auto detect the platform language then install. So there's only en-us download page for this installer. I think the locale in the link should not be removed so everyone will go to en-us download page.

Thanks,
Junxiao

From: Ran Ye <raye@microsoft.com>
Sent: Monday, April 8, 2019 11:09 AM
To: MicrosoftDocs/sql-docs <reply@reply.github.com>; MicrosoftDocs/sql-docs <sql-docs@noreply.github.com>; Junxiao Ma <jum@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/sql-docs] add details for oracle in release notes page (#1857)

+Junxiao

**Comment by MightyPen** [comment]
Merging now.
.
@MSraye Hi Ricky, I understand your point.
I then tried the link with the kind of explicit locale node that a French person in France would implicitly be forced to try, and the link failed with node 'fr-fr/'.  Therefore I also accept and agree with your point.
.
Thanks. GeneMi.
.
CC: @ktoliver

**Pull request merged**
