### PR TITLE
update previous releases for SSDT forVS2017 15.9.2

### PR DESCRIPTION
**Pull request by MSraye**
update previous releases for SSDT forVS2017 15.9.2

### CODE REVIEW

**Comment by PRMerger20** [comment]
@MSraye : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevestein** [comment]
#hold-off 

DO NOT MERGE YET

**Comment by stevestein** [comment]
#sign-off

**Comment by stevestein** [comment]
@jborsecnik - and this one. 

Is the assessing label causing these to get hung up or is automation not working to get the ready to merge label added today?

**Pull request merged**
