### PR TITLE
Updated to correct mount path

### PR DESCRIPTION
**Pull request by jsturtevant**
Running as is caused error "Kernel bug check: No such file or directory" error:

```
This program has encountered a fatal error and cannot continue running at Wed Nov 27 19:00:23 2019
The following diagnostic information is available:

         Reason: 0x00000006
        Message: Kernel bug check
        Address: 0x6a847d60
     Parameters: 0x10861f590
    Stack Trace:
                 000000006a93539e
                 000000006a847dbb
                 000000006a83447e
                 000000006a843025
                 000000006a8431f6
                 000000006a93366c
                 000000006a9321df
                 000000006a9755d1
        Process: 8 - sqlservr
         Thread: 12 (application thread 0x4)
    Instance Id: f07ce1aa-41f5-478a-8dca-c19e30791522
       Crash Id: 3e2b160d-7399-476f-b177-d861115f74b7
    Build stamp: 80fb92dd4d876182c7b8d6d599e31b3f6d91efe87f8c1bb6540962021ef4b921
   Distribution: Ubuntu 16.04.6 LTS
     Processors: 2
   Total Memory: 7284359168 bytes
      Timestamp: Wed Nov 27 19:00:23 2019
     Last errno: 2
Last errno text: No such file or directory
```

Updating to include data directory based on fix: https://github.com/microsoft/mssql-docker/issues/441#issuecomment-533057362

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jsturtevant : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@jsturtevant - thank you. Verifying.

**Comment by vin-yu** [comment]
@jsturtevant - I was able to deploy SQL Server 2017 and 2019 latest with the instructions in the docs. At the time of your discovery of this issue, what image tag were you using? 

Thanks,
VIn

**Comment by MikeRayMSFT** [comment]
@jsturtevant - I'm going to close this issue for now as we haven't reproduced the issue. Feel free to open it again if it reproduces with current images in your environment.

**Pull request closed without merging**
