### PR TITLE
Update assign-alerts-to-an-operator.md

### PR DESCRIPTION
**Pull request by himanshu-ram-punjabi**
Adding space between 'Operator Name' and 'Properties'.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@markingmyname 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by markingmyname — APPROVED** [review]

**Comment by markingmyname** [comment]
#sign-off

**Comment by markingmyname** [comment]
#sign-off

**Comment by markingmyname** [comment]
#sign-off

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
