### PR TITLE
Describe side effects of Disable Login

### PR DESCRIPTION
**Pull request by brettshearer**
There are few references to this internal locks. Getting this information into sql-docs will help other developers when searching for relatively undocumented locks.

### CODE REVIEW

**Comment by Court72** [comment]
@VanMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Checking with the Product Group.

**Comment by VanMSFT** [comment]
Following-up with PG again.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
The current proposed text states that disabling a login, which takes a `SERVER_PRINCIPAL` metadata lock, will "stop statements being run by the login on other connections." However, it's not entirely clear whether this refers to stopping new statements from starting, or halting currently executing statements.

For better clarity, I suggest we revise this to explicitly state that this lock prevents the initiation of new statements, but doesn't typically interfere with statements that are already running at the time of disabling the login. For example, we might say:

"Disabling a login in SQL Server acquires a `SERVER_PRINCIPAL` metadata lock. This lock specifically blocks new statements from being initiated by the login on other connections, but doesn't typically halt or interfere with statements that are already in execution at the time of disabling the login."

Ideas?

**Comment by VanMSFT** [comment]
Thanks, @0x7FFFFFFFFFFFFFFF for the suggestion. We'll revise the text once we get more information and confirmation from the Product Team.

**Comment by VanMSFT** [comment]
Hi @brettshearer, sorry for the delay! I confirmed with our Product Team that this metadata lock behavior is not something we will document. I apologize for the inconvenience.

**Pull request closed without merging**
