### PR TITLE
Typo "&#40;Database Engine&#41;"→"\(Database Engine\)"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/t-sql/data-types/tostring-database-engine?view=sql-server-ver15
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger12** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by hyoshioka0128** [comment]
@ktoliver - Thank you as always.
Since the ja-jp page had a strange Japanese translation, I made a Pull Request for the source code of the en-us page. 
ja-jp:
tostring-database-engine_j

en-us: https://docs.microsoft.com/en-us/sql/t-sql/data-types/tostring-database-engine?view=sql-server-ver15
tostring-database-engine_e

**Comment by ktoliver** [comment]
Looks good; thanks @hyoshioka0128.

**Pull request merged**
