### PR TITLE
Update availability of partition features for SQL 2016 SP1

### PR DESCRIPTION
**Pull request by SvenAelterman**

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @SvenAelterman for the help.  @MikeRayMSFT please review.

**Comment by MikeRayMSFT** [comment]
Verifying technical accuracy with PG.

**Comment by craigg-msft** [comment]
@MikeRayMSFT can we merge this?

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by craigg-msft** [comment]
per @MikeRayMSFT merging.

**Pull request merged**
