### PR TITLE
Update sql-server-linux-active-directory-authentication.md

### PR DESCRIPTION
**Pull request by liweiSecurity**
Kerberos authentication only works for remote session in SQL Windows platform. SQL Linux makes it available for local connection.

I added following statement in section 'Connect to SQL Server using AD Authentication'
Different from SQL Windows, Kerberos authentication works for local connection in SQL Linux. You can test the Windows Authentication in the SQL Linux box.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@liweiSecurity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Dylan-MSFT** [comment]
To prevent confusion, can you please specify that it only works if you specify the fqdn of the host for local connections. Maybe something like the following:

Different from SQL Windows, Kerberos authentication works for local connection in SQL Linux. However, you still need to provide the FQDN of the host, and AD authentication will not work if you attempt to connect to '.', '(local)', '127.0.0.1', etc.

**Comment by PRMerger17** [comment]
@liweiSecurity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Dylan-MSFT** [comment]
#signoff

**Pull request merged**
