### PR TITLE
Decription Change and minor wording fixes

### PR DESCRIPTION
**Pull request by aliceku**

### CODE REVIEW

**Comment by aliceku** [comment]
#220

**Comment by aliceku** [comment]
#sign-off

**Comment by PRmerger** [comment]
@aliceku : Thanks for your contribution to the SQL documentation! The author, @"becczhang", has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@aliceku apologies but there is now a merge conflict with this PR. There have been a lot of content updates in the past few weeks. Do you think you can update the PR to resolve the conflict? or perhaps it is easier to submit a new PR via the internal process.

**Comment by aliceku** [comment]
@craigg-msft I think this is my original change that I made on the public repo by mistake.  I then made the same change in the correct repo, and Carl submitted it for me.  I don't know where to see the conflicts, but I assume I can just close this request now.

**Comment by craigg-msft** [comment]
Thank you @aliceku .  I am closing.

**Pull request closed without merging**
