### PR TITLE
Update sp-execute-external-script-transact-sql.md

### PR DESCRIPTION
**Pull request by viradu**
Corrected a typo

### CODE REVIEW

**Comment by PRMerger9** [comment]
@viradu : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@viradu - thanks for the fix. This article has recently changed in the same paragraph and now there is a merge conflict. I also noticed another instance of WITH RESULTS further down in this article.  If you can resolve the merge conflict and update the other WITH RESULTS, we can get this merged in. Thanks

**Comment by PRMerger8** [comment]
@viradu : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@viradu thank you for the edits an apologies for the delay.

**Pull request merged**
