### PR TITLE
Update reference-azdata-bdc-spark-session.md

### PR DESCRIPTION
**Pull request by rl-msft**
missing "bdc" argument for azdata in few places in the document

### CODE REVIEW

**Comment by PRMerger20** [comment]
@rl-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@MikeRayMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Added a space in `bdcspark` -> `bdc spark` in one case.

**Comment by MikeRayMSFT** [comment]
Thank you @rl-msft

**Pull request merged**
