### PR TITLE
typo: Double word "through"

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@nschonni : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @nschonni , this PR isn't showing any differences on my end. Can you please resubmit? Thanks! #hold-off

**Comment by MashaMSFT** [comment]
Hi @nschonni , just kidding, I found it.. the UI isn't highlighting it for some reason! Thanks again for your contribution! #sign-off

**Comment by PRMerger13** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by nschonni** [comment]
@MashaMSFT yup, sometimes long lines don't diff that well. The trick I find useful for Markdown is to switch to the "rich diff" and then the works show up as the rendered word add/delete

**Pull request merged**
