### PR TITLE
Update hide-an-instance-of-sql-server-database-engine.md

### PR DESCRIPTION
**Pull request by juannahmelwyn**

### CODE REVIEW

**Comment by juannahmelwyn** [comment]
Hi Mike
Yes. It is meant as an example.. 
ThanksLeo


-----Original Message-----

**Comment by PRMerger17** [comment]
@MikeRayMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@MikeRayMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by juannahmelwyn** [comment]
Hi
Thank you.
Please let me know if anything should be done from y side
Thank you Leo

-----Original Message-----

**Pull request merged**
