### PR TITLE
Update improve-the-performance-of-full-text-indexes.md

### PR DESCRIPTION
**Pull request by 07101994**
Font changes.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@07101994 : Thanks for your contribution to the SQL documentation! The author, @JennieHubbard, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
@07101994 Thank you!

**Comment by JennieHubbard** [comment]
#sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
