### PR TITLE
Make SQL sample style consistent

### PR DESCRIPTION
**Pull request by DanielCarmingham**
This is in fixes the code style inconsistency mentioned in #8488

### CODE REVIEW

**Comment by DanielCarmingham** [comment]
@microsoft-github-policy-service agree

**Comment by rwestMSFT** [comment]
#sign-off

**Comment by Court72** [comment]
@WilliamDAssafMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Pull request merged**
