### PR TITLE
Update constants-transact-sql.md

### PR DESCRIPTION
**Pull request by fziglio**
Minor updates. `constantsare` -> `constants are`. Add an example for negative money.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@fziglio : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by fziglio** [comment]
Oh... there's another issue which I don't know how to change. In money section somebody put some references about commas inside money. However if I issue a `SELECT $123,4` I'm getting 2 columns (one with money `$123` and another with integer `4`) indicating that commas are not allowed at all on money literals.

**Review by MikeRayMSFT — APPROVED** [review]

**Comment by MikeRayMSFT** [comment]
@fziglio - thank you for the submission. I'm going to approve the original pull request so you can sign off. Can you please ask the money question at https://docs.microsoft.com/en-us/answers/topics/sql-server-general.html? 

Thanks 

Mike
#sign-off

**Pull request merged**
