### PR TITLE
DSNs with sqlcmd and bcp

### PR DESCRIPTION
**Pull request by stummsft**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@stummsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by David-Engel — APPROVED** [review]

**Review by Matteo-T — APPROVED** [review]
It makes sense to me., I'm mostly approving based on the fact that David did.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@markingmyname - Could you sign off if you approve the updates to your two articles? Thanks.

**Review by David-Engel — APPROVED** [review]

**Comment by ktoliver** [comment]
@David-Engel is a PM and "trusted source" per the internal contributor guide, so I'll merge this now. Thanks, all.

**Pull request merged**
