### PR TITLE
Update open-a-template.md

### PR DESCRIPTION
**Pull request by divyapasa**
Document states that to use the 'Replace Template Parameters' dialog box instead of 'Specify Values for Template Parameters' dialog box.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@divyapasa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
IMPORTANT: When this content is ready to merge, the reviewer must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger10** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Review by markingmyname — APPROVED** [review]
Thanks for yuor contribution.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
