### PR TITLE
Discuss custom deployments that schedule pods to k8s master

### PR DESCRIPTION
**Pull request by nfd9001**
More commentary from the same user mentioned in some of my prior pulls. While I don't think we should _encourage_ deployments that use the master to do BDC work per-se, it's not a wholly unreasonable usecase for single-node or other small deployments, especially for lighter-on-compute pools like `shared`.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@nfd9001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @MikeRayMSFT - Could you take a look at this pull request from December? Thanks

**Comment by MikeRayMSFT** [comment]
Reviewing

**Comment by ktoliver** [comment]
#hold-off

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
