### PR TITLE
Update catalog-check-schema-version.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
Adding result

### CODE REVIEW

**Comment by PRMerger14** [comment]
@DanielAdeniji : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @chugugrace -- Could you review the proposed update to your article? Thanks.

**Comment by PRMerger20** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@DanielAdeniji Thank you for this recommended change. The raw HTML table format needed to be changed to markdown format. I did this and made some simplifications. Feel free to make additional suggestions. @chugugrace could you please take a look and approve or provide your feedback. Thank you!

**Comment by DanielAdeniji** [comment]
Jason:-

I likely do not yet have access to your changes.

If I do, please provide me a bit more detail as to how to access your changes.

Thanks,

Daniel
________________________________

**Comment by ktoliver** [comment]
@DanielAdeniji - To see the last changes made in your pull request, select the hyperlinked commit number: https://github.com/MicrosoftDocs/sql-docs/pull/5566/commits/ab90c037b6b57016a8e7cb27c286ec930018668b.

image

Your initial revisions are on the left (red); @rothja edits to your pull request are on the right (green).

**Comment by DanielAdeniji** [comment]
Kristine:-

That is exactly what I needed.

Adding the result columns sure helps.

I think it needs to be stated that the contextual database should be SSISDB, as well.

Thanks,

Daniel
________________________________

**Comment by rothja** [comment]
Thanks, @DanielAdeniji.

@chugugrace Could you please review the propose change in the file changes tab of this pull request? I need you to approve before we can merge the changes. If you see anything you would like changed, please add a comment to the pull request thread. Thank you!

**Comment by DanielAdeniji** [comment]
#5945

**Comment by PRMerger6** [comment]
@DanielAdeniji: I'm sorry - only the author of this article, @chugugrace, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by DanielAdeniji** [comment]
> @chugugrace,

@chugugrace :- Please sign off.

**Comment by rothja** [comment]
@DanielAdeniji Sorry for the long delay. I am going to approve and merge this change. @chugugrace If you see anything inaccurate in this change, please let me know and we'll fix it in a subsequent PR. Thank you!

**Pull request merged**
