### PR TITLE
Update save-transaction-transact-sql.md

### PR DESCRIPTION
**Pull request by latusekpiotr**
Changed transaction_name to savepoint_name in a description of the savepoint_name argument.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@latusekpiotr : Thanks for your contribution to the SQL documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@edmacauley can you please review.

**Comment by edmacauley** [comment]
Thanks for catching and fixing that error!  #sign-off

**Comment by craigg-msft** [comment]
Thank you @edmacauley and @latusekpiotr

**Pull request merged**
