### PR TITLE
Split out the documentation of the -d option

### PR DESCRIPTION
**Pull request by larsw**
Since it was mixed up with the image/tag description.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@larsw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hello @larsw! Thanks for submitting this PR. Let me check on the changes and get back to you. Thanks!

**Comment by rothja** [comment]
@vin-yu @VanMSFT This looks right based on the docker run documentation [here](https://docs.docker.com/engine/reference/run/#detached--d). I'm going to sign off on this change. Thanks, @larsw! I think these changes are only for the 2017 section of the article, so we should probably go back and make the same changes for the 2019 section. We can do that later or you're welcome to submit a new PR if you have time. #sign-off

**Comment by PRMerger20** [comment]
@rothja: I'm sorry - only the author of this article, @vin-yu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
