### PR TITLE
Removing Shardmap references.

### PR DESCRIPTION
**Pull request by srinia**
Still need to fix the picture (.png) to remove the shard map scenario

### CODE REVIEW

**Comment by srinia** [comment]
#sign-off

**Comment by WilliamDAssafMSFT** [comment]
@srinia Do you need help getting the image updated? We shouldn't remove the text describing the section of the image before altering the image.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by srinia** [comment]
I agree @WilliamDAssafMSFT.  How do we alter/edit the image in there (.png). I would love to have some help there.

**Comment by WilliamDAssafMSFT** [comment]
I can help with that, looks easy enough to crop the .png. Standby @srinia

**Comment by WilliamDAssafMSFT** [comment]
Need to do this in the private repo. I will close this and create a new PR.

**Pull request closed without merging**
