### PR TITLE
Update sql-server-management-studio-changelog-ssms.md

### PR DESCRIPTION
**Pull request by BrentOzar**
Fixing line break on "Always Encrypted" so it shows up in another section.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@BrentOzar : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@dnethi can you please review.

**Comment by dnethi** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@dnethi: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by stevestein** [comment]
#sign-off

**Pull request merged**
