### PR TITLE
Add performance setting 'Enable performance improvement setting'

### PR DESCRIPTION
**Pull request by v-redu**
Add performance setting 'Enable performance improvement setting'
We will release this change on SQL Server 2017 CU13 and SQL Server 2016 SP2 CU5.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@v-redu : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by TrishaMc** [comment]
@craigg-msft: Please confirm that this PR is ready for merge. Thank you.

**Comment by craigg-msft** [comment]
pinged @LeoLiMSFT

**Comment by craigg-msft** [comment]
#sign-off and I will clean up the text a bit after the merge.

**Comment by PRMerger14** [comment]
@craigg-msft: I'm sorry - only the author of this article, @leolimsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
