### PR TITLE
Removed the word "two"

### PR DESCRIPTION
**Pull request by SeanGallardy**
Apparently it was causing people to believe that was some hard limit set. There is not.

### CODE REVIEW

**Comment by MashaMSFT** [comment]
awesome, thanks @SeanGallardy #sign-off

**Comment by PRMerger15** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @cawrites, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Jak-MS** [comment]
@MashaMSFT - thanks for approving.

**Comment by Jak-MS** [comment]
Publishing in this repository is suspended until Tuesday, May 25. Merging will resume Tuesday, and we'll merge this approved pull request at that time. Thanks.

**Pull request merged**
