### PR TITLE
connect timeout clarification

### PR DESCRIPTION
**Pull request by jadarnel27**
The "connect timeout" setting mentions that, if it's set to 0, the value from sp_configure will be used.  But there is no "connect timeout" setting in sp_configure.

Based on practical testing (which I mentioned on DBA Stack Exchange [here](https://dba.stackexchange.com/questions/207389/linked-server-connections-to-multi-subnet-failover-cluster/207404#207404)), I think this really refers to the "remote login timeout" setting.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@markingmyname 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Hey Josh, this looks good. We'll get this merged once a PM confirms.

**Comment by jadarnel27** [comment]
Thanks, Randolph!

**Comment by rwestMSFT** [comment]
Sorry for the delay. Feedback from the product group was to add some more language around it, so I'll pull this into an internal PR and you'll see an update in the next day or so. When the internal PR is merged, this PR will automatically close, and you'll still get credit.

**Pull request closed without merging**
