### PR TITLE
Fix a link

### PR DESCRIPTION
**Pull request by yoichinak**
I'm trying to fix a link...

### CODE REVIEW

**Comment by PRMerger16** [comment]
@yoichinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@yoichinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
This looks correct to me, but it's not possible to tell definitively in GitHub preview. I'll move the commit to the private repository to verify on staging. Then, we'll close this PR.

**Comment by ktoliver** [comment]
@yoichinak Thanks for your contribution! I was able to verify on staging in the private repo that the link works. We'll merge it here.

**Pull request merged**
