### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by MohsinAhmedQureshi**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@MohsinAhmedQureshi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
thanks @MohsinAhmedQureshi for this edit!

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
