### PR TITLE
fix powershell commands referencing old AzureStorage prefix

### PR DESCRIPTION
**Pull request by mikeehsu**
when converting over from the AzureRm to the new Az syntax some older AzureStorage commands were overlooked. The updates correct the oversight so that the script works in pwsh 6.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@mikeehsu : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by mikeehsu** [comment]
Opps.. sorry accidentally closed the request. Reopening it.

**Comment by MikeRayMSFT** [comment]
@mikeehsu thank you for the submission - I'm double checking the syntax with engineering and will update.

**Comment by MikeRayMSFT** [comment]
#sign-off 
Thank you, @mikeehsu

**Pull request merged**
