### PR TITLE
update download page for SSDT for VS2017 15.9.2

### PR DESCRIPTION
**Pull request by MSraye**
update download page for SSDT for VS2017 15.9.2

### CODE REVIEW

**Comment by stevestein** [comment]
#hold-off 

DO NOT MERGE YET

**Comment by markingmyname** [comment]
@stevestein and @MSraye 

I meet with the PMs for SSDT today.

I will bring this up to them.

Thank you.

**Comment by stevestein** [comment]
#sign-off

**Comment by stevestein** [comment]
#sign-off

**Comment by stevestein** [comment]
@jborsecnik - is the assessing label keeping this from getting the ready to merge label?

**Pull request merged**
