### PR TITLE
Update SQL Server versions to include 2022

### PR DESCRIPTION
**Pull request by jBarrineau**
Updating documentation to let readers know that SSMS 19 can work with SQL Server 2022.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jBarrineau : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@erinstellato-ms 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger5** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Review by erinstellato-ms — APPROVED** [review]
thanks for the catch!

**Pull request merged**
