### PR TITLE
Remove msfttutorial

### PR DESCRIPTION
**Pull request by matt40k**
Looks like a copy and paste fail.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@matt40k : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @matt40k , thank you for your contribution! Actually, one is supposed to show the syntax, while the second shows an example of how that syntax is used. It is as it's intended, but I can see how it might cause some confusion. If you'd like, you can modify your PR to add a comment saying that the second code snippet is an example. If not, I can close out this PR, and make this edit myself. Thanks!

**Comment by matt40k** [comment]
I thought that was the cause I just was a bit confused as its the only one. Wonder if its worth doing the same for the other examples? Happy for you \ me to close this!

**Comment by Jak-MS** [comment]
Hi @MashaMSFT -  please let us know how you'd like to proceed with this PR: 

- `#sign-off` if it's ready to merge
- `#hold-off` if it requires changes before it's ready for sign off
- `#please-close` - if these changes aren't going to be merged

Thanks!

**Comment by MashaMSFT** [comment]
Hi @matt40k, we can proceed with closing this PR out, and I'll just add a quick note to the doc pointing out it's an example. Thanks again for bringing this to our attention :) #please-close

**Pull request closed without merging**
