### PR TITLE
Update SecureConnectionLevel

### PR DESCRIPTION
**Pull request by johlju**
Improve documentation that SecureConnectionLevel was made an on/off switch in SQL Server 2008 R2.

Please let me know if this need to be changed/improved and I'm happy to do so.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@johlju : Thanks for your contribution to the SQL documentation! The author, @guyinacube, has been notified to review your proposed change.

**Comment by guyinacube** [comment]
Validating that this is accurate with the engineering team. I will follow up when I've heard back.

**Comment by johlju** [comment]
@guyinacube Heard anything from the engineering team yet?

**Comment by craigg-msft** [comment]
@maggiesMSFT please review / followup

**Comment by guyinacube** [comment]
I did get confirmation of the behavior.

**Comment by guyinacube** [comment]
#sign-off

**Comment by PRMerger7** [comment]
Only the author, @asaxton, can sign off on this pull request.

**Comment by craigg-msft** [comment]
Thank you @johlju  and @guyinacube

**Pull request merged**
