### PR TITLE
Update sp-cursoropen-transact-sql.md

### PR DESCRIPTION
**Pull request by lotsahelp**
Corrected a missing space

### CODE REVIEW

**Comment by PRMerger3** [comment]
@lotsahelp : Thanks for your contribution to the SQL documentation! The author, @edmacauley, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
Thank you @lotsahelp for the edit.  Looks good to me

#sign-off

**Comment by craigg-msft** [comment]
Thank you @lotsahelp and @edmacauley

**Comment by lotsahelp** [comment]
Welcome. I had a nice chuckle when I found it.

**Pull request merged**
