### PR TITLE
Correct Download for Oracle Connector

### PR DESCRIPTION
**Pull request by JMCARY**
- the documentation around this is really confusing, there are multiple spots to download the connector. The previous link dates to 2017, while the proposed link is from 2020.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@JMCARY : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by MikeRayMSFT — APPROVED** [review]

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @chugugrace, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
