### PR TITLE
Add verbiage regarding filetable and email

### PR DESCRIPTION
**Pull request by JamesFerebee**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@JamesFerebee : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @CarlRabeler - Could you review the proposed changes? Thank you.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@CarlRabeler: I'm sorry - only the author of this article, @douglaslMS, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
