### PR TITLE
Update AKS version for Cluster Create Command

### PR DESCRIPTION
**Pull request by clayton006**
The minimum Kubernetes version available in AKS is 1.11.6. I've updated the "az aks create" command to reflect this.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@clayton006 : Thanks for your contribution! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@SQLSourabh  - please review.

@clayton006 - thank you for the submission.

**Comment by MikeRayMSFT** [comment]
@clayton006 - thanks again for this. I'm working on this. Trying to figure out the update that will keep the article current in cycle with AKS version updates.

**Comment by clayton006** [comment]
Yeah I would agree as if we just apply a static version it will keep lagging behind eventually. Thanks for following up!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by MikeRayMSFT** [comment]
Moving to private repository: https://github.com/MicrosoftDocs/sql-docs-pr/pull/9375

**Pull request closed without merging**
