### PR TITLE
Update cdc-capture-instance-ct-transact-sql.md

### PR DESCRIPTION
**Pull request by petermcneely**
Detail the nuance of change table rows that are created as a result of a "deferred update" operation.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@petermcneely : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by LitKnd** [comment]
Hi @petermcneely ,

Thanks for submitting this issue. I am checking if @Sait-MSFT may know who can help us with this. 

We have an existing article on [deferred updates in general](https://docs.microsoft.com/en-us/troubleshoot/sql/replication/update-statements-replicated-as-delete-insert). Potentially wording if linking to that article might help if this PR is accepted, but would also require a review of that article.

Cheers,
Kendra

Content Developer on the Database Docs team

**Comment by LitKnd** [comment]
#assign: @MaraSteiu

**Comment by LitKnd** [comment]
Hi @petermcneely ,

Thanks again for submitting this. Our team reviewed this and approved signing off on your suggestion.

We appreciate your contributions!

Kendra from the Database Docs Team

#sign-off

**Pull request merged**
