### PR TITLE
Update what-s-new-in-sql-server-2022.md

### PR DESCRIPTION
**Pull request by thesqlsith**
Please add the hyperlink to the Parameter sensitive plan optimization section of this documentation (line 91) - https://docs.microsoft.com/sql/relational-databases/performance/parameter-sensitivity-plan-optimization.  Or the relative path is - ../relational-databases/performance/parameter-sensitivity-plan-optimization.md

### CODE REVIEW

**Comment by PRMerger8** [comment]
@thesqlsith : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@MikeRayMSFT, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

**Comment by rwestMSFT** [comment]
Please assign this to me, and we'll handle this with an internal PR.

**Comment by jborsecnik** [comment]
> Please assign this to me, and we'll handle this with an internal PR.

Thanks. Should we close this PR?

**Comment by rwestMSFT** [comment]
> > Please assign this to me, and we'll handle this with an internal PR.
> 
> Thanks. Should we close this PR?

No need, the internal PR will handle it for us.

**Pull request closed without merging**
