### PR TITLE
Correct version of @include_total_xtp_storage parameter

### PR DESCRIPTION
**Pull request by stummsft**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@stummsft : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
@stummsft thanks for your edit!  can you change both the comment and the include file though? It would look something like this:

 [!INCLUDE[sssql17-md](../../includes/sssql17-md.md)]

**Comment by PRMerger17** [comment]
@stummsft : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by edmacauley** [comment]
@stummsft thanks!  #sign-off

**Pull request merged**
