### PR TITLE
Update what-s-new-in-sql-server-2022.md

### PR DESCRIPTION
**Pull request by pmasl**
Suggest several clarifications to IQP features. Also, somehow the Degree of parallelism (DOP) feedback and CE Feedback are not linking to the docs pages specific to those features, and those were done in the EAP repo before. cc @MikeRayMSFT

### CODE REVIEW

**Comment by PRMerger4** [comment]
@pmasl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by pmasl** [comment]
#assign:@MikeRayMSFT

**Comment by PRMerger12** [comment]
@pmasl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@pmasl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by pmasl — COMMENTED** [review]
Changes based on recent edits from today

**Comment by MikeRayMSFT** [comment]
Moving to private side in https://github.com/MicrosoftDocs/sql-docs-pr/pull/22224 to resolve merge conflicts and review. 

With thanks to @pmasl

**Pull request closed without merging**
