### PR TITLE
Update upgrading-always-on-availability-group-replica-instances.md

### PR DESCRIPTION
**Pull request by m82labs**
Added a note to the intro about the automatic database upgrade process on the secondary that executes upon initial  failover. This is not well documented, and when dealing with a large number of databases in an AG (hundreds) it can take considerable time.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@m82labs : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@m82labs : Our product team is validating the content. Thank you for the submission.

**Comment by seshenoy** [comment]
#sign-off   Testing purpose : need to show a comment below preventing non-authors to sign off

**Comment by PRMerger18** [comment]
@seshenoy: Only the author, @MikeRayMSFT, can sign off on this pull request.

**Comment by seshenoy** [comment]
@MikeRayMSFT Can you please sign-off again as there was a recent deployment ? Sorry for the inconvenience.

**Comment by PRMerger13** [comment]
@m82labs : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by v-caxian** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@v-caxian: Only the author, @MikeRayMSFT, can sign off on this pull request.

**Pull request merged**
