### PR TITLE
Update quickstart-install-connect-suse.md

### PR DESCRIPTION
**Pull request by amvin87**

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @amvin87 - We'll leave this PR in the public repo for review, but would you make future content updates in the private repository? PMs should work in the private repo, per the contributor guide. Thanks!

**Comment by amvin87** [comment]
Hi Kristin,

This was by mistake. Will ensure going forward the changes happen in my private repo.

Thanks,
Amit Khandelwal
Sr. Program Manager| Data Platform- SQL Server

**Comment by ktoliver** [comment]
Thanks. 👍

**Comment by VanMSFT** [comment]
#sign-off

**Review by VanMSFT — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks! This PR can be merged when publishing in the repository resumes Tuesday, 9/22, at 7 AM.

**Pull request merged**
