### PR TITLE
Fixed example code to use ANSI joins

### PR DESCRIPTION
**Pull request by way0utwest**
Updated code to remove old style FROM a, b joins to use FROM a inner join b.
Code tested as valid on SQL SErver 2016/2017

### CODE REVIEW

**Comment by PRMerger10** [comment]
@way0utwest : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@way0utwest : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by rothja** [comment]
@way0utwest These changes look *much* more readable and modern. Thanks! #sign-off

**Comment by PRMerger7** [comment]
@rothja: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
