### PR TITLE
Listener restart require to take into effect

### PR DESCRIPTION
**Pull request by dna360d**
Add a note under "Important" section about the restart of the resource in order to take effect the changes

### CODE REVIEW

**Comment by PRMerger6** [comment]
@dna360d : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by markingmyname — APPROVED** [review]
Approved.

Good work, @dna360d

**Comment by markingmyname** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@markingmyname: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
