### PR TITLE
Update integration-services-ssis-logging.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
The sentence "In SQL Server Server Properties, under the Server logging level property, you can select a default server-wide logging level." is not clear enough.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@DanielAdeniji : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Merging per email. I added a commit to apply Microsoft style.

**Comment by ktoliver** [comment]
Thanks @DanielAdeniji.

**Pull request merged**
