### PR TITLE
Update build-database-projects-by-using-sql-server-management-studio.md

### PR DESCRIPTION
**Pull request by SimpleSamples**
You can ignore my changes if you wish but I think people have gotten in the habit of always saying "by using" even when the "by" is unnecessary. I have made other improvements too.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@SimpleSamples : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SimpleSamples** [comment]
Also, I do not know if "a group of scripts" should be "the group of scripts" but I think it should be one of those.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, May 19. Merging will resume at 7:00 AM PT Tuesday. Authors can still review and sign off on PRs during this time. Thanks.

**Comment by markingmyname** [comment]
@SimpleSamples 

I reviewed the changes and added a few more edits.  Please make the changes above and then this PR can be approved.

Thank you.

**Comment by SimpleSamples** [comment]
Sorry, if I am supposed to do something then I am not sure what. I clicked on the Edit button and saved but otherwise I do not know what to do.

**Comment by ktoliver** [comment]
@SimpleSamples @markingmyname - Sometimes the original contributor can't make updates in the PR. I don't know if that's the case here, but I applied the updates that the author asked for in his review of the pull request.

**Comment by SimpleSamples** [comment]
Good. Everything looks good.

**Comment by markingmyname** [comment]
Thanks, @ktoliver, and @SimpleSamples.

Approved.

@ktoliver 

Please merge.

**Comment by markingmyname** [comment]
#sign-off

**Comment by ktoliver** [comment]
Thanks, all. 👍

**Pull request merged**
