### PR TITLE
Update sql-server-transaction-locking-and-row-versioning-guide.md

### PR DESCRIPTION
**Pull request by mohammad-hekmat**

### CODE REVIEW

**Comment by mohammad-hekmat** [comment]
is it the right statement?! 
INSERT INTO dbo.employee  
       SET name = 'New' WHERE ID = 5;  
@PRMerger14

**Comment by rothja** [comment]
@mohammad-hekmat  Thanks for the contribution. I think the statement was confused between and UPDATE and an INSERT. I like your change, but should we reverse your values to match the column names you listed in the same order:

(Id, Name) VALUES(6, 'New');

**Comment by PRMerger6** [comment]
@mohammad-hekmat : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by mohammad-hekmat** [comment]
@rothja  Thanks for answering. I changed it.

**Comment by rothja** [comment]
@mohammad-hekmat  Thank you. I'm signing off on this fix. #sign-off

**Pull request merged**
