### PR TITLE
Update appliesto-ss-xxxx-xxxx-xxx-md.md

### PR DESCRIPTION
**Pull request by masank**
Polybase is supported by all of the listed products and services.

### CODE REVIEW

**Comment by GitHubber17** [comment]
@rothja - Would you review the proposed changes? Thanks

**Comment by rothja** [comment]
@masank Hi. This include file is used by many many articles to indicate that something applies to SQL Server but not to the other products listed. To change one specific article, you have to change the include file to one that represents the right product list. So I can't accept this PR, but I could accept a PR that changes the include file on one or more topics. For more information, see the section on Applies-to includes on http://aka.ms/editsqldocs.

Also, is PolyBase supported by Azure SQL Database? I thought that it was only SQL Server and SQL DW? Thanks!

**Comment by masank** [comment]
Hi Jason,

Thank you for looking at my request and applogize about Applies-to, I have not read applies-to include section.

Thanks,
Masanori

**Comment by GitHubber17** [comment]
@rothja - Would you add a [hash comment](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-automation?branch=master) to indicate the action to take on this PR? Thanks

**Comment by rothja** [comment]
@GitHubber17 Yes, sorry. I think for now we can close this one unless there is a specific PolyBase topic that should be using a different include. #please-close

**Pull request closed without merging**
