### PR TITLE
windows docker image is wrong

### PR DESCRIPTION
**Pull request by options**
windows docker image name has to be changed.

### CODE REVIEW

**Comment by craigg-msft** [comment]
Thank you @options   @rothja can you please do a quick review.  Thanks!

**Comment by rothja** [comment]
@options The quickstart is actually using the Linux container on both Linux and Windows for consistency in the walkthrough. I'll look at how we can be more consistent in explaining this decision for the tutorial. I could possibly add a note that explains how to create the windows image instead. But this line is actually as intended here. Let me know if that makes sense, and thank you for the feedback!

**Comment by craigg-msft** [comment]
@rothja Should I close this PR?

**Comment by rothja** [comment]
@craigg-msft I think we should close it, because the changes needed are to explain Windows containers better and to make this topic more clear that it is using a Linux container. But the original change is not needed in a Linux-only container tutorial. Thanks.

**Comment by craigg-msft** [comment]
closing

**Pull request closed without merging**
