### PR TITLE
Remove suggestion to use email as a plausible means to transfers a db

### PR DESCRIPTION
**Pull request by DBArgenis**

### CODE REVIEW

**Comment by ktoliver** [comment]
@stevestein - Could you review the proposed changes? Thanks.

**Comment by PRMerger7** [comment]
@DBArgenis : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@DBArgenis I agree with the change but the PR now has a conflict.  Do you have time to please resolve that and repush the PR?  if so @ me and I will give it a quick view and merge it.  Thanks!

**Comment by PRMerger9** [comment]
@DBArgenis : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by DBArgenis** [comment]
I believe I've corrected the issue, @craigg-msft. Can you please validate?

**Comment by craigg-msft** [comment]
Thank you @DBArgenis !

**Pull request merged**
