### PR TITLE
Fix typo in differential backups docs

### PR DESCRIPTION
**Pull request by Kissaki**

### CODE REVIEW

**Comment by PRMerger4** [comment]
@Kissaki : Thanks for your contribution! The author(s) have been notified to review your proposed change. @LitKnd

**Comment by rwestMSFT** [comment]
#assign:rwestMSFT

**Comment by rwestMSFT** [comment]
@Kissaki Thank you for this edit.

#sign-off

**Comment by PRMerger14** [comment]
@rwestMSFT: I'm sorry - only the author of this article, @LitKnd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by rwestMSFT** [comment]
I have submitted an internal PR to update this article, which will close this PR when it is approved. The refreshed article will appear later today.

**Pull request closed without merging**
