### PR TITLE
Typo '**jdoe@xyz.com**'→'**jdoe\@xyz.com**'

### PR DESCRIPTION
**Pull request by hyoshioka0128**
Bold with escape characters

https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-operator-transact-sql?view=sql-server-ver15

### CODE REVIEW

**Comment by PRMerger19** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@stevestein - Could you review the proposed update?

Escaping the @ character here (which currently appears in the live version), makes the email address "hot," which isn't optimal in this case because it's an example email address. What might work best is using inline code: `jdoe` or `jdoe@xyz.com`

**Comment by rothja** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@rothja: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
