### PR TITLE
Updated GDPR article

### PR DESCRIPTION
**Pull request by aliceku**
We have a new whitepaper which needs to link here, also updated the wording of this article

### CODE REVIEW

**Comment by PRMerger20** [comment]
@aliceku : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by aliceku** [comment]
@edmacauley can you make me the author of this article?

**Comment by Jak-MS** [comment]
Hi @aliceku - the changes in this PR are too extensive to be submitted through the public repo. Can you resubmit your commits to the private repo so that we can use the staging and validation tools there? (sql-docs-pr )

Thanks.
#please-close 

***
FYI: Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Comment by aliceku** [comment]
@Jak-MS I cannot find the article in sql-docs-pr and cannot find the path anymore.  This article is extremely outdated and needs an update...

**Comment by Jak-MS** [comment]
Just to wrap this up... @aliceku - looks like the article was removed from the repositories in this PR https://github.com/MicrosoftDocs/sql-docs-pr/pull/5975 .

**Comment by aliceku** [comment]
thank you, will work on adding the updated version now.

**Pull request closed without merging**
