### PR TITLE
Severity has 0

### PR DESCRIPTION
**Pull request by taroarai**
Since this view shows 0 in severity, we should change 1-25 to 0-25.

### CODE REVIEW

**Comment by taroarai** [comment]
We see there is 0 in severity.

https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-error-severities?view=sql-server-
*****
Severity level | Description
0-9 | Informational messages that return status information or report errors that aren't severe. The Database Engine doesn't raise system errors with severities of 0 through 9.

**Comment by Court72** [comment]
@rwestMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
#sign-off

**Comment by rwestMSFT** [comment]
Thanks, Taro.

**Pull request merged**
