### PR TITLE
Update dynamic-data-masking.md

### PR DESCRIPTION
**Pull request by carlosbourque**
Just a small change on the code.

### CODE REVIEW

**Comment by edmacauley** [comment]
@carlosbourque would you also mind changing the field name in the INSERT statement?

**Comment by craigg-msft** [comment]
@carlosbourque can you please update per Ed's ask?  Or should I just close this PR?

**Comment by carlosbourque** [comment]
Sure! let me change it.

**Comment by PRMerger19** [comment]
@carlosbourque : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
Thank you @carlosbourque  fyi @edmacauley  merging

**Pull request merged**
