### PR TITLE
remove duplicate content

### PR DESCRIPTION
**Pull request by Dodev-S**
The last paragraph was repeated.

### CODE REVIEW

**Review by LitKnd — APPROVED** [review]

**Comment by LitKnd** [comment]
@Dodev-S , thank you for submitting this correction to our team, we appreciate your contribution.

Best,
Kendra from the SQL Docs team

#sign-off

**Comment by PRMerger15** [comment]
@LitKnd: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
