### PR TITLE
not supported in contained databases

### PR DESCRIPTION
**Pull request by martinbherbener**
indicate lack of support in contained databases, with link to contained database info page

### CODE REVIEW

**Comment by PRMerger18** [comment]
@martinbherbener : Thanks for your contribution! The author, @rothja, has been notified to review your proposed change.

**Comment by rothja** [comment]
@martinbherbener Thanks for this addition. How did you discover this was not supported? I was doing a quick search just to confirm and could not find much on this. I just want to check before approving. Thank you!!

**Comment by martinbherbener** [comment]
This page: https://docs.microsoft.com/en-us/sql/relational-databases/databases/contained-databases?view=sql-server-2017#Limitations says so.  I haven't tested it myself and have no inside knowledge.

**Comment by rothja** [comment]
@martinbherbener Oh, of course. I should have looked there first. Thanks for pointing me to the right place. #sign-off

**Pull request merged**
