### PR TITLE
Update sql-server-database-replica.md

### PR DESCRIPTION
**Pull request by FonsecaSergio**
Added additional information to avoid confusion when reading documentation related to Transaction Delay

### CODE REVIEW

**Comment by PRMerger7** [comment]
@FonsecaSergio : Thanks for your contribution! The author, @julieMSFT, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by FonsecaSergio** [comment]
@julieMSFT it got broken in final version https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-database-replica?view=sql-server-2017. It does not show like that in github preview

**Comment by julieMSFT** [comment]
@FonsecaSergio I fixed this in a separate PR, [#10554](https://github.com/MicrosoftDocs/sql-docs-pr/pull/10554) The link was not formatted correctly.

**Comment by julieMSFT** [comment]
#10554

**Pull request merged**
