### PR TITLE
Describe Linux support and limits

### PR DESCRIPTION
**Pull request by stummsft**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@stummsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@chugugrace @LeoLiMSFT Could one of you review the suggested change to add a support statement about SSIS and Linux to your docs in this PR? @stummsft Thanks for the suggestion. #assign:LeoLiMSFT.

**Comment by PRMerger6** [comment]
LeoLiMSFT. is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger6** [comment]
lrtoyou1223. is not a valid GitHub ID, or is not a collaborator on this repo.

**Pull request merged**
