### PR TITLE
Renamed: "New connection" to "Add connection" to reflect current UI

### LINKED ISSUE #7509: Label change: Button was renamed to "Add connection"
The page states:

> For Connection type, select Azure Monitor Logs.

However, the button seems to have been renamed to "Add connection":

grafik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aecdd154-9637-879f-dee2-34c2aa258026
* Version Independent ID: ddf6aa52-ff98-ad96-8814-ead8c433a774
* Content: [Azure Monitor Logs extension for Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/azure-monitor-logs-extension?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/extensions/azure-monitor-logs-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/extensions/azure-monitor-logs-extension.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

### PR DESCRIPTION
**Pull request by NenoLoje**
Fixes #7509 

Summary of changes:
- Renamed: "New connection" to "Add Connection" (1 occurrence)

### CODE REVIEW

**Comment by PRMerger6** [comment]
@NenoLoje : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@markingmyname

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by markingmyname — COMMENTED** [review]
We appreciate the suggestion, however, in the Azure Data Studio application in the newest version.  it continues to show as a "New Connection."  Thank you.

**Comment by NenoLoje** [comment]
@markingmyname What version do you run?

I'm running this one (and it says there are no updates available):

grafik

The big blue button clearly states "Add connection" (whereas the tooltip says "New connection"):
grafik

**Comment by markingmyname** [comment]
@NenoLoje 

I see what you are referring to now.

I am more referencing the icon at the top showing "New Connection" than the blue bar "Add Connection."

But I know both can work.

this si good feedback to give to the PG.

Mind if I request to submit a feature request to the [Azure Data Studio repo](https://github.com/microsoft/azuredatastudio)

**Comment by NenoLoje** [comment]
> Mind if I request to submit a feature request to the [Azure Data Studio repo](https://github.com/microsoft/azuredatastudio)

Done: https://github.com/microsoft/azuredatastudio/issues/19242

Thanks, @markingmyname!

**Pull request closed without merging**
