### PR TITLE
Update dynamic-data-masking.md

### PR DESCRIPTION
**Pull request by Max-Meng**
Remove the line saying data masking is not supported for PolyBase external table, because per my test, it is supported now.

### CODE REVIEW

**Comment by Court72** [comment]
@VanMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Hi @Max-Meng - Thanks for your feedback. We appreciate you taking the time to test and making the updates to our documentation. Just as a note, a scenario working does not always equate to it being supported. The Product Team will need to test and confirm, as well as willing to support the scenario. I will need to defer to my colleague, @WilliamDAssafMSFT to confirm internally on this. Thanks!

**Comment by VanMSFT** [comment]
FYI @Madhumitatripathy

**Comment by Madhumitatripathy** [comment]
[like]  Madhumita Tripathy reacted to your message:
________________________________

**Comment by WilliamDAssafMSFT** [comment]
Thanks @Max-Meng for taking the time to file this. @VanMSFT is right on. While it may technically be possible to implement DDM on _some_ external tables, currently this is not a supported scenario.

**Comment by Max-Meng** [comment]
> Thanks @Max-Meng for taking the time to file this. @VanMSFT is right on. While it may technically be possible to implement DDM on _some_ external tables, currently this is not a supported scenario.

thanks for confirming that!

**Comment by Madhumitatripathy** [comment]
@VanMSFT is right. It's not supported as of now, we will add this to our backlog.

**Pull request closed without merging**
