### PR TITLE
Revised Information regarding SQLPS, added comment to Windows Admin Center

### PR DESCRIPTION
**Pull request by Karl-WE**
remote related #4828, 
#4827 @markingmyname

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@Karl-WE - again thank you for your persistence. We have pulled your submissions into the private repository for review.

**Pull request closed without merging**
