### PR TITLE
Update to SQL Server on Linux Security Limitations - Authentication Mode

### PR DESCRIPTION
**Pull request by clayton006**
Adding information to document on SQL Server authentication for SQL Server on Linux.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@clayton006 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by amvin87 — APPROVED** [review]

**Comment by amvin87** [comment]
#sign-off  
@VanMSFT  can you please help merge this change to the live doc

**Comment by PRMerger12** [comment]
@amvin87: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@amvin87 I can merge this with your approval. Thanks for the review.

**Pull request merged**
