### PR TITLE
Fix typo in using-azure-active-directory.md

### PR DESCRIPTION
**Pull request by lgvacanti**
Fix typo

### CODE REVIEW

**Comment by PRMerger3** [comment]
@lgvacanti : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Review by David-Engel — APPROVED** [review]
Thanks for catching that!

**Comment by David-Engel** [comment]
#sign-off

**Pull request merged**
