### PR TITLE
Update transparent-data-encryption-byok-azure-sql.md

### PR DESCRIPTION
**Pull request by hirokib**
says supports DW

### CODE REVIEW

**Comment by hirokib** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@hirokib : Thanks for your contribution to the SQL documentation! The author, @aliceku, has been notified to review your proposed change.

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by aliceku** [comment]
#sign-off

**Comment by craigg-msft** [comment]
Thank you @hirokib and @aliceku . merging

**Pull request merged**
