### PR TITLE
minor update to reflect new snapshot backup technology

### PR DESCRIPTION
**Pull request by emad-almousa**
minor update to reference SQL Server 2022 technology name : Transact-SQL snapshot backup instead of "snapshot backups"

### CODE REVIEW

**Comment by Court72** [comment]
@WilliamDAssafMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Hi @emad-almousa! We don't use the phrase "transact-sql snapshot backup" anywhere else. Can you maybe take a step back and help me understand the source of confusion?

**Comment by emad-almousa** [comment]
Hi @WilliamDAssafMSFT thanks for your feedback.
Here is a reference link for the official name: https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup?view=sql-server-ver16

It's not a big deal to be honest, the phrase can be kept as is.

Have a Nice Day
Emad

**Comment by WilliamDAssafMSFT** [comment]
Ah, nice! This is good to make a distinction because this is _also_ different. 

Thanks!

#sign-off

**Pull request merged**
