### PR TITLE
Update tempdb-database.md

### PR DESCRIPTION
**Pull request by jogietze**
Fix broken link.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@jogietze : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@jogietze : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@jogietze - thanks for the fix!

#sign-off

**Comment by stevestein** [comment]
#sign-off

**Pull request merged**
