### PR TITLE
Typo "**@retention**"→"**\@retention**"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-mergecleanupmetadata-transact-sql?view=sql-server-2017

### CODE REVIEW

**Comment by stevestein** [comment]
@hyoshioka0128 - thanks for submitting this update. Looks like there's a merge conflict that needs to be fixed before we can accept this. 

Thanks!

**Comment by hyoshioka0128** [comment]
@stevestein - resolved conflicts.
Thanks.

**Comment by stevestein** [comment]
@hyoshioka0128 - thanks for fixing the conflict. Looks like the fix was picked up from a change in the ja-jp version. I think it was _your original fix!_ that was then brought into this version that caused the conflict. Looks like we're good becasue there's no longer any files in this PR.

Thanks!!

#please-close

**Comment by stevestein** [comment]
https://github.com/MicrosoftDocs/sql-docs/commit/93a5206e4dae2bd57d35d25f64da0f8a7dc12a5e#diff-6407b79dd3c2a6e01f8c0b7360194d81

**Pull request closed without merging**
