### PR TITLE
Update configure-a-report-server-database-connection-ssrs-configurati…

### PR DESCRIPTION
**Pull request by JoshGer**
…on-manager.md

### CODE REVIEW

**Comment by PRMerger18** [comment]
@JoshGer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JoshGer** [comment]
Added a note for support limitation when using Azure SQL Managed Instance for the RS databases. This only needs to be added for SSRS 2019 and later. SSRS 2017 and earlier do not support SQL MI.

**Comment by maggiesMSFT** [comment]
Hi, @JoshGer -- I'm going to close this PR and add the note to the article in the private repo, so I can add the 2019 monikers. That way it only shows up if viewing 2019+ content. 
#please-close

**Comment by JoshGer** [comment]
Sounds great! Thanks Maggie!

Josh Gerszewski | Microsoft SQL Server BI Support | P.980-776-2901 | joshger@microsoft.com<mailto:joshger@microsoft.com> | Sunday 11:00am-8:00pm EST; Mon-Wed 12:00pm-9:00pm EST; Thurs 8:00am-5:00pm EST

**Pull request closed without merging**
