### PR TITLE
Update filegroupproperty-transact-sql.md

### PR DESCRIPTION
**Pull request by fbsolo**
Text revisions to tighten and optimize the reading flow of the material.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@MashaMSFT please review

**Comment by PRMerger16** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @fbsolo, thank you so much for your contribution! I've modified your proposed changes a bit to better align with Microsoft's [style guide](https://docs.microsoft.com/en-us/style-guide/welcome/). Thanks for your input and your suggestions :) #sign-off

**Comment by PRMerger8** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @edmacauley, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
