### PR TITLE
READ_WRITE_ROUTING_URL is missing description

### PR DESCRIPTION
**Pull request by taroarai**
READ_WRITE_ROUTING_URL is documented in syntax part, but it does not have discription nor link to following Docs.

Secondary to primary replica read/write connection redirection (Always On Availability Groups)
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/secondary-replica-connection-redirection-always-on-availability-groups?view=sql-server-ver15

### CODE REVIEW

**Comment by PRMerger7** [comment]
@taroarai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Thank you, @taroarai - validating

**Comment by PRMerger14** [comment]
@MikeRayMSFT, you can only sign off in the main PR conversation, not in review comments.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
