### PR TITLE
Fixed typo in Alpine download URLs in ODBC Driver installation page

### PR DESCRIPTION
**Pull request by pezia**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@pezia : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by pezia** [comment]
Maybe this could be improved further by adding -O to the curl commands to actually save the files.

**Comment by MightyPen** [comment]
@David-Engel  Hi again David,  Can you pass judgment on this PR #4070, which like PR #4104 is about ODBC in the context Linux-Mac.

Thanks. G

**Comment by PRMerger19** [comment]
@pezia : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@v-makouz Hello Maxim, Can you please process this customer-create "public" Pull Request #4070.
This PR proposes changes that Conflict with one of your recent PRs (your PR being dated perhaps January/31-ish).

Maxim, we need you to either (A) Resolve the conflicts here (or MS Teams chat with me while you watch me Resolve), or (B) Ask me to Close this PR and give the reason (such as Incorrect change proposal, or outdated, or...?).

Thank you.  (GeneMi = MightyPen)

cc: @pezia

**Comment by v-makouz** [comment]
@MightyPen Adding `-O` is good (that was my bad for missing it) and the verification for the tools. But the package filename has to remain `msodbcsql17_17.5.1.1-1_amd64.apk`

Also the version for tools should change to 17.5.1.2 (this is a recent fix, so it wasn't in the original doc)

For the conflict, you can either resolve it here with those changes, or you can close this PR and I'll make another one with both changes (-O, tools verify, and tools version) whichever is easier

**Comment by MightyPen** [comment]
@pezia Hello Zsolt,  We like part of your PR #4070, but we do not want all parts of it.
So with our thanks to you, we are going to add the extra `gpg` line your PR offers, plus the important `-O` additions.
But for this particular PR, we are going to Close it, rather than Merge it.

Thank you for submitting this PR, it is very helpful. We hope to hear from you again.

**Pull request closed without merging**
