### PR TITLE
Suggest to resolve '?'

### PR DESCRIPTION
**Pull request by yoichinak**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@yoichinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MightyPen** [comment]
@yoichinak  Hello Yoichi, Overall this is a helpful public PR 2477. I will Approve this PR.

There are a couple things we would have changed differently, but your choices are clearly sensible.
I am going to record here my personal scratchy notes (for my possible later referencing), else I will lose them.

---

_(GeneMi's notes, from detailed review of this public PR 2477.)_

DESIRED:
  EXEC?master.doc.sp_    (Excellent fix.  'docs/relational-databases/replication/configure-distribution-availability-group.md')

  {`&accute;` and `&uml;` | insensitive to diacritical marks such as a tilde (**~**), acute accent mark (**&acute;**), or umlaut (**&uml;**) (that is, *accent sensitive* or *accent insensitive*). For example, suppose you specify the pattern "caf&eacute;" to be replaced by}


ACCEPTABLE:
  &mldr;   (We prefer to use three plain period characters, rather than the more difficult to Search for non-ASCII 0x7F ellipsis.  However, there are rare exceptions.)


NOT OUR FAVORITE TYPE OF FIX, BUT OKAY:
  `&apos;`  (Just use STRAIGHT single-quotation mark ' instead of `&apos;` .)
  `&ldquo;` and `&rdquo;`  (We do not want the CURLY style of quote marks.  Unfortunately they leak in by accident, via copy-paste from MS Word. Just use STRAIGHT double-quotation marks for both.  And append ';' if using &any; .)

  `&sup1`   (However, `&sup1;` would be fine.)

  Within table data rows, replacement of '?' with '-' is maybe okay.  But this change tends to hide the original problem from future detection and real fixing.

  Literal ellipsis are bad, partly because they are not ASCII 0x7F or less.  The literal should not be pasted in to replace '?'.  Instead, must use `&mdlr;` , but really should use three plain ASCII 0x7F dots.  (docs/relational-databases/replication/security/view-and-modify-replication-security-settings.md) 


UNSURE:
  docs/relational-databases/replication/configure-web-synchronization.md :  Why not delete the '?' characters, instead of replacing them with '-' chars?

---

Thank you.
 . .

**Comment by MightyPen** [comment]
#sign-off

**Comment by ktoliver** [comment]
@mightypen @yoichinak - We're going to move this commit to the private repo so we (and any reviewers) can validate the formatting changes on staging and via PRMerger. When I have the private repo PR number, I'll post that here and then close this PR. Thanks.

**Comment by ktoliver** [comment]
Private repo PR 10983 replaces this pull request. We moved the commit to the private repo so we can validate formatting changes by using automated validation and staging. We'll close this PR now.

@mightypen - PR reviewers will do a check on staging as usual. If all looks good to us, we'll apply your sign-off here to the new PR and merge. Thanks.

**Comment by yoichinak** [comment]
I don't mind either escapes or characters. Thank you for considering my PR :)

**Pull request closed without merging**
