### PR TITLE
Update winauth-azuread-setup-modern-interactive-flow.md

### PR DESCRIPTION
**Pull request by mudeeb**
adding |Azure subscription under the same Azure AD tenant you plan to use for authentication. |  to match what we have under 

https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/winauth-azuread-setup?view=azuresql#modern-interactive-authentication-flow

### CODE REVIEW

**Comment by PRMerger10** [comment]
@mudeeb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@srdan-bozovic-msft 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by rothja** [comment]
@srdan-bozovic-msft Could you take a look at the proposed change in this public PR? There are merge conflicts that I can help resolve if you approve the change. Otherwise, you can comment in this PR with your feedback. Thanks!

**Comment by MashaMSFT** [comment]
Hi @mudeeb, looks like this change was already made in this commit https://github.com/MicrosoftDocs/sql-docs/commit/15850ee3ecbce4b28c0d28aedaa3b780abf692bd :) thanks so much for your contribution!

**Pull request closed without merging**
