### PR TITLE
Fixed sample T-SQL

### PR DESCRIPTION
**Pull request by johnmart82**
The T-SQL example here was the same as that in the article for creating an alert based on an error message. I have corrected the sample code to create an alert based on detection of a severity level in line with the content of this page.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@johnmart82 : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
#sign-off 

@johnmart82 Thanks for this PR.  I am approving it now.

**Comment by PRMerger15** [comment]
@MightyPen: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
I have sent email to TechDocPRs, asking them to merge this PR 1575.

**Pull request merged**
