### PR TITLE
Update rename-transact-sql.md

### PR DESCRIPTION
**Pull request by charithcaldera**
"ALTER DATABASE" cannot be used to rename databases in Azure Synapse Analytics. 
Currently, Serverless SQL pool does not supported for "ALTER DATABASE MODIFY NAME" and SQL Dedicated Pools cannot be renamed. 
Test scenario is attached
[Test Scenario - Rename SQL Pools.docx](https://github.com/MicrosoftDocs/sql-docs/files/8817665/Test.Scenario.-.Rename.SQL.Pools.docx)
.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@charithcaldera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@ronortloff, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged"

**Comment by jborsecnik** [comment]
@vvasic-msft, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged" 
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger15** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by vvasic-msft** [comment]
Correct, it's not supported in serverless.

#sign-off

**Comment by PRMerger5** [comment]
@vvasic-msft: I'm sorry - only the author of this article, @ronortloff, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
