### PR TITLE
Update polybase-configure-sql-server.md

### PR DESCRIPTION
**Pull request by pabechevb**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@pabechevb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by MikeRayMSFT** [comment]
@pabechevb - thank you for the submission. We are reviewing.

**Comment by MikeRayMSFT** [comment]
Staging in private repo

**Pull request closed without merging**
