### PR TITLE
Update create-database-scoped-credential-transact-sql.md

### PR DESCRIPTION
**Pull request by NandanHegde15**
Added an additional scenario of Secret length restriction in Azure Synapse

### CODE REVIEW

**Comment by PRMerger16** [comment]
@NandanHegde15 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @NandanHegde15 - I apologize for the delay.

@julieMSFT - Hi Julie, is this something you can take a look at for Azure Synapse?

**Comment by julieMSFT** [comment]
@nanditavalsan Please review this update.

**Comment by nanditavalsan** [comment]
Azure Synapse Analytics and other Azure SQL services have the same secret length for database scoped credentials. Please re-submit your change without specifying the service name if you believe that additional details will be useful. The new PR will be directed to the correct team.
#please-close

**Comment by NandanHegde15** [comment]
> Azure Synapse Analytics and other Azure SQL services have the same secret length for database scoped credentials. Please re-submit your change without specifying the service name if you believe that additional details will be useful. The new PR will be directed to the correct team.
> #please-close

Hey @nanditavalsan,
The issue is only for Azure SQL DW and not for Azure SQL database, hence had explicitly called out.
We were able to create a database scoped credential via SAS value in Azure SQL database but the same SAS value when we tried in synapse it failed with the restriction error.

**Comment by nanditavalsan** [comment]
Are you attempting to create a database scoped credential for use with Polybase or load data from Azure Storage? This will not work for SAS as noted here in the document. https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?view=sql-server-ver15#b-creating-a-database-scoped-credential-for-a-shared-access-signature.
The sentence ahead of the change you are proposing states that you must use an Azure Storage key, "To load from Azure Blob storage into Azure Synapse Analytics or Parallel Data Warehouse, the Secret must be the Azure Storage Key.".

**Comment by NandanHegde15** [comment]
Hey @nanditavalsan ,
Yes, we had seen that Synapse doesn't support use of SAS and we were testing out what all properties are different between SQL database and synapse and there we found that synapse has a length restriction whereas Azure SQL database doesn't.
So I added that note in this PR highlighting Synapse

**Pull request closed without merging**
