### PR TITLE
update release note for SSDT for VS2017 15.9.6

### PR DESCRIPTION
**Pull request by MSraye**
update release note for SSDT for VS2017 15.9.6

### CODE REVIEW

**Comment by PRMerger18** [comment]
@MSraye : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dzsquared** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Edited for grammar (the use of articles) and Microsoft style. Note that the Microsoft Writing Style Guide says to never use "VS" in text to refer to Visual Studio (branding). Also, there's a code comment with guidance to the author that should be resolved. Thanks! Merging now.

**Pull request merged**
