### PR TITLE
Correct TrustServerCertificate keyword

### PR DESCRIPTION
**Pull request by RobJohnston**
Corrects the connection string keyword from "Trust Server Certificate" to "TrustServerCertificate" as per
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-string-syntax#using-trustservercertificate.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@RobJohnston : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@David-Engel 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by David-Engel — APPROVED** [review]
Actually, both properties are correct. "TrustServerCertificate" is a synonym for "Trust Server Certificate" in Microsoft.Data.SqlClient:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.trustservercertificate?view=sqlclient-dotnet-standard-4.1

I'm fine changing it here to be consistent with other doc references and with System.Data.SqlClient, which doesn't have the synonym.

**Comment by David-Engel** [comment]
#sign-off

**Pull request merged**
