### PR TITLE
Update service-tier-hyperscale-frequently-asked-questions-faq.yml

### PR DESCRIPTION
**Pull request by KoprowskiT**
A few changes with grammar, punctuation, and wording.

### CODE REVIEW

**Comment by rwestMSFT** [comment]
@KoprowskiT Please make all your changes in a single PR next time, not multiple. I counted eight in total, with one conflict.

I'm replacing all eight with an internal PR, where we will probably use most of your changes, and you will get appropriate credit.

Thanks for your contribution!

**Comment by rwestMSFT** [comment]
Replaced by internal PR https://github.com/MicrosoftDocs/sql-docs-pr/pull/28663.

@KoprowskiT We use the Oxford comma, so I removed a few of your edits. As my colleague also noted, Azure SQL Database is the name of the service, so other edits were redacted.

It will take about a day for the internal PR to be approved and published, at which point you will see the updated content.

Thank you again for your contributions. We appreciate your close attention to our content.

**Comment by KoprowskiT** [comment]
Thank You, @rwestMSFT & @dimitri-furman , for clarification! 

I will refrain from pulling nonsense changes (like Oxford and the articles into front of product names (I'm still learning things). But I hope some suggestions were sensible after all. And I'll try to continue checking and updating suggestions - in the worst case, you can easily reject the pull requests, won't you?

Thank you for the great opportunity to help make this better for everyone!!

**Comment by rwestMSFT** [comment]
@KoprowskiT Yes, they were definitely helpful. We get a lot of content changes through here, and a keen eye is always appreciated.

**Pull request closed without merging**
