### PR TITLE
Fixed terms

### PR DESCRIPTION
**Pull request by allanhirt**
The feature name is Always On failover cluster instance, not SQL Server failover cluster. Fixed a bunch of stuff here. 

Lots of doc needs to be corrected, but I'm tackling them when I see them. Already put 3 in today for you guys besides this.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@rothja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@allanhirt I fixed a merge conflict due to some updates in our applies-to include files. @MashaMSFT please take a look at the proposed terminology fixes now that the merge conflict is resolved.

**Comment by PRMerger12** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
#sign-off 

thanks @allanhirt !

**Pull request merged**
