### PR TITLE
update download page for SSDT for VS2017 15.9.6

### PR DESCRIPTION
**Pull request by MSraye**
update download page for SSDT for VS2017 15.9.6

### CODE REVIEW

**Comment by PRMerger18** [comment]
@MSraye : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @MSraye Release notes should be updated in the private repo so the revisions can be checked on staging and pass quality validations before merging. Would you submit this update in the private repo? Let me know if you need information about how to access the private repo; I can email it to you. Thanks. We'll close this PR.

**Comment by MSraye** [comment]
Hi Kristine,

May you please share more on how to access the private repo?

Thanks,
Ran

**Comment by ktoliver** [comment]
Hi @MSraye I've reopened the PR so it can move forward with review. I'll send email with information about working in the private repo. Thanks.

**Comment by ktoliver** [comment]
@dzsquared Would you review the proposed update to your article? If you approve the PR, we can merge it. Thanks.

**Comment by dzsquared** [comment]
holding on approving until the release notes are corrected and ready to merge

**Comment by dzsquared** [comment]
#sign-off

**Pull request merged**
