### PR TITLE
Update dma command line

### PR DESCRIPTION
**Pull request by siyangMicrosoft**
Assessment: support RDS assessment(source platform is RdsSqlServer). Add /AssessmentSouecePlatform setting input. This is optional. 

Target Readiness Assessment: support RDS assessment and Cassandra assessment. Add /AssessmentSourcePlatform and /AssessmentTargetPlatform settings. Both are optional. In config file, add <SourcePlatform> and <TargetPlatform> element.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@siyangMicrosoft : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@siyangMicrosoft : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@craigg-msft - can you review the changes or assign to an appropriate author? @pochiraju no longer shows up in the Git Hub lists. Thanks!

**Comment by craigg-msft** [comment]
email author internally, and with suggestions on how to link git id.

**Comment by guerrajames** [comment]
Who the hell is this because I'm not involved with this GitHub stuff

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ysy68251435** [comment]
close

**Comment by craigg-msft** [comment]
@HJToland3 said the PRs are good an he will also become the author of the topics.

**Pull request merged**
