### PR TITLE
new example using constraint

### PR DESCRIPTION
**Pull request by pricardo03**
hope help to understand how create directed graphs and relations between nodes :)

### CODE REVIEW

**Comment by PRMerger16** [comment]
@pricardo03 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@shkale-msft -- Hi, could you review the proposed update to your article? Thanks.

**Review by shkale-msft — APPROVED** [review]
looks good.

**Comment by shkale-msft** [comment]
#sign-off

**Pull request merged**
