### PR TITLE
Spelling Fix Wave 2

### PR DESCRIPTION
**Pull request by ArieHein**
Continuation of the Spelling fixes from before the freeze.

Ill be sending more in separate PRs, one at a time, @rwestMSFT enjoy !

### CODE REVIEW

**Comment by rwestMSFT** [comment]
We're going to do this in two or three internal PRs because of the number of files I also found (another 30 or so). This PR will close when the _first_ one is merged, so give it a couple business days after that before going for the next batch.

**Comment by ArieHein** [comment]
@rwestMSFT  would you prefer i do it in smaller batches, to ease your internal PR cycles ?
At the time of this writing, i have about 120 more and its growing :)

**Comment by rwestMSFT** [comment]
> @rwestMSFT would you prefer i do it in smaller batches, to ease your internal PR cycles ? At the time of this writing, i have about 120 more and its growing :)

No, that’s my problem to solve. Please keep doing what you’re doing. However, note that we may not get to it for a couple of weeks due to other factors.

**Comment by ArieHein** [comment]
Ok, ive closed the next wave with 260 more additional files that have at least one spelling.
Would next week be ok for creating a new PR or you want it all now ? :)

**Comment by rwestMSFT** [comment]
@ArieHein Send it all now, please. It will be merged before January, but I can't give a more accurate timeline.

**Pull request closed without merging**
