### PR TITLE
Update clr-enabled-server-configuration-option.md

### PR DESCRIPTION
**Pull request by aharpervc**
- add missing quote
- correct capitalization

### CODE REVIEW

**Comment by PRMerger14** [comment]
@aharpervc : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by aharpervc** [comment]
> See the terminology usage at Common Language Runtime (CLR). https://docs.microsoft.com/en-us/dotnet/standard/clr

I see that that example is sentence case in body text. And I can certainly update this PR for sentence casing. However, it's listed here as title case https://www.visualstudio.com/license-terms/ecma-c-common-language-infrastructure-standards/ and in the linked docs here, "Common Language __" is always title cased even in body text.

Since these docs have been around for awhile, is it a recent development that "common language __" should always be sentence cased?

**Comment by PRMerger13** [comment]
@aharpervc : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
@aharpervc - I'm actually running this by a terminologist here to verify. I appreciate you bringing the inconsistency to our attention. I'm going to hold this to verify. 
Thanks,
Mike

**Comment by MikeRayMSFT** [comment]
The terminologist answer is that common language runtime is not a name and so it should be lowercase. Thanks again for the submission. #sign-off

**Pull request merged**
