### PR TITLE
add two known issues in Download page

### PR DESCRIPTION
**Pull request by MSraye**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@MSraye : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@MSraye - Not sure if this is still relevant after the last couple PRs. If still needed as soon as the merge conflict is addressed I'll sign off on this.

**Comment by MSraye** [comment]
Hi Steve,

Thanks for the reminder. One known issue in the below PR still needs to be added to download page and changelog page.
I have posted two new PR for it and please help sign off them.

Thanks,
Ran

**Comment by stevestein** [comment]
Changes covered in PRs 1219 and 1220. Closing this one...

**Pull request closed without merging**
