### PR TITLE
Added notes for Azure SQL DB and for SQL MI

### PR DESCRIPTION
**Pull request by rarandiv**
Added notes - T-SQL debugging is not supported for Azure SQL DB as well for SQL Managed Instance

### CODE REVIEW

**Comment by PRMerger17** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by markingmyname — APPROVED** [review]
Changes approved.

Made one small edit - to remove an extra "isn't"

Once the build is complete I will sign-off

**Comment by markingmyname** [comment]
#sign-off

**Review by markingmyname — APPROVED** [review]

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
