### PR TITLE
Update sys-dm-db-resource-stats-azure-sql-database.md

### PR DESCRIPTION
**Pull request by fixersatoh**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@fixersatoh : Thanks for your contribution to the SQL documentation! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by CarlRabeler** [comment]
@craigg-msft why am I getting this notice that only the author can sign off - as I am the author

**Comment by craigg-msft** [comment]
Thank you @fixersatoh and @CarlRabeler

**Pull request merged**
