### PR TITLE
Fixed first listed sp to not be a Header

### PR DESCRIPTION
**Pull request by mstehrani**

### CODE REVIEW

**Comment by mstehrani** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@mstehrani: I'm sorry - only the author of this article, @ronortloff, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @mstehrani - We'll merge the PR; would you make future content updates in the private repo? Small fixes like this usually auto-merge in the private repo, so it's more efficient. 👍  Thanks!

**Comment by mstehrani** [comment]
@ktoliver Apologies on that, I now know for next time. Thank you!

**Pull request merged**
