### PR TITLE
typo: remove value from no value context SUSER_ID()

### PR DESCRIPTION
**Pull request by jong82**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@jong82 : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by seshenoy** [comment]
@jong82 closing and reopening the PR.

**Comment by rothja** [comment]
@jong82 Thank you for this fix. Reviewed and signing off. #sign-off

**Comment by PRMerger16** [comment]
@rothja: I'm sorry - only the author of this article, @edmacauley, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
