### PR TITLE
Add the new options for XEvent consumption by PowerShell and .NET

### PR DESCRIPTION
**Pull request by TomerWeisberg**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@TomerWeisberg : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @TomerWeisberg , thank you for your contribution! Let me verify a few things on my end. Thanks!

**Comment by PRMerger10** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
Hi @TomerWeisberg , thanks again for adding this to our documentation! Certainly helpful :) #sign-off

**Comment by PRMerger18** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
