### PR TITLE
Adapt growth value to context and give clarity on growth unit

### LINKED ISSUE #8210: Would suggest to adapt the query to check current size and growth to have growth in MB, like size is in MB for consistency reasons
The size and growth check query in chapter: https://learn.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver16#optimizing-tempdb-performance-in-sql-server, is referring to the growth value in a different unit than the size value, which is mega-bytes. I think for consistency reasons, it would be better to have growth in MB as well like:

```
SELECT name AS FileName,
    size*1.0/128 AS FileSizeInMB,
    CASE max_size
        WHEN 0 THEN 'Autogrowth is off.'
        WHEN -1 THEN 'Autogrowth is on.'
        ELSE 'Log file grows to a maximum size of 2 TB.'
    END,
    **growth*1.0/128 AS 'GrowthValueInMB',**
    'GrowthIncrement' =
        CASE
            WHEN growth = 0 THEN 'Size is fixed.'
            WHEN growth > 0 AND is_percent_growth = 0
                THEN 'Growth value is in 8-KB pages.'
            ELSE 'Growth value is a percentage.'
        END
FROM tempdb.sys.database_files;
GO
```

It's just a suggestion.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37fab3b5-a2f3-5612-06e2-01e0406a615d
* Version Independent ID: 2daa00e0-8234-bf26-13c0-8d5200a1f4a5
* Content: [tempdb database - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver16#feedback)
* Content Source: [docs/relational-databases/databases/tempdb-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/tempdb-database.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

### PR DESCRIPTION
**Pull request by brunogonzalez**
In case of a file growth set in MB, the original query gives the data file growth size in units of 8-KB pages, which is not really clear for some people. Plus, the file size is in MB, so it lacks a bit of consistency. This proposal will give the growth value in MB in this case instead of 8-KB pages, and will keep percentage value or 0 for fixed size.

Resolves https://github.com/MicrosoftDocs/sql-docs/issues/8210

### CODE REVIEW

**Comment by brunogonzalez** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by ShannonLeavitt** [comment]
@WilliamDAssafMSFT 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WilliamDAssafMSFT** [comment]
Thanks @brunogonzalez for taking the time to submit this PR! I've updated your commit with some formatting. Once we sign off, your commit will be merged and this article update is in flight. After the updated article is published, GitHub will list you as an article contributor. 

Please confirm the CLA.

**Comment by WilliamDAssafMSFT** [comment]
No response from customer, but this looks good. #sign-off 
FYI @rwestMSFT

**Pull request merged**
