### PR TITLE
Add BusinessRuleUserScriptExecuteFirst setting information

### PR DESCRIPTION
**Pull request by v-redu**
Add BusinessRuleUserScriptExecuteFirst setting information. We have added a system setting record for business rule. This change will release on SQL Server 2017 CU11.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@v-redu : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@v-redu Josh, please make the following simple changes. Then I will sign off on your PR.

1. We prefer to use only the present tense. Change "will execute" to "executes".

2. Change "is change" to "is changed".

3. Change "hide setting" to "hidden setting", assuming that this is the intended meaning.

**Comment by PRMerger13** [comment]
@v-redu : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@douglaslMS: I'm sorry - only the author of this article, @leolimsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
