### PR TITLE
Clarify System MI usage

### PR DESCRIPTION
**Pull request by ErikEJ**
Make it clearer that object id of system assigned managed identity must be used and placed in 'user id' connection string property.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@ErikEJ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by cheenamalhotra — APPROVED** [review]

**Comment by ErikEJ** [comment]
@karinazhou ...

**Comment by ktoliver** [comment]
We'll merge the PR. The approval didn't turn up in our twice daily queries, and I just saw that @cheenamalhotra approved 14 days ago. Also, we usually need sign-off by the content team or program management team, but in this case, @cheenamalhotra appears to work on the same team as the listed author, so we'll merge. 

To be sure that PR reviewers see an approval and can then merge the PR, the author should type `#sign-off` in a comment in the PR. Thanks!

**Comment by ErikEJ** [comment]
@ktoliver Thanks, is the #sign-off thing documented anywhere - I am a community contributor.

**Comment by PRMerger8** [comment]
@ErikEJ: I'm sorry - only the author of this article, @karinazhou, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor Thanks, is the #sign-off thing documented anywhere - I am a community contributor.

Hi @ErikEJ - My [comment ](https://github.com/MicrosoftDocs/sql-docs/pull/6230#issuecomment-818231069) about sign-off was directed at the Microsoft reviewers, although in general I was explaining why the pull request wasn't merged quickly, like it usually would be. I will be more specific in the future. I didn't mean to cause any confusion or ambiguity. Thanks!

**Pull request merged**
