### PR TITLE
fix moniker

### PR DESCRIPTION
**Pull request by yidetu**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@yidetu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@yidetu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
You can only sign off in the main PR conversation, not in review comments. In general, the creator of the PR should sign off, not the tech reviewer.

**Comment by yidetu** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@yidetu: I'm sorry - only the author of this article, @lrtoyou1223, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by lrtoyou1223** [comment]
#sign-off

**Comment by ktoliver** [comment]
We verified the updates on staging; looks good.

@lrtoyou1223 There's an existing issue with list numbering and indentation that's probably caused by the placement of monikers. We'll request an edit pass in the private repository to address this. Thanks.

**Pull request merged**
