### PR TITLE
Update alter-index-transact-sql.md

### PR DESCRIPTION
**Pull request by JohnKNess**
Fixed various small issues with ] and } terminators, spacing and spelling issues

### CODE REVIEW

**Comment by JohnKNess** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@rwestMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Looks good, thanks @JohnKNess!

#sign-off

**Comment by Court72** [comment]
Due to the upcoming Ignite conference, all merging and publishing is on hold until the morning of 11/15.

This PR is ready for merge on 11/15.

#label: "event-triaged-to-10AM"
#label: "missed-content-complete"

**Pull request merged**
