### PR TITLE
Fixed a precendence order explanation

### PR DESCRIPTION
**Pull request by bbetov**
The order of operations was swapped in the explanation sentence.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@bbetov : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by douglaslMS** [comment]
@bbetov Branimir, I think that our use of "higher" and "lower" is somewhat ambiguous, but I believe that the page is correct as written. The higher-level operator _at the same level_ is evaluated first. For example, in the example `SET @MyNumber = 2 * 4 + 5;`, the higher-level multiplication operator is evaluated first. On the other hand, if I enclose an operation in parentheses, then that nested operation is evaluated first - maybe this is what you had in mind?

**Comment by bbetov** [comment]
@douglaslMS Indeed. I was helping a friend that got confused by the wording and I was trying to make it a bit clearer, but re-reading it now, it is still ambiguous. How about clarifying that 1 is highest and 8 is lowest? 

Perhaps:
*An operator on higher levels is evaluated before an operator on a lower level (1 is highest and 8 lowest level).*

**Comment by bbetov** [comment]
@douglaslMS Sure - will do. Thanks.

**Comment by PRMerger20** [comment]
@bbetov : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@douglaslMS - if you approve, please sign off and we'll merge this. thanks.

**Comment by douglaslMS** [comment]
#sign-off

**Pull request merged**
