### PR TITLE
Update connect.md

### PR DESCRIPTION
**Pull request by PhilB-MSFT**
Adding note that SQL FCI is not supported for Arc-enabled SQL Server, as per PG update on IcM 336227961.

### CODE REVIEW

**Comment by Court72** [comment]
@anosov1960 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by twright-msft** [comment]
#sign-off

**Comment by anosov1960** [comment]
#sign-off

**Review by MikeRayMSFT — APPROVED** [review]

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
