### PR TITLE
Typo: Changed Hadoop to Azure Blob Storage

### PR DESCRIPTION
**Pull request by gitegite**
This is a simple fix for #2764 

Hope it helps 👍.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@gitegite : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Checking

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please look into this PR 2765.

**Comment by rothja** [comment]
@MikeRayMSFT This looks correct to me based on the context. I'm signing off. Thanks! #sign-off

**Comment by PRMerger13** [comment]
@rothja: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
