### PR TITLE
Fix "Adding versioning to non-temporal tables"

### PR DESCRIPTION
**Pull request by Achilles1515**
I don't know what has been going on with these changes recently, but the most recent update removed the PERIOD FOR SYSTEM_TIME clause making it invalid SQL. This change adds this line back in, in the exact same fashion as before.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Achilles1515 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Achilles1515** [comment]
@[jborsecnik](https://github.com/jborsecnik)

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by rwestMSFT** [comment]
There was a recent update that was merged accidentally and I’m looking at fixing it. Thank you for drawing attention to this.

**Comment by rwestMSFT** [comment]
#please-close

**Pull request closed without merging**
