### PR TITLE
Update ss-force-failover-read-scale-out.md

### PR DESCRIPTION
**Pull request by suresh-kandoth**
add additional step for listener.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@suresh-kandoth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by ktoliver** [comment]
@MikeRayMSFT Before I merge, can you verify that my grammar edits don't change the meaning? Thanks.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
