### PR TITLE
adding the operators Left shift and Right shift

### PR DESCRIPTION
**Pull request by pituach**
adding the operators Left shit and Right shift, which were added in SQL Server 2022

### CODE REVIEW

**Comment by pituach** [comment]
Note! I had a typo in the content I added

I wrote:
&#40;Shift right - SQL Server 2022& and abive#41;

But it should be:
&#40;Shift right - SQL Server 2022 and above&#41;

I fixed it now

**Comment by rwestMSFT** [comment]
@pituach Ronen, do you mind editing the typo in the pull request title?

**Comment by Court72** [comment]
@rwestMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Thanks for the edit, @Court72. I'll look into this PR shortly.

**Pull request closed without merging**
