### PR TITLE
Update Synchronizing status description for the Failover Group in SQL MI

### PR DESCRIPTION
**Pull request by luis-aranda**
It seems there is a contradiction on the documentation as it is stated clearly that the in the Seeding status, we cannot failover
The Synchronizing status description states that the failover can be performed on the Seeding status, which doesn't match to the previous statement. Seems to be a typo

### CODE REVIEW

**Comment by PRMerger12** [comment]
@luis-aranda : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@MladjoA - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by MladjoA — APPROVED** [review]

**Comment by MladjoA** [comment]
@luis-aranda , thanks for noticing and fixing the typo!

**Comment by MladjoA** [comment]
#sign-off

**Pull request merged**
