### PR TITLE
chore: Add Docs Authoring Pack suggestions

### PR DESCRIPTION
**Pull request by nschonni**
This will suggest the Docs Authoring pack when editors are using VS Code to modify the repo

### CODE REVIEW

**Comment by PRMerger8** [comment]
@nschonni : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@jmazzotta Hi Joe, Do you know who in APEX can tell me & our SQL Documentation team what the proposed changes do (here in PR 1472 , repo 'MicrosoftDocs/sql-docs')?

**Comment by nschonni** [comment]
@MightyPen sorry, maybe this gives a bit better overview https://github.com/MicrosoftDocs/feedback/issues/893

**Comment by MightyPen** [comment]
@nschonni Nick, We have decided not to merge this PR 1472, and instead to close it permanently, unmerged.  We prefer to minimize any churn in our config files that is less than necessary.  This decision is not doubting the accuracy or value of this proposed PR.  Thank you.

**Comment by nschonni** [comment]
No problem, I'll see if it gets pushed centrally like the boilerplate `.gitattributes` was

**Pull request closed without merging**
