### PR TITLE
Added new example T for temp table creation.

### PR DESCRIPTION
**Pull request by jzabroski**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@jzabroski : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@jzabroski : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@jzabroski : Thanks for your contribution! The author, @CarlRabeler, has been notified to review your proposed change.

**Pull request merged**
