### PR TITLE
Update sql-server-browser-service.md

### PR DESCRIPTION
**Pull request by chrisbaudo**
Removing references to SQL Server Managed Instance.

From my understanding the SQL Server Browser Service does not apply to SQL Server Managed Instance.  Instead, an internal load balancer and the SQL Managed Instance gateway replace the SQL Server Browser Service functionality to redirect connections to the correct managed instance.  This is described separately in the SQL Managed Instance documentation:

"This private IP address belongs to the internal load balancer for SQL Managed Instance. The load balancer directs traffic to the SQL Managed Instance gateway. Because multiple managed instances can run inside the same cluster, the gateway uses the SQL Managed Instance host name to redirect traffic to the correct SQL engine service."

https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/connectivity-architecture-overview#virtual-cluster-connectivity-architecture

This documentation makes it appear as though the SQL Server Browser Service is actively used as a part of SQL Server Managed Instance.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@chrisbaudo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by markingmyname — APPROVED** [review]

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
