### PR TITLE
Example for COPY INTO with MSI

### PR DESCRIPTION
**Pull request by thesqlpro**
I would like to get this example added for COPY INTO using MSI. Customer has tried to go through our documentation, and was unable to find the exact syntax to have copy only use MSI for credentialing.  Worked with Synapse Team (Artur Vieira Artur.Vieira@microsoft.com> provided this example) to get code to work with the customer.

### F. Load using MSI credentials

Set the Synapse SQL to use “-AssignIdentity”

Set-AzSqlServer -ResourceGroupName $resourcegroupname -ServerName $servername -AssignIdentity

Create a Scoped credential on your Database

CREATE DATABASE SCOPED CREDENTIAL msi_cred WITH IDENTITY = 'Managed Service Identity';

COPY INTO dbo.myCOPYDemoTable

FROM 'https://storlabarturv.blob.core.windows.net/test/bcpDemo.txt'

WITH (

    FILE_TYPE = 'CSV',

    CREDENTIAL = (IDENTITY = 'Managed Identity'),

    FIELDQUOTE = '"',

    FIELDTERMINATOR=','

)

### CODE REVIEW

**Comment by PRMerger8** [comment]
@thesqlpro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by thesqlpro** [comment]
Any updates on this?

**Comment by ktoliver** [comment]
@MightyPen Could you or someone on your team review this pull request? Thanks.

**Comment by kevinvngo** [comment]
Thanks for providing this example! We don't need scoped credential for COPY:

Create a Scoped credential on your Database
CREATE DATABASE SCOPED CREDENTIAL msi_cred WITH IDENTITY = 'Managed Service Identity';

Other than that, it looks good.

**Comment by PRMerger17** [comment]
@julieMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@julieMSFT: I'm sorry - only the author of this article, @kevinvngo, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by julieMSFT** [comment]
@ktoliver HI Kristine, I spoke with Kevin and updated the PR. This can be merged.

**Comment by ktoliver** [comment]
Thanks, all

**Pull request merged**
