### PR TITLE
Add creation of a container access policy

### PR DESCRIPTION
**Pull request by jshealth**
Creating the SAS without a start, expiry and permissions as in the AZ cli example causes backups to fail.

I tested using SQL Server 2016 (SP2-CU10) (KB4524334) running on an Azure VM
and 1) `managed_backup.sp_backup_config_schedule` 2)  `msdb.managed_backup.sp_backup_config_basic` and 3) `managed_backup.sp_backup_on_demand`

Using the Az CLI SAS as described causes 3) to fail.

Additionally using a SAS generated by Terraform `azurerm_storage_account_blob_container_sas`  will work with 3) but not 1) and 2)

Although the documented Powershell example appears to work, I've added creation of a Policy on the Storage Container which works in all cases 1), 2) and 3)

Also see the following where a Policy is used https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-2016#1---create-stored-access-policy-and-shared-access-storage

The policy also allows for easier management of the SAS by invalidating, or modifying the policy, including extending or shortening the expiry.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@jshealth - Could you sign the CLA so we can consider your changes? The CLA is all electronic and will take just a few minutes: https://cla.microsoft.com. Thank you.

**Comment by jshealth** [comment]
> @jshealth - Could you sign the CLA so we can consider your changes? The CLA is all electronic and will take just a few minutes: https://cla.microsoft.com. Thank you.

Hi @ShannonLeavitt  I'm employed by NSW Health and so I'm just checking with them first before signing the CLA, thanks.

**Comment by ktoliver** [comment]
@jshealth has not returned to sign the Contributor License Agreement. We'll close the PR.

**Comment by jshealth** [comment]
I requested permission from my managers to sign the CLA, but never got approval. Thanks for closing this.

**Pull request closed without merging**
