### PR TITLE
Update download-oledb-driver-for-sql-server.md

### PR DESCRIPTION
**Pull request by v-mkmiecik**

### CODE REVIEW

**Review by a-gazin — APPROVED** [review]

**Review by David-Engel — APPROVED** [review]
LGTM

**Review by chris-rossi — APPROVED** [review]

**Review by VictorBei — APPROVED** [review]

**Comment by v-mkmiecik** [comment]
#sign-off

**Comment by David-Engel** [comment]
#sign-off

**Comment by David-Engel** [comment]
#hold-off

**Pull request closed without merging**
