### PR TITLE
Added xml_compression and xml_compression_desc to sys.partitions

### PR DESCRIPTION
**Pull request by dhmacher**

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@rwestMSFT

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@dmacher Are you sure about XML compression and SQL Server 2016 specifically? As far as I know, it was only introduced in SQL Server 2022.

**Comment by dhmacher** [comment]
@rwestMSFT I may have misunderstood the syntax of the include tag, thinking that version 16 is SQL Server 2022? I copied the "applies to" block from a few lines up, where 11 is meant to reference SQL Server 2012.

**Comment by dhmacher** [comment]
Ah, I see they changed it, starting with version 2014 (12 -> 14). Will update my contribution. :)

**Comment by rwestMSFT** [comment]
@dmacher Thanks :grin: I need to refresh the underlying article, so your change will be incorporated into that internal PR. You'll still get credit, and this PR will automatically close when that happens.

**Pull request closed without merging**
