### PR TITLE
Update columnstore-indexes-data-loading-guidance.md

### PR DESCRIPTION
**Pull request by SQLvariant**
Corrected bracket in Minimal logging: section to make link work.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@SQLvariant : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SQLvariant** [comment]
Adding @MashaMSFT since I discussed this correction with her.

**Comment by MashaMSFT** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @MikeRayMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
