### PR TITLE
Author name & clarification

### PR DESCRIPTION
**Pull request by allanhirt**
I wrote this. Didn't notice my name in the header.

Also qualified text for log shipping change

### CODE REVIEW

**Comment by PRMerger13** [comment]
@allanhirt : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
Thank You @allanhirt. #sign-off

**Comment by PRMerger7** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @MashaMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeRayMSFT** [comment]
@MashaMSFT - FHI I verified, submitted, and merge.

**Pull request merged**
