### PR TITLE
Update dbcc-traceon-trace-flags-transact-sql.md

### PR DESCRIPTION
**Pull request by rayyenmstw**
Several customer encountered the database recovery very long period issue which the database contains large in-memory table, especially there is no performance bottleneck. The following KB provide the trace flag 9944 as fix. So, I want to let this trace flag visible on central location.  
FIX: In-Memory OLTP database takes a long time to recover in SQL Server 2017 (https://support.microsoft.com/en-us/help/4090789/in-memory-oltp-database-takes-a-long-time-to-recover-in-sql-server)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@rayyenmstw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rayyenmstw** [comment]
@pmasl Would you review the proposed update to your article?

Thanks.

**Comment by pmasl** [comment]
I'll update the article separately. Thanks for calling out that the TF exists in another KB.

#please-close

**Comment by rayyenmstw** [comment]
@pmasl Thank you very much!

**Pull request closed without merging**
