### PR TITLE
Wrong retirement date

### PR DESCRIPTION
**Pull request by DaniBunny**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@DaniBunny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DaniBunny** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@DaniBunny: I'm sorry - only the author of this article, @WilliamDAssafMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by WilliamDAssafMSFT** [comment]
Will address with this internal PR:

**Pull request closed without merging**
