### PR TITLE
Update register-a-service-principal-name-for-kerberos-connections.md

### PR DESCRIPTION
**Pull request by andreasjordan**
Fixed a typo (I think it is a typo)

### CODE REVIEW

**Comment by Court72** [comment]
@rwestMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
This looks correct, but I need to check with a product manager first. Thanks for the contribution.

**Comment by rwestMSFT** [comment]
#sign-off

**Comment by andreasjordan** [comment]
Just a quick feedback about the process: All was very easy, thanks for the well designd workflow.

**Pull request merged**
