### PR TITLE
Small typo/english fix to docs attach-a-database

### PR DESCRIPTION
**Pull request by jstolp**
Fixed a small typo in docs/relational-databases/databases/attach-a-database.md

### CODE REVIEW

**Comment by edmacauley** [comment]
@craigg-msft I'm not the author, but this change looks good just in case.

**Comment by PRMerger3** [comment]
@jstolp : Thanks for your contribution to the SQL documentation! The author, @JennieHubbard, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
@jstolp Thank you for making this change! As others have said, your changes look good. 👍

**Comment by JennieHubbard** [comment]
#sign-off

**Pull request merged**
