### PR TITLE
compatibility for Windows 7 and Windows 2008 R2 differs

### PR DESCRIPTION
**Pull request by Karl-WE**
I have changed the doc, in case this is a mistake. Otherwise please comment and close PR.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by David-Engel** [comment]
@Karl-WE Thanks for the submission. But your edit has changed the SQL support table, not the operating system support table. Based on you comment, it sounds like you just confused the tables. Windows 7 and Windows 2008 R2 support is already identical in the OS table for version 17.4.

Feel free to re-open and update your PR if you meant to change something else.

#please-close

**Comment by Karl-WE** [comment]
@David-Engel thank you for pointing this out. I think I have misread the table infact.
So 2008R2 is supported as OS with 17.4 but not the SQL DB of the same generation. It that correct? 
If so then the close is correct. Thank you for your reply.

**Comment by David-Engel** [comment]
> So 2008R2 is supported as OS with 17.4 but not the SQL DB of the same generation. It that correct?

@Karl-WE Correct. Driver support for OS/database aligns with general/extended support for those products. [Support for SQL Server 2008 R2 ended July 9, 2019](https://support.microsoft.com/en-us/help/4456242/end-of-support-for-sql-server-2008-and-sql-server-2008-r2). ODBC Driver 17.4 released July 31, 2019. [Windows 2008 R2 support ended January 14, 2020](https://www.microsoft.com/en-us/cloud-platform/windows-server-2008).

**Pull request closed without merging**
