### PR TITLE
Update basic-availability-groups-always-on-availability-groups.md

### PR DESCRIPTION
**Pull request by kazuyuk**
Following line is not needed, because SSMS is supported on v16.x  for create with basic DMV command.
 >   'At this time, there is no UI support to create basic availability groups in SQL Server Management Studio.'

### CODE REVIEW

**Comment by PRMerger17** [comment]
@kazuyuk : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by kazuyuk** [comment]
Ooops, sorry, I think following message is better than trimed. 
  'There is UI support to create basic availability groups in newest SQL Server Management Studio.'

**Comment by MashaMSFT** [comment]
Hi @kazuyuk, thank you so much for your contribution! You're correct, this is a great addendum to highlight. Thanks again! #sign-off

**Comment by PRMerger15** [comment]
@kazuyuk : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Pull request merged**
