### PR TITLE
PHP Code Style and Markdown Format

### PR DESCRIPTION
**Pull request by sgotre**
For better readability

### CODE REVIEW

**Comment by craigg-msft** [comment]
@sgotre thank you for the contribution.  Did you sign the CLA?  thanks

**Comment by craigg-msft** [comment]
closing and re-opening to see if the CLA check passes

**Comment by craigg-msft** [comment]
@sgotre I am closing this PR.  if you sign the CLA, please re-submit.  Thank you

**Comment by sgotre** [comment]
sorry i can not sign this :( bit please take my PR as inspiration :)

**Pull request closed without merging**
