### PR TITLE
Fixes typo

### PR DESCRIPTION
**Pull request by bertwagner**
Adds a missing space between words "processfits" -> "process fits"

### CODE REVIEW

**Comment by PRMerger3** [comment]
@bertwagner : Thanks for your contribution to the SQL documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
Thank you @bertwagner  for the help.
@MightyPen can you please review.

**Comment by MightyPen** [comment]
@bertwagner @craigg-msft  Good fix (PR 325).
#sign-off

**Comment by PRMerger3** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
