### PR TITLE
Update lesson-1-6-adding-and-configuring-the-lookup-transformations.md

### PR DESCRIPTION
**Pull request by TonyTedjo**
I think the current SQL statement is referring to incorrect table and column name.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@TonyTedjo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
See also https://github.com/MicrosoftDocs/sql-docs/pull/6553

**Comment by ktoliver** [comment]
@chugugrace Could you take a look at the proposed update to your article?

Thanks!

**Comment by ktoliver** [comment]
Approved via email; merging.

**Pull request merged**
