### PR TITLE
Update sql-server-linux-active-directory-authentication.md

### PR DESCRIPTION
**Pull request by tejasaks**
Removing extra space in addent command lines which would have caused error with the command.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@tejasaks : Thanks for your contribution! The author, @Dylan-MSFT, has been notified to review your proposed change.

**Comment by tejasaks** [comment]
https://github.com/MicrosoftDocs/sql-docs/pull/2050

**Comment by tejasaks** [comment]
Adding Jason Roth.

~Tejas Shah | Senior Program Manager | SQL Tiger Team

**Comment by rothja** [comment]
@tejasaks I assume that this was meant to stay open and get merged in? If so, I can do that. Thanks!

**Comment by tejasaks** [comment]
Yes it was, thanks for taking care of it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rothja** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@rothja: I'm sorry - only the author of this article, @Dylan-MSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
