### PR TITLE
Update dynamic-data-masking.md

### PR DESCRIPTION
**Pull request by MideMSFT**
The serveradmin system role can't see unmasked data because it does not have enough permission to databases. So, I removed it.

### CODE REVIEW

**Comment by Court72** [comment]
@VanMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by VanMSFT** [comment]
Thanks, @MideMSFT!

Hi @Madhumitatripathy - Can you please review this PR? Thanks!

**Comment by Madhumitatripathy** [comment]
@MideMSFT Thanks for checking this and the change will be committed.

**Comment by Madhumitatripathy** [comment]
#sign-off

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
