### PR TITLE
Fix list style

### PR DESCRIPTION
**Pull request by imba-tjd**
You may squash this if you want a better commit message

### CODE REVIEW

**Comment by PRMerger16** [comment]
@imba-tjd : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@imba-tjd : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@imba-tjd : Thanks for your contribution! The author, @MashaMSFT, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Verified editorial correction.

**Pull request merged**
