### PR TITLE
Update kusto-extension.md with known issues

### PR DESCRIPTION
**Pull request by MsSQLGirl**
Known issues as at Azure Data Studion v.1.23.0 (October release)

### CODE REVIEW

**Comment by PRMerger16** [comment]
@MsSQLGirl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MsSQLGirl** [comment]
@markingmyname Can you please review the changes?

**Comment by ktoliver** [comment]
Hi @MsSQLGirl -- Could you submit this content update in the private repo? If you want the author to review the update, you can at-mention them in a comment in the PR before you add `#sign-off` (in a private repo PR). Thank you! We'll close this PR.

**Comment by markingmyname** [comment]
New Pr in the private repo - https://github.com/MicrosoftDocs/sql-docs-pr/pull/17730

**Pull request closed without merging**
