### PR TITLE
Specify optional parameters

### PR DESCRIPTION
**Pull request by way0utwest**
Noting which parameters are required and which are optional

### CODE REVIEW

**Comment by VanMSFT** [comment]
@way0utwest - Hi Steve! Thanks for this addition. Although we appreciate your attempt at clarifying the article further, noting whether a parameter is optional is not something we normally do. This is because it's implied in the Syntax section, and the way we specify our syntax convention. Please let us know if you have further feedback, but for now, I will deny this addition. Thanks!

**Comment by way0utwest** [comment]
I get that. The thing that was strange here is you have the various parameters specified the same in the syntax section, but some are not optional. Should the syntax diagram reflect that?

**Comment by VanMSFT** [comment]
> I get that. The thing that was strange here is you have the various parameters specified the same in the syntax section, but some are not optional. Should the syntax diagram reflect that?

Absolutely. If you see that the Syntax is formulated incorrectly according to the convention, that would be where to fix it.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@way0utwest This change has been incorporated into an internal PR. When that PR is merged, this one will automatically close, and the article will be published shortly thereafter.

Thank you again for your contribution.

**Pull request closed without merging**
