### PR TITLE
Update tds-8-and-tls-1-3.md

### PR DESCRIPTION
**Pull request by prakashkc07**
Following is logged in error log which seems to be from CEIP Service. 
--------------------------------------
YYYY-MM-DD HH:mm:ss Logon       Error: 17819, Severity: 20, State: 1.
YYYY-MM-DD HH:mm:ss Logon       The SQL Server or the endpoint is configured to accept only strict (TDS 8.0 and above) connections. The connection has been closed.

### CODE REVIEW

**Comment by Court72** [comment]
@VanMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@prakashkc07 By default, CEIP does not use TCP/IP to connect to the SQL Server instance, and therefore is unaffected by TLS 1.3 and TDS 8.0.

I will be closing this PR, but if you have more information to share, please let us know.

**Comment by taroarai** [comment]
@rwestMSFT
I checked with CEIP PG, and it does not work with "Force Strict Encryption" is enabled.
Also, it might be good to tell the service by "SQL CEIP Service(SQLTELEMETRY or SQLTELEMETRY$<instance name> service)"

Ref: 388867958

**Comment by rwestMSFT** [comment]
@prakashkc07 Thanks for opening this PR and for your patience as we validated the issue. The updated article will publish tomorrow morning 9AM Pacific.

**Pull request closed without merging**
