### PR TITLE
This feature was deprecated in 18.0 RC1

### PR DESCRIPTION
**Pull request by leifp1**
Latest version does NOT include this feature

### CODE REVIEW

**Comment by PRMerger20** [comment]
@leifp1 : Thanks for your contribution! The author, @egranet, has been notified to review your proposed change.

**Comment by MightyPen** [comment]
@leifp1 Hi Leif, This PR 1864 might be moot, and thus Close-able, without it ever being Merged.
Thus it might not be worthwhile to Resolve the Conflict.

- `https://github.com/MicrosoftDocs/sql-docs/commit/72a224fe0dbb7787a2ce9b383d40f29c2580db8c#diff-ac0045e3e860d795e73997d0c8a367c0`

@AliceKu might have already fixed this general deprecation situation / note.
CC: @stevestein @MightyPen (GeneMi)

**Comment by aliceku** [comment]
Yes, please close.  I created a new pull request to change the author.  Thx. Alice

**Comment by MightyPen** [comment]
Closing.

**Pull request closed without merging**
