### PR TITLE
Update create-database-encryption-key-transact-sql.md

### PR DESCRIPTION
**Pull request by Hemin-MSFT**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Hemin-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks for the addition, @Hemin-MSFT 

Hey @shohamMSFT - Do you mind confirming the changes here?

**Comment by shohamMSFT** [comment]
Certificates used for TDE are limited to a private key size of 3456 bits. I am further validating the 3456 bit private key length with our Engineering team.

**Comment by shohamMSFT** [comment]
@Hemin-MSFT As discussed on Teams, can you update 3456 to 3072 and then submit the PR. Thanks!

**Comment by PRMerger14** [comment]
@Hemin-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Hemin-MSFT** [comment]
> @Hemin-MSFT As discussed on Teams, can you update 3456 to 3072 and then submit the PR. Thanks!

Updated to 3072

**Review by shohamMSFT — APPROVED** [review]

**Comment by jborsecnik** [comment]
@VanMSFT, ok to merge? Thanks.

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
