### PR TITLE
8.23 release notes

### PR DESCRIPTION
**Pull request by nilabjaball**
#sign-off

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nilabjaball : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by nilabjaball** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@nilabjaball: I'm sorry - only the author of this article, @nahk-ivanov, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Merging exception per email.

**Pull request merged**
