### PR TITLE
Revert "Update installing-the-microsoft-odbc-driver-for-sql-server.md"

### PR DESCRIPTION
**Pull request by David-Engel**
Reverts MicrosoftDocs/sql-docs#454

### CODE REVIEW

**Comment by PRMerger13** [comment]
@David-Engel : Thanks for your contribution! The author, @MightyPen, has been notified to review your proposed change.

**Comment by David-Engel** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@David-Engel: I'm sorry - only the author of this article, @MightyPen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MightyPen** [comment]
The '17' removal made sense at one time, but now it belongs.    So it is being added back.
#sign-off

**Comment by MightyPen** [comment]
@craigg-msft @David-Engel  Craig, can you please use your admin auth to Merge this public PR 493.

**Pull request merged**
