### PR TITLE
Update create-user-transact-sql.md

### PR DESCRIPTION
**Pull request by WHinDenver**
I found that CREATE USER  [Domain\User] FOR LOGIN [Domain\User]  and CREATE USER  [Domain\Group] FOR LOGIN [Domain\Group]  succeeds even when there is not a Instance login of the same name, provided that the user or group is valid on the domain.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@WHinDenver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @WHinDenver - Thanks for the update. The added portion is not needed. What you are referencing is creating a user based on a contained database model, and is referenced throughout the documentation. We also have a specific example in the doc: https://docs.microsoft.com/sql/t-sql/statements/create-user-transact-sql. I'm rejecting this for now, but we thank you for your contribution.

**Comment by WHinDenver** [comment]
My example works in non-contained situations

Sent from my iPhone

On May 5, 2021, at 12:23 PM, Van To ***@***.***> wrote:

﻿
Hi @WHinDenver - Thanks for the update. The added portion is not needed. What you are referencing is creating a user based on a contained database model, and is referenced throughout the documentation. We also have a specific example in the doc: https://docs.microsoft.com/sql/t-sql/statements/create-user-transact-sql. I'm rejecting this for now, but we thank you for your contribution.

**Comment by VanMSFT** [comment]
Hi @WHinDenver - We do list those types Users under **Users based on Windows principals without logins in master** of https://docs.microsoft.com/sql/t-sql/statements/create-user-transact-sql#SyntaxSummary

**Comment by WHinDenver** [comment]
The functionality works regardless of contained/uncontained database, hence the request to update the instructions to include it.
    On Wednesday, May 5, 2021, 12:23:09 PM MDT, Van To ***@***.***> wrote:  
 
 


Hi @WHinDenver - Thanks for the update. The added portion is not needed. What you are referencing is creating a user based on a contained database model, and is referenced throughout the documentation. We also have a specific example in the doc: https://docs.microsoft.com/sql/t-sql/statements/create-user-transact-sql. I'm rejecting this for now, but we thank you for your contribution.

**Pull request closed without merging**
