### PR TITLE
Adding Spark 3.1 support notes

### PR DESCRIPTION
**Pull request by DaniBunny**
Taking in #7158

### CODE REVIEW

**Comment by PRMerger16** [comment]
@DaniBunny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by WilliamDAssafMSFT — APPROVED** [review]

**Comment by DaniBunny** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@DaniBunny: I'm sorry - only the author of this article, @WilliamDAssafMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Pull request merged**
