### PR TITLE
Updated capitalization

### PR DESCRIPTION
**Pull request by icoric**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@icoric : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rothja** [comment]
@icoric Thank you. #sign-off

**Comment by ktoliver** [comment]
Hi @icoric - It looks like you are internal to Microsoft. Per the [Microsoft Docs Contributor Guide](https://review.docs.microsoft.com/help/contribute/?branch=master), as a Microsoft contributor, you should:

- [Link your GitHub & Microsoft accounts](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-github?branch=master#link-your-github--microsoft-accounts)
- [Join MicrosoftDocs organization](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-github?branch=master#join-microsoftdocs-organization-and-others)
- Work in the [private repository](https://github.com/MicrosoftDocs/sql-docs-pr) for advanced quality validations and staging (you also can sign off directly in the private repo and take advantage of auto-merge for PRs that qualify). For more information, see the [partner quick reference](https://review.docs.microsoft.com/help/contribute/contribute-quick-reference?branch=master).

We'll leave the PRs that you've already opened in the public repo for review, but we'll close future PRs in the public repo (up through #5113 are still open and pending approval by the listed authors). 

To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. 

Thanks!

**Comment by icoric** [comment]
Hi @ktoliver! 
Thank you for letting me know, I really appreciate that.

**Comment by ktoliver** [comment]
@icoric You bet. Thanks.

**Pull request merged**
