### PR TITLE
typo: Markdown links with HTML escaped braces

### PR DESCRIPTION
**Pull request by nschonni**
They had `(`=`#40` encoded on both sides of the link instead of `#40` and `#41`. Switch to escaped braces for readablity

### CODE REVIEW

**Comment by PRMerger6** [comment]
@nschonni : Thanks for your contribution! The author, @mzaman1, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @mzaman1, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@nschonni - thanks for cleaning these up.
#sign-off

**Comment by PRMerger16** [comment]
@stevestein: I'm sorry - only the author of this article, @markingmyname, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mzaman1** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@mzaman1: I'm sorry - only the author of this article, @markingmyname, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
