### PR TITLE
Small update

### PR DESCRIPTION
**Pull request by kendaleiv**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@kendaleiv : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @kendaleiv. The Microsoft internal style guidance is to avoid using "ARM" or "RM" for "Azure Resource Manager." (The exception is "ARM template," which is OK after using "Azure Resource Manager template (ARM template)" on first reference.) The update in the PR doesn't align with this guidance, so we'll close it. Thank you for contributing to the documentation.

**Comment by ktoliver** [comment]
@kendaleiv Wait--does the updated sentence actually refer to the ARM computing architecture, and not to Azure Resource Manager at all?

**Comment by kendaleiv** [comment]
Yup, ARM architecture.

**Comment by ktoliver** [comment]
Looks good; merging.

**Pull request merged**
