### PR TITLE
Update deny-database-principal-permissions-transact-sql.md

### PR DESCRIPTION
**Pull request by AssafFraenkel**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@AssafFraenkel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
#sign-off

**Comment by VanMSFT** [comment]
#hold-off

This PR is addressing the same file as in https://github.com/MicrosoftDocs/sql-docs/pull/7835

**Comment by MikeRayMSFT** [comment]
Pulling to private repo

**Pull request closed without merging**
