### PR TITLE
Update sql-server-linux-setup-ssis.md

### PR DESCRIPTION
**Pull request by anthonypants**
This package is not available outside of the 16.04 repo.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@anthonypants : Thanks for your contribution! The author, @leolimsft, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Hi @craigg-msft - I can't assign this to @LeoLiMSFT for some reason. Can you review or reassign? 

Thanks.

**Comment by craigg-msft** [comment]
I believe Leo changed his git id to @lrtoyou1223 I have reassigned.  Leo, the change is minor but I wonder if we do need  / want to list the specific version as it will need to be updated whenever a new version releases.  perhaps that is desired.

**Comment by anthonypants** [comment]
I think it's important to note, because if you add the repo and try to install the package on, say, 18.04 (the current LTS version), it'll fail. Secondly, it should encourage whoever's in charge of the repo to deploy an updated package for later versions.

**Comment by lrtoyou1223** [comment]
Yes, current SSIS on Linux only supports Ubuntu 16.04.

**Comment by craigg-msft** [comment]
#sign-off

**Comment by MightyPen** [comment]
@rothja @MikeRayMSFT Hi Jason & Mike, just FYI to follow-up our email discussion (dated 2019/May/08-09, Subject contains 'PR 1904'):

The " **16.04**" addition to the following line, got merged into article .md file:

- docs/linux/sql-server-linux-setup-ssis.md 

```
[Ubuntu 16.04](#ubuntu)
```

. .

**Comment by rothja** [comment]
@anthonypants Thanks for this clarification and direct change. @MikeRayMSFT @MightyPen and I were thinking that it might be better to point to the supported platforms page rather than list the version here directly (in case it changes). I might make another change to this affect, but it should still make it clear here to check the supported platform versions. I just want to give you a heads up if you see a different change appear soon than what you did here. Let me know if you have any questions or concerns.

**Pull request merged**
