### PR TITLE
useful backup information for databases taken using t-sql snapshot ap…

### PR DESCRIPTION
**Pull request by emad-almousa**
…proach

Added the following query that i think will add value to the content:

select database_name,type,backup_size,backup_start_date,backup_finish_date,is_snapshot from msdb.dbo.backupset where is_snapshot='1';

### CODE REVIEW

**Comment by Court72** [comment]
@perrysk-msft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
@emad-almousa Thanks for your contribution.

We have noticed the number of contributions from you, and we appreciate your passion in wanting to improve the documentation. However, there are some formatting and style basics that are outlined in the contributor guide, that you should be mindful of.

When editing existing content, your contribution needs to match the existing style exactly. You also need to check your spelling and grammar carefully.

Additionally, your contribution has to add value to the millions of readers we get looking at our documentation every year. Adding something that you think is cool, might seem valuable to you, but may not meet our editorial guidelines. Every contribution you make needs to be maintained for the lifetime of the product, and that includes the people who are translating our content into multiple languages. For instance, we still have many articles that contain wording first written in the 1990s.

You can visit https://learn.microsoft.com/style-guide/ to read our text formatting and style guide. Please pay particular attention to text formatting, voice, and style.

Again, thank you. Please don't take offence if we close your PRs. As you get more familiar with how we do things here, you'll begin to recognise what we will find valuable.

I would also like to encourage you to start your own blog if you have not yet done so, to practice your writing. That's the best way to learn.

**Comment by rwestMSFT** [comment]
This change has been included in an internal PR, which modifies the formatting to match our style guide. This PR will be closed automatically, and the change will be published in the next day or so.

Thank you again for your contribution.

**Comment by emad-almousa** [comment]
@rwestMSFT   Thanks for your feedback. In the future I will be more careful about formatting style, spelling,....etc.  My objective is to improve the documentation within the context of the topic and technology itself....at the end your team are the SME's to decide and review if the "proposed" suggestion worth addition or not.

side remark: I have 3 blogs that I proactively write content in:
https://sqlserverwarrior.wordpress.com/
https://geodatamaster.com/
https://databasesecurityninja.wordpress.com/

Thanks again and Have a Nice Day
Emad

**Comment by rwestMSFT** [comment]
@emad-almousa Thank you for responding. I will add those URLs to my personal RSS feed.

We appreciate your contributions, so please keep them coming. You should already see the refreshed snapshot article today with your contribution, and you listed as a contributor.

Here's a link to the section: https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup?view=sql-server-ver16#list-backupset-details-for-t-sql-snapshot-backups

If you click on the list of contributors, your name is third in the list.

**Pull request closed without merging**
