### PR TITLE
Update error-state-transact-sql.md

### PR DESCRIPTION
**Pull request by fbsolo**
Text revisions to tighten and optimize the reading flow of the material. I deleted a duplicate SQL Server example.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@fbsolo : Thanks for your contribution! The author, @edmacauley, has been notified to review your proposed change.

**Comment by craigg-msft** [comment]
@MightyPen please review.

**Comment by MightyPen** [comment]
I took 4 minute glance through this PR's file changes. Some of the changes seems good, but I am less sure about some others. I am on vacation, and this PR 765 needs more time to carefully assess than I can give it at the moment. I will reexamine this PR soon after Tuesday July/17.  Thank you.  (2018-07-05 09:44am)

**Comment by MightyPen** [comment]
Overall I think it is simpler to not accept this set of changes.
Several of the text changes add verbosity that deviates from the telegraphic style that is common to our reference documentation. And, I disagree with the idea of deleting the code example.

Changes that fix errors of grammer or spelling are helpful. But stylistic changes must achieve a level of importance to be accepted.
I am now permanently Closing this PR 765.
Thanks.  (GeneMi = MightyPen)

**Pull request closed without merging**
