### PR TITLE
Update execute-as-transact-sql.md

### PR DESCRIPTION
**Pull request by CoderCH62**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@CoderCH62 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, March 2. Merging will resume Tuesday. Authors can still review and sign off on PRs in the interim. Thanks.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @CoderCH62 for submitting your feedback. Your suggestions help improve our documentation. A doc update is in flight. 
After the updated article is published, GitHub lists you as an article contributor.

**Comment by WilliamDAssafMSFT** [comment]
#sign-off

**Pull request merged**
