### PR TITLE
Clarify Offline Description

### PR DESCRIPTION
**Pull request by JamesFerebee**
Added clarification to "Offline" section

### CODE REVIEW

**Comment by PRMerger6** [comment]
@JamesFerebee : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@JamesFerebee : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@julieMSFT : Thanks for your contribution! The author, @stevestein, has been notified to review your proposed change.

**Comment by julieMSFT** [comment]
#sign-off
@JamesFerebee Thank you for your input!

**Comment by PRMerger15** [comment]
@julieMSFT: I'm sorry - only the author of this article, @stevestein, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
