### PR TITLE
Querying Random Data Using the NEWID() Function

### PR DESCRIPTION
**Pull request by saitorhan**
Added random data query example using NEWID function.

### CODE REVIEW

**Comment by Court72** [comment]
@MikeRayMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by saitorhan** [comment]
Hi @Court72, Hope you are well.
Do I need doing anything else for this pull request?

**Comment by Court72** [comment]
> Do I need doing anything else for this pull request?

Hi @saitorhan, not at this time. 
@MikeRayMSFT might have some suggested changes after they review, so stay tuned. Thanks!

**Review by MikeRayMSFT — COMMENTED** [review]
Edited submission. Thanks for the submission.

**Comment by MikeRayMSFT** [comment]
@saitorhan, thank you for the submission. I did a minor edit. #sign-off

**Review by MikeRayMSFT — APPROVED** [review]

**Pull request merged**
