### PR TITLE
Update ssis-azure-deploy-run-monitor-tutorial.md

### PR DESCRIPTION
**Pull request by dbaduck**
Modified some of the Powershell code to actually work better.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@dbaduck : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@swinarko - Hi, would you review the proposed update to your article? 

Publishing in this repository is suspended until Tuesday, September 22; merging will resume at 7 AM Pacific Tuesday. With your `#sign-off`, we can merge the PR at that time.

Thanks.

**Comment by swinarko** [comment]
#sign-off

**Review by swinarko — APPROVED** [review]

**Comment by ktoliver** [comment]
@swinarko Thanks for the review. This PR is ready to merge on 9/22.

**Pull request merged**
