### PR TITLE
Corrected and clarified ANSI_NULLS remarks

### PR DESCRIPTION
**Pull request by NReilingh**
Fixed a number of errors and omissions related to SET ANSI_NULLS and boolean data types in "Comparison Operators" and "Equals".

Resolves issues noticed on SO in 2012: https://stackoverflow.com/q/9707111/152891

### CODE REVIEW

**Comment by ktoliver** [comment]
@douglaslMS - Would you review the proposed changes? Thank you.

**Comment by douglaslMS** [comment]
@ktoliver see my comments above.

**Comment by NReilingh** [comment]
@douglaslMS Thanks for the note about future tense — I've added a commit that corrects this in my additions.

I actually started by writing "comparing NULL to NULL" (commit 1630db9) but felt that it was ambiguous as to what kind of comparison was occurring. (For example, if you were doing a "not equals" comparison, the statement would be untrue.) If you are satisfied that any comparisons referred to on the "Equals" page are assumed to be equivalency comparisons, I have no objections to changing that wording.

**Comment by douglaslMS** [comment]
@NReilingh Nick, thank you for the corrections. I could tell that you were trying to be extra clear. But yes, on the Equals page, I think we can assume we're talking about equivalency comparisons, and go with "comparing null to null."

**Comment by douglaslMS** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@NReilingh : Thanks for your contribution! The author, @douglaslMS, has been notified to review your proposed change.

**Pull request merged**
