### PR TITLE
Note added to @allow_partition_switch section

### PR DESCRIPTION
**Pull request by Valentina83IT**
Same note has been added to 
https://docs.microsoft.com/en-us/sql/relational-databases/replication/publish/replicate-partitioned-tables-and-indexes?view=sql-server-ver15#replication-support-for-partition-switching

### CODE REVIEW

**Comment by PRMerger17** [comment]
@valcanms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MashaMSFT** [comment]
thanks so much @Valentina83IT  #sign-off

**Comment by PRMerger8** [comment]
@MashaMSFT: I'm sorry - only the author of this article, @markingmyname, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
