### PR TITLE
Manually updating password for Grafana and Kibana

### PR DESCRIPTION
**Pull request by demoolya**
Manually updating AZDATA_PASSWORD does not update the password for Grafana and Kibana and we need to update those manually. Adding the steps to update the  password for Grafana and Kibana.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@demoolya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by cloudmelon — APPROVED** [review]
Looks good ! Thanks for the contribution. If there anything we can do for the pictures ?  @MikeRayMSFT

**Comment by WilliamDAssafMSFT** [comment]
@demoolya the images are not acceptable quality (grainy resolution), can you send me full resolution images via email? I will need to re-home them in the SQL-Docs repository. Can you also provide a sentence or two on each describing the steps in each image? I should be able to can generate alt-text for accessibility from there. I’ll deploy in a new PR.

**Comment by WilliamDAssafMSFT** [comment]
Got new images and descriptions from @demoolya, pulled these changes into https://github.com/MicrosoftDocs/sql-docs-pr/pull/18673/ for publishing.

**Pull request closed without merging**
