### PR TITLE
Update dma-consolidatereports.md

### PR DESCRIPTION
**Pull request by ChrisLound**
added Azure PowerShell Modules as dependency

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ChrisLound : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@douglaslMS - Would you review the proposed changes? I'm not finding @pochiraju in the Assignees box. If the GitHub user name is correct for the article author, he might need to [link his GitHub and Microsoft accounts](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master#link-your-github-and-microsoft-accounts). Thanks.

**Comment by douglaslMS** [comment]
@ktoliver Thanks, I've emailed @pochiraju to remind him to link his accounts.

**Comment by PRMerger16** [comment]
@GitHubber17 : Thanks for your contribution! The author, @pochiraju, has been notified to review your proposed change.

**Pull request merged**
