### PR TITLE
Fix the code to reflect the description "occurred today"

### PR DESCRIPTION
**Pull request by 0x7FFFFFFFFFFFFFFF**

### CODE REVIEW

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@MashaMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
The underlying article has been refreshed, with this change included. This PR will close automatically.

**Pull request closed without merging**
