### PR TITLE
 Fix missing / misleading statements, and formatting in CREATE and ALTER CERTIFICATE

### PR DESCRIPTION
**Pull request by srutzky**
### CREATE CERTIFICATE

1. Fixed description of "WITH PRIVATE KEY" to account for "BINARY =" option introduced in SQL Server 2012.

2. Fixed specification of BINARY for certificate (public key):
    1. added "BINARY ="
    2. moved above private key options to be properly grouped with public key options
    3. added "Applies to"

3. Updated remarks to indicate that certificates can also be loaded from a binary constant (as of SQL Server 2012).

4. Added note about "CLR strict security" server config option at the bottom of "Example C" (as of SQL Server 2017).

5. Added links to CERT_ID and CERTPROPERTY functions in "See Also" section.

### ALTER CERTIFICATE

1. Fixed main description as it was both incomplete and misleading.

2. Fixed syntax

3. Fixed formatting in "Arguments" section to be consistent with formatting found in CREATE CERTIFICATE page (and I have been told to specifically _not_ escape underscores unless they are causing formatting issues).

4. Changed "password" in `DECRYPTION BY PASSWORD` and `ENCRYPTION BY PASSWORD` clauses to be "current_password" and "new_password", respectively, to hopefully be more intuitive to those who are less experienced with certificates.

5. Removed "from a file" wording in "Remarks" section since the private key can be imported from multiple sources

6. Changed "Example A" to be "Removing a private key". Previously it was "Changing the password of a certificate", which is identical to "Example B", except the title is slightly different and the order of the `ENCRYPTION BY PASSWORD` and `DECRYPTION BY PASSWORD` clauses is different. No need for redundant examples.

7. Reversed the order of the `ENCRYPTION BY PASSWORD` and `DECRYPTION BY PASSWORD` clauses in "Example B" because it is probably more intuitive to have decryption first since that is actually what happens first.

8. Fixed typo in "Example C": removed extraneous backslash in file path.

9. Added links to  CERTENCODED, CERTPRIVATEKEY, CERT_ID, and CERTPROPERTY functions in "See Also" section.

### Both

For details /  testing, please see:  https://sqlquantumleap.com/2019/04/22/can-a-certificates-private-key-be-imported-restored-from-a-binary-literal-hex-bytes/

### CODE REVIEW

**Comment by PRMerger13** [comment]
@srutzky : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@VanMSFT : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@VanMSFT : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Hi @srutzky! Thanks for the detailed update. We really appreciate your testing and knowledge on this. I went through details, and everything looks applicable. Besides a slight change to syntax, I'll go ahead and approve. Thanks again!

#sign-off

**Comment by srutzky** [comment]
Cool. Good catch on the syntax change. And you are quite welcome 😺 

There are one or two minor additions I just thought of for ALTER CERTIFICATE, partially related to the PR I just submitted for `BACKUP CERTIFICATE` : #1976  . Is it too late to add them to this PR?

**Comment by VanMSFT** [comment]
#hold-off

@srutzky - Go ahead and add to this PR if needed.

**Comment by srutzky** [comment]
Thanks...won't take long..

**Comment by PRMerger7** [comment]
@srutzky : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by srutzky** [comment]
Additional changes consist of:

1. Moved the "REMOVE PRIVATE KEY" clause to the top to be in the same order as shown in the syntax (that is how most other pages are done)
2. Added clarification regarding what private keys are used for in "Remarks", in the paragraph about removing the private key.
3. Added note to explicitly state how to accomplish changing the password rather than importing, else it was only mentioned in the description and shown in an example.
4. Added `CERTPRIVATEKEY` link to "Important" note regarding backing up the private key before removing it (this became an option in SQL Server 2012).

**Comment by srutzky** [comment]
oops...sorry, one more quick thing...

**Comment by PRMerger10** [comment]
@srutzky : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by srutzky** [comment]
Final edit:
1. Added info about default file location. Test case is in script linked in PR for `BACKUP CERTIFICATE`: #1976

**Comment by srutzky** [comment]
@VanMSFT all done now...thanks..

**Comment by Jak-MS** [comment]
@VanMSFT - if you approve, can you `#sign-off` ? After the PR is signed off, we'll check it against the PR review criteria before it gets merged. thanks.

**Comment by VanMSFT** [comment]
Reviewed. Thanks @srutzky!
#sign-off

**Comment by srutzky** [comment]
Yer welcome.

**Comment by PRMerger9** [comment]
@GitHubber17 : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@GitHubber17 : Thanks for your contribution! The author, @VanMSFT, has been notified to review your proposed change.

**Pull request merged**
