### PR TITLE
Replaced Depreciated apt-key

### PR DESCRIPTION
**Pull request by dphaas2004**
Replaced Depreciated apt-key with recommendations from apt-key man page.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@VanMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Co-assigning myself to remember to track this.

#assign:rwestMSFT

**Comment by VanMSFT** [comment]
@dphaas2004 - Thanks Daniel! Looks correct to me.

@amvin87-zz - Amit, can you please verify the changes?

**Comment by VanMSFT** [comment]
@amitkh-msft - Amit, can you please verify the changes?

**Comment by VanMSFT** [comment]
PG also verified. Approving.

#sign-off

**Pull request merged**
