### PR TITLE
Update sys-dm-xe-sessions-transact-sql.md

### PR DESCRIPTION
**Pull request by DanielAdeniji**
Adding new columns to  the sys.dm_xe_sessions dmv.

The column names are:-

1) session_source
2) buffer_processed_count
3) buffer_full_count
4) total_bytes_generated

### CODE REVIEW

**Comment by PRMerger13** [comment]
@DanielAdeniji : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by WilliamDAssafMSFT** [comment]
Thanks @DanielAdeniji for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
@DanielAdeniji thanks again for the time and attention to submit this pull request. Your commit has been pulled into an internal PR that is in progress and under review. This is a valid issue, we are hunting down confirmation on some details which will expand the definitions you've provided. Will update you here in this space when new information is published. Your commit will be merged with others. After the updated article is published, GitHub will list you as an article contributor.

**Comment by WilliamDAssafMSFT** [comment]
Thanks again @DanielAdeniji, just an update that a doc update is in flight and should be published in the next 24 hours.  Thanks again for your time and attention here, your feedback helps improve our docs for everyone.

**Pull request closed without merging**
