### PR TITLE
Add a missing word

### PR DESCRIPTION
**Pull request by Rubenisme**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Rubenisme : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Rubenisme : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Rubenisme : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Rubenisme : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Rubenisme** [comment]
Done, although I don't agree with the style-guide (styleguide? 😉). Nonkey seems like a spelling mistake of monkey (Chrome indicates a red squiggly line at this moment) and in general spelling checkers don't recognize all variations of prefix and compound words (which we use in Dutch for nearly all possible combinations and as such spelling checking is very bad). But alas, it's not up to me and as such changed.

**Comment by MikeRayMSFT** [comment]
Good points. Apparently several others agree with you, which is why we haven't shown consistency internally. 

I would love to arbitrate the style guide but my lot is much less exciting...

**Comment by Rubenisme** [comment]
@MikeRayMSFT did you still need to sign off on this to get it merged?

**Pull request closed without merging**
