### PR TITLE
Add LPIM requirement

### PR DESCRIPTION
**Pull request by PiJoCoder**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@PiJoCoder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@PiJoCoder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@MikeRayMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeRayMSFT** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@MikeRayMSFT: I'm sorry - only the author of this article, @DBArgenis, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
