### PR TITLE
Update create-asymmetric-key-transact-sql.md

### PR DESCRIPTION
**Pull request by Hemin-MSFT**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Hemin-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by VanMSFT** [comment]
Thanks @Hemin-MSFT 

@shohamMSFT - Hey Shoham, can you confirm this for TDE? Thanks

**Review by shohamMSFT — COMMENTED** [review]
The Create Asymmetric Key command supports upto RSA-4096. Certificates used for TDE are limited to a private key size of 3456 bits.

**Comment by VanMSFT** [comment]
> The Create Asymmetric Key command supports upto RSA-4096. Certificates used for TDE are limited to a private key size of 3456 bits.

Thanks, @shohamMSFT - Do you want to make a suggested change to @Hemin-MSFT's text

image

image

Or should we change it to:

> Certificates used for TDE are limited to a private key size of 3456 bits.

**Review by shohamMSFT — CHANGES_REQUESTED** [review]
Please update the 3456 to 3072 and then resubmit the PR.

**Comment by PRMerger12** [comment]
@Hemin-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Hemin-MSFT** [comment]
> Please update the 3456 to 3072 and then resubmit the PR.

Updated to 3072 in this PR

**Review by shohamMSFT — APPROVED** [review]

**Comment by jborsecnik** [comment]
@VanMSFT, ok to merge? Thanks.

**Comment by VanMSFT** [comment]
#sign-off

**Pull request merged**
